### DISCUSSION TITLE
overrides in `APISIX_STAND_ALONE=true`

### DISCUSSION THREAD

**Discussion by michael-riha** [apache/apisix#10458] [General]
I have APISix running in my docker compose setup in `APISIX_STAND_ALONE=true`

It looks like

```yaml
apisix:
    # enable if you have arm64 processor (Mac M1 & M2)
    # platform: linux/x86_64 
    image: apache/apisix:3.3.0-debian
    volumes:
      - ./services_configs/apisix_conf/standalone_config.yaml:/usr/local/apisix/conf/config.yaml
      - ./services_configs/apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    environment:
      - APISIX_STAND_ALONE=true #standalone has no /admin https://apisix.apache.org/docs/apisix/next/deployment-modes/#standalone
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp" #this is the API Gateway
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:
 ...
```

- I just want my routes in YAML to be persistent, but they get overwritten every time the server starts?
Any way to make this happen, as it is annoying over time.

I know it can be solved with `ectd` by why do I need another container just for simply mapping or not overwrite a file?

---

- I wanted to change the logs, so [I configured the `config.yaml` accordingly](https://github.com/apache/apisix/blob/ce5986c4dae5de942342e94ba52c0c3294f2adcc/conf/config-default.yaml#L216) though also here, this file get's overwritten every restart/start.

⬆️  in this case as it is not reloaded every 1 sec as the `apisix.yaml` 
**it is not even possible to do, in standalone is that correct?**
