### DISCUSSION TITLE
APISIX集群，重启一台机器，导致js加载404问题

### DISCUSSION THREAD

**Discussion by heichong** [apache/apisix#10576] [Q&A]
apisix版本：2.3.1
# 现象
目前apisix有三台组成集群。h1 ,h2,h3 ，docker-compose部署。
我今天修改了h1的配置，增加了如下配置
```
plugins:
  - log-rotate


plugin_attr:
  # 日志切割方式
  log-rotate:
    interval: 3600    # rotate interval (unit: second)
    max_kept: 100     # max number of log files will be kept
    max_size: -1      # max size of log files will be kept
    enable_compression: false    # enable log file compression(gzip) or not, default false
```
然后通过以下命令**删除并重新创建容器**
```
docker-compose down
dokcer-compose up -d
```

启动成功，没有问题。

但是随后发现，请求到h1的js文件都直接404了
error.js日志如下
```
4.177:9916 404 0.001 "http://front.xxxx.com.cn"
10.3.4.189 - - [01/Dec/2023:10:00:38 +0800] front.xxxx.com.cn "GET /om-weekly-report/assets/index-a6f0d4af.js HTTP/1.1" 404 555 0.002 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 10.3.4.177:9916 404 0.002 "http://front.xxxx.com.cn"
10.3.4.189 - - [01/Dec/2023:10:00:39 +0800] front.xxxx.com.cn "GET /om-weekly-report/assets/index-a6f0d4af.js HTTP/1.1" 404 555 0.003 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 10.3.4.177:9916 404 0.004 "http://front.xxxx.com.cn"
10.3.4.189 - - [01/Dec/2023:10:00:39 +0800] front.xxxx.com.cn "GET /om-weekly-report/assets/index-a6f0d4af.js HTTP/1.1" 404 555 0.001 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 10.3.4.177:9916 404 0.001 "http://front.xxxx.com.cn"
10.3.4.189 - - [01/Dec/2023:10:00:39 +0800] front.xxxx.com.cn "GET /om-weekly-report/assets/index-a6f0d4af.js HTTP/1.1" 404 555 0.001 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 10.3.4.177:9916 404 0.001 "http://front.xxxx.com.cn"


```
接着我关闭了h1，这些js的请求都进入了h2，h2能成功返回js
h2的日志如下
```
10.3.4.189 - - [01/Dec/2023:10:01:58 +0800] front.xxxx.com.cn "GET /om-weekly-report/assets/index-a6f0d4af.js HTTP/1.1" 200 1776 0.002 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 10.3.4.177:9916 200 0.002 "http://front.xxxx.com.cn/assets/index-a6f0d4af.js"
10.3.4.189 - - [01/Dec/2023:10:01:58 +0800] front.xxxx.com.cn "GET /om-weekly-report/assets/index-a6f0d4af.js HTTP/1.1" 304 0 0.001 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 10.3.4.177:9916 304 0.001 "http://front.xxxx.com.cn/assets/index-a6f0d4af.js"
10.3.4.189 - - [01/Dec/2023:10:01:59 +0800] front.xxxx.com.cn "GET /om-weekly-report/assets/index-a6f0d4af.js HTTP/1.1" 304 0 0.000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 10.3.4.177:9916 304 0.000 "http://front.xxxx.com.cn/assets/index-a6f0d4af.js"
10.3.4.189 - - [01/Dec/2023:10:01:59 +0800] front.xxxx.com.cn "GET /om-weekly-report/assets/index-a6f0d4af.js HTTP/1.1" 304 0 0.001 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 10.3.4.177:9916 304 0.001 "http://front.xxxx.com.cn/assets/index-a6f0d4af.js"
10.3.4.189 - - [01/Dec/2023:10:01:59 +0800] front.xxxx.com.cn "GET /om-weekly-report/assets/index-a6f0d4af.js HTTP/1.1" 304 0 0.001 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 10.3.4.177:

```

# 疑问

我怀疑和删除h1容器，或者和js缓存有关。

docker-compose.yml如下
```
version: '3'

services:
  apisix:
    image: 'apache/apisix:3.2.1-centos'
    container_name: apisix
    restart: always
    ports:
      - 80:80 
      - 443:443 
      - 9443:9443 
      - 9180:9180
      - 9091:9091
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./config/debug.yaml:/usr/local/apisix/conf/debug.yaml
      - ./data/logs:/usr/local/apisix/logs

```

哪位帮忙看看，如何解决这个问题。
