### DISCUSSION TITLE
How to Configure Multiple Global Rules in Standalone Mode?

### DISCUSSION THREAD

**Discussion by wojja** [apache/apisix#10840] [Q&A]
I am playing with standalone mode on v3.7.0 and would like to establish two global rules based on the response-rewrite plugin as catch-all for client errors (4xx) and server errors (5xx).

The global rules section of my current configuration in `apisix.yaml` looks like this:
```
global_rules:
  -
    id: 1
    plugins:
      response-rewrite:
        headers:
          Content-Type: "text/plain"
        body: "Client error"
        vars:
          -
            - "status"
            - ">="
            - 400
          - 
            - "status"
            - "<"
            - 500
  -
    id: 2
    plugins:
      response-rewrite:
        headers:
            Content-Type: "text/plain"
        body: "Server error"
        vars:
          - 
            - "status"
            - ">="
            - 500
          -
            - "status"
            - "<"
            - 600
```
Each rule works individually, but I somehow I cannot make them work together. Only the second rule (id 2) seems to be active. So far, I haven't found any example with more than one global rule.

What is wrong with my configuration? Or could I combine both rules in a single one?
