### DISCUSSION TITLE
External Service Upstream Rediect to ipaddress

### DISCUSSION THREAD

**Discussion by the-mgi** [apache/apisix#11273] [Q&A]
how can i configure this in such a way that ApisixUpstream point to an ip address with aa given port so that x.app.com serves content from x.x.x.x:8080

```yaml

apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: proxy-route
spec:
  http:
    - name: rule1
      match:
        hosts:
          - x.app.com
        paths:
          - /*
      upstreams:
        - name: proxy-upstream

apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  namespace: dev
  name: proxy-upstream
spec:
  externalNodes:
    - type: Domain
      name: x.x.x.x
```
