### DISCUSSION TITLE
Standalone deployment on Kuberentes

### DISCUSSION THREAD

**Discussion by mikyll** [apache/apisix#11278] [Q&A]
What's the proper configuration to deploy Apisix in **standalone mode** on **Kubernetes**?

I tried using these values for the apisix/apisix Helm chart:
```yaml
apisix:
  deployment:
    mode: standalone
    role: "data_plane"

etcd:
  enabled: false

service:
  type: LoadBalancer

ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: ingress-apisix
      adminAPIVersion: v3
```

 but the ingress-controller Pod gets stuck on initialization, with the `wait-apisix-admin` InitContainer spamming these log messages:
```lang-none
waiting for apisix-admin
waiting for apisix-admin
waiting for apisix-admin
waiting for apisix-admin
```
