### DISCUSSION TITLE
How to route traffic to another service in apisix k8s ingress

### DISCUSSION THREAD

**Discussion by AlecKotovichSAM** [apache/apisix#11308] [Q&A]
Hello, how can i route traffic  to another service in apisix k8s ingress, when all requests go to the first "/" service ?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    k8s.apisix.apache.org/use-regex: "true"  
spec:
  ingressClassName: apisix
  rules:
  - host: my.host
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name:  frontend-svc
            port:
              number: 80
      - path: /anotherservice
        pathType: ImplementationSpecific
        backend:
          service:
            name: another-svc
            port:
              number: 80        
```
