### DISCUSSION TITLE
Cost of plugins pipelines - Serverless plugin in production ?

### DISCUSSION THREAD

**Discussion by arnauddeman** [apache/apisix#11323] [Q&A] [answered]
Hi,
In our project, for some specific externs services, we will have a service catalog which will provide information on the upstream service to use for a given user.
I created a POC that uses these plugins:
- Openid-connect: checks the access token,
- Serverless pre-function: queries the service catalog and sets variables for upstream and access point,
- Traffic split: select the upstream,
- Proxy Rewrite: Sets endpoint.

It works fine, but I wonder about the cost of such pipelines and especially the serverless one (regardless of the function itself).

Thanks in advance !

**Comment by nfrankel** [comment]
I'd personally avoid `traffic-split` because it's not designed with that in mind.

However, are you aware that you can define multiple routes, define an additional check in addition to the usual domain/URI/method, and APISIX will try them them in order and forward to the first match found.

[Here's an example](https://github.com/ajavageek/data-residency/blob/master/config/apisix/apisix.yml) using an HTTP header:

```yaml
routes:
  - uri: /thingies*
    name: Europe
    upstream_id: 1
    vars: [["http_x-country", "==", "fr"]]
    priority: 3
  - uri: /thingies*
    name: USA
    upstream_id: 2
    vars: [["http_x-country", "==", "us"]]
    priority: 2
  - uri: /thingies*
    name: default
    upstream_id: 1
    priority: 1
```

APISIX will try to match the route `Europe`, which has a priority 3; it matches if there's an HTTP Header `X-Country: fr`. It will then try the `USA` route, which matches if there's an HTTP Header `X-Country: en`. If none matches, it defaults to the `default` route that has no additional check.

You can use **any** NGINX variable, not only HTTP headers (cookies, etc.).
