### DISCUSSION TITLE
Route not matching

### DISCUSSION THREAD

**Discussion by troke12** [apache/apisix#11378] [Q&A] [answered]
My config

```yml
apisix:
  delete_uri_tail_slash: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

routes:
  -
    uri: "/history"
    service_id: 3

upstreams:
  -
    id: "history_upstream"
    nodes:
      "10.10.1.35:3099": 1
    type: roundrobin

services:
  -
    id: 3
    upstream_id: history_upstream

nginx_config:
  log_level: debug
#END
```

any help that when i tried to accessing my swagger-ui on apisix server with standalone mode http://10.10.1.30:9080/history/swagger-ui the response is :

```json
{
   "path": "[/history/swagger-ui](http://10.10.1.30:9080/history/swagger-ui)",
   "error": "Unauthorized",
   "message": "Full authentication is required to access this resource",
   "status": 401
}
```

when using kong is worked as well showing all my swagger-ui, any help to match this?
