### DISCUSSION TITLE
Enable sticky session in APISIX with discovery type as kubernetes.

### DISCUSSION THREAD

**Discussion by prashantsinghb** [apache/apisix#11520] [Q&A]
Need help in enabling sticky session for an application routed via APISIX. 
- I have react application using express-session package for session management
- Have routed the application via following upstream configuration in apisix.
upstream:
      -
        id: 1
        type: chash           
        hash_on: cookie              
        key: connect.sid
        discovery_type: kubernetes
        service_name: k8s_ns/k8s_service

Have already gone through https://dev.to/apisix/sticky-sessions-with-apache-apisix-3l03, but it is not working for me.

**Comment by dosubot** [comment]
Hey @prashantsinghb, I'm here to help you with any issues you're facing. Let's work together to solve the problem.


To enable sticky sessions in APISIX with the discovery type as Kubernetes for your React application using the `express-session` package, you need to configure the upstream with the `session_sticky` plugin. Here is an example configuration:

```yaml
upstream:
  name: "example-upstream"
  type: roundrobin
  discovery_type: "kubernetes"
  service_name: "k8s_ns/k8s_service"
  timeout:
    connect: 6
    send: 6
    read: 6
  plugin_config:
    session_sticky:
      cookie_name: "connect.sid"
      cookie_path: "/"
      cookie_domain: "your-domain.com"
      cookie_max_age: 3600
      mode: "cookie"
```

In this configuration:
- `discovery_type` is set to `kubernetes`.
- `service_name` should be in the format `namespace/service-name`.
- `plugin_config` includes the `session_sticky` plugin with the necessary cookie settings.

Make sure to replace `your-domain.com` with the actual domain for your setup.

Additionally, ensure that your Kubernetes discovery configuration is properly set up in APISIX. If running inside a Pod, the minimal configuration would be:

```yaml
discovery:
  kubernetes: { }
```

If running outside a Pod, you need to specify the Kubernetes API server details and a valid service account token:

```yaml
discovery:
  kubernetes:
    service:
      schema: https
      host: # enter apiserver host value here
      port: # enter apiServer port value here
    client:
      token: # enter serviceaccount token value here
```

This ensures that APISIX can discover the Kubernetes services correctly and apply the sticky session configuration <sup>[[1]](https://github.com/apache/apisix/blob/master/docs/en/latest/discovery/kubernetes.md)</sup><sup>[[2]](https://github.com/apache/apisix/blob/master/docs/zh/latest/discovery/kubernetes.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
