### DISCUSSION TITLE
Hello, it's always 404 to use apisix routing to forward a site. If it's a service, it's good. Are you puzzled?

### DISCUSSION THREAD

**Discussion by danielmlc** [apache/apisix#11677] [General]
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: node-auth-service
spec:
  http:
  - name: authService
    match:
      hosts:
      - apis.yearrow.com
      paths:
      - "/authServer/*"
    backends:
    - serviceName: node-auth-service
      servicePort: 8080
  - name: desktop-element
    match:
      hosts:
      - apis.yearrow.com
      paths:
        - "/desktop-element/*"
    backends:
    - serviceName: element-plus-extension
      servicePort: 8080
```
Think about the above configuration，  The authServer is service access is fine, desktop-element is a static resource site proxied with the nginx container is not accessible. The strange thing is that I'm using
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: node-auth-service
spec:
  http:
  - name: desktop-element
    match:
      hosts:
      - apis.yearrow.com
      paths:
        - "/*"
    backends:
    - serviceName: element-plus-extension
      servicePort: 8080
```
In this way, it is good if you visit such a site on the root node in path. I don't know what the problem is?
