### DISCUSSION TITLE
Problems enabling a stream route

### DISCUSSION THREAD

**Discussion by zarconike** [apache/apisix#11696] [Q&A] [answered]
Hello, I installed APISIX version 3.10.0 with Helm. When I try to create a stream_routes (according to the documentation https://apisix.apache.org/docs/apisix/next/stream-proxy/), I get the following message: "error_msg": "stream mode is disabled, can not add stream routes." I've completed all the configuration correctly according to the documentation, but it's still not working.

I have already added the following to config.yaml:

stream_proxy:                 # TCP/UDP proxy
        tcp:                        # TCP proxy port list
          - addr: 1935
            allow: all
            deny: 0.0.0.0/0
        udp:                        # UDP proxy port list
          - 9200

And it still doesn’t work.

**Comment by dosubot** [comment, marked as answer]
To resolve the "stream mode is disabled, can not add stream routes" error in APISIX 3.10.0, ensure that you have set `apisix.proxy_mode` to `stream` or `http&stream` in your `config.yaml`. Here's an example configuration:

```yaml
apisix:
  proxy_mode: http&stream  # or 'stream' if you only want stream proxy
  stream_proxy:
    tcp:
      - addr: 1935
        allow: all
        deny: 0.0.0.0/0
    udp:
      - 9200
```

Make sure both `proxy_mode` and `stream_proxy` are correctly configured. This should enable stream routes and resolve the error <sup>[[1]](https://apisix.apache.org/docs/apisix/next/stream-proxy)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
