### DISCUSSION TITLE
routing structure to search services with the same path

### DISCUSSION THREAD

**Discussion by aytemuryakup** [apache/apisix#11716] [Q&A]
I just started using Apisix. The gateways I used before had this feature, but I could not find a definition for this feature in Apisix.
While routing through /demo path, it is looking for the same path in the service I want to route.
```yaml
routes:
    -
      uri: /demo
      upstream:
        nodes:
          "nginx-service.default.svc:80": 1
        type: roundrobin
```
For example;
I define a route as above. 
When I sent a request to **https://xxx.test.local/demo** apisix endpoint, I saw that my nginx service was looking for **/demo** path. 
You can see my nginx service logs as below.

_[error] 7#7: *1 open() "/usr/share/nginx/html/demo" failed (2: No such file or directory), client: 10.244.0.51, server: localhost, request: "GET /demo HTTP/1.1", host: "xxx.test.local"_

Here I solved it down using the rewrite plugin
```yaml
routes:
    -
      uri: /demo
      upstream:
        nodes:
          "nginx-service.default.svc:80": 1
        type: roundrobin
      plugins:
        proxy-rewrite:
          regex_uri: ["^/demo(.*)", "/$1"]
```

But sending it directly to the root path of the service, i.e. '/', is a common structure from other gateway applications. Is there such a structure? If so, how can I use it or is it planned to be written?
