### DISCUSSION TITLE
OIDC Relying Party flow setup issues

### DISCUSSION THREAD

**Discussion by plamenlakov** [apache/apisix#11939] [Q&A]
Hello,

I've successfully implemented the openid-connect plugin to protect my backend services via Keycloak an an OIDC identity provider. However this was done using the token introspection flow, meaning that the bearer token would be stored somewhere in the front-end. Obviously this is not ideal since it makes the token accessible client-side. I'd like to make use of the http-only session cookie same as how the Relying Party flow is being handled but I'm having a bit of trouble setting it up considering backend & frontend are two separate services. 

My current APISIX configuration looks like this, but I find it hard on handling this flow on the front-end. How do I redirect to the OIDC provider login page without pointing to an existing RESTful API endpoint (my upstream) and then redirect back to my frontend application? Possibly also being able to specify the redirect uri after successful authentication dynamically, since I want to be flexible in terms of the amount of front-end applications that can communicate with the OIDC authenticated gateway.

My current APISIX config is like this:
```
upstreams:
  - name: backend-upstream
    id: 1
    type: roundrobin
    nodes:
      - host: 172.17.0.1
        port: 3000
        weight: 1

routes:
  - uri: /*
    name: backend-route
    upstream_id: 1
    plugins:
      openid-connect:
        client_id: apisix
        client_secret: 6dE1dzUQFX1r7wa1hgyYGknJjaNrhmi1
        discovery: https://172.17.0.1:8443/realms/users/.well-known/openid-configuration
        introspection_endpoint: https://172.17.0.1:8443/realms/users/protocol/openid-connect/token/introspect
        bearer_only: false
        realm: users
        scope: openid email profile
        session:
          secret: "MjMzZDFlYzAtN2Y3OC00M2MyLTg1OGYtZTk1NGVkZDEyZjZhCg=="
        use_jwks: true
      cors:
        allow_origins: "https://localhost:8000"
        allow_methods: "GET, POST, OPTIONS"
        allow_headers: "Authorization, Content-Type"
        expose_headers: "Content-Length, X-Access-Token"
        max_age: 3600
        allow_credential: true

#END
```

Also I'd appreciate your help @dosu ;)
