### DISCUSSION TITLE
How to append SameSite=None to Set-Cookie?

### DISCUSSION THREAD

**Discussion by rohitkrishna-marneni** [apache/apisix#11975] [Q&A]
I have an endpoint which returns a set of cookies. However I need to append(or modify) these cookies so that they have SameSite=None attribute set. More about [SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value).

So I have my yml configuration like this.

```yml
services:
  - name: my-service
    upstream: # my upstream information
      name: my-upstream
      #...
    routes:
      - name: my-first-route
        hosts:
          - "my-service.com"
        uris:
          - /my-service
        plugins:
          response-rewrite:
            body_base64: false
            headers:
              set:
                Set-Cookie: "uuid=12345; SameSite=None"
```

I am able to modify the cookie uuid, however its actual settings like path=/ is being overriden. Also with this approach I can only append SameSite=None to one cookie(which is uuid in my case). However I want to append SameSite=None to all my cookies which are sent in set-cookie header after a call to endpoint /my-service. 

Is there a way to do it in apisix?
