### DISCUSSION TITLE
How do you do healthcheck to ApiSix deployment (liveness/readiness probes)

### DISCUSSION THREAD

**Discussion by bokjo** [apache/apisix#11970] [Q&A] [answered]
Hello ApiSix people,

I'm trying to figure out how to do a health check on the ApiSix deployment itself.

Looking at the K8s/Helm implementation, the stateful set/pods do not have liveness/readiness probes set at all.

Is there a special port or endpoint on the GW(9080), AdminAPI (9180), or somewhere else for a simple `/healthz` check as others do?

I'm trying to deploy to GKE K8s through the new K8s Gateway implementation, but the health check always fails.

I've made a proxy on the GW(9080) `/healthz` to hosts like `127.0.0.1` and `*.10` (since the GoogleHC sets the host to http://10.1.1.10 for example)... but no luck, ApiSix always says 404 route not found.

GW(9080) `/healthz` - just proxies the requests to Istio health check `/healthz/ready` port `15021`

Any ideas are welcome!

p.s is there other way to get access to the Slack channel? send an email already while back, no luck... or it is meant only for `@apache.org` users?

**Comment by dosubot** [comment, marked as answer]
Hey @bokjo,

I'm here to help you with your ApiSix deployment question. I'm a bot that can assist you with bug fixes, answer questions, and guide you on how to become a contributor. Let me know how I can assist you!

[Dosu](https://dosu.dev)


To perform a health check on an APISIX deployment using liveness/readiness probes, you can configure the probes in your Kubernetes deployment YAML file. The specific port and endpoint for the health check on the Gateway is port 9080 with the endpoint `/healthz`. Here is an example configuration:

```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: my-apisix-pod
spec:
  containers:
  - name: my-apisix-container
    image: my-apisix-image
    livenessProbe:
      httpGet:
        path: /healthz
        port: 9080
      initialDelaySeconds: 15
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /readyz
        port: 9080
      initialDelaySeconds: 10
      periodSeconds: 5
```

This configuration sets up a liveness probe that checks the `/healthz` endpoint on port 9080 every 10 seconds to determine if the application is running. If the application is unhealthy, Kubernetes will restart the instance. The readiness probe checks the `/readyz` endpoint on the same port to determine if the application is ready to receive traffic <sup>[[1]](https://api7.ai/blog/3-tips-for-deploying-apisix-in-k8s-2)</sup>.

Additionally, I found a similar closed issue where the suggested solution was to create a router `/health` by referring to the documentation at [this link](https://docs.api7.ai/apisix/getting-started/configure-routes) <sup>[[2]](https://github.com/apache/apisix/issues/9974)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/dac9c6df-0664-4fde-a8af-75362a6d87c3?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/dac9c6df-0664-4fde-a8af-75362a6d87c3?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/dac9c6df-0664-4fde-a8af-75362a6d87c3?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/dac9c6df-0664-4fde-a8af-75362a6d87c3?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/dac9c6df-0664-4fde-a8af-75362a6d87c3?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/dac9c6df-0664-4fde-a8af-75362a6d87c3?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/dac9c6df-0664-4fde-a8af-75362a6d87c3?feedback_type=other)</sup>

**Comment by boscard** [comment]
@bokjo have you found any solution? I'm trying to resolve the same problem...

**Reply by bokjo** [reply]
> @bokjo have you found any solution? I'm trying to resolve the same problem...

@boscard I've created a route `/healthz/ready` in ApiSix that is essentially a proxy towards the Istio healthcheck in my case!

```
{
  "uri": "/healthz/ready",
  "name": "health-check",
  "desc": "Health check route for dev environment",
  "plugins": {
    "prometheus": {
      "_meta": {
        "disable": true
      },
      "prefer_name": false
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "istio-ingressgateway.***.svc.cluster.local",
        "port": 15021,
        "weight": 1
      }
    ],
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "http",
    "pass_host": "pass"
  },
  "status": 1
}
```

Now the LB GKE HealthCheck is checking  port `9080` on `/healthz/ready`

**Reply by boscard** [reply]
So if I understand correctly @bokjo , in your case health check status is returned not by ApiSix but by Istio?

**Reply by bokjo** [reply]
> So if I understand correctly @bokjo , in your case health check status is returned not by ApiSix but by Istio?

Yes, but that makes sense in my case... If Istio is not healthy ApiSix/LB health check will fail and not serve traffic... also if ApiSix deployment is not up, the proxy HC will not go through, and traffic won't be served again.

If only ApiSix healthcheck is of your concern, you can make the `/healthz/ready` directly return a response with the `response-rewrite` plugin from ApiSix.

**Reply by ohbibi-gdurand** [reply]
Hello, 
I am facing the same problem. To get around it, I created a route without a host and path "/healthz" that responds with 200 using the “mocking” plugin and restricting the request to the Google LB User Agent via "ua-restriction" plugin

It's far from perfect, but it works well and has the advantage of not sending traffic until apisix has started and loaded its configuration

here is the config I use
```
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: root-health-check
  namespace: apisix
spec:
  ingressClassName: apisix
  http:
    - name: root-health-check
      match:
        paths:
          - "/healthz"
        methods:
          - GET
      plugins:
        - name: ua-restriction
          enable: true
          config:
            allowlist:
              - "GoogleHC/1.0"
            message: "Not allowed"
        - name: mocking
          enable: true
          config:
            _meta:
              priority: 2000
            content_type: "text/plain"
            response_status: 200
            response_example: "OK"
```

On Google LB side, you have to configure the healthcheck this way, I'm doing it via BackendConfig but you can do it manually if you prefer

```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: apisix-backendconfig
  namespace: apisix
spec:
  healthCheck:
    port: 9080
    requestPath: /healthz
    type: HTTP
```

There is another way to do a health check via the control port 9090 (control) and path `/v1/healthcheck`, but you have no guarantee that the configuration is loaded, just that the service is up, i don't recommend it
