### DISCUSSION TITLE
Combining Global and Route-Specific Plugins in ApisixRoute

### DISCUSSION THREAD

**Discussion by sopacifics** [apache/apisix#12024] [Q&A] [answered]
Hi APISIX Team,

We are currently facing an issue when trying to combine the use of `plugin_config_name` with inline `plugins` definitions within a single ApisixRoute resource. Our goal is to have a global plugin (for example, an OIDC configuration) applied to multiple routes, while still allowing route-specific plugins (such as proxy-rewrite) to be defined inline without repeating the global configuration on every route.

**Scenario:**

- **Not Working (Using Both `plugin_config_name` and inline `plugins`):**

  ```yaml
  apiVersion: apisix.apache.org/v2
  kind: ApisixRoute
  metadata:
    name: nginx-route
    namespace: api-gateway
  spec:
    http:
    - name: nginx-rule
      match:
        paths:
          - /nginx/*
      plugins:
      - name: proxy-rewrite
        enable: true
        config: 
          regex_uri:
          - "^/nginx/(.*)"
          - "/$1"
      backends:
      - serviceName: nginx-service
        servicePort: 80
      plugin_config_name: oidc-global
  ```

  In this configuration, only the plugins defined in the referenced ApisixPluginConfig (`nginx-oidc-global`) are applied. The inline `proxy-rewrite` plugin is ignored.

- **Working (Defining All Plugins Inline):**

  ```yaml
  apiVersion: apisix.apache.org/v2
  kind: ApisixRoute
  metadata:
    name: nginx-route
    namespace: api-gateway
  spec:
    http:
    - name: nginx-rule
      match:
        paths:
          - /*
          - /nginx/*
      plugins:
      - name: proxy-rewrite
        enable: true
        config: 
          regex_uri:
          - "^/nginx/(.*)"
          - "/$1"
      - name: openid-connect 
        enable: true
        config:
          client_id: "**********************************"
          client_secret: "**********************************"
          discovery: "https://sso-**********************************"
          redirect_uri: "http://**********************************/"
          scope: "openid profile"
          bearer_only: true
          introspection_endpoint_auth_method: "client_secret_basic"
          realm: "master"
      backends:
      - serviceName: nginx-service
        servicePort: 80
  ```

 In this case, both the OIDC and proxy-rewrite plugins are applied, but I need to repeat the OIDC configuration in every ApisixRoute.

**Question:**

Is there any supported way to combine a global plugin configuration (such as openid-connect via `plugin_config_name`) with additional route-specific plugins (like proxy-rewrite) in a single ApisixRoute resource without having to duplicate the global configuration on each route? If not, is the recommended approach to handle this scenario?

We’d appreciate any guidance or workarounds you might suggest for this scenario.

Thanks in advance for your help!

Best regards,

Sofia

**Comment by dosubot** [comment]
Hey @sopacifics! I'm here to help you with any bugs, questions, or contributions. Let's tackle this issue together while we wait for a human maintainer.


Yes, there is a supported way to achieve this in APISIX. You can use the ApisixPluginConfig CRD to extract and reuse commonly used plugins and bind them directly to a route. This allows you to avoid duplicating the global configuration on each route.

When you use `plugin_config_name` to reference a global plugin configuration, the plugins from the ApisixPluginConfig will be merged with the route's inline `plugins`. However, if the same plugin is defined both in the global configuration and inline, the inline configuration will not override the global one.

Here's an example of how you can configure this:

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: nginx-route
  namespace: api-gateway
spec:
  http:
  - name: nginx-rule
    match:
      paths:
        - /nginx/*
    plugin_config_name: nginx-oidc-global
    plugins:
    - name: proxy-rewrite
      enable: true
      config: 
        regex_uri:
        - "^/nginx/(.*)"
        - "/$1"
    backends:
    - serviceName: nginx-service
      servicePort: 80
```

In this setup, the `proxy-rewrite` plugin is added specifically for the route, while the global OIDC configuration from the `nginx-oidc-global` Plugin Config is applied to the route. This way, you can combine global and route-specific plugins without duplicating the global configuration on each route <sup>[[1]](https://github.com/apache/apisix/blob/master/docs/zh/latest/terminology/plugin-config.md)</sup><sup>[[2]](https://github.com/apache/apisix/blob/master/docs/en/latest/terminology/plugin-config.md)</sup><sup>[[3]](https://apisix.apache.org/docs/ingress-controller/next/concepts/apisix_route)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/ba4e7614-0ad8-406a-838a-c0c91d6e8c8a?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/ba4e7614-0ad8-406a-838a-c0c91d6e8c8a?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/ba4e7614-0ad8-406a-838a-c0c91d6e8c8a?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/ba4e7614-0ad8-406a-838a-c0c91d6e8c8a?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/ba4e7614-0ad8-406a-838a-c0c91d6e8c8a?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/ba4e7614-0ad8-406a-838a-c0c91d6e8c8a?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/ba4e7614-0ad8-406a-838a-c0c91d6e8c8a?feedback_type=other)</sup>
