### DISCUSSION TITLE
Custom plugin not found

### DISCUSSION THREAD

**Discussion by samimusallam** [apache/apisix#12059] [Q&A]
Hi, I have APISIX setup as a helm chart with values.yaml containing various configuration.
I'm trying to create a custom plugin that after authenticating with okta using the openid-connect plugin, will validate with an IAM Service that the user/client can access the requested endpoint.
I followed [this tutorial](https://apisix.apache.org/docs/ingress-controller/next/tutorials/using-custom-plugins/) but couldnt get the custom plugin to be recognized by APISIX.
Im assuming this tutorial is out of date as when I add the customPlugin config to my values.yaml I get the following error:

```
apisix:
- customPlugins: luaPath is required
```

This is my values.yaml:

```
apisix:
  customPlugins:
    enabled: true
    luaPath: "/apisix/plugins/?.lua"
    plugins:
      - name: "custom-iam-auth"
        attrs: { }
        configMap:
          name: "custom-plugin-config"
          mounts:
            - key: "custom-iam-auth.lua"
              path: "/usr/local/apisix/apisix/plugins/custom-iam-auth.lua"
  
  plugins:
    - custom-iam-auth
  
  openid-connect:
    enabled: true

  gateway:
    type: NodePort

  dashboard:
    enabled: true

  ingress-controller:
    enabled: true
    config:
      apisix:
        serviceNamespace: apisix
        adminAPIVersion: v3
```
My Chart.yaml:
```
apiVersion: v2
name: apisix
version: 1.0.0
dependencies:
  - name: apisix
    version: "2.10.0"
    repository: "https://charts.apiseven.com"
```

Things I've tried:
* `kubectl exec -it apisix-**** -- ls apisix/plugins/` Could not find the custom-iam-auth.lua in this path
* describing a route that uses the custom plugin shows an error: ` * unexpected status code 400; error message: {"error_msg":"unknown plugin [custom-iam-auth]"}`

**Comment by dosubot** [comment]
Hello, @samimusallam! I'm here to help you with any bugs or questions you have while we wait for a human maintainer. Let's get started!


I found a similar open issue where a user faced a problem with custom plugins not being recognized by APISIX. The suggested solution involved ensuring that the `extra_lua_path` is correctly set and that the Lua files are placed in the correct directory structure <sup>[[1]](https://github.com/apache/apisix/issues/11639)</sup>.

For your specific case, here are some steps to troubleshoot and resolve the issue:

1. **Lua Path Configuration**: Ensure that the `luaPath` in your `values.yaml` is correctly pointing to the directory where your Lua files are located. It should be set to the directory containing your custom plugin files. For example:
   ```yaml
   customPlugins:
     enabled: true
     luaPath: /usr/local/apisix/apisix/plugins/?.lua
   ```

2. **Directory Structure**: Verify that your custom plugin file `custom-iam-auth.lua` is placed in the correct directory within the APISIX container. The path should match the `luaPath` configuration. You can check this by executing:
   ```bash
   kubectl exec -it <apisix-pod-name> -- ls /usr/local/apisix/apisix/plugins/
   ```

3. **ConfigMap Setup**: Ensure that the ConfigMap is correctly set up and mounted. The path specified in the ConfigMap should match the directory structure expected by APISIX.

4. **Plugin Activation**: Make sure that your custom plugin is listed in the `plugins` section of your `values.yaml` file, as you have done.

5. **Restart APISIX**: After making changes, restart the APISIX pods to ensure that the new configuration is loaded.

By following these steps, you should be able to resolve the issue with your custom plugin not being recognized by APISIX.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/f9c2718f-e179-46a0-9b5b-211e03e1e0a0?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/f9c2718f-e179-46a0-9b5b-211e03e1e0a0?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/f9c2718f-e179-46a0-9b5b-211e03e1e0a0?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/f9c2718f-e179-46a0-9b5b-211e03e1e0a0?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/f9c2718f-e179-46a0-9b5b-211e03e1e0a0?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/f9c2718f-e179-46a0-9b5b-211e03e1e0a0?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/f9c2718f-e179-46a0-9b5b-211e03e1e0a0?feedback_type=other)</sup>

**Reply by samimusallam** [reply]
@dosu I've tried these steps, but I still cannot see the custom-iam-auth.lua in /usr/local/apisix/apisix/plugins/

**Reply by dosubot** [reply]
Ensure that the ConfigMap is correctly configured and mounted in your Kubernetes setup. Here are some steps to verify and troubleshoot:

1. **Check ConfigMap Configuration**: Verify that the ConfigMap is correctly defined in your Kubernetes manifest. It should include the `custom-iam-auth.lua` file with the correct key and path.

2. **Mount the ConfigMap**: Ensure that the ConfigMap is mounted to the correct path in the APISIX pod. You can check the pod's volume mounts to confirm this.

3. **Verify Pod Configuration**: Use `kubectl describe pod <apisix-pod-name>` to check if the ConfigMap is mounted correctly. Look for the volume mounts section to ensure the path `/usr/local/apisix/apisix/plugins/` includes your custom plugin.

4. **Check for Errors**: Review the APISIX pod logs for any errors related to loading the custom plugin. This can provide insights into what might be going wrong.

5. **Reapply Configurations**: If there are any discrepancies, update the ConfigMap and reapply the configurations using `kubectl apply -f <your-config-file.yaml>`, then restart the APISIX pods.

These steps should help ensure that your custom plugin is correctly placed and recognized by APISIX.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/5ff6dc02-fd3e-4be4-a1d2-f66a5d278ef3?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/5ff6dc02-fd3e-4be4-a1d2-f66a5d278ef3?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/5ff6dc02-fd3e-4be4-a1d2-f66a5d278ef3?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/5ff6dc02-fd3e-4be4-a1d2-f66a5d278ef3?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/5ff6dc02-fd3e-4be4-a1d2-f66a5d278ef3?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/5ff6dc02-fd3e-4be4-a1d2-f66a5d278ef3?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/5ff6dc02-fd3e-4be4-a1d2-f66a5d278ef3?feedback_type=other)</sup>

**Reply by samimusallam** [reply]
I went over these steps, I'm not missing any of these things yet I still don't see the custom plugin

**Reply by timdavidfriedrich** [reply]
Hi @samimusallam, I have the same issue, did you solve it?

**Reply by samimusallam** [reply]
Hi @timdavidfriedrich, this is what solved the issue:

```
apisix:
  service:
    type: NodePort
    
  dashboard:
    enabled: true
    
  apisix:
    plugins:
      - openid-connect
      - proxy-rewrite

    customPlugins:
      enabled: true
      luaPath: "/opt/?.lua"
      plugins:
        - name: "custom-plugin"
          attrs: { }
          configMap:
            name: "custom-plugin-config"
            mounts:
              - key: "custom-plugin.lua"
                path: "/opt/apisix/plugins/custom-plugin.lua"
```
If I want to modify the dashboard, I can simply add a `dashboard` section under the root `apisix` section in my values.yaml. However, when looking at [the official values.yaml](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml), I noticed that the `customPlugins` section is nested under another `apisix` block. Once I added an additional `apisix` section under the root `apisix`, everything started working.

Hope this helps :)
