### DISCUSSION TITLE
APISIX 100% Memory Usage on RedHat Openshift Kubernetes Cluster

### DISCUSSION THREAD

**Discussion by geeky-akshay** [apache/apisix#12227] [Q&A] [answered]
Hi Community,

I'm seeing high memory usage of apisix-data-plane pod on RedHat Openshift Cluster. After periodic requests the usage climbs up to 100%. Where as on AWS EKS cluster the memory usage is significantly low.

On RedHat Openshift Cluster, the memory limit is set to 3Gi and it is using 100% of the memory.
```
$ oc adm top pods -n apisix
NAME                                        CPU(cores)   MEMORY(bytes)
apisix-control-plane-98ccc95b8-v2lgl        154m         2530Mi
apisix-dashboard-5ff849bcc8-fsh9j           15m          47Mi
apisix-data-plane-75cfc58f96-2chzv          288m         3071Mi
```
```
$ oc describe deployment apisix-data-plane | grep -i limits -A 3
    Limits:
      cpu:                1500m
      ephemeral-storage:  2Gi
      memory:             3Gi
```

Where as on AWS EKS Cluster
```
$ kubectl top pod -n apisix
NAME                                        CPU(cores)   MEMORY(bytes)
apisix-control-plane-f788744f-zqdfg         37m          339Mi
apisix-dashboard-5d98674fc4-rxnq2           67m          52Mi
apisix-data-plane-558498cf46-q25mc          22m          373Mi
```

APISIX VERSION: 3.12.0
```
$ apisix version
/opt/bitnami/apisix/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
3.12.0
```
LUAROCKS VERSION: 3.8.0
```
$ luarocks --version
/opt/bitnami/apisix/openresty/bin/luarocks 3.8.0
LuaRocks main command-line interface
```

Can anyone help me identify the issue?

Thanks

**Comment by juzhiyuan** [comment]
Hi @geeky-akshay , to debug the root reason, we need a relroducable env like yours.

1. Your configurations (Gateway and Services/Plugins)
2.  Your deployment.

Can you take some time to orgainze and send it to us? so we can have a try

**Comment by geeky-akshay** [comment]
### Environment
RedHat Openshift Container Platform Version: 4.16.36
```
$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.16.36   True        False         13d     Cluster version is 4.16.36
```

LoadBalancer: MetalLB
MetalLB is installed using metallb operator (https://docs.redhat.com/en/documentation/openshift_container_platform/4.9/html/networking/load-balancing-with-metallb#metallb-operator-install)
You'll have to create necessary L2Advertisemet and IPAddressPool which will be used by APISIX for External IP address

Monitoring Stack: https://docs.redhat.com/en/documentation/openshift_container_platform/3.11/html/configuring_clusters/prometheus-cluster-monitoring#installing-monitoring-stack

### Deployment
APISIX is deployed using Bitnami Helm Chart: https://github.com/bitnami/charts/tree/main/bitnami/apisix (version: 4.2.5, appVersion: 3.12.0)

Custom Values:
```yaml
global:
  security:
    allowInsecureImages: true

controlPlane:
  extraConfig:
    apisix:
      ssl:
        ssl_trusted_certificate: '/bitnami/certs/{{ .Values.controlPlane.tls.certCAFilename }}'
  lifecycleHooks:
    postStart:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            sleep 5;
            rm /usr/local/apisix/logs/worker_events.sock
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        clusterobservability: "1"
        cluster_component: "apisix-control-plane"
      metricRelabelings:
      - targetLabel: "cluster_component"
        replacement: "apisix-control-plane"
  resourcesPreset: "large"
dataPlane:
  extraConfig:
    apisix:
      ssl:
        fallback_sni: "apisix-data-plane.local"
    plugin_attr:
      prometheus:
        metrics:
          http_status:
            expire: 600
          http_latency:
            expire: 600
          bandwidth:
            expire: 600
          upstream_status:
            expire: 600
      redirect:
        https_port: 443
  lifecycleHooks:
    postStart:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            sleep 5;
            rm /usr/local/apisix/logs/worker_events.sock
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        clusterobservability: "1"
        cluster_component: "apisix-data-plane"
      metricRelabelings:
      - targetLabel: "cluster_component"
        replacement: "apisix-data-plane"
  resourcesPreset: "large"
ingressController:
  extraConfig:
    apisix_resource_sync_interval: 30m
    kubernetes:
      resync_interval: 1h
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        clusterobservability: "1"
        cluster_component: "apisix-ingress-controller"
      metricRelabelings:
      - targetLabel: "cluster_component"
        replacement: "apisix-ingress-controller"
  replicaCount: 3
  resourcesPreset: "small"
etcd:
  autoCompactionMode: "revision"
  autoCompactionRetention: "3"
  extraEnvVars:
    - name: ETCD_QUOTA_BACKEND_BYTES
      value: "4294967296"
  metrics:
    enabled: true
    podMonitor:
      enabled: true
      namespace: "openshift-monitoring"
      additionalLabels:
        clusterobservability: "1"
        cluster_component: "apisix-etcd"
      relabelings:
      - targetLabel: "cluster_component"
        replacement: "apisix-etcd"
  resourcesPreset: null
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
```

Extra Resources:
ApisixClusterConfig.yaml
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixClusterConfig
metadata:
  name: default
  namespace: apisix
spec:
  monitoring:
    prometheus:
      enable: true
```

ApisixGlobalRule.yaml
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: global
  namespace: apisix
spec:
  plugins:
    - name: redirect
      enable: true
      config:
        http_to_https: true
```

ApisixTls.yaml
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: apisix-tls
  namespace: apisix
spec:
  hosts:
  - <APISIX-EXTERNAL-IP-ADDRESS>
  - apisix-data-plane.local
  secret:
    name: <CERT-CONTAINING-APISIX-EXTERNAL-IP-ADDRESS>
    namespace: apisix
```
