### DISCUSSION TITLE
APISIX Standalone 'plugin_configs'

### DISCUSSION THREAD

**Discussion by singhjoga** [apache/apisix#5615] [Q&A] [answered]
Hi Guys,
What is the equaivalent of '/apisix/admin/plugin_configs' in the Standalone mode?
At the moment I am using 'global_rules' to do the same thing. Is it the same as 'plugin_configs' in Admin API? 
I would like to create plugin configs with Ids and use them in routes/services as with 'plugin_configs'. However, I could not find the documentation for the same in standalone mode.

Regards,

Joga

**Comment by tokers** [comment, marked as answer]
@singhjoga Hi,

Try to define a plugin config object with an id assigned by yourself, and use the plugin_config_id in the Route.

**Comment by boekkooi-lengoo** [comment]
As an example you can use something like:
```YAML
    plugin_configs:
      - id: customer-auth
        desc: "Ensure the user is an authenticated customer"
        plugins:
          openid-connect: {}
```
