### DISCUSSION TITLE
ingress https backend

### DISCUSSION THREAD

**Discussion by tirelibirefe** [apache/apisix#6771] [Q&A] [answered]
Hello,
At NGINX, we can define backend protocol by the following annotation:

`nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"`

Is there an alternative at apisixroute?

Please look at my Kibana apisix route:

```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: $KIBANANAME
  namespace: $NAMESPACE
  annotations:
    k8s.apisix.apache.org/backend-protocol: "HTTPS" ### not working
spec:
  http:
    - name: root
      match:
        hosts:
          - $KIBANANAME.myawesomedomain.com
        paths:
          - /*
      backends:
      - serviceName: $KIBANANAME-kb-http
        servicePort: 5601
      websocket: true

```
