### DISCUSSION TITLE
MicroK8s, ApiSix and MetalLB

### DISCUSSION THREAD

**Discussion by MarkCupitt** [apache/apisix#7226] [Q&A]
I am trying to configure ApiSix without using Ingress behind MetalLB with a public network and a private Network (For admin access) on MIcroK8s.

We would like to use the admin-api (JSON) for all configuration, We understand that apisix-Ingress requires use of declarative YAML.

Question 1: Is this actually possible

If Yes ..

Question 2: Any reason to NOT do this.
Question 3: Can I use a Sevice account like this to connect to the API port (9080)?

```
apiVersion: v1
kind: Service
metadata:
  name: apisix-external-service
spec:
  type: LoadBalancer
  selector:
    name: apisix
  ports:
    - name: apisix-gateway
      protocol: TCP
      port: 80
      targetPort: 9080
```
Question 4: Will this scale OK
Question 5: Is there a better way to do this

Many thanks in advance
