### DISCUSSION TITLE
性能测试结果，apisix对比nginx不符合预期，请教一下是什么原因

### DISCUSSION THREAD

**Discussion by lanss315425** [apache/apisix#7618] [General]
您好，我在阿里云ecs测试了apisix，预期是想取代nginx，但是性能差异太大，希望提出宝贵意见

运行主机环境：node01 阿里云ecs 8核 16G
apisix：2.15.0
etcd：3.5.4 

测试主机环境：node02 阿里云ecs 8核 16G
etcd：3.5.4 
wrk：4.0.2

运行主机环境：node03 阿里云ecs 8核 16G
etcd：3.5.4 
nginx：1.23.0 

压测nginx：
```
docker run --rm --add-host api.test.com:node03 williamyeh/wrk:4.0.2 -t30 -c800 -d30s http://api.test.com:81/api/test01 
Running 30s test @ http://api.test.com:81/api/test01
 30 threads and 800 connections
   Thread Stats   Avg      Stdev     Max   +/- Stdev
   Latency     9.05ms   11.49ms 230.00ms   91.72%
   Req/Sec     3.74k   653.80    11.53k    75.84%
   3358997 requests in 30.10s, 4.97GB read
Requests/sec: 111612.65
Transfer/sec:    169.14MB
```

apisix config.yaml配置
```
apisix:
  node_listen:                      # This style support multiple ports
    - 80
  port_admin: 9180
  allow_admin:
    - 0.0.0.0/0
  ssl:
    enable: true
    listen:                       # APISIX listening port in https.
      - 443
nginx_config:
  worker_rlimit_nofile: 65535
  event:
    worker_connections: 65535
  http:
    enable_access_log: false
etcd:
  host:
    - "http://node01:2379"
    - "http://node02:2379"
    - "http://node03:2379"
  prefix: "/apisix"
  timeout: 30
plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
```

配置一个反向代理，配置：
```
{
  "uri": "/*",
  "name": "test",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "host": "api.test.com",
  "plugins": {
  },
  "upstream": {
    "nodes": [
      {
        "host": "node03",
        "port": 81,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```

压测apisix：
```
docker run --rm --add-host api.test.com:node01 williamyeh/wrk:4.0.2 -t30 -c800 -d30s http://api.test.com/api/test
Running 30s test @ http://api.test.com/api/test
    30 threads and 800 connections 
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    25.76ms   46.51ms   2.00s    91.15%
    Req/Sec     1.67k   408.84     5.05k    71.62%
  1501211 requests in 30.10s, 2.23GB read
  Socket errors: connect 0, read 0, write 0, timeout 4
Requests/sec:  49881.15
Transfer/sec:     75.97MB
```
