### DISCUSSION TITLE
what's the difference between these two 'prometheus-metrics' ?

### DISCUSSION THREAD

**Discussion by liuguangyu133** [apache/apisix#8170] [Q&A] [answered]
config-default.yaml: 
```
nginx_config:
  meta:
    lua_shared_dict:
      prometheus-metrics: 15m
  http:
    lua_shared_dict:
      prometheus-metrics: 10m
```
