### DISCUSSION TITLE
help request: how to configure file-log plugin?

### DISCUSSION THREAD

**Discussion by ederparaiso** [apache/apisix#8292] [Q&A]
I tried to enable file-log plugin on my route but no file was created. What i missed? Any aditional config in other place/entity?

If I use a relative path, as doc example (logs/file.log), what is the base directory?

```yaml
uri: /test/*
name: test
priority: 7
methods:
  - GET
  - OPTIONS
plugins:
  file-logger:
    path: /file.log
upstream:
  nodes:
    - host: my.host.com
      port: 443
      weight: 1
  timeout:
    connect: 6
    send: 6
    read: 6
  type: roundrobin
  scheme: https
  pass_host: pass
  keepalive_pool:
    idle_timeout: 60
    requests: 1000
    size: 320
status: 1
```

Also, is there any way to log apisix requests to upstream services? Does file-log plugin records it?

APISIX version: 3.0.0
