### DISCUSSION TITLE
how can I use it with external-dns

### DISCUSSION THREAD

**Discussion by big-thousand** [apache/apisix#8327] [Q&A]
how can I use it with external-dns

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/blob/master/docs/en/latest/discovery/dns.md

**Reply by SamSpiri** [reply]
Question was about https://github.com/kubernetes-sigs/external-dns
I also didn't find the answer to this yet.

**Comment by SamSpiri** [comment]
I added this config to values.yml of helm chart:
```
gateway:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: 'my.domain.name'
```
That results in apisix external service have the annotation which is picked up by external-dns.
The same approach as in knative documentation https://github.com/dewitt/knative-docs/blob/master/serving/using-external-dns.md

I'd suffer less if apisix had this in it's own documentation.
