### DISCUSSION TITLE
APISIX retuen error 3 name error with multi Consul DNS

### DISCUSSION THREAD

**Discussion by Fabriceli** [apache/apisix#8338] [Q&A]
Version info:
- APISIX 3.0.0
- Consul 1.9.5
- Linux arch x86_64

ERROR:
```sh
[error] 43382#43382: *1626 [lua] init.lua:428: handle_upstream(): failed to set upstream: no valid upstream node: failed to query the DNS server: dns server error: 3 name error, client: a.a.a.a, server: _, request: "GET /api/v0/test/ HTTP/1.1", host: "b.b.b.b"
```

with `/usr/local/apisix/conf/config.yaml`:
```yaml
discovery:
  dns:
    servers:
      - "x.x.x.x:8600" 
      - "y.y.y.y:8600"
```
service A is **only** valid in Consul y.y.y.y:8600. APISIX is not support multi Consul DNS?

**Comment by Fabriceli** [comment]
Consul x.x.x.x:8600 and Cosnul y.y.y.y:8600 are not the same cluster.

**Comment by tzssangglass** [comment]
> service A is **only** valid in Consul y.y.y.y:8600. APISIX is not support multi Consul DNS?

After a quick review of the code, I think this should be supported. Can you describe in detail the reproduction steps?

**Reply by Fabriceli** [reply]
Step 1: add `x.x.x.x:8600` and `y.y.y.y:8600` in `/usr/local/apisix/conf/config.yaml` discovery.dns
```yaml
discovery:
  dns:
    servers:
      - "x.x.x.x:8600" 
      - "y.y.y.y:8600"
```
and restart apisix

Step 2: add upstream `consul-test-x` with `[service name].service.[data center name].consul`
```yaml
{
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "scheme": "http",
  "discovery_type": "dns",
  "pass_host": "pass",
  "name": "consul-test-x",
  "service_name": "service-name-x.service.dc-name-x.consul",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}
```

Setp 3: add route
```yaml
{
  "uri": "/test/*",
  "name": "test",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "upstream_id": "434655845121262271",
  "status": 1
}
```

**service-name-x** only in `x.x.x.x:8600` consul cluster. 
if I commented `- "y.y.y.y:8600"` in `/usr/local/apisix/conf/config.yaml` and restart APISIX, i can get the correct response.
