### DISCUSSION TITLE
404 Route not Found with basic-auth

### DISCUSSION THREAD

**Discussion by perbellinie** [apache/apisix#8743] [Q&A]
Hi I have configured apisix in the config.yaml file "apisix: config_center: yaml " and I would like to use "basic-auth".
I entered the route but it is not working

```
routes:
  - id: 1
    uri: /*
    upstream_id: 1
    plugins:
      - name: basic-auth
        config:
          name: test
          password: test
upstreams:
  - id: 1
    type: roundrobin
    nodes:
      '127.0.0.1:9090': 1
#END
```
On every call we get the 404 route not found error. 
Where is the configuration error?

Thank You.
