### DISCUSSION TITLE
attempt to index upvalue 'router' (a nil value)

### DISCUSSION THREAD

**Discussion by attson** [apache/apisix#8757] [Q&A]
error.log: 

2023/01/31 15:30:26 [error] 20600#20600: *4428 lua entry thread aborted: runtime error: /home/dowte/LuaProjects/apisix-2.15.1/apisix/init.lua:809: attempt to index upvalue 'router' (a nil value)
stack traceback:
coroutine 0:
	/home/dowte/LuaProjects/apisix-2.15.1/apisix/init.lua: in function 'http_admin'
	content_by_lua(nginx.conf:250):2: in main chunk, client: 127.0.0.1, server: _, request: "GET /apisix/admin/routes?page=1&page_size=10 HTTP/1.1", host: "127.0.0.1:9080"

**Comment by attson** [comment]
I build from source code, follow https://apisix.apache.org/docs/apisix/2.15/building-apisix/

```
sudo apisix init
sudo apisix init_etcd
sudo apisix start
```

then 
```
curl http://127.0.0.1:9080/apisix/admin/routes -X GET -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1"
```
but got error.

**Reply by attson** [reply]
```
<!DOCTYPE html>
<html>
<head>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<meta content="utf-8" http-equiv="encoding">
<title>500 Internal Server Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>You can report issue to <a href="https://github.com/apache/apisix/issues">APISIX</a></p>
<p><em>Faithfully yours, <a href="https://apisix.apache.org/">APISIX</a>.</em></p>
</body>
</html>

```

**Comment by attson** [comment]
I try use apisix-3.1.0. got same error.
How to solve the problem ? need help.

**Reply by attson** [reply]
config.yaml

```
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin
```
