### DISCUSSION TITLE
404 Route Not Found

### DISCUSSION THREAD

**Discussion by perbellinie** [apache/apisix#8761] [Q&A]
I have these configuration  in apisix.yaml
```
consumers:
  - username: consumer1
    plugins:
        key-auth:
            key: auth-one

upstreams:
  - name: example_upstream
    nodes:
    - host: 127.0.0.1
      port: 8080

routes:
  - uri: /example
    upstream: example_upstream
    plugins:
        key-auth: consumer1
#END
```
and I changed the property config_center: yaml.

I call by browser url:"http://xxxxxx/example" but I receiver the same error 404.
Please help me, because I didn't understand wher is the error.
