### DISCUSSION TITLE
Mqtt proxy connections problem under pressure test

### DISCUSSION THREAD

**Discussion by liujun69** [apache/apisix#8801] [Q&A]
When performing a pressure test，Whether through the tcp proxy or configuring the mqtt-proxy plugin;The maximum number of connections is always only one or two thousand；Apisix service runs in docker,the running version is v2.14.1 & running by standalone mode
Is there any other configuration optimization I need to configure?
The following is the current configuration：
config.yaml
```
stream_proxy:
    tcp:
      - 9082
```
apisix.yaml
```
stream_routes:
    -
        upstream_id: 9 
        server_port: 9082
        scheme: tcp
upstreams:
    id: 9
        timeout:
             connect: 3600
             send: 3600
             read: 3600
        nodes:
             - 
               host: "172.16.15.151"
               port: 1883
               weight: 2
             - 
               host: "172.16.1.41"
               port: 1883
               weight: 1
             - 
               host: "172.16.1.83"
               port: 1883
               weight: 1 
        type: least_conn
        scheme: tcp
        keepalive_pool:
             size: 320
             idle_timeout: 300
             requests: 10000
```
The mqtt-proxy plug-in has not been improved through the following configuration：
```
stream_routes:
    -
        upstream_id: 9 
        server_port: 9082
        scheme: tcp
        plugins:
           mqtt-proxy: 
                protocol_name: "MQTT"
                protocol_level: 4
```
