### DISCUSSION TITLE
config ssl enable, but https not work

### DISCUSSION THREAD

**Discussion by defp** [apache/apisix#9184] [Q&A]
https://github.com/apache/apisix/blob/81149cd31567f6a86e33100fa7d09d7550073157/docs/zh/latest/FAQ.md#%E5%9C%A8%E5%A4%84%E7%90%86-http-%E6%88%96-https-%E8%AF%B7%E6%B1%82%E6%97%B6%E6%88%91%E8%AF%A5%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE-apache-apisix-%E6%9D%A5%E7%9B%91%E5%90%AC%E5%A4%9A%E4%B8%AA%E7%AB%AF%E5%8F%A3

deploy with docker compose 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/612381/228243628-879c6e83-3bd9-4566-93b8-f1894bbec361.png">

443 port 
<img width="2427" alt="image" src="https://user-images.githubusercontent.com/612381/228243738-0b3c7693-5963-41b9-b1b1-cd2fa3bdde3c.png">

docker-compose.yml config
```
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.2.0-debian}
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "80:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:
```


test

```
☸ dev (data-dev) in istio-inspect on  master [✓]  ➜
curl -v http://dataengine-kg-rest-svc.data-dev.nocodetech.cn/health
*   Trying 198.18.1.186:80...
* Connected to dataengine-kg-rest-svc.data-dev.nocodetech.cn (198.18.1.186) port 80 (#0)
> GET /health HTTP/1.1
> Host: dataengine-kg-rest-svc.data-dev.nocodetech.cn
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< date: Tue, 28 Mar 2023 12:59:47 GMT
< content-length: 16
< x-envoy-upstream-service-time: 3
< server: istio-envoy
<
* Connection #0 to host dataengine-kg-rest-svc.data-dev.nocodetech.cn left intact
{"kg-rest":true}%                                                                                                                                                                                                                                           
☸ dev (data-dev) in istio-inspect on  master [✓]  ➜
curl -v https://dataengine-kg-rest-svc.data-dev.nocodetech.cn/health
*   Trying 198.18.1.186:443...
* connect to 198.18.1.186 port 443 failed: Connection refused
* Failed to connect to dataengine-kg-rest-svc.data-dev.nocodetech.cn port 443 after 11 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to dataengine-kg-rest-svc.data-dev.nocodetech.cn port 443 after 11 ms: Couldn't connect to server
```

admin sni config

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/612381/228245938-4f5d92e5-f29f-400f-9501-99e95815c50d.png">
