### DISCUSSION TITLE
How to use multiple key-auth?

### DISCUSSION THREAD

**Discussion by lochen** [apache/apisix#9792] [General]
Hi,

I would like to set multiple key in one route, how can i setup it? thank you.

```

routes:
  -
    id: test
    uri: /test/*
    name: test
    username: test_keyauth
    plugins:
      proxy-rewrite:
        regex_uri:
          - /test/(.+)
          - /api/unknown
      key-auth:
        header: "X-API-KEY"
    upstream:
      nodes:
        "reqres.in:443": 1
      timeout:
        connect: 6
        send: 6
        read: 6
      type: roundrobin
      scheme: https
      pass_host: node
      keepalive_pool:
        idle_timeout: 60
        requests: 1000
        size: 320
    status: 1
consumers:
  - username: test_keyauth
    plugins:
        key-auth:
            key: 
            - "abcdef"
            - "foobarxyz"
```
