### DISCUSSION TITLE
jwt-auth： 404 not found in Stand-alone mode

### DISCUSSION THREAD

**Discussion by WwwJy** [apache/apisix#9817] [Q&A] [answered]
Hi Community

My Apisix service is started in Stand-alone mode
When I requested the  **/apisix/plugin/jwt/sign** interface to prepare to obtain a token, I received a result of 404 not found

I configured the content of auth and public-api on apisix.yaml according to the documents, but still obtained the same results

The guidance we are following include:
https://apisix.apache.org/docs/apisix/2.15/stand-alone/
https://apisix.apache.org/docs/apisix/2.15/plugins/public-api/
https://apisix.apache.org/zh/docs/apisix/2.15/plugins/jwt-auth/

Please refer to our operation step as Appendix.

The configuration of apisix.yaml is as follows
```
consumers:
- plugins:
    jwt-auth:
      key: user-key
      secret: my-secret-key
    public-api: {}
  uri: /apisix/plugin/jwt/sign
  username: jack
```

I noticed that there is very little description of apisix.yaml and there is no configuration template to refer to, which makes it difficult for me to determine if my configuration items are truly correct

Your feedback is really appreciated so much.

**Comment by WwwJy** [comment]
There was an error in my configuration. The plugin-api should be configured on the **route.** After I updated it, it should be like this
```
consumers:
- plugins:
    jwt-auth:
      key: user-key
      secret: my-secret-key
  username: jack
routes:
  plugins:
    public-api: {}
  uri: /apisix/plugin/jwt/sign
```
Now I have a new error
```log
[error]: failed to set upstream: missing upstream configuration in Route or Service
````

I don't understand why we need to configure upstream？

**Comment by WwwJy** [comment, marked as answer]
I solved it

The configuration that needs to be displayed is in the plugin list of **config.yaml**
```
apisix:
  config_center: yaml
  enable_admin: false
  ssl:
    listen_port:
      - 19080
  router:
    ssl: 'radixtree_sni'

plugins:
  - uri-blocker                    # priority: 2900
  - limit-count                    # priority: 1002
  - api-breaker                    # priority: 1005
  - proxy-rewrite                  # priority: 1008
  - jwt-auth
  - public-api

```
