### DISCUSSION TITLE
Override default timeout value.

### DISCUSSION THREAD

**Discussion by nphariharan** [apache/apisix#9896] [Q&A]
I am using APISIX 3.4 version(Standalone mode).

How to set a global timeout rule for all upstream servers? The default timeout value is 60 seconds. I want to override this 60 seconds to 900 seconds. 

Pl provide me a sample yaml configuration file to achieve the same.

Thanks,
Hariharan.

**Comment by moonming** [comment]
@Sn0rt please take a look

**Comment by Sn0rt** [comment]
nginx usually connects to upstream usually has three timeouts

1. connect timeout
2. read timeout
3. write timeout

let me check how setting this.


```yaml
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# example
routes:
  -
    uri: /hello
    upstream:
      nodes:
        "127.0.0.1:1980": 1
      type: roundrobin
      timeout:
        connect: 60s
        send: 60s
        read: 60s
#END
```

reference: https://github.com/apache/apisix/pull/3401/files
