### ISSUE TITLE
feat: Add health check to get healthy nacos nodes. 

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#10081]
### Description

How to configure multiple nacos to add weights, apisix documentation is really too simple.
my config:
```
discovery:                       # service discovery center
  nacos:
    host:
    - "http://ip1:8848"
    prefix: "/nacos/v1/"
    fetch_interval: 30    # default 30 sec
    weight: 1           # default 100
    timeout:
      connect: 2000       # default 2000 ms
      send: 2000          # default 2000 ms
      read: 5000          # default 5000 ms
    host:
    - "http://ip2:8848"
    prefix: "/nacos/v1/"
    fetch_interval: 30    # default 30 sec
    weight: 2           # default 100
    timeout:
      connect: 2000       # default 2000 ms
      send: 2000          # default 2000 ms
      read: 5000          # default 5000 ms
```

The configuration cannot be invalidated because ip1 is always matched

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
