### ISSUE TITLE
help request: APISIX behind NGINX - Openid-connect issue

### ISSUE THREAD

**Issue by slysiou** [apache/apisix#10149]
### Description

Hi,

I am using the container [jc21/nginx-proxy-manager](https://hub.docker.com/r/jc21/nginx-proxy-manager) as the first reverse proxy. Very convenient UI to generate and update SSL certificate.
APISIX after this first NGINX.

Internet --- NGINX proxy manager --- APISIX with openid-connect --- Web app

After authentication, redirection to `https://xxxx.com:/callback?state=XXXXX&session_state=xxxxx&code=xxxx` generate this error: 
```
XXXXX XXXX [error] 54#54: *52215124 [lua] openidc.lua:1475: authenticate(): request to the redirect_uri path but there's no session state found ...
```

If I bypass the first NGINX (using [ngrok](https://ngrok.com/)) everything works fine.

I get to the conclusion that the first NGINX is blocking an information needed for openid-connect. But, after 2 days searching, I can't find it.

Is anyone using the same kind of architecture ?
Any idea of the missing information ?

Env:

### Environment

- APISIX container: [apache/apisix:3.4.1-debian](https://hub.docker.com/r/apache/apisix)
- NGINX Manager: [jc21/nginx-proxy-manager](https://hub.docker.com/r/jc21/nginx-proxy-manager)

**Comment by slysiou** [comment]
Thanks @Revolyssup,

I activated debug using debug.yaml:
```yaml
basic:
  enable: true
http_filter:
  enable: false         # enable or disable this feature
  enable_header_name: X-APISIX-Dynamic-Debug # the header name of dynamic enable
hook_conf:
  enable: true                 # enable or disable this feature
  name: hook_phase              # the name of module and function list
  log_level: debug               # log level
  is_print_input_args: true     # print the input arguments
  is_print_return_value: true   # print the return value

hook_phase:                     # module and function list, name: hook_phase
  apisix:                       # required module name
    - http_access_phase         # function name
    - http_header_filter_phase
    - http_body_filter_phase
    - http_log_phase

#END
```
But I didn't get much details.

How to run APISIX in the debug mode you are talking ?
