### ISSUE TITLE
help request: Ingress routing returns HTTP ERROR 400

### ISSUE THREAD

**Issue by ventaubain** [apache/apisix#10228]
### Description

I have a Minio instance with TLS enabled so I can communicate with it by HTTPS on the port 9443 (console GUI interface) with a port-forward. I want forward requests with an Apisix Ingress instance to replace the port-forward. To do that, I apply the following configuration with TLS enabled between user and ingress but I have an HTTP ERROR 400 as result.

The problem seems to be between ingress and Minio instance. My hypothesis is that Apisix upstream communicates in HTTP and not HTTPS so Minio refuses to communicate but I don't know how verify that and if it is, how modify the upstream from the ApisixRoute definition.

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-storage-ingress-cert
  namespace: minio-storage
spec:
  dnsNames:
    - "gui.minio.app.ccg"
    - "*.miniod.app.ccg"
  issuerRef:
    kind: Issuer
    name: minio-storage-issuer
  secretName: minio-storage-ingress-cert-secret
  usages:
    - digital signature
    - key encipherment
  renewBefore: 96h0m0s
  duration: 2160h0m0s
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: minio-storage-route
  namespace: minio-storage
spec:
  http:
    - name: minio-storage
      match:
        hosts:
          - gui.minio.app.ccg
        paths:
          - "/*"
      backends:
        - serviceName: minio-storage-console
          servicePort: 9443
      #websocket: true
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: minio-storage-tls
spec:
  hosts:
    - gui.minio.app.ccg
  secret:
    name: minio-storage-ingress-cert-secret
    namespace: minio-storage
```

Log from apisix
```
10.0.3.92 - - [18/Sep/2023:13:15:06 +0000] gui.minio.app.ccg:32443 "GET / HTTP/1.1" 400 729 0.000 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" - - - "://"
10.0.3.92 - - [18/Sep/2023:13:15:07 +0000] gui.minio.app.ccg:32443 "GET /favicon.ico HTTP/1.1" 400 729 0.000 "http://gui.miniod47.app.ccg:32443/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" - - - "://"
```

### Environment

- APISIX version (run `apisix version`): 3.5.0
