### ISSUE TITLE
help request: 'failed to process entries: closed' when using elasticsearch-logger

### ISSUE THREAD

**Issue by coco961003** [apache/apisix#10276]
### Description

Log:
```shell
2023/09/28 08:54:09 [error] 49#49: *184583 [lua] batch-processor.lua:95: Batch Processor[elasticsearch-logger] failed to process entries: closed, context: ngx.timer, client: 192.168.137.254, server: 0.0.0.0:9080
2023/09/28 08:54:09 [error] 49#49: *184583 [lua] batch-processor.lua:104: Batch Processor[elasticsearch-logger] exceeded the max_retry_count[1] dropping the entries, context: ngx.timer, client: 192.168.137.254, server: 0.0.0.0:9080
```

```json
{
            "value": {
                "plugins": {
                    "elasticsearch-logger": {
                        "max_retry_count": 0,
                        "endpoint_addr": "<my ip address>",
                        "buffer_duration": 60,
                        "retry_delay": 1,
                        "name": "elasticsearch-logger",
                        "field": {
                            "index": "services"
                        },
                        "auth": {
                            "password": "<my-pwd>",
                            "username": "elastic"
                        },
                        "batch_max_size": 1000,
                        "timeout": 10,
                        "inactive_timeout": 5,
                        "ssl_verify": true
                    }
                },
                "status": 1,
                "priority": 0,
                "create_time": 1695887308,
                "id": "test-es",
                "uri": "/*",
                "upstream_id": 1,
                "host": "test-es.com",
                "update_time": 1695891235
            },
            "createdIndex": 972,
            "modifiedIndex": 978,
            "key": "/apisix/routes/test-es"
        }
```

```yml
    elasticsearch:
        image: elasticsearch:8.10.1
        container_name: elasticsearch
        environment:
          - ES_JAVA_OPTS=-Xms512m -Xmx512m
          - discovery.type=single-node
        volumes:
          - es-data:/usr/share/elasticsearch/data
          - es-plugins:/usr/share/elasticsearch/plugins
        privileged: true
        ports:
          - "9200:9200"
          - "9300:9300"
        networks:
          apisix:
```
Thank you.

### Environment

- APISIX version (run `apisix version`): 3.5
- ES version: 8.10.1
