### ISSUE TITLE
help request: SSL_do_handshake() failed

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#10325]
### Description

Hello.
I receive this error when trying to send request:

`SSL_do_handshake() failed (SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:SSL alert number 40) while SSL handshaking to upstream, client: 10.10.53.97, server: _, request: "PUT /accounts/v1/ids HTTP/1.1", upstream: "https://xx.xxx.xxx.xx:443/accounts/v1/ids", host: "xxx.com"`

But when I use curl to access upstream directly it works fine. What could be the reason?

My route is very simple:

```
curl "http://127.0.0.1:9180/apisix/admin/routes/12" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["PUT"],
  "uri": "/accounts/v1/ids",
  "upstream": {
    "type": "roundrobin",
	"scheme": "https",
    "nodes": {
      "xxx.com": 1
    }
  }
}'
```

### Environment

- APISIX version (run `apisix version`): 3.5
- Operating system (run `uname -a`): Red Hat
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by PlasticJonbenetDoll** [comment]
I tried to add ciphers to config.yaml but nothing changed:
```
apisix:
  router:
    http: 'radixtree_uri_with_parameter'
  ssl:
    ssl_protocols: TLSv1.2 TLSv1.3
    ssl_ciphers: TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
```
