### ISSUE TITLE
bug: failed to parse graphql

### ISSUE THREAD

**Issue by GuoMonth** [apache/apisix#10346]
### Current Behavior

this my request

``` csharp
 public async Task<PageData<ClientInfoData>> RetrieveByPage(int index, int size)
        {
            GraphQLRequest fetchQuery = new()
            {
                Query = @"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {
    tClientInfo(
        filters: { status: { eq: 1 } }
        pagination: { page: { limit: $pageSize, page: $pageIndex } }
        orderBy: { updateTime: DESC }
    ) {
        nodes {
            id
            clientId
            clientCode
            clientName
            status
            createUser
            createTime
            remark
            updateTime
            updateUser
        }
        paginationInfo {
            pages
            current
        }
    }
}",
                Variables = new
                {
                    pageSize = size,
                    pageIndex = index,
                },
            };

            var token = await this.LocalStorage.GetItemAsync<string>("Token");
            this.GraphqlHttp.HttpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var fetchResJson = await this.GraphqlHttp.SendQueryAsync<JsonDocument>(fetchQuery);
 // ....
}
```

### Expected Behavior

get a respond

### Error Logs

```
2023/10/17 00:55:32 [error] 50#50: *577068048 [lua] ctx.lua:138: get_parsed_graphql(): failed to parse graphql: Syntax error near line 1 body: {"query":"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {\n    tClientInfo(\n        filters: { status: { eq: 1 } }\n        pagination: { page: { limit: $pageSize, page: $pageIndex } }\n        orderBy: { updateTime: DESC }\n    ) {\n        nodes {\n            id\n            clientId\n            clientCode\n            clientName\n            status\n            createUser\n            createTime\n            remark\n            updateTime\n            updateUser\n        }\n        paginationInfo {\n            pages\n            current\n        }\n    }\n}\n","variables":{"pageSize":15,"pageIndex":0}}, client: 172.17.0.15, server: _, request: "POST /client/graphql HTTP/1.1"
```

### Steps to Reproduce

1. Run APISIX in k8s
2. config route
3. use C# GraphQL.Client.Http.GraphQLHttpClient request.

the route config info:

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: fx-client-route
spec:
  http:
  - name: fx-client-rule-1
    match:
      paths:
      - /client/save/*
      - /client/find_client_info_by_page
    backends: 
      - serviceName: fx-service-client-service
        servicePort: 8007
    plugins:
      - name: jwt-auth
        enable: true
      - name: cors
        enable: true
  - name: fx-client-rule-2
    match:
      methods: ["GET"]
      paths:
      - /client/hi
      - /client/graphql
    backends: 
      - serviceName: fx-service-client-service
        servicePort: 8007
    plugins:
      - name: cors
        enable: true
  - name: fx-client-rule-3
    match:
      methods: ["POST"]
      paths:
      - /client/graphql
      exprs:
      - subject:
          scope: Variable
          name: graphql_operation
        op: Equal
        value: query
    backends: 
      - serviceName: fx-service-client-service
        servicePort: 8007
    plugins:
      - name: jwt-auth
        enable: true
      - name: cors
        enable: true
```

### Environment

- APISIX image version apache/apisix：3.4.0-debian

**Comment by GuoMonth** [comment]
in my local, without APISIX, direct request GraphQL Servier is success.

**Comment by kayx23** [comment]
You mean direct request **from your C# app** to GraphQL Server without APISIX sitting in the middle works alright?

**Comment by GuoMonth** [comment]
Yes

**Comment by kayx23** [comment]
@Revolyssup please take a look

**Comment by Revolyssup** [comment]
@GuoMonth Can you add the "GET" method here as well?
```yaml
      methods: ["POST","GET"]
      paths:
      - /client/graphql
```

**Comment by kayx23** [comment]
Not sure if adding `GET` helps as the config has `exprs` below to match requests. Does it work if you remove the `exprs`?

```
      exprs:
      - subject:
          scope: Variable
          name: graphql_operation
        op: Equal
        value: query
```

Also I don't see `Variable` as an acceptable value for the `scope` in the [doc](https://github.com/apache/apisix-ingress-controller/blob/0736bba3f3bda0d47620ef1c6414f73d5b2056e5/docs/en/latest/references/apisix_route_v2.md?plain=1#L53). Please double check.

Additionally this _may_ be relevant https://github.com/apache/apisix-ingress-controller/issues/1223

**Comment by GuoMonth** [comment]
I am do some test, this is result:

1. nothing change, just use postman request, success.
2. remove the `exprs`, postman and  C# app  request all success.

**Comment by GuoMonth** [comment]
do nothing change, I am use curl request , success.

```
curl --location 'http://x.x.x.x:xxx/client/graphql' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxxciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc2NzgyOTAsImtleSI6InVzZXIta2V5In0.uwbJBHgSRwKRSPloqq9uqeiXHmK9OhsXaPXFnlW19wI' \
--data '{"query":"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {\n    tClientInfo(\n        filters: { status: { eq: 1 } }\n        pagination: { page: { limit: $pageSize, page: $pageIndex } }\n        orderBy: { updateTime: DESC }\n    ) {\n        nodes {\n            id\n            clientId\n            clientCode\n            clientName\n            status\n            createUser\n            createTime\n            remark\n            updateTime\n            updateUser\n        }\n        paginationInfo {\n            pages\n            current\n        }\n    }\n}","variables":{"pageSize":10,"pageIndex":1}}'
```

**Comment by GuoMonth** [comment]
It's really incomprehensible!

 I compare graphql request strings from C# app and cURL, No difference found.
 and compare graphql request strings from cURL and error log , No difference found.
 
 String mystery... 💔

**Comment by kayx23** [comment]
> do nothing change(with the exprs), I am use curl request , success.
> 
> ```
> curl --location 'http://x.x.x.x:xxx/client/graphql' \
> --header 'Content-Type: application/json' \
> --header 'Authorization: Bearer xxxxciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc2NzgyOTAsImtleSI6InVzZXIta2V5In0.uwbJBHgSRwKRSPloqq9uqeiXHmK9OhsXaPXFnlW19wI' \
> --data '{"query":"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {\n    tClientInfo(\n        filters: { status: { eq: 1 } }\n        pagination: { page: { limit: $pageSize, page: $pageIndex } }\n        orderBy: { updateTime: DESC }\n    ) {\n        nodes {\n            id\n            clientId\n            clientCode\n            clientName\n            status\n            createUser\n            createTime\n            remark\n            updateTime\n            updateUser\n        }\n        paginationInfo {\n            pages\n            current\n        }\n    }\n}","variables":{"pageSize":10,"pageIndex":1}}'
> ```
> 
> response
> 
> ```
> {
>     "data": {
>         "tClientInfo": {
>             "nodes": [],
>             "paginationInfo": {
>                 "pages": 1,
>                 "current": 1
>             }
>         }
>     }
> }
> ```

Is this sent to APISIX? What if you send one to APISIX this way:

![image](https://github.com/apache/apisix/assets/39619599/b57438b9-42fb-4889-9377-20cd2a4b5324)

screenshot from [this blog](https://apisix.apache.org/blog/2022/03/02/apisix-integration-graphql/).

**Comment by Revolyssup** [comment]
@GuoMonth Any updates?

**Comment by GuoMonth** [comment]
I will try something today.

**Comment by GuoMonth** [comment]
# Test Case 1

## config the apisix route

```bash
~> kubectl apply -n xxxx-services  -f /Users/guosheng/AzureDevOps/fx-service-client/apisix-test.yaml
apisixroute.apisix.apache.org/fx-client-route created
~>kubectl describe ApisixRoute -n xxxx-services fx-client-route
Name:         fx-client-route
Namespace:    xxxx-services
Labels:       <none>
Annotations:  <none>
API Version:  apisix.apache.org/v2
Kind:         ApisixRoute
Metadata:
  Creation Timestamp:  2023-10-26T02:10:29Z
  Generation:          1
  Resource Version:    27913024655
  Self Link:           /apis/apisix.apache.org/v2/namespaces/xxxx-services/apisixroutes/fx-client-route
  UID:                 b75529cd-ed8c-4036-xxxx-3660775fxxxx
Spec:
  Http:
    Backends:
      Service Name:  xxxx-fx-service-client-service
      Service Port:  8007
    Match:
      Methods:
        POST
        GET
      Paths:
        /client/graphql
    Name:  fx-client-rule-graphql
    Plugins:
      Enable:  true
      Name:    jwt-auth
      Enable:  true
      Name:    cors
Status:
  Conditions:
    Message:              Sync Successfully
    Observed Generation:  1
    Reason:               ResourcesSynced
    Status:               True
    Type:                 ResourcesAvailable
Events:
  Type    Reason           Age              From           Message
  ----    ------           ----             ----           -------
  Normal  ResourcesSynced  6s (x2 over 6s)  ApisixIngress  ApisixIngress synced successfully
```

## apisix-test.yaml content

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: fx-client-route
spec:
  http:
    - name: fx-client-rule-graphql
      match:
        methods: ["POST", "GET"]
        paths:
          - /client/graphql
      backends:
        - serviceName: xxxx-fx-service-client-service
          servicePort: 8007
      plugins:
        - name: jwt-auth
          enable: true
        - name: cors
          enable: true

```

## Test

1 cURL: success!

```
 ~> curl --location 'http://1.xx.xx.45:8082/client/graphql' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgzNzI1MjcsImtleSI6InVzZXIta2V5In0.JN126xataNmTw7-PgxxxvCwYClRSttob-xxxCerlRs' \
--data '{"query":"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {\n    tClientInfo(\n        filters: { status: { eq: 1 } }\n        pagination: { page: { limit: $pageSize, page: $pageIndex } }\n        orderBy: { updateTime: DESC }\n    ) {\n        nodes {\n            id\n            clientId\n            clientCode\n            clientName\n            status\n            createUser\n            createTime\n            remark\n            updateTime\n            updateUser\n        }\n        paginationInfo {\n            pages\n            current\n        }\n    }\n}\n","variables":{"pageSize":3,"pageIndex":1}}'

{"data":{"tClientInfo":{"nodes":[],"paginationInfo":{"pages":1,"current":1}}}}%
```

2 my .net 7 App, Include="GraphQL.Client" Version="6.0.0": success!

```csharp
        public async Task<PageData<ClientInfoData>> RetrieveByPage(int index, int size)
        {
            GraphQLRequest fetchQuery = new()
            {
                Query = @"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {
                    tClientInfo(
                        filters: { status: { eq: 1 } }
                        pagination: { page: { limit: $pageSize, page: $pageIndex } }
                        orderBy: { updateTime: DESC }
                    ) {
                        nodes {
                            id
                            clientId
                            clientCode
                            clientName
                            status
                            createUser
                            createTime
                            remark
                            updateTime
                            updateUser
                        }
                        paginationInfo {
                            pages
                            current
                        }
                    }
                }",
                Variables = new
                {
                    pageSize = size,
                    pageIndex = index,
                },
            };

            var token = await this.LocalStorage.GetItemAsync<string>("Token");
            this.GraphqlHttp.HttpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var fetchResJson = await this.GraphqlHttp.SendQueryAsync<JsonDocument>(fetchQuery);
            var fetchResData = fetchResJson.Data.RootElement.GetProperty("tClientInfo").GetProperty("nodes");
            var fetchResPaginationInfo = fetchResJson.Data.RootElement.GetProperty("tClientInfo").GetProperty("paginationInfo");

            var totalPages = fetchResPaginationInfo.GetProperty("pages").GetInt32();
            var data = fetchResData.Deserialize<List<ClientInfoData>>() ?? new List<ClientInfoData>();

            var clientInfoPage = new PageData<ClientInfoData>
            {
                Data = data,
                TotalPages = totalPages,
                PageIndex = index,
                PageSize = size,
                Total = totalPages * size, // note: this is not accurate, because graphql not respond 'total' info.
            };

            return clientInfoPage;
        }
```

**Comment by GuoMonth** [comment]
# Test Case 2

## config the apisix route

```bash
 ~> kubectl apply -n xxxx-services  -f /Users/guosheng/AzureDevOps/fx-service-client/apisix-test.yaml
apisixroute.apisix.apache.org/fx-client-route configured

~> kubectl describe ApisixRoute -n xxxx-services fx-client-route
Name:         fx-client-route
Namespace:    xxxx-services
Labels:       <none>
Annotations:  <none>
API Version:  apisix.apache.org/v2
Kind:         ApisixRoute
Metadata:
  Creation Timestamp:  2023-10-26T02:10:29Z
  Generation:          2
  Resource Version:    27913423206
  Self Link:           /apis/apisix.apache.org/v2/namespaces/xxxx-services/apisixroutes/fx-client-route
  UID:                 b75529cd-ed8c-4036-b855-3xxxx75fc67f
Spec:
  Http:
    Backends:
      Service Name:  xxxx-fx-service-client-service
      Service Port:  8007
    Match:
      Exprs:
        Op:  Equal
        Subject:
          Name:   graphql_operation
          Scope:  Variable
        Value:    query
      Methods:
        POST
        GET
      Paths:
        /client/graphql
    Name:  fx-client-rule-graphql
    Plugins:
      Enable:  true
      Name:    jwt-auth
      Enable:  true
      Name:    cors
Status:
  Conditions:
    Message:              Sync Successfully
    Observed Generation:  2
    Reason:               ResourcesSynced
    Status:               True
    Type:                 ResourcesAvailable
Events:
  Type    Reason           Age                From           Message
  ----    ------           ----               ----           -------
  Normal  ResourcesSynced  11s (x4 over 18m)  ApisixIngress  ApisixIngress synced successfully
```

## apisix-test.yaml

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: fx-client-route
spec:
  http:
    - name: fx-client-rule-graphql
      match:
        methods: ["POST", "GET"]
        paths:
          - /client/graphql
        exprs:
          - subject:
              scope: Variable
              name: graphql_operation
            op: Equal
            value: query
      backends:
        - serviceName: xxxx-fx-service-client-service
          servicePort: 8007
      plugins:
        - name: jwt-auth
          enable: true
        - name: cors
          enable: true

```

## Test

1 cURL: success!

```bash
 ~> curl --location 'http://xx.xx.xx.xx:xxx/client/graphql' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhxxxx1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOxxxgzNzI1MjcsImtleSI6InVzZxxxn0.JN126xataNmTw7-Pgj34vCwYCxxxttob-l2FYCerlRs' \
--data '{"query":"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {\n    tClientInfo(\n        filters: { status: { eq: 1 } }\n        pagination: { page: { limit: $pageSize, page: $pageIndex } }\n        orderBy: { updateTime: DESC }\n    ) {\n        nodes {\n            id\n            clientId\n            clientCode\n            clientName\n            status\n            createUser\n            createTime\n            remark\n            updateTime\n            updateUser\n        }\n        paginationInfo {\n            pages\n            current\n        }\n    }\n}\n","variables":{"pageSize":3,"pageIndex":1}}'

{"data":{"tClientInfo":{"nodes":[],"paginationInfo":{"pages":1,"current":1}}}}%
```

2 my .net 7 App, Include="GraphQL.Client" Version="6.0.0": failed!

```csharp
        public async Task<PageData<ClientInfoData>> RetrieveByPage(int index, int size)
        {
            GraphQLRequest fetchQuery = new()
            {
                Query = @"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {
                    tClientInfo(
                        filters: { status: { eq: 1 } }
                        pagination: { page: { limit: $pageSize, page: $pageIndex } }
                        orderBy: { updateTime: DESC }
                    ) {
                        nodes {
                            id
                            clientId
                            clientCode
                            clientName
                            status
                            createUser
                            createTime
                            remark
                            updateTime
                            updateUser
                        }
                        paginationInfo {
                            pages
                            current
                        }
                    }
                }",
                Variables = new
                {
                    pageSize = size,
                    pageIndex = index,
                },
            };

            var token = await this.LocalStorage.GetItemAsync<string>("Token");
            this.GraphqlHttp.HttpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var fetchResJson = await this.GraphqlHttp.SendQueryAsync<JsonDocument>(fetchQuery);
            var fetchResData = fetchResJson.Data.RootElement.GetProperty("tClientInfo").GetProperty("nodes");
            var fetchResPaginationInfo = fetchResJson.Data.RootElement.GetProperty("tClientInfo").GetProperty("paginationInfo");

            var totalPages = fetchResPaginationInfo.GetProperty("pages").GetInt32();
            var data = fetchResData.Deserialize<List<ClientInfoData>>() ?? new List<ClientInfoData>();

            var clientInfoPage = new PageData<ClientInfoData>
            {
                Data = data,
                TotalPages = totalPages,
                PageIndex = index,
                PageSize = size,
                Total = totalPages * size, // note: this is not accurate, because graphql not respond 'total' info.
            };

            return clientInfoPage;
        }
```

apisix error log:

```text
172.17.0.6 - - [26/Oct/2023:02:34:07 +0000] xx.xx.xx.xx:xx "POST /client/graphql HTTP/1.1" 404 47 0.000 "http://localhost:5003/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.61" - - - "http://xx.xx.xx.xx:xx"
2023/10/26 02:34:59 [error] 52#52: *669067163 [lua] ctx.lua:138: get_parsed_graphql(): failed to parse graphql: Syntax error near line 1 body: {"query":"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {\n                    tClientInfo(\n                        filters: { status: { eq: 1 } }\n                        pagination: { page: { limit: $pageSize, page: $pageIndex } }\n                        orderBy: { updateTime: DESC }\n                    ) {\n                        nodes {\n                            id\n                            clientId\n                            clientCode\n                            clientName\n                            status\n                            createUser\n                            createTime\n                            remark\n                            updateTime\n                            updateUser\n                        }\n                        paginationInfo {\n                            pages\n                            current\n                        }\n                    }\n                }","variables":{"pageSize":15,"pageIndex":0}}, client: 172.17.0.6, server: _, request: "POST /client/graphql HTTP/1.1", host: "xx.xx.xx.xx:xx", referrer: "http://localhost:5003/"
```

**Comment by GuoMonth** [comment]
# Test Case 3

Directly request local grapql services without going through the gateway
1. web wasm client: .net 7 App, Include="GraphQL.Client" Version="6.0.0"
1. graphql service: rust 1.73,
```toml
async-graphql = { version = "5.0.10", default-features = false }
async-graphql-axum = "5.0.10"
sea-orm = { version = "0.12", default-features = false}
seaography = {version = "^1.0.0-rc.2", default-features = false}
```

1 success!

```csharp
                Query = @"query tClientInfo($pageSize: Int!, $pageIndex: Int!) {
                    tClientInfo(
                        filters: { status: { eq: 1 } }
                        pagination: { page: { limit: $pageSize, page: $pageIndex } }
                        orderBy: { updateTime: DESC }
                    ) {
                        nodes {
                            id
                            clientId
                            clientCode
                            clientName
                            status
                            createUser
                            createTime
                            remark
                            updateTime
                            updateUser
                        }
                        paginationInfo {
                            pages
                            current
                        }
                    }
                }",
                Variables = new
                {
                    pageSize = size,
                    pageIndex = index,
                },
            };
```
- failed
```cschar
GraphQLRequest fetchQuery = new()
            {
                Query = "query tClientInfo{\n tClientInfo(\n filters: { status: { eq: 1 } }\n pagination: { page: { limit: $pageSize, page: $pageIndex } }\n orderBy: { updateTime: DESC }\n ) {\n nodes {\n id\n clientId\n clientCode\n clientName\n status\n createUser\n createTime\n remark\n updateTime\n updateUser\n }\n paginationInfo {\n pages\n current\n }\n }\n }",
            };
```
