### ISSUE TITLE
bug: Trouble with opentelemetry plugin

### ISSUE THREAD

**Issue by jonathan-dev** [apache/apisix#10389]
### Current Behavior

I am running the image `apache/apisix:3.6.0-debian` with almost standard settings for the opentelemtry plugin:
```
plugin_attr:
  opentelemetry:
    resource:
      service.name: APISIX
      tenant.id: business_id
    collector:
      address: otel-collector:4318
      request_timeout: 3
      request_headers:
        foo: bar
    batch_span_processor:
      drop_on_queue_full: false
      max_queue_size: 6
      batch_timeout: 2
      inactive_timeout: 1
      max_export_batch_size: 2
```
plugin section for route:
```
  "plugins": {
    "opentelemetry": {
      "disable": false,
      "sampler": {
        "name": "always_on"
      }
    },
```
looking at the apisix logs I get the following error:

```
2023/10/24 10:32:00 [error] 60#60: *1448554 lua entry thread aborted: runtime error: bad argument #1 to '?' (invalid value)
stack traceback:
coroutine 0:
        [C]: in function 'gsub'
        ...s/share/lua/5.1/opentelemetry/trace/exporter/encoder.lua:22: in function 'hex2bytes'
        ...s/share/lua/5.1/opentelemetry/trace/exporter/encoder.lua:66: in function 'for_otlp'
        ...deps/share/lua/5.1/opentelemetry/trace/exporter/otlp.lua:102: in function 'export_spans'
        ...are/lua/5.1/opentelemetry/trace/batch_span_processor.lua:45: in function 'process_batches'
        ...are/lua/5.1/opentelemetry/trace/batch_span_processor.lua:77: in function <...are/lua/5.1/opentelemetry/trace/batch_span_processor.lua:57>, context: ngx.timer, client: 172.18.0.1, server: 0.0.0.0:9443
```
I also failed to get the logging in place that is described [here](https://apisix.apache.org/blog/2023/10/05/release-apache-apisix-3.6.0/#support-the-use-of-nginx-variables-in-opentelemetry-plugin) here I'm not sure If I need to put the http section in the top level or under the `nginx_config: ` (when i put it there I get errors and when its on the root level I get nothing).

### Expected Behavior

no errors 
working plugin

### Error Logs

mentioned above

### Steps to Reproduce

startup apisix and send request to route that has the plugin setup

### Environment

determined by the docker image
