### ISSUE TITLE
help request: kafka-logger request body nil

### ISSUE THREAD

**Issue by eifcode** [apache/apisix#10416]
### Description

routes configer plugin kafka-logger :
`{
    "id": "test-kafka-log",
    "methods": ["POST", "GET"],
    "uri": "/log/data",
    "plugins": {
        "kafka-logger": {
            "brokers": [
                {
                    "host": "192.168.1.171",
                    "port": 9092
                }
            ],
            "kafka_topic": "tmp_data_r1p2",
            "include_req_body": true
        },
        "mocking": {
            "response_status": 201,
            "response_example": "{\"success\":\"ok\"}"
        }
    }
}`

add log in util/log-util.log , get_full_log func req_get_body_data() and ngx.req.get_body_file() is nill

apisix config is default

Missing configuration ? No other information in the document .

### Environment

- APISIX version (run `apisix version`): 3.6.0
- Operating system (run `uname -a`): Linux 3.10.0-1160.102.1.el7.x86_64 #1 SMP Tue Oct 17 15:42:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"hostname":"qzsh55","boot_time":1698661888,"etcd_version":"3.5.0","id":"42ffcf2e-1ebc-4f33-8e33-f9abe98c5ee9","version":"3.6.0"}
- APISIX Dashboard version, if relevant: 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Please elaborate/provide detailed reproduction steps.

**Comment by eifcode** [comment]
1. install Apisix by RPM
2. config routes
`{ "id": "test-kafka-log", "methods": ["POST"], "uri": "/log/data", "plugins": { "kafka-logger": { "brokers": [ { "host": "192.168.1.171", "port": 9092 } ], "kafka_topic": "tmp_data_r1p2", "include_req_body": true }, "mocking": { "response_status": 201, "response_example": "{\"success\":\"ok\"}" } } }`
3. Postman send request 
![image](https://github.com/apache/apisix/assets/79137350/fd2262f6-cdc4-4152-aca7-50ee79b408fd)
4. Apisix send kafka log not request body
![image](https://github.com/apache/apisix/assets/79137350/d038e5af-ee01-4675-84a1-b8c864214604)
5. Apisix utils add log , get_req_body() is nil
![image](https://github.com/apache/apisix/assets/79137350/913903aa-86b5-46f8-aa74-1002eacb39a6)

config-default.yml default config `client_max_body_size 0` ，try to modify value `10m` and restart apisix not effective。

**Comment by shreemaan-abhishek** [comment]
can you confirm if you changed the plugin-metadata using the [admin-api](https://apisix.apache.org/docs/apisix/admin-api/#plugin-metadata)? With the default plugin metadata it works for me.

kafka setup:

<details>
<summary>Click me </summary>
<br>

Docker compose:

```yaml
version: "3.8"

services:
  zookeeper-server1:
    image: bitnami/zookeeper:3.6.0
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    restart: unless-stopped
    ports:
      - "2181:2181"
    networks:
      kafka_net:

  zookeeper-server2:
    image: bitnami/zookeeper:3.6.0
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    restart: unless-stopped
    ports:
      - "12181:12181"
    networks:
      kafka_net:

  kafka-server1:
    image: bitnami/kafka:2.8.1
    container_name: notkafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-server1:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
    restart: unless-stopped
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
    networks:
      kafka_net:

  kafka-server2:
    image: bitnami/kafka:2.8.1
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-server2:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:19092,SASL_PLAINTEXT://0.0.0.0:19094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:19092,SASL_PLAINTEXT://127.0.0.1:19094
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: /opt/bitnami/kafka/config/certs/kafka.keystore.jks
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_CFG_SSL_KEY_PASSWORD: changeit

    restart: unless-stopped
    ports:
      - "19092:19092"
      - "19094:19094"
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
    networks:
      kafka_net:

networks:
  kafka_net:
```

route:

```shell
curl "http://127.0.0.1:9180/apisix/admin/routes/1" -X PUT \
  -H "X-API-KEY: ${ADMIN_API_KEY}" \
  -d '{
    "plugins": {
      "kafka-logger": {
        "brokers": [
          {
            "host": "127.0.0.1",
            "port": 9092
          }
        ],
        "kafka_topic": "test2",
        "key": "key1",
        "batch_max_size": 1,
        "name": "kafka logger",
        "include_req_body": true
      }
    },
    "upstream": {
      "nodes": {
        "httpbin.org:80": 1
      },
      "type": "roundrobin"
    },
    "uri": "/post"
  }'
```

wait for logs from kafka:

```shell
docker exec -it notkafka kafka-console-consumer.sh --bootstrap-server kafka-server1:9092 --topic test2 --from-beginning
```

Send request:

```shell
curl -i "http://127.0.0.1:9080/post" -d '{"a": "b"}' -XPOST -H "content-type: application/json"
```

</details>
