### ISSUE TITLE
help request: oidc-connect plugin: Multiple client IDs on the same route

### ISSUE THREAD

**Issue by csotiriou** [apache/apisix#10454]
### Description

I have the following simple **use case** using **APISIX Ingress Controller** with OpenID connect (with Keycloak as the OpenID provider, I don't know if that plays a role). I believe, however, that my question may also apply to APISIX itself, and not just the Ingress Controller use case.

Here is my use case:

- ClientID1 has to be able to access APIs A1, A2, A3
- ClientID2 has to be able to access A2,A3,A4

As you can see, there will be APIs that need to be able to be accessed by **more than one client** (such as A2 and A3).

My question is:
Can I have a configuration in an APISIXRoute with the openid plugin configured multiple times but with different client id? below is an example of a route that I want to be accessed with a valid token from either ClientID1 or ClientID2 `client_credentials` token

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: api2-apisix
spec:
  http:
  - name: echo2http
    match:
      hosts:
      - echo2.k8s.orb.local
      paths:
      - "/*"
    backends:
    - serviceName: echoserver2-service
      servicePort: 80
    plugins:
      - name: "openid-connect"
        enable: true
        config:
          client_id: "ClientID1"
          client_secret: "ljyo3d9bbDqOvQYBMP9Bgr6HjoDuQegV"
          discovery: ".....apisixrealm/.well-known/openid-configuration"
          bearer_only: true
          realm: "apisixrealm"
      - name: "openid-connect"
        enable: true
        config:
          client_id: "ClientID2"
          client_secret: "..."
          discovery: "....apisixrealm/.well-known/openid-configuration"
          bearer_only: true
          realm: "apisixrealm"
```

Is something like this supported? If not, is there any other way I can support my use case?

Thank you in advance

### Environment

I'm using APISIX Ingress Controller installed in Kubernetes, a very simple configuration using the defaults.
