### ISSUE TITLE
bug:  failed calling webhook "validate.gateway.networking.k8s.io"

### ISSUE THREAD

**Issue by willzhang** [apache/apisix#10470]
### Current Behavior

I reference this docs: https://apisix.apache.org/zh/docs/ingress-controller/tutorials/configure-ingress-with-gateway-api/

but get error when  Configuring Ingress
```yaml
# httpbin-ingress.yaml 
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: httpbin-route
spec:
  hostnames:
  - local.httpbin.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: httpbin
      port: 80
```

i have Enable Gateway API
```
root@ubuntu:~/apisix# helm -n ingress-apisix get values apisix
USER-SUPPLIED VALUES:
dashboard:
  enabled: true
  service:
    type: NodePort
gateway:
  type: NodePort
ingress-controller:
  config:
    apisix:
      adminAPIVersion: v3
      serviceNamespace: ingress-apisix
    kubernetes:
      enableGatewayAPI: true
  enabled: true
```

```
root@ubuntu:~/apisix#  kubectl get crd |grep gateway
gatewayclasses.gateway.networking.k8s.io              2023-11-10T07:04:06Z
gateways.gateway.networking.k8s.io                    2023-11-10T07:04:06Z
httproutes.gateway.networking.k8s.io                  2023-11-10T07:04:06Z
```

### Expected Behavior

apply Configuring Ingress success

### Error Logs

```
root@ubuntu:~/apisix# kubectl apply -f httpbin-ingress.yaml 
Error from server (InternalError): error when creating "httpbin-ingress.yaml": Internal error occurred: failed calling webhook "validate.gateway.networking.k8s.io": failed to call webhook: Post "https://gateway-api-admission-server.gateway-system.svc:443/validate?timeout=10s": no endpoints available for service "gateway-api-admission-server"
```

### Steps to Reproduce

```
NAME=${NAME:-"apisix"}
NAMESPACE=${NAMESPACE:-"ingress-apisix"}
CHART=${CHARTS:-"./charts/apisix"}
HELM_OPTS=${HELM_OPTS:-" \
--set gateway.type=NodePort \
--set ingress-controller.enabled=true \
--set ingress-controller.config.apisix.serviceNamespace=ingress-apisix \
--set ingress-controller.config.apisix.adminAPIVersion=v3 \
--set dashboard.enabled=true \
--set dashboard.service.type=NodePort \
--set ingress-controller.config.kubernetes.enableGatewayAPI=true \
x"}

helm upgrade -i ${NAME} ${CHART} -n ${NAMESPACE} --create-namespace ${HELM_OPTS}
```

```
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.5.0/standard-install.yaml
```

```
kubectl apply -f httpbin-ingress.yaml
```

### Environment

- APISIX version (run `apisix version`): v3.6.0
- Operating system (run `uname -a`): ubuntu 22.04
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
