### ISSUE TITLE
help request: Datadog plugin configuration

### ISSUE THREAD

**Issue by swo-ralf** [apache/apisix#10473]
### Description

I'm working the first time with DataDog and Apisix.

I have a Kubernetes cluster running on Azure AKS with version 1.27.3. I have successfully installed and integrated DataDog via DataDog Operator and see logs and couple of metrics of the Kubernetes cluster itself.

Also successfully with Apisix chart 1.7.0 I have Apisix as ingress controller and have some basic routes defined via CRDs. Now I want to integrate the Apisix DataDog plugin and it does not work. Neither I see a hard config error nor an error in the logs. But routing still works so I guess something is odd in the config.

My plugin config CRD for DataDog:
```
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: datadog-plugin
spec:
  plugins:
  - name: datadog
    enable: true
``` 

And the route CRD:
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: dotnetonweb-route
  namespace: web
spec:
  http:
  - name: dotnetonweb
    match:
      hosts:
      - somewhere.com
      paths:
      - "/foo*"
    backends:
       - serviceName: foo
         servicePort: 80
    plugin_config_name: datadog-plugin
``` 

My questions:
- What do I oversee?
- Do namespaces play a role?

Apisix is deployed to a namespace ingress-apisix, the workloads are in dedicated namespaces.

Thanks for the help :)

### Environment

- AKS 1.27.3
- Apisix chart 1.7.0
- Apisix: 3.6.0
- DataDog Operator 1.2.0 with DataDog Agent 3.47
- DataDog Agent runs on each AKS node, DogStatsD host port is default and exposed (at least I see it correctly in the POD YAMl description).
