### ISSUE TITLE
help request: forward auth not passing the headers to the service when using a Front end App

### ISSUE THREAD

**Issue by Kozatoo** [apache/apisix#10506]
### Description

Context: I'm trying to build an application with an Auth Service which should only validate the tokens, and admin service which sould be protected. 

This works perfectly with development tools like insomnia/postman but when effectuating these API calls from a front-end application: 
   1- I get a CORS error.
   2- The authorization header is not present inside the request sent with forward-auth plugin (even though I've added it inside the request_headers) 

apisix.yaml
```

routes:
  - uri: /auth/*
    plugins:
      proxy-rewrite:
        regex_uri: ["^/auth/(.*)","/$1"]

    upstream:
      nodes:
        "AuthService" :1
      type: roundrobin
    
  - uri: /admin/*
    plugins:  
      proxy-rewrite:
        regex_uri: ["^/admin/(.*)","/$1"]
      forward-auth:
        uri: http://AuthService/validate
        ssl_verify: false
        request_headers: ["Authorization",authorization]
    upstream:
      nodes:
        "AdminService": 1
    
#END

```
ps: I've tried different approaches with the request_headers value, with/witout quotes but the all don't seem to work

### Environment

APISIX: 3.6 dockerized
etcd:3.4.15 dockerized
