### ISSUE TITLE
help request: TCP rule Error: socket hang up

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix#10525]
### Description

my service
```
[root@VM-24-15-centos ~]# kubectl get svc -n rbd-system
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                     AGE
rbd-api-api                 ClusterIP   10.43.138.229   <none>        8443/TCP                                                                                                    68d
rbd-api-api-inner           ClusterIP   10.43.157.248   <none>        8888/TCP                                                                                                    68d
rbd-api-healthz             ClusterIP   10.43.48.247    <none>        8889/TCP                                                                                                    68d
rbd-api-websocket           ClusterIP   10.43.219.249   <none>        6060/TCP                                                                                                    68d
rbd-app-ui                  ClusterIP   10.43.164.138   <none>        7070/TCP                                                                                                    68d
```

my tcp rule

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: tcp-route
spec:
  stream:
    - name: rbd-app-ui
      protocol: TCP
      match:
        ingressPort: 7070
      backend:
        serviceName: rbd-app-ui
        servicePort: 7070

```

my apisix config

```yaml
    apisix:
      proxy_mode: "http&stream"
      ssl:
        enable: true
        listen:
          - port: 443
      enable_control: true
      enable_reuseport: true
      node_listen:
        - 80
      stream_proxy:
        only: false
        tcp:
          - addr: 7070
          - addr: 8443
```

<img width="1047" alt="图片" src="https://github.com/apache/apisix/assets/62740231/4cf67619-99eb-4692-9999-10038ff7b877">

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
 3.6.0 apisix
