### ISSUE TITLE
help request: How to enable plugins on routing rules created by Kubernetes

### ISSUE THREAD

**Issue by Richard0706** [apache/apisix#10608]
### Description

I created a rule like this:
```
spec:
  ingressClassName: apisix
  rules:
  - host: apisix-dashboard.mytest.com
    http:
      paths:
      - backend:
          service:
            name: apisix-dashboard
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```
There is nothing wrong with these, I want to use the elasticsearch-logger plugin, so I executed a command like this:
```
curl http://127.0.0.1:9180/apisix/admin/routes/d6a65f62 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "uris": [
    "/*"
  ],
  "name": "ing_apisix_apisix-dashboard_71cd8a6c",
  "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
  "host": "apisix-dashboard.mytest.com",
    "plugins":{
        "elasticsearch-logger":{
            "endpoint_addr":"http://192.168.1.5:9200",
            "field":{
                "index":"services-apisix-dashboard"
            }
        }
    },  
  "upstream_id": "6624cd4a",
  "labels": {
    "managed-by": "apisix-ingress-controller"
  },
  "status": 1
}'
```
**When I just finished executing this, everything was normal and I could see the data in the es index, but after a few minutes, the rule to enable the elasticsearch-logger plugin disappeared.**
**I need your help. Most of my routing rules come from Kubernetes ingress. How can I enable plug-ins on the already created rules so that they will always take effect?**

### Environment

- APISIX version (run `apisix version`): 3.2
- Operating system (run `uname -a`): kubernetes v1.21.14

**Comment by basuotian** [comment]
try to use ApisixRoute instead of Ingress, ApisixRoute contains plugins field

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: apisix-dashboard
spec:
  http:
  - backends:
    - serviceName: apisix-dashboard
       servicePort: 80
    match:
      hosts:
      - apisix-dashboard.mytest.com
      paths:
      - /*
    name: apisix-dashboard
    plugins:
    - name: elasticsearch-logger
      enable: true
      config:
        endpoint_addr: "http://192.168.1.5:9200"
        field: 
          index: "services-apisix-dashboard"
```

if you insist to use Ingress, you should create an ApisixPluginConfig like
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: test-plugin
spec:
  plugins:
  - name: elasticsearch-logger
    enable: true
    config:
      endpoint_addr: "http://192.168.1.5:9200"
      field: 
        index: "services-apisix-dashboard"
```
then add annotation to your Ingress object
```yaml
metadata:
  annotations:
    k8s.apisix.apache.org/plugin-config-name: elasticsearch-logger
```
