### ISSUE TITLE
Health check is not working

### ISSUE THREAD

**Issue by AmerDwight** [apache/apisix#10602]
### Description

Dear Team of APISIX
I'm learning to use APISIX, and I face an issue about health-checking mechanism is not working.
Since I have a test upstream of nginx as a backend, and I already built a endpoint like /health
followed：[monitor-api-health-check](https://apisix.apache.org/docs/apisix/next/tutorials/monitor-api-health-check/)

But I cannot trace any health-check request in whether access.log / error.log / prometheus record
And it cannot catch the unhealthy state while I stop the container of nginx

upstream in apisix
``` 
{
  "nodes": [
    {
      "host": "nginx_web1",
      "port": 80,
      "weight": 1
    }
  ],
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "checks": {
    "active": {
      "concurrency": 2,
      "healthy": {
        "http_statuses": [
          200,
          302
        ],
        "interval": 2,
        "successes": 1
      },
      "http_path": "/health",
      "timeout": 2,
      "type": "http",
      "unhealthy": {
        "http_failures": 2,
        "http_statuses": [
          429,
          404,
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "interval": 1,
        "tcp_failures": 2,
        "timeouts": 3
      }
    }
  },
  "scheme": "http",
  "pass_host": "pass",
  "name": "Nginx",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}
```

nginx conf
``` 
worker_processes 1;
error_log stderr notice;
events {
    worker_connections 1024;
}

http {
    variables_hash_max_size 1024;
    access_log  /var/log/nginx/access.log;
    real_ip_header X-Real-IP;
    charset utf-8;

    server {
        listen 80;
        
        location / {
            return 200 "It's a backend web server, built with nginx \n";
        }

        location /health {
            return 200 "OK";
        }

        access_log  /var/log/nginx/domain1.access.log;
    }
}
```

I'm pretty sure the connection and gateway function is fine.
And, I've referenced the issue #2739 and #8889 
The first one seems not my case, and for the second one, I've already run the route and tried well.
Did I do something dumb?

### Environment

- APISIX version (run `apisix version`):3.6.0
- Operating system (run `uname -a`):docker
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> But I cannot trace any health-check request in whether access.log / error.log / prometheus record

you need to use the control api to check the health status: 
<img width="809" alt="image" src="https://github.com/apache/apisix/assets/61597896/a9575e10-e01b-45bd-a7ad-adefaffc598f">

**Comment by AmerDwight** [comment]
Yes, I've read that too. [Control Api](https://apisix.apache.org/docs/apisix/3.6/control-api/#get-v1healthcheck)
If I curl the control api, it shows like：
```
{
   "type":"http",
   "name":"/apisix/upstreams/490103218550866940",
   "nodes":{}
}
```

and there is nothiing listed in  " localhost:9092/v1/healthcheck " 
(I set the 9092 for the port not 9090, which you can ignore)

To privide more detail, the following are configs for apisix：
```
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    allow_admin:               # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30                     # 30 seconds

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
  
nginx_config:
  error_log_level: "info"
```
