### ISSUE TITLE
help request: Is there a possible way to reach different-network upstreams with proxy?

### ISSUE THREAD

**Issue by AmerDwight** [apache/apisix#10627]
### Description

Dear menbers of APISIX,

I'm wondering, if there is a possible way to config upstreams with proxy?
Since there are policies to separate networks by some logic, 
a place to set up my APISIX would not be a place for some upstreams to live.

After my experiments, it seems no way to achieve my purpose in a simple method/config.
it all require second layer of reverse proxy or customized plugin.
Is it true or I'm too young for this? 

To conclud it,
I'm searching for a way out for directly reach upstreams in different-network with existed proxy.
Is there any straight way to achieve that?
Appreciate for all helps 

### Environment

- APISIX version (3.6.0):
- Operating system (docker):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
> Since there are policies to separate networks by some logic...
> I'm searching for a way out for directly reach upstreams in different-network...

Not sure I understand the scenario... different networks how?

Could you provide a more concrete example or perhaps a simple diagram of what you're trying to achieve?

**Comment by AmerDwight** [comment]
Thanks for your reply.

Here is my scenario:
Assume there are separated networks, A and B in private.
If the node in Network.A wants to visit the server in Network.B, then it goes with a proxy,
the existed proxy would direct the request to the Network.B

Now, if the apisix nodes are held in one of the net, and the upstream stays in the other.
How would I setup a route or attach some plugins?

It shall looks like：
```
+-----------------+         +---------+         +-----------------+
|    Network A    |         |         |         |    Network B    |
|                 |         |  Proxy  |         |                 |
|    [APISIX]-----|-------->|         |-------->|---[Server]      |
|        ^        |         |         |         |                 |
|        |        |         |         |         |                 |
|    [Request]    |         |         |         |                 |
+-----------------+         +---------+         +-----------------+
```

**Comment by kayx23** [comment]
What defines these networks? Any firewall? e.g., in Azure I'd be checking my VNets and firewall rules.

Do you know where your request is blocked along the way?

**Comment by AmerDwight** [comment]
The networks are separated by rules some are physical locations and some are manager rules.
e.g. network in office is serious restricted to connect to fab/ production networks. 
The formal way to access is to work through specific proxy.

The following is how I tried to do:
before that, I've tried curl -x to testify the proxy works fine.

1. I defined the proxy as the upstream
2. use proxy-rewrite and set up some：
```
"proxy-rewrite": {
      "headers": {
        "Accept": "*/*",
        "Host": "outersite:80",
        "Proxy-Connection": "Keep-Alive"
      },
      "host": "outersite",
      "uri": "/"
    }
```

The request is actually sent to the proxy, but it goes wrong still 
Did I mess up something?

**Comment by kayx23** [comment]
> before that, I've tried curl -x to testify the proxy works fine.

So if your request doesn't go through APISIX, it goes through just fine?

```
+-----------------+         +---------+         +-----------------+
|    Network A    |         |         |         |    Network B    |
|                 |         |  Proxy  |         |                 |
|    [Request]----|-------->|         |-------->|---[Server]      |
|                 |         |         |         |                 |
|                 |         |         |         |                 |
|                 |         |         |         |                 |
+-----------------+         +---------+         +-----------------+
```

**Comment by AmerDwight** [comment]
Thanks for your patient, I didn't decribe it well.

> So if your request doesn't go through APISIX, it goes through just fine? Upstream server in network B responds as intended?

Yes, it is. 

> And it goes wrong how? What's the error?

The proxy did receive the request from APISIX but proxy didn't **process** it.
And the information that I setup in `proxy-rewrite` **didn't be received** by the proxy.
( In track of the proxy log, there is no headers that I put in `proxy-rewrite` )

To summarize the issue:
1. **In my case, to set things up in `proxy-rewrite` is a correct way?**
　　Here are my build steps:
　　　　　1. set proxy as the upstream
　　　　　2. define a route
　　　　　3. attach `proxy-rewrite` and set destination server in headers
　　　　　
2.  **Now the proxy didn't get the headers that I set up in `proxy-rewrite`**
　　-->　a. How do I track the transported-request from APISIX? 
　　　　　　　( I'm using file_logger now, there are come-in logs but no come-out logs )
　　-->　b. If the headers were read by proxy, in common scenario, it shall works fine?

**Comment by kayx23** [comment]
> The proxy did receive the request from APISIX but proxy didn't process it.
> And the information that I setup in proxy-rewrite didn't be received by the proxy.

In other words, the condition for your proxy to forward this request is to for it to be able to detect a certain header, which was, for some reasons, not added by `proxy-rewrite`?

**Comment by AmerDwight** [comment]
Please refer the following settings:

Route
```yml
{
  "uri": "/proxy",
  "name": "proxy-t1-route",
  "plugins": {
    "proxy-rewrite": {
      "headers": {
        "Accept": "*/*",
        "Connection": "Keep-Alive",
        "Host": "outersite",
        "Proxy-Connection": "Keep-Alive"
      },
      "host": "outersite",
      "method": "GET",
      "uri": "/"
    }
  },
  "upstream_id": "491273801099641868",
  "status": 1
}
```

Upstream
```yml
{
  "nodes": [
    {
      "host": "squid",  # proxy server
      "port": 3128,
      "weight": 1
    }
  ],
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "scheme": "http",
  "pass_host": "pass",
  "name": "proxy-t1",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}
```
