### ISSUE TITLE
bug: failed to verify jwt

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix#10651]
### Current Behavior

 When I use the JWT plugin, there is a high probability of authentication failure, but a low probability of authentication success 
 
 ```
...
      plugins:
        - name: limit-count
          enable: true
          config:
            show_limit_quota_header: true
            count: 150000
            time_window: 86400
            key: http_authorization
            rejected_code: 429
            rejected_msg: "24小时内请求超过最大次数"
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/openapi-service/(.*)"
              - "/$1"
        - name: jwt-auth
          enable: true
          config:
            key: zhang

      authentication:
        enable: true
        type: jwtAuth
        jwtAuth:
          header: Authorization
          query: jwt
```
consumer
```
apiVersion: apisix.apache.org/v2
kind: ApisixConsumer
metadata:
  namespace: itihey-system
  name: apisix-consumer-jwt
spec:
  authParameter:
    jwtAuth:
      value:
        key: zhang
```

### Steps to Reproduce

1

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
1
