### ISSUE TITLE
help request: ip-restriction doesn't work

### ISSUE THREAD

**Issue by tian67890** [apache/apisix#10657]
### Description

apisix version 3.3
the plugin ip-restriction is set up in config.yaml
but our whitelist configured in the route doesn't work

### Environment

- APISIX version (run `apisix version`): 3.3
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by juzhiyuan** [comment]
Hi @tian67890, please paste your complete configurations and detailed steps to reproduce your case. This will be easier for us to know what happened exactly.

**Comment by tian67890** [comment]
a complete route as following:
{
  "uri": "/*",
  "name": "kuboard",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "kuboard.xxx.com",
  "plugins": {
    "ip-restriction": {
      "disable": false,
      "whitelist": [
        "172.0.0.0/8",
        "127.0.0.1"
      ]
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "172.30.160.7",
        "port": 80,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 60,
      "send": 60,
      "read": 60
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "enable_websocket": true,
  "status": 1
}

![Uploading apisix-1.jpg…]()

**Comment by tian67890** [comment]
@juzhiyuan 
a complete json as following:
```json
{
  "uri": "/*",
  "name": "kuboard",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "kuboard.xxx.com",
  "plugins": {
    "ip-restriction": {
      "disable": false,
      "whitelist": [
        "61.148.62.179",
        "172.0.0.0/8",
        "127.0.0.1"
      ]
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "172.30.160.7",
        "port": 80,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 60,
      "send": 60,
      "read": 60
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "enable_websocket": true,
  "status": 1
}
```

**Comment by tian67890** [comment]
apisix runs in a container of the k8s cluster，section of plugins configuration is like this:
```yaml
plugin_attr:
  log-rotate:
    interval: 3600    # rotate interval (unit: second)
    max_kept: 168     # max number of log files will be kept
    max_size: -1      # max size of log files will be kept
    enable_compression: false    # enable log file compression(gzip) or not, default false      
plugins:    # plugin list
  - api-breaker
  - authz-keycloak
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  - echo
  - fault-injection
  - file-logger
  - grpc-transcode
  - hmac-auth
  - http-logger
  - ua-restriction
  - jwt-auth
  - kafka-logger
  - key-auth
  - limit-conn
  - limit-count
  - limit-req
  - node-status
  - openid-connect
  - authz-casdoor
  - authz-casdoor-user
  - authz-casbin
  - prometheus
  - proxy-cache
  - proxy-mirror
  - proxy-rewrite
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - serverless-post-function
  - serverless-pre-function
  - sls-logger
  - syslog
  - tcp-logger
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - traffic-split
  - gzip
  - real-ip
  - ext-plugin-pre-req
  - ext-plugin-post-req
  - log-rotate
stream_plugins:
  - mqtt-proxy
  - limit-conn 
  - ip-restriction
```
