### ISSUE TITLE
help request: Can't APISIX  routing request thru a middle-proxy between upstream?

### ISSUE THREAD

**Issue by AmerDwight** [apache/apisix#10652]
### Description

In my case, the upstream server is hosted in other net, which is separated from net of APISIX
The way to connect is probably go thru with middle-proxy, like:
```
+-----------------+         +---------+         +-----------------+
|    Network A    |         |         |         |    Network B    |
|                 |         |  Proxy  |         |                 |
|    [APISIX]-----|-------->|         |-------->|---[Server]      |
|        ^        |         |         |         |                 |
|        |        |         |         |         |                 |
|    [Request]    |         |         |         |                 |
+-----------------+         +---------+         +-----------------+
```

So, I set middle-proxy info in environment, ( Docker image: apisix:3.2.2-centos )
and testify the middle-proxy by curl command, which is doing fine.

But if I build in route of APISIX, it goes 503 response. 
I don't know why APISIX did not sent requests follow the middle-proxy setting in environment

upstream:
```yml
{
  "nodes": [
    {
      "host": "outersite", # this is a address that APISIX shall access with middle-proxy 
      "port": 80,
      "weight": 1
    }
  ],
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "scheme": "http"
}
``` 

routes:
```yml
{
  "uri": "/proxy",
  "name": "proxy-t1-route",
  "upstream_id": "491273801099641868",
  "status": 1
}
```

CentOS proxy-set:
/etc/bashrc
```bash
export http_proxy=http://squid:3128
export https_proxy=https://squid:3128
```

### Environment

- APISIX version (run `apisix version`): apisix:3.2.2-centos
- Operating system (run `uname -a`): Docker - centos
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): bitnami/etcd:3.5
- APISIX Dashboard version, if relevant: apache/apisix-dashboard:latest
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
