### ISSUE TITLE
help request: Datadog plugin config - can't define DogStatsD target with CRDs

### ISSUE THREAD

**Issue by swo-ralf** [apache/apisix#10748]
### Description

First, a happy new year to everyone :)

Follow up for #10473. As discussed there, I tried the approach with defining a K8s service for the DogStatsD DaemonSet but still I only see in the logs, that the local host is tried to be reached:

`2024/01/03 09:41:39 [error] 49#49: *3894 [lua] datadog.lua:143: send_metric_over_udp(): failed to report request latency to dogstatsd server: host[127.0.0.1] port[8125] err: connection refused, context: ngx.timer, client: 10.224.0.5, server: 0.0.0.0:9080`

My used service:
```
kind: Service
apiVersion: v1
metadata:
  name: dogstatsd-service
  namespace: datadog
spec:
  selector:
    app.kubernetes.io/instance: datadog-agent
  ports:
  - protocol: UDP
    port: 8125
    targetPort: 8125
```

And the following Apisix plugin config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-metadata-config-map
  namespace: ingress-apisix
data:
  config.yaml: |
    - cluster: <kubernetes cluster name>
      plugins:
      - name: datadog
        metadata:
          host: "dogstatsd-service.datadog.svc.cluster.local"
          port: 8125
          namespace: "datadog"
```

I tried also with cluster name default, no change. Also with dedicated global rule, but it didn't make change. Also using the cluster ip of the created service as host didn't make any change.
```
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: global
spec:
  plugins:
  - name: datadog
    enable: true
    config:
      host: "dogstatsd-service.datadog.svc.cluster.local"
      port: 8125
      namespace: "datadog"
      constant_tags: ["source:apisix"]
```

Little namespace overview:
- datadog: place of Datadog installation and created service for the DogStatsD DaemonSet
- ingress-apisix: place of Apisix installation

@Revolyssup I hope you have an idea.

Thanks for the support!

### Environment

AKS 1.27.3
Apisix chart 1.7.1
Apisix: 3.6.0
DataDog Operator 1.2.0 with DataDog Agent 3.47
DataDog Agent runs on each AKS node, DogStatsD host port is default and exposed (at least I see it correctly in the POD YAMl description).
