### ISSUE TITLE
bug: etcd timeout error 

### ISSUE THREAD

**Issue by amyrprv** [apache/apisix#10769]
### Current Behavior

I am getting the below error from Apisix in my local envirment in error.log

`2024/01/06 14:55:26 [error] 86#86: *438 [lua] config_etcd.lua:284: init_watch_ctx(): wait main watcher to start, key: /apisix/protos, err: timeout, context: ngx.timer`

### Steps to Reproduce

1. Run apisix with docker-compose:

```
version: "3"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    - ./dashboard_conf/schema.json:/usr/local/apisix-dashboard/conf/schema.json
    ports:
    - "9000:9000"
    networks:
      apisix:

  apisix:
    image: apache/apisix:3.2.2-centos
    # restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_plugins:/usr/local/apisix/apisix/plugins
      - ./apisix_tests:/usr/local/apisix/t
      #- ./apisix_cache:/tmp/disk_cache_one
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:
 
  web1:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
```

### Environment

- APISIX version (run `apisix version`): 3.2.2
- Operating system (run `uname -a`): docker
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
