### ISSUE TITLE
bug: The configuration of the ETCD section through "helm - f values. yaml" did not take effect

### ISSUE THREAD

**Issue by jiangxiulong** [apache/apisix#10762]
### Current Behavior

I am installing Apisix and Apisix dashboard, useing:
`helm install apisix ./apisix-2.5.0.tgz -f apisix-values.yaml -n apisix`
But the etcd of Apisix still prompts to connect“ http://etcd.host:2379/version "The configuration of configmap has not changed, but enabled: false has taken effect because it did not start etcd on its own. I tried to manually change configmap, which is normal."

### Expected Behavior

May I ask why it will partially take effect? I don't want to specify that I still need to manually change the configmap

### Steps to Reproduce

# apisix values.yaml
```
etcd:
  enabled: false
  host:
    - "http://xxxxx:2379"
  user: "user"
  password: "password"


dashboard:
  enabled: true
  config:
    conf:
      etcd:
        endpoints:
          - "http://xxxxx:2379"
        username: username
        password: password
```
# apisix configmap
```
etcd:
   host:                          # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
       - "http://etcd.host:2379"             # multiple etcd address
   prefix: "/apisix"    # configuration prefix in etcd
   timeout: 30    # 30 seconds
   user: "root"
   password: "${{ APISIX_ETCD_PASSWORD }}"
```

### Environment

- APISIX version (run `apisix version`): 3.7
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5
- APISIX Dashboard version, if relevant: 3.0.0
