### ISSUE TITLE
help request: apisix without etcd using ingress controller

### ISSUE THREAD

**Issue by beeant0512** [apache/apisix#10842]
### Description

按照官方文档，[APISIX Ingress Controller：一种无需 etcd 的轻量级部署方式](https://apisix.apache.org/zh/blog/2023/10/18/ingress-apisix/#%E5%AE%89%E8%A3%85-apisix-ingress-controller)，在k8s上还是部署失败了，因为apisix的config好像还是需要有etcd服务，请问有人部署成功过吗？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hanqingwu** [comment]
按说明是在内部模拟 etcd的， 
`模拟 etcd server API：根据 CRD 构建 KV 内存数据库，并模拟 etcd server API 提供给 APISIX 进行使用。APISIX 将会尝试 watch Controller 提供的资源配置，并通知到 APISIX 实例。`

你部署 失败的现象是什么样的？

**Comment by beeant0512** [comment]
> 按说明是在内部模拟 etcd的， `模拟 etcd server API：根据 CRD 构建 KV 内存数据库，并模拟 etcd server API 提供给 APISIX 进行使用。APISIX 将会尝试 watch Controller 提供的资源配置，并通知到 APISIX 实例。`
> 
> 你部署 失败的现象是什么样的？

用的[https://github.com/apache/apisix-helm-chart.git](https://github.com/apache/apisix-helm-chart.git) 提供的charts，把配置etcd改成了false，然后apisix启动报无法连接 localhost:2379

```

# -- Ingress controller configuration
ingress-controller:
  enabled: true
......

etcd:
  # -- install etcd(v3) by default, set false if do not want to install etcd(v3) together
  enabled: false

```
