### ISSUE TITLE
help request: request termination 

### ISSUE THREAD

**Issue by 223311** [apache/apisix#10850]
### Description

Hello team,

I have three paths defined for a domain as shown below. I want to block all requests except those mentioned in the paths. Is there a plugin available that allows me to forcefully terminate requests?

For example:
```
apisix_mappings:
    domain_name: "example.com"
    services:
        - name: test-service
          path: "/httpbin"
          destination: "httpbin.org/anything"
        - name: google-service
          path: "/google/"
          destination: "google.com"
        - name: block-service
          path: "/*"
```

apisix route config file :
[config.txt](https://github.com/apache/apisix/files/13980023/config.txt)

In this context, my objective is to restrict all traffic to the /* path and return a custom message for such requests. Only requests directed to the /httpbin and /google paths should be permitted.

### Environment

version : apisix/3.7
