### ISSUE TITLE
I need to listen multiple ports and apply routing policies on specific port

### ISSUE THREAD

**Issue by Mr-Koala** [apache/apisix#10885]
### Description

As a user, I have started multiple listening ports in APISIX, and I need to apply the defined routing policies on specific ports. However, I couldn't find any relevant documentation in the official documentation. The answer provided by GPT is as follows, but it doesn't seem to work:

```
apisix:
  node_listen:
    - host: "0.0.0.0"
      port: 8080
      proto: http

routes:
  - name: route1
    methods: ["GET", "POST"]
    uris: ["/api"]
    hosts: ["example.com"]
    upstream:
      type: roundrobin
      nodes:
        - target: "http://127.0.0.1:8000"
    attributes:
      node_listen:
        - port: 8080 
   ```
