### ISSUE TITLE
Request Header Fields Too Large. StatusCode: 431

### ISSUE THREAD

**Issue by Cairry** [apache/apisix#11002]
### Description

背景：
request 中携带的hader过大，导致431请求失败。
<img width="407" alt="image" src="https://github.com/apache/apisix/assets/115769353/98f97fb4-21a8-4b12-8e07-5b554fb5ce5c">

解决方案：
查阅文档，配置了如下两个解决方案，但是都没有起到有效作用。
1. 添加client-control插件
```    
plugins:
    - config:
        max_body_size: 0
      enable: true
      name: client-control
```
2. 修改config
```
        client_header_buffer_size: 10240k
        large_client_header_buffers: 6 10240k
```

---
还有其他解决方案吗？
