### ISSUE TITLE
Unable to validate audience claim using openid-connect

### ISSUE THREAD

**Issue by mc-round2** [apache/apisix#11018]
### Description

Hi,

Im trying to use OIDC to authenticate my APIs, so far its working but its working a bit too well because every single token can pass as long as it is a valid token. 

Im trying to only allow tokens that were created for the specific API that im trying to connect to be allowed, and tokens that are valid BUT *not for this specific API* to be unauthorized.

My token provider provides the audience claim that ideally should be cross referenced with the client_id of the route. From my understanding of the documentation (and according to the APISIX DOCS AI) this should come out of the box... but it clearly doesnt.

Am I missing something? 

This is the current config that I have for the openid-connect plugin:
```yaml
bearer_only: true
client_id: wtv
client_secret: wtvwtvw
discovery: https://auth.wtv.wtv/auth/realms/wtv/.well-known/openid-configuration
introspection_endpoint: https://auth.wtv.wtv/auth/realms/wtv/protocol/openid-connect/token/introspect
introspection_endpoint_auth_method: client_secret_basic
use_jwks: true
```
