### ISSUE TITLE
bug: Upstream HealthCheck Issue - Unhealthy Upstream doesn't be excluded temporarily

### ISSUE THREAD

**Issue by kworkbee** [apache/apisix#11016]
### Current Behavior

Same as [apache/apisix-ingress-controller#2176](https://github.com/apache/apisix-ingress-controller/issues/2176).

There is a problem with the unhealthy external service being delivered as it is without being excluded from routing targets.

![Mar-06-2024 17-37-44](https://github.com/apache/apisix-ingress-controller/assets/18034626/5065cdf3-33a9-427f-ae61-c6c4a523e624)

### Expected Behavior

Two external services (ALB configured in front of each) are configured as upstream nodes and should be temporarily excluded from routing if a 5XX error occurs through health check configuration.

### Steps to Reproduce

For reproducing the issue, one service is deployed, and the other one is not deployed (only ALB's are set up.)

```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: route
  namespace: apisix
spec:
  http:
    - match:
        hosts:
          - kubernetes.corp.com
        methods:
          - POST
        paths:
          - /svc/*
      name: route
      plugins:
        - config:
            regex_uri:
              - ^\/svc\/(.+)$
              - /$1
          enable: true
          name: proxy-rewrite
      upstreams:
        - name: upstream
          weight: 100
```
```
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: upstream
  namespace: apisix
spec:
  externalNodes:
    - name: svc01.corp.com
      port: 443
      type: Domain
      weight: 50
    - name: svc02.corp.com
      port: 443
      type: Domain
      weight: 50
  healthCheck:
    active:
      healthy:
        httpCodes:
          - 200
          - 404
        interval: 3s
        successes: 1
      httpPath: /
      type: https
      unhealthy:
        httpCodes:
          - 500
          - 501
          - 502
          - 503
          - 504
        httpFailures: 1
        tcpFailures: 1
        interval: 3s
        timeouts: 3
    passive:
      healthy:
        httpCodes:
          - 200
          - 404
        successes: 1
      type: https
      unhealthy:
        httpCodes:
          - 500
          - 501
          - 502
          - 503
          - 504
        httpFailures: 1
        tcpFailures: 1
        timeouts: 3
  loadbalancer:
    type: roundrobin
  passHost: node
  scheme: https
```

### Environment

APISIX Ingress controller version (run apisix-ingress-controller version --long)
Kubernetes cluster version (run kubectl version)
OS version if running APISIX Ingress controller in a bare-metal environment (run uname -a)
Runs on an AWS EKS Cluster (Kubernetes v1.25). Uses APISIX Helm Chart (1.11.0, App 3.8.0).
