### ISSUE TITLE
help request: 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#11051]
### Description

Hi, I have an issue.

My rout:
curl "http://127.0.0.1:9180/apisix/admin/routes/8" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["POST"],
  "uri": "/api/v1/generateToken",
  "upstream": {
    "type": "roundrobin",
	"scheme": "https",
	"pass_host": "rewrite",
	"upstream_host": "xxx.pp.prod",
    "nodes": {
      "xxx.pp.prod": 1
    }
  }
}'

When I do simple curl to upstream, it works fine:

curl -v --location 'https://xxx.pp.prod/api/v1/generateToken' \
--header 'Content-Type: application/json' \
--data '{
  "username": "USER",
  "password": "PASSWORD"
}'

But if I do request using apisix, it returns 503 

 TCP_NODELAY set
 Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
 POST /api/v1/generateToken HTTP/1.1
 Host: 127.0.0.1:9080
 User-Agent: curl/7.61.1
 Accept: */*
 Content-Type: application/json
 Content-Length: 182

 upload completely sent off: 182 out of 182 bytes
 HTTP/1.1 503 Service Temporarily Unavailable
 Date: Fri, 15 Mar 2024 10:38:47 GMT
 Content-Type: text/html; charset=utf-8
 Content-Length: 269
 Connection: keep-alive
 Server: APISIX/3.6.0

What can be the reason for this?

Error.log:

2024/03/15 16:38:43 [error] 179606#179606: *631795 [lua] resolver.lua:80: parse_domain(): failed to parse domain: xxx.pp.prod, error: failed to query the DNS server: dns server error: 3 name error, client: 127.0.0.1, server: _, request: "POST /api/v1/generateToken HTTP/1.1", host: "127.0.0.1:9080"
2024/03/15 16:38:43 [error] 179606#179606: *631795 [lua] upstream.lua:79: parse_domain_for_nodes(): dns resolver domain: xxx.pp.prod error: failed to query the DNS server: dns server error: 3 name error, client: 127.0.0.1, server: _, request: "POST /api/v1/generateToken HTTP/1.1", host: "127.0.0.1:9080"
2024/03/15 16:38:43 [error] 179606#179606: *631795 [lua] init.lua:551: handle_upstream(): failed to set upstream: no valid upstream node, client: 127.0.0.1, server: _, request: "POST /api/v1/generateToken HTTP/1.1", host: "127.0.0.1:9080"

### Environment

- APISIX version (run `apisix version`): 3.6
- Operating system (run `uname -a`): Linux Redhat
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by PlasticJonbenetDoll** [comment]
2024/03/15 16:38:43 [error] 179606#179606: *631795 [lua] resolver.lua:80: parse_domain(): failed to parse domain: xxx.pp.prod, error: failed to query the DNS server: dns server error: 3 name error, client: 127.0.0.1, server: _, request: "POST /api/v1/generateToken HTTP/1.1", host: "127.0.0.1:9080"
2024/03/15 16:38:43 [error] 179606#179606: *631795 [lua] upstream.lua:79: parse_domain_for_nodes(): dns resolver domain: xxx.pp.prod error: failed to query the DNS server: dns server error: 3 name error, client: 127.0.0.1, server: _, request: "POST /api/v1/generateToken HTTP/1.1", host: "127.0.0.1:9080"
2024/03/15 16:38:43 [error] 179606#179606: *631795 [lua] init.lua:551: handle_upstream(): failed to set upstream: no valid upstream node, client: 127.0.0.1, server: _, request: "POST /api/v1/generateToken HTTP/1.1", host: "127.0.0.1:9080"

**Comment by kayx23** [comment]
You APISIX config used HTTPS scheme. When you curl to the upstream, you used HTTP scheme. Which one does your upstream support?

**Comment by PlasticJonbenetDoll** [comment]
It's https.

I think I have found the reason for this error. I needed to add dns_resolver to my config. I did that, but the error still continues. 

My config.yaml:

```
apisix:
  router:
    http: 'radixtree_uri_with_parameter'
    dns_resolver:                 # If not set, read from `/etc/resolv.conf`
      - 10.8.1.15
      - 10.8.1.16
      - 10.8.70.70
    dns_resolver_valid: 30        # Override the default TTL of the DNS records.
  ssl:
    ssl_protocols: TLSv1.2 TLSv1.3
    ssl_ciphers: TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    #ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    #fallback_sni: "api.stage.kisc.kz"

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
  etcd:
    host:
      - "http://10.11.53.96:2379"
    prefix: "/apisix"
    timeout: 30

nginx_config:                     
  error_log: logs/error.log
  error_log_level:  error
  http:
    proxy_ssl_server_name: true
```
