### ISSUE TITLE
help request: metric occurs even when there is no traffic.

### ISSUE THREAD

**Issue by Ari-suhyeon** [apache/apisix#11108]
### Description

I installed apisix on EKS with helm chart (apisix-2.6.0, APP VERSION 3.8.0).
After changing the deployment replicas of apisix from 1 to 10, I noticed that the metrics went up even though I didn't load test them.
Why is this happening?
![image](https://github.com/apache/apisix/assets/121844970/b2753bd8-2a36-4a1d-bdeb-28331be2d0a6)

helm values.yaml
```yaml
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: apisix

apisix:
  plugins:
    - prometheus
    - public-api
  pluginAttrs:
    prometheus: 
      export_uri: /apisix/prometheus/metrics 
      metric_prefix: apisix_ 
      enable_export_server: true 
      export_addr: 
        ip: 0.0.0.0 
        port: 9091 
      prefer_name: true

metrics:
  serviceMonitor:
    enabled: true
    namespace: apisix
    name: apisix-service-monitor
    interval: "15s"

service:
  type: LoadBalancer

resources:
  limits:
    memory: "2Gi"
    cpu: "2"
  requests:
    memory: "2Gi"
    cpu: "2"
```

resource.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apisix
  name: test-dp
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        ...
---
apiVersion: v1
kind: Service
metadata:
  namespace: apisix
  name: test-svc
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3100
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  namespace: apisix
  name: apisix-route
spec:
  http:
    - name: port-route
      match:
        hosts:
          - XXXXX
        paths:
          - /*
      backends:
        - serviceName: test-svc
          servicePort: 80
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
