### ISSUE TITLE
bug: ext-plugin-pre-req conf value doesn't allow anything else then string

### ISSUE THREAD

**Issue by mkyc** [apache/apisix#11158]
### Current Behavior

Currently only possible type passed to `ext-plugin-pre-req` value is `string`. So to pass anything else then just single value we need to encode it. 

```yaml
      plugins:
        - config:
            conf:
              - name: my-plugin
                value: "{\"test\":\"ugly\"}"
          enable: true
          name: ext-plugin-pre-req
```

### Expected Behavior

It'd be much nicer to make it possible to pass anything there i.e.: 

```yaml
      plugins:
        - config:
            conf:
              - name: my-plugin
                value: 
                  test: "nice"
          enable: true
          name: ext-plugin-pre-req
```

### Steps to Reproduce

NA

### Environment

NA
