### ISSUE TITLE
The protocol configured for k8s apisix ingress grpc does not take effect, please help me

### ISSUE THREAD

**Issue by olddriver4** [apache/apisix#11206]
### Current State

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-grpc
  namespace: app
  annotations:
    kubernetes.io/ingress.class: apisix
    k8s.apisix.apache.org/upstream-scheme: grpc
spec:
  rules:
    - host: "base-grpc.app.ntrnl"
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: base
                port:
                  name: grpc

```     
![image](https://github.com/apache/apisix/assets/28889568/187f4856-7585-4b10-b065-ad28e8ac1d06)     

`grpcurl -plaintext base-grpc.app.ntrnl:80 list social.base.PortalService`       
The protocol configured for k8s apisix ingress grpc does not take effect, please help me. The error is reported as follows:
Error invoking method "social.base.PortalService": rpc error: code = Unavailable desc = failed to query for service descriptor "social.base": error reading from server: EOF         

My domain name has been host-resolved, and LB uses Layer 4 TCP protocol. I would like to know where this problem lies. I have searched for online configurations but can't solve it!
There is absolutely no problem with the service, because I use svc host to access it correctly!      

This is the configuration of the apisix service：    
```
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: apisix
  labels:
    app: apisix
    version: "3.7.0"
spec:
  type: LoadBalancer
  ports:
  - name: apisix-gateway-http
    port: 80
    targetPort: 9080
    protocol: TCP
  - name: apisix-gateway-https
    port: 443
    targetPort: 9080
    protocol: TCP
  selector:
    app: apisix
    version: "3.7.0"
```    
The above are all the steps of my configuration. I really don’t have more detailed configuration problems. Could you please help me detect whether it is a configuration problem there or a LB problem?   @spacewander 

### Desired State

done
