### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by allenwzj** [apache/apisix#11271]
### Description

![image](https://github.com/apache/apisix/assets/3293145/3ba3cd45-bbac-42be-b0c1-00bb93879d25)

apisix dashbord中上游配置如上图：采用的是k8s域名规则 demo.default.svc.cluster.local, 端口是demo service的端口。请求路由返回504 Gateway Time-out

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hanqingwu** [comment]
Please check  apisix whether reach demo.default.svc.cluster.local ?

**Comment by allenwzj** [comment]
> Please check apisix whether reach demo.default.svc.cluster.local ?

请问下如何确认？我在apisix的日志中看到这样的日志信息：
2024/05/22 08:41:38 [error] 49#49: *2066505 [lua] config_etcd.lua:193: watchdir err: has no healthy etcd endpoint available, context: ngx.timer
2024/05/22 08:41:59 [error] 58#58: *2066935 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.10.7.15, server: _, request: "GET /demo/getConfigName HTTP/1.1", upstream: "http://172.16.254.208:9010/demo/getConfigName", host: "xxxxxxx"

**Comment by hanqingwu** [comment]
The log reveal pod  apisix can not  reach  172.16.254.208:9010 .
So please check pod network whether  normal , 
For example  try  `curl -I http://172.16.254.208:9010/demo/getConfigName` in a pod .

**Comment by allenwzj** [comment]
> The log reveal pod apisix can not reach 172.16.254.208:9010 . So please check pod network whether normal , For example try `curl -I http://172.16.254.208:9010/demo/getConfigName` in a pod .

我是通过helm安装的apisix，里面yum命令都没有，也没有curl工具。有其他镜像吗？

**Comment by hanqingwu** [comment]
centos-pod.yaml
```
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-pod
spec:
  containers:
    - image: centos:7
      imagePullPolicy: IfNotPresent
      name: centos-container
      command: ["/bin/bash", "-ce", "tail -f /dev/null"]
```
kubectl apply -f  centos-pod.yaml
then enter pod `  kubectl exec -it centos-pod bash`
