### ISSUE TITLE
help request: failed to query the DNS server

### ISSUE THREAD

**Issue by ilya-tishonok** [apache/apisix#11311]
### Current Behavior

"DNS resolver domain: ${{LOS_SERVICE_UPSTREAM_ADDRESS}} error: failed to query the DNS server: DNS server error: 3 name error" appears when sending a request to the target service (LOS), but the request is hitting the target service. (No configuration was changed after the APISIX server startup). Apisix is started in standalone mode and docker enviroment.

It looks like everything in the request flow is working as expected, but it constantly produces such errors in the logs even if the request was upstreamed to the correct target service (which means that the ENV variable was found).

### Expected Behavior

No errors should be produced in the logs

### Error Logs

![image](https://github.com/apache/apisix/assets/67690609/9ecc9c58-4cc6-4b7c-9732-e5a46cd1bc71)

### Steps to Reproduce

1. Configure apisix.yaml to retrieve node for upstream from envs variables:
```yaml
upstreams:
  -
    id: los_service_upstream
    nodes:
      "${{LOS_SERVICE_UPSTREAM_ADDRESS}}": 1
    type: roundrobin
```
2. Run apisix in docker environment (standalone mode).

### Environment

Docker image: apache/apisix:3.9.0-debian
