### ISSUE TITLE
bug: openid-connect yml conf could not use $env to set plugin properties

### ISSUE THREAD

**Issue by 150149** [apache/apisix#11319]
### Current Behavior

When I use yaml config to set plugin properties, apisix openid-connect plugin could not read $env://KEYCLOAK_PWDvalue.
Environment variable can be seen through linux cmd:
```sh
echo $KEYCLOAK_PWD
```
But apisix plugin could not read those config properties

### Expected Behavior

Apisix plugin can read those config properties

### Steps to Reproduce

1. Create config(Show only key code)
```yaml
  - uri: /api/xxx/*
    service_id: xxxx
    plugins:
      openid-connect:
        client_id: xxx
        client_secret: $ENV://KEYCLOAK_PWD
        discovery: xxxx
        scope: openid
```

### Environment

- APISIX version (3.2.0):
- Operating system (Linux 3.10.0-1160.118.1.el7.x86_64 SMP Thu Apr 4 03:33:23 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux):
- OpenResty / Nginx version (openresty/1.21.4.2):
- etcd version, if relevant (not use):
- APISIX Dashboard version, if relevant(not use)
