### ISSUE TITLE
How to forward to upstream after successful authentication using the forward-auth plugin

### ISSUE THREAD

**Issue by lengdanlexin** [apache/apisix#11363]
### Description

```
curl -X PUT 'http://10.192.25.196:9180/apisix/admin/routes/forward-auth' \
    -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
    -H 'Content-Type: application/json' \
    -d '{
    "uri": "/forward-auth",
    "plugins": {
        "forward-auth": {
            "request_method": "GET",
            "uri": "http://10.192.57.102/auth-bod",
            "request_headers": ["UserName", "Source", "Token"]
        },
        "proxy-rewrite": {
            "regex_uri": ["^/forward-auth(.*)", "/$1"]
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "10.192.203.32:80": 1
        }
    }
}'
```
使用这种方式配置在鉴权成功后可以成功跳转到10.192.203.32:80
如果我想通过CRD的方式去实现相同的效果应该如何做呢
```
---
# 配置上游服务
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: forward-auth-upstream
  namespace: default
spec:
  externalNodes:
    - name: 10.192.203.32
      port: 80
      weight: 1


---
# 部署forward-auth插件

apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: forward-auth-route
  namespace: apisix
spec:
  http:
    - name: forward-auth-rule
      match:
        paths:
          - /forward-auth
      backends:
        - serviceName: forward-auth-upstream
          weight: 1
      plugins:
        - name: forward-auth
          enable: true
          config:
            request_method: GET
            uri: "http://apisix-gateway.apisix.svc.cluster.local/auth-header"
            request_headers:
              - UserName
              - Source
              - Token
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/forward-auth(.*)"
              - "/$1"
        - name: response-rewrite
          enable: true
          config:
            status_code: 200
            headers:
              Server: ""
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
