### ISSUE TITLE
help request:  worker_events.sock failed (98: Address already in use)

### ISSUE THREAD

**Issue by winneryong** [apache/apisix#11376]
### Description

Install from yum, but not start success,  error messgae:

[root@localhost ~]# apisix start
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua start
nginx: [emerg] bind() to unix:/usr/local/apisix/logs/worker_events.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/usr/local/apisix/logs/worker_events.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/usr/local/apisix/logs/worker_events.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/usr/local/apisix/logs/worker_events.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/usr/local/apisix/logs/worker_events.sock failed (98: Address already in use)
nginx: [emerg] still could not bind()

[root@localhost ~]# netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      5692/etcd           
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      5692/etcd           
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd           
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      1729/dnsmasq        
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1087/sshd           
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      1091/cupsd          
tcp        0      0 127.0.0.1:2379          127.0.0.1:52280         ESTABLISHED 5692/etcd           
tcp        0      0 127.0.0.1:52280         127.0.0.1:2379          ESTABLISHED 5692/etcd           
tcp        0    232 192.168.163.128:22      192.168.163.1:51292     ESTABLISHED 1981/sshd: root [pr 
tcp6       0      0 :::3306                 :::*                    LISTEN      1950/mysqld         
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd           
tcp6       0      0 :::22                   :::*                    LISTEN      1087/sshd           
tcp6       0      0 ::1:631                 :::*                    LISTEN      1091/cupsd 

### config.yml
```
deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
        role: admin
  etcd:
    host:
      - http://127.0.0.1:2379
```

### Environment

- APISIX version : 3.9.1
- Operating system : Linux localhost.localdomain 4.18.0-553.5.1.el8_10.x86_64
- OpenResty / Nginx version : openresty/1.25.3.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
