### ISSUE TITLE
Setting gRPC response status via Lua

### ISSUE THREAD

**Issue by federicotdn** [apache/apisix#11402]
### Description

Hi,

I am using APISIX 3.8.0 as an Ingress controller for Kubernetes. I have set up a gRPC route with a single plugin; a `serverless-pre-function` for the `rewrite` phase.

If the endpoint were HTTP, I would be able to write:
```lua
return 404, "Not found"
```
anywhere in the plugin function, and that would correctly return a 404. However gRPC has [its own set of status codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html); is it possible to set these via Lua? If I use the above code for the gRPC endpoint, then client side I just get `Unimplemented` code each time. 

Thanks!

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zhoujiexiong** [comment]
@federicotdn 

Could you show the config similar with your scenario?

**Comment by federicotdn** [comment]
Hi, our ApisixRoute looks a bit like this, unfortunately I can't share all of the details:
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata: ...
spec:
  http:
  - match:
      paths:
      - /foo.Bar/*
    name: grpc
    plugins:
    - config:
        functions:
        - |
          return function(_, ctx)
             local core = require("apisix.core")
             local some_header = core.request.header(ctx, "x-foobar")

             if some_header ~= "some_value" then
                return 404, "Not found"
             end
          end
        phase: rewrite
      enable: true
      name: serverless-pre-function
    upstreams:
    - name: my-upstream
      weight: 1
```
