### ISSUE TITLE
help request: if apisix support proxy http and grpc request in same port

### ISSUE THREAD

**Issue by jujiale** [apache/apisix#11405]
### Description

hello, I want to know **if apisix support proxy http and grpc request in same port**
I find in config.yaml, a port is either `enable_http2: false `or `enable_http2: true `
according my test , a port only support one.

why apisix could not do this,  hope for your reply, thanks

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jujiale** [comment]
I just think, if it is because that in client -> apisix, the apisix keepalive pool is use ip+port to maintain, if use same port to support proxy http and grpc, then the http1.1 connection and http2.0 connection may use confound.

**Comment by zwtesttt** [comment]
![image](https://github.com/user-attachments/assets/6fbd4030-2058-4f07-974e-9023608271b3)

I tried in APISIX 3.5.1 and it is possible to proxy both HTTP and gRPC requests on the same port. You can check if this is the functionality you are looking for.
`apisix.yaml`:
```
routes:
  -
    uri: "/*"
    name: "111"
    methods:
      - "POST"
      - "GET"
    upstream:
      nodes:
        - host: "192.168.31.158"
          port: 50051
          weight: 1
      type: "roundrobin"
      hash_on: "vars"
      scheme: "grpc"
      pass_host: "pass"
    status: 1
  -
    uri: "/test"
    name: "test-route"
    methods:
      - "POST"
      - "GET"
    upstream:
      nodes:
        - host: "192.168.31.158"
          port: 888
          weight: 1
      type: "roundrobin"
      hash_on: "vars"
      scheme: "http"
      pass_host: "pass"
    status: 1

services:
  -
    id: 1
    upstream_id: anything_upstream

upstreams:
  -
    id: "anything_upstream"
    nodes:
      "httpbin.org:80": 1
    type: roundrobin
#END
```
`config.yaml`:
```
apisix:
  enable_http2: true
deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

#END
```
