### ISSUE TITLE
help request: Add annotations about timeout on Ingress , but it not work  on the dashboard

### ISSUE THREAD

**Issue by Pepperpotato** [apache/apisix#11410]
### Description

I want to add annotations about timeout upstream on Ingress,   and I found the docs in there [https://apisix.apache.org/zh/docs/ingress-controller/concepts/annotations/#upstream-timeout](url)

So I edit my ingress yaml and this is my yaml
```yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        k8s.apisix.apache.org/enable-websocket: "true"
        k8s.apisix.apache.org/upstream-connect-timeout: 300s
        k8s.apisix.apache.org/upstream-read-timeout: 300s
        k8s.apisix.apache.org/upstream-send-timeout: 300s
      creationTimestamp: "2024-02-01T08:43:21Z"

```

 but when I update the ingress yaml ,it not work on the apisix dashboard, it still is 6s， the only diff between my yaml and your is my `300s` missing the ""。 I had it with me when I edited it, but when I saved it, it was gone。I don't know if that's what caused it

### Environment

My apisix version : 3.2
