### ISSUE TITLE
docs: how does APISIX configure a forwarding configuration similar to the following figure

### ISSUE THREAD

**Issue by zhaomingcheng01** [apache/apisix#11443]
### Current State

![image](https://github.com/user-attachments/assets/816f5949-dcf3-4f07-97ac-e9319c78ba39)

### Desired State

给一个示例

**Comment by zhoujiexiong** [comment]
Hi @zhaomingcheng01 

Here is an example for standalone mode:

edit `conf/apisix.yaml` config file
```
deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

routes:
  -
    uri: /apollo/*
    upstream:
        nodes:
            "127.0.0.1:8070": 1
        type: roundrobin
#END
```

And proxy_set_header X-Forwarded-Host & X-Forwarded-For are the default settings of APISIX v3

<img width="599" alt="image" src="https://github.com/user-attachments/assets/16806176-1c17-4bd8-b171-239c6ed7c93b">


For more: https://apisix.apache.org/docs/apisix/deployment-modes/#how-to-configure-rules
