### ISSUE TITLE
help request: forward-auth connection timeout

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix#11488]
### Description

In the process of using apisix 2.13, the following logs often appear, even if the timeout has been adjusted to 30,000ms.
```log
2024/08/06 20:16:13 [error] 56#56: *20145140658 [lua] forward-auth.lua:113: phase_func(): failed to process forward auth, err: connection timed out, client: xxx, server: _, request: "POST /xxxx/a HTTP/1.1", host: "xxxxx"

2024/08/06 20:02:15 [error] 57#57: *19151547372 [lua] forward-auth.lua:113: phase_func(): failed to process forward auth, err: connection timed out, client: xxxx, server: _, request: "GET /xxx HTTP/1.1", host: "xxxxx"
```

```yaml
apiVersion: apisix.apache.org/v2beta3
kind: ApisixPluginConfig
metadata:
  name: forward-auth
  namespace: xxxx
spec:
  plugins:
  - config:
      client_headers:
      - Location
      request_headers:
      - X-Forwarded-Host
      - X-Forwarded-Uri
      - X-Requested-With
      timeout: 30000
      upstream_headers:
      - Host
      uri: http://xxxxx.xxx
    enable: true
    name: forward-auth
``` 

### Environment

- APISIX version (run `apisix version`): 2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
