### ISSUE TITLE
help request: Does it support stream poxy match with difference host with same apisix port to difference upstream?

### ISSUE THREAD

**Issue by Mararesliu** [apache/apisix#11516]
### Description

I use APISIX for mysql proxy, Can I use different domain to the same port with apisix for different mysql instance? Can connect with different host to mysql instance.

By the way. If i change some config, and apisix reload when in high traffic, Will there be any connection issues？If that How can i prevent?

THX

### Environment

- APISIX version (run `apisix version`): 3.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@Mararesliu The existing connections wont be dropped when you do apisix reload.


For the stream-proxy related doubt, are you talking about something like

```yaml
apisix:
  stream_proxy: # TCP/UDP proxy
    tcp: # TCP proxy address list
      -127.0.0.9:9101 #mysql server 1
      - "127.0.0.10:9101" #mysql server 2
```

```bash
curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H "X-API-KEY: $admin_key" -X PUT -d '
{
    "server_port": 9101,
    "upstream": {
        "nodes": {
            "127.0.0.1:3306": 1
        },
        "type": "roundrobin"
    }
}'
```

then apisix should forward to the two mysql servers?

**Comment by Revolyssup** [comment]
Do you mean something like

Client -> Apisix @ x:y -> mysql1
Client -> Apisix @x:z -> mysql2 ?

Then you can create two stream routes pointing to same upstream
```yaml
apisix:
  stream_proxy: # TCP/UDP proxy
    tcp: # TCP proxy address list
      - x:y
      - x:z
```

```bash
curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H "X-API-KEY: $admin_key" -X PUT -d '
{
    "server_addr": "x",
    "server_port": y,
    "upstream": {
        "nodes": {
            "mysql1 address": 1
        },
        "type": "roundrobin"
    }
}'


curl http://127.0.0.1:9180/apisix/admin/stream_routes/2 -H "X-API-KEY: $admin_key" -X PUT -d '
{
    "server_addr": "x",
    "server_port": z,
    "upstream": {
        "nodes": {
            "mysql2 address": 1
        },
        "type": "roundrobin"
    }
}'
```
