### ISSUE TITLE
bug: cors plugin does not allow setting ** if allow_credential is true

### ISSUE THREAD

**Issue by rajan123456** [apache/apisix#11586]
### Current Behavior

I am trying to define an APISIX route using CRD. I am trying to enable cors plugin but facing an issue with specifying *

```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: my-test-route
spec:
  http:
  - name: my-test-route-login-post
    match:
      hosts:
      - "login.internal"
      paths:
      - /login*
      methods:
      - "POST"
    backends:
      - serviceName: my-internal-service
        servicePort: 80
    plugins:
      - name: cors
        enable: true
        config:
          allow_origins: "**"
          allow_credential: true
          allow_methods: "**"
          allow_headers: "**"
```

I get the below error after applying the CRD

```
* unexpected status code 400; error message: {"error_msg":"failed to check the configuration of plugin cors err: you can not set '*' for other option when 'allow_credential' is true"}
```

### Expected Behavior

As per docs, forcefully specifying wildcards is supported if ** is specified instead of *

### Steps to Reproduce

1. Deploy APISIX using Helm chart
2. Deploy application as backend
3. Apply ApisixRoute CRD to create Route with specified settings

### Environment

- APISIX version (run `apisix version`): 3.9.1
- Operating system (run `uname -a`): Linux aau-apisix-control-plane-69f888b585-lnzgt 5.15.0-1061-nvidia #62-Ubuntu SMP Mon Jul 15 15:06:50 UTC 2024 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
nginx version: openresty/1.25.3.1
built with OpenSSL 3.2.0 23 Nov 2023
TLS SNI support enabled
configure arguments: --prefix=/opt/bitnami/apisix/openresty/nginx --with-debug --with-cc-opt='-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC -O2 -DAPISIX_RUNTIME_VER=1.2.0 -DNGX_GRPC_CLI_ENGINE_PATH=/opt/bitnami/apisix/openresty/libgrpc_engine.so -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/opt/bitnami/apisix/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/opt/bitnami/apisix/openresty/zlib/include -I/opt/bitnami/apisix/openresty/pcre/include -I/opt/bitnami/apisix/openresty/openssl3/include' --add-module=../ngx_devel_kit-0.3.3 --add-module=../echo-nginx-module-0.63 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.33 --add-module=../ngx_lua-0.10.26 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.37 --add-module=../array-var-nginx-module-0.06 --add-module=../memc-nginx-module-0.20 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.14 --with-ld-opt='-Wl,-rpath,/opt/bitnami/apisix/openresty/luajit/lib -Wl,-rpath,/opt/bitnami/apisix/openresty/wasmtime-c-api/lib -L/opt/bitnami/apisix/openresty/zlib/lib -L/opt/bitnami/apisix/openresty/pcre/lib -L/opt/bitnami/apisix/openresty/openssl3/lib -Wl,-rpath,/opt/bitnami/apisix/openresty/zlib/lib:/opt/bitnami/apisix/openresty/pcre/lib:/opt/bitnami/apisix/openresty/openssl3/lib' --add-module=/tmp/tmp.LFFzS0ylCK/openresty-1.25.3.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.LFFzS0ylCK/openresty-1.25.3.1/../ngx_multi_upstream_module-1.2.0 --add-module=/tmp/tmp.LFFzS0ylCK/openresty-1.25.3.1/../apisix-nginx-module-1.16.0 --add-module=/tmp/tmp.LFFzS0ylCK/openresty-1.25.3.1/../apisix-nginx-module-1.16.0/src/stream --add-module=/tmp/tmp.LFFzS0ylCK/openresty-1.25.3.1/../apisix-nginx-module-1.16.0/src/meta --add-module=/tmp/tmp.LFFzS0ylCK/openresty-1.25.3.1/../wasm-nginx-module-0.7.0 --add-module=/tmp/tmp.LFFzS0ylCK/openresty-1.25.3.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.LFFzS0ylCK/openresty-1.25.3.1/../grpc-client-nginx-module-v0.5.0 --add-module=/tmp/tmp.LFFzS0ylCK/openresty-1.25.3.1/../lua-resty-events-0.2.0 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --with-http_v3_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --without-pcre2 --with-http_ssl_module
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.14
- APISIX Dashboard version, if relevant: 3.0.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0
