### ISSUE TITLE
bug: apisix not allow request, when user-agent set to "Go-http-client/2.0"

### ISSUE THREAD

**Issue by wuyue92tree** [apache/apisix#11625]
### Current Behavior

when set a request with User-Agent: Go-http-client/2.0, return 500
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/c828c98a-5f80-41f8-bfdb-0481bb3ae8bb">

### Expected Behavior

return the real data

### Steps to Reproduce

1. start a web service behand apisix
2. `curl https://webservice -H "User-Agent: Go-http-client/2.0"` 

### Environment

- APISIX version (run `apisix version`): 3.9.1

**Comment by zhoujiexiong** [comment]
What about the route/plugin config?

**Comment by wuyue92tree** [comment]
> What about the route/plugin config?

My apisix is with k8s

only enable chaitin-waf & redirect plugin in globalrule

```
---
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: antio-top-global-rule
spec:
  plugins:
    - name: chaitin-waf
      enable: true
    - name: redirect
      enable: true
      config:
        http_to_https: true

---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: antio-top-route
  namespace: default
spec:
  http:
  - name: one-api
    match:
      hosts:
      - oneapi.antio.top
      paths:
      - /*
    backends:
       - serviceName: one-api
         servicePort: 3000

---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: antio-top-tls
spec:
  hosts:
  - antio.top
  - '*.antio.top'
  secret:
    name: antio-top-tls
    namespace: default

```
