### ISSUE TITLE
bug: cannot turn of accesslog

### ISSUE THREAD

**Issue by caibirdme** [apache/apisix#11633]
### Current Behavior

cannot turn off access log according to #2769

### Expected Behavior

Seems not work in standalone mode(apisix-3.10.0).
I want to turn off the access log, but it still keep logging to the console.

### Steps to Reproduce

Step to reproduce:

1. config.yaml:
```yaml
apisix:
  node_listen:
    - port: 9080
  nginx_config:
    error_log_level: crit
    http:
      enable_access_log: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
```
2. apisix.yaml
```yaml
routes:
  - uri: /foo/bar
    plugins:
      mocking:
        delay: 0
        content_type: "text/plain"
        response_status: 200
        response_example: "hello,world!"
#END
```

3. docker-compose.yaml
```yaml
services:
  apisix:
    image: apache/apisix:3.10.0-debian
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    environment:
      - APISIX_STAND_ALONE=true
    expose:
      - 9080
    user: "${UID}:${GID}"
    
  wrk:
    image: williamyeh/wrk
    command: -t2 -c400 -d5m http://apisix:9080/foo/bar
    depends_on:
      - apisix
```

4. run
```bash
docker compose -f docker-compose.yaml up
```

access log still keep producing, seems that `enable_access_log: false` not work

### Environment

- APISIX version (run `apisix version`): 3.10.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
