### ISSUE TITLE
help request:init_by_lua error: /usr/local/openresty/lualib/resty/core/base.lua:80: loop or previous error loading module 'apisix.core'

### ISSUE THREAD

**Issue by ahululu** [apache/apisix#11660]
### helm deploy apisix, and add custom plugins in values.yaml:
```
apisix:
     plugins:
        - opentelemetry
        - custom-plugin
     customPlugins:
        enabled: true
        luaPath: "/usr/local/apisix/apisix/plugins/?.lua"
        plugins:
          - name: "custom-plugin"
            attrs: { }
            configMap:
              name: "custom-plugin-cm"
              mounts:
                - key: "custom-plugin.lua"
                  path: "/usr/local/apisix/apisix/plugins/custom-plugin.lua"
```
### apisix pod error log
```
Defaulted container "apisix" out of: apisix, wait-etcd (init)
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
2024/10/16 10:36:36 [warn] 1#1: low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:201
nginx: [warn] low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:201
2024/10/16 10:36:36 [error] 1#1: init_by_lua error: /usr/local/openresty/lualib/resty/core/base.lua:80: loop or previous error loading module 'apisix.core'
stack traceback:
	[C]: in function 'error'
	/usr/local/openresty/lualib/resty/core/base.lua:80: in function 'require'
	/usr/local/apisix/apisix/plugins/inspect.lua:17: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/apisix/core/config_etcd.lua:30: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/apisix/core.lua:27: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/apisix/init.lua:29: in main chunk
	[C]: in function 'require'
	init_by_lua:3: in main chunk

```
### other
Apisix pod run well when disable custom plugin.

### Environment

- APISIX version (run `apisix version`): 3.10.0(helm official latest chart)
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
