### ISSUE TITLE
bug: Two sessions shown when using openid-connect

### ISSUE THREAD

**Issue by arnab-sharma** [apache/apisix#11711]
### Current Behavior

We see two sessions 'session' and 'session_2' being set as cookies when using openid-connect. Wanted to understand why session_2 is being set as well.

### Expected Behavior

Expected to see only one cookie 'session' being set.

### Error Logs

![Two_session_cookies](https://github.com/user-attachments/assets/6a9e5ea7-d3e3-4c9f-8b17-763731c81af2)

### Steps to Reproduce

Sample Code:
![image](https://github.com/user-attachments/assets/7c073840-3024-40ea-bdea-7c56431718dc)

### Environment

- APISIX version (run `apisix version`): 3.9.1
- Operating system (run `uname -a`): Kubernetes-compatible Linux x86
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.10
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by arnab-sharma** [comment]
@juzhiyuan - Could you please take a look at above issue?

**Comment by yardenshoham** [comment]
I am also seeing this behavior and want to understand it.

**Comment by yardenshoham** [comment]
Looks like it's happening because the session is too large. You could reduce it's size by adding this config to the plugin:

```yaml
openid-connect:
  ...
  bearer_only: false
  # this comes from https://github.com/zmartzone/lua-resty-openidc, if this is missing, all information will be stored in the session. This
  # causes the cookies to be too large and the request to fail. We have control over id_token, user, enc_id_token, and access_token.
  # We currently include only access_token in the session. If this gets too big we can remove it as well.
  session_contents: 
    access_token: true
  session:
    secret: "NTgzZWY1MzAtOTcyNi00MzA5LWI1MjItNjFhMzI2NzRkZWQxCg==" # used `uuidgen|base64` to generate this secret
```
