### ISSUE TITLE
help request: Stream Proxy with TLS 

### ISSUE THREAD

**Issue by JorgeAraujo123** [apache/apisix#11736]
### Description

I'm using apisix on K8S and i'm trying to do stream proxy via TCP with TLS
I've done the following (via helm):
```yaml
proxy_mode: http&stream
stream_proxy:
  tcp: 
    - addr: 636
      tls: true
service:
  stream:
    enabled: true
    tcp:
      - addr: 636
        tls: true
```

And create the tls and the route:
```yaml
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: vldap-tls
spec:
  hosts:
    - vldap.test.com
  secret:
    name: secret
    namespace: apisix
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: vldap
spec:
  stream:
  - name: vldap
    protocol: TCP
    match:
      ingressPort: 636
      host: vldap.test.com
    backend:
      serviceName: vldap
      servicePort: 636
```

If i do the request direct to the service i get the response, but via apisix i don't:
```
ldap_err2string
ldap_result: Can't contact LDAP server (-1)
ldap_do_free_request: asked to free lr 0x55f921e8f3e0 msgid 1 refcnt 0
ldap_free_connection 1 1
ldap_free_connection: actually freed
```
Am i missing something?

### Environment

- APISIX version (run `apisix version`): 3.9.0
- APISIX Ingress Controller version 1.8.2
- Operating system (run `uname -a`): EKS kubernetes amazon linux
- Load balancer: AWS NLB with proxy protocol
