### ISSUE TITLE
help request: can not create an ApisixPluginConfig of traffic-split

### ISSUE THREAD

**Issue by FIREcup** [apache/apisix#11923]
### Description

this is the ApisixPluginConfig yaml content:
```
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: test-traffic-split
  namespace: xiaom
spec:
  plugins:
  - name: traffic-split
    enable: true
    config:
      rules:
        - match:
            vars:
              - ["http_release", "==", "staging"]
          weighted_upstreams:
            - upstream:
                name: xiaom-svc2
                type: roundrobin
                nodes:
                  "[svc2.xiaom.svc.cluster.local:80](http://svc2.xiaom.svc.cluster.local/)": 10
              weight: 10
```
after I apply this yaml file, I see errors by describing the resource:
`unexpected status code 400; error message: {"error_msg":"invalid configuration: additional properties forbidden, found name"}`
Who know the reason?

### Environment

- APISIX version: 3.6.0
