### ISSUE TITLE
help request: unexpected redirect port

### ISSUE THREAD

**Issue by Nicolfo** [apache/apisix#11974]
### Description

Recently I started using apisix as an ingress controller. I installed it using Helm Chart, but i am stuck with one big problem: every time one of my backend service is sending a redirect response the port get changed from the original 443 to 9443, accessing an unavailable resource. Is there a way to setup apisix to keep the original port when intercepting a redirect request?

WHAT IS HAPPENING:
- user request a resource https://url-of-resource/redirect
- backend send a 302 to /destination url
- apisix rewrite the response to https://url-of-resource:9443/destination (instead of https://url-of-resource/destination)

I configured the endpoint of my backend with an ingress resource:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: apisix
  rules:
    - host: {{ include "uri" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 80
```
Everything else (tls termination/http-to-https plugin) works as expected

### Environment

- APISIX version (run `apisix version`):apache/apisix:3.11.0-debian 
- Operating system (run `uname -a`): 5.15.0-126-generic #136-Ubuntu SMP Wed Nov 6 10:38:22 UTC 2024 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.25.3.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
