### ISSUE TITLE
bug: redirect_uri appended with .apisix/redirect when using openid-connect plugin

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [apache/apisix#12105]
### Current Behavior

Protected routes using openid-connect Relying Party Flow aren't working properly.  

If I set a `redirect_uri` it always redirects to another route.  
Even when I'm still logged in.  

A route that always redirect to another route doesn't make sense and the worst, another route that is unprotected, because if I set another route that is protected, Apisix will redirect to the route appended with .apisix/redirect

If I don't set a `redirect_uri` it always redirects to the same url with a string appended: .apisix/redirect  
Even when I'm yet logged in.  

___________

### My Settings

I have 2 Node.js applications, 2 containers: delivery, panel.  
Both have routes: dashboard, panel, etc.  
In my computer I added in /etc/hosts to facilitate my life:  
127.0.0.1  panel  
127.0.0.1  dashboard  
127.0.0.1  apisix  

If you want delivery and panel services easy, You can run as json-server:  

docker-compose.yml snippet using json-server:  
```
  delivery:
    image: clue/json-server
    container_name: delivery
    volumes:
      - ./data/db.json:/data/db.json
    ports:
      - 3001:80
    networks:
      apisix:

  panel:
    image: clue/json-server
    container_name: panel
    volumes:
      - ./data/db.json:/data/db.json
    ports:
      - 3002:80
    networks:
      apisix:
```

data/db.json  
```json
{
  "delivery": [
    { "id": 1, "body": "foo" },
    { "id": 2, "body": "bar" }
  ],
  "dashboard": [
    { "id": 1, "body": "foo" },
    { "id": 2, "body": "bar" }
  ],
  "panel": [
    { "id": 1, "body": "baz", "postId": 1 },
    { "id": 2, "body": "qux", "postId": 2 }
  ]
}
```

docker-compose.yml  
```yml
services:

  apisix:
    container_name: apisix
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.11.0-debian}
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9180:9180/tcp" #Listen for requests to Admin API.
      - "9080:9080/tcp" #Listen for user requests.
      - "9091:9091/tcp" #Set the port where APISIX exports metrics for Prometheus.
      - "9443:9443/tcp" #Listen for user requests with SSL enabled.
      - "9092:9092/tcp" #
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.5.11
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

  web1:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  web2:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  # prometheus:
  #   image: prom/prometheus:v2.25.0
  #   restart: always
  #   volumes:
  #     - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     apisix:

  # grafana:
  #   image: grafana/grafana:7.3.7
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "./grafana_conf/provisioning:/etc/grafana/provisioning"
  #     - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
  #     - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
  #   networks:
  #     apisix:

  delivery:
    image: delivery
    container_name: delivery
    build:
      context: ./delivery
      target: development
    volumes:
      - ./delivery:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      #- 3001:3001
      - 9229:9229
    command: npm run start:dev
    networks:
      apisix:

  panel:
    container_name: panel
    image: panel
    build:
      context: ./panel
      target: development
    volumes:
      - ./panel:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3002:3002
    command: npm run start:dev
    networks:
      apisix:

  keycloakweb:
    image: mykeycloak
    restart: on-failure
    ports:
      - "18080:18080"
      - "18443:18443"
      - "19000:19000"
    environment:
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      DB_VENDOR: postgres
      DB_USER: root
      DB_PASSWORD: electron
      KC_DB_URL: "jdbc:postgresql://keycloakdb:15432/keycloak"
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: electron
      KC_HOSTNAME: "https://keycloakweb:18443"
      KC_HOSTNAME_ADMIN: "https://keycloakweb:18443"
      KEYCLOAK_FRONTEND_URL: "http://keycloakweb/auth"
      KC_HTTP_PORT: 18080
      KC_HTTPS_PORT: 18443
      KC_HTTP_MANAGEMENT_PORT: 19000
    volumes:
      - ./keycloak/conf/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    networks:
      keycloak-net:
      apisix:

  keycloakdb:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: electron
      PGPORT: 15432
    ports:
      - "15432:15432"
    volumes:
      - ./keycloak/postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net
      
networks:
  apisix:
    driver: bridge
  keycloak-net:
    driver: bridge

volumes:
  etcd_data:
    driver: local
```

___________

### Scenario 1

Without setting `redirect_uri` in the route.

route's configuration:  
```sh
curl -XPUT http://apisix:9180/apisix/admin/routes/dashboard -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -d '{
    "uri": "/dashboard",
    "plugins": {
        "openid-connect": {
            "client_id": "shipment",
            "client_secret": "pbQj2y1uPCzchMidI3XHLfbsRF02kYFJ",
            "discovery": "http://keycloakweb:18080/realms/delivery/.well-known/openid-configuration",
            "scope": "openid profile",
            "bearer_only": false,
            "realm": "delivery",
            "redirect_uri": "/panel",
            "logout_path": "/dashboard/logout"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "panel:3002":1
        }
    }
}'
```

The scenario is as below:

When I type in the browser:  
http://apisix:9080/dashboard

It is redirected to Keycloak login page:  
https://keycloakweb:18443/realms/delivery/protocol/openid-connect/auth?response_type=code&state=fee4ebc1cfda2ec5076c5bce1c163664&scope=openid&client_id=shipment&redirect_uri=http://apisix:9080/dashboard/.apisix/redirect

after logged in the Keycloak, I'm redirected to:  
http://apisix:9080/dashboard/.apisix/redirect?state=d1029196460a1ac98e7860570213e905&session_state=30f149cf-cdf9-480d-ad29-05e3a356311a&iss=https%3A%2F%2Fkeycloakweb%3A18443%2Frealms%2Fdelivery&code=79bd2310-6d82-4ccd-95ba-51c729af66e6.30f149cf-cdf9-480d-ad29-05e3a356311a.dd6b3294-6f28-4c39-a402-051e0059c3f5

And I get this error:

{"error_msg":"404 Route Not Found"}

___________

### Scenario 2

If I set the `redirect_uri` to http://apisix:9080/dashboard in the route:  

snippet from the route's configuration:  
```json
  "uri": "/dashboard",
  "plugins": {
      ...
      "redirect_uri": "/dashboard"
    }
```

or

```json
      "redirect_uri": "http://apisix:9080/dashboard"
```

When I type the route in the browser, this error is printed in the console:  
  
apisix-1       | 2025/03/31 15:04:48 [error] 58#58: *135942 [lua] openidc.lua:1098: authenticate(): unhandled request to the redirect_uri: /dashboard, client: 172.25.0.1, server: _, request: "GET /dashboard HTTP/1.1", host: "apisix:9080"
apisix-1       | 2025/03/31 15:04:48 [error] 58#58: *135942 [lua] openid-connect.lua:588: phase_func(): OIDC authentication failed: unhandled request to the redirect_uri: /dashboard, client: 172.25.0.1, server: _, request: "GET /dashboard HTTP/1.1", host: "apisix:9080"
apisix-1       | 2025/03/31 15:04:48 [warn] 58#58: *135942 [lua] plugin.lua:1174: run_plugin(): openid-connect exits with http status code 500, client: 172.25.0.1, server: _, request: "GET /dashboard HTTP/1.1", host: "apisix:9080"

___________

### Scenario 3

uri: /*  
redirect_uri = http://apisix:9080/*  

```json
curl http://127.0.0.1:9180/apisix/admin/routes/dashboard -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "uri": "/*",
  "plugins": {
    "openid-connect": {
      "client_id": "shipment",
      "client_secret": "pbQj2y1uPCzchMidI3XHLfbsRF02kYFJ",
      "discovery": "http://keycloakweb:18080/realms/delivery/.well-known/openid-configuration",
      "scope":"openid profile",
      "bearer_only": false,
      "realm": "delivery",
      "introspection_endpoint_auth_method":"client_secret_post",
      "redirect_uri": "http://apisix:9080/*"
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "delivery:3001": 1
    }
  }
}'
```
Typing in the browser:  
http://apisix:9080/dashboard

It is redirected to:  
https://keycloakweb:18443/realms/delivery/protocol/openid-connect/auth?redirect_uri=http://apisix:9080/&state=a5d90c7c72fe96041cbe50b7f4ab2ad6&scope=openid%20profile&client_id=shipment&response_type=code

After logged in I'm redirected to:  
apisix:9080/dashboard

But I get the error:  

HTTP CODE 431 (Request Header Fields Too Large)

My upstream is a Node.js app with a dashboard route, I exported the port 3001 and if I type in the browser:  
localhost:3001/dashboard, I get my response normally.  

___________

### Scenario 4

If I set the route using:  
uri: /*  
redirect_uri = http://apisix:9080  

Typing in the browser:  
http://apisix:9080/dashboard

It is redirected to:  
http://apisix:9080/?state=df804196858dfcf2d8e399764e9f48b4&session_state=46991e66-721a-4ce1-b94f-17510f015a04&iss=https%3A%2F%2Fkeycloakweb%3A18443%2Frealms%2Fdelivery&code=1225d43b-5848-4ef2-af55-26849ccca75b.46991e66-721a-4ce1-b94f-17510f015a04.dd6b3294-6f28-4c39-a402-051e0059c3f5

But I get the error:  

ERR_TOO_MANY_REDIRECTS

_______

#### Scenario 5

If I set the route using:  
uri: /*  
redirect_uri = http://apisix:9080/callback  

Typing in the browser:  
http://apisix:9080/dashboard

But I get the error:  

HTTP CODE 431 (Request Header Fields Too Large)

_______

### Expected Behavior

The openid-connect plugin get the request from the protected route, identify the Authorization Header, instropect the Access Token and call the upstream route.

________

### Environment

- APISIX version (run `apisix version`): 3.11.0

- Operating system (run `uname -a`): Linux de10960c9a98 6.8.0-56-generic #58-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 14 15:33:28 UTC 2025 x86_64 GNU/Linux

- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
nginx version: openresty/1.25.3.2
built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
built with OpenSSL 3.2.0 23 Nov 2023
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_RUNTIME_VER=1.2.1 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl3/include' --add-module=../ngx_devel_kit-0.3.3 --add-module=../echo-nginx-module-0.63 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.33 --add-module=../ngx_lua-0.10.26 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.37 --add-module=../array-var-nginx-module-0.06 --add-module=../memc-nginx-module-0.20 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.14 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl3/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl3/lib' --add-module=/tmp/tmp.0vt0zLPiwq/openresty-1.25.3.2/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.0vt0zLPiwq/openresty-1.25.3.2/../ngx_multi_upstream_module-1.2.0 --add-module=/tmp/tmp.0vt0zLPiwq/openresty-1.25.3.2/../apisix-nginx-module-1.16.1 --add-module=/tmp/tmp.0vt0zLPiwq/openresty-1.25.3.2/../apisix-nginx-module-1.16.1/src/stream --add-module=/tmp/tmp.0vt0zLPiwq/openresty-1.25.3.2/../apisix-nginx-module-1.16.1/src/meta --add-module=/tmp/tmp.0vt0zLPiwq/openresty-1.25.3.2/../wasm-nginx-module-0.7.0 --add-module=/tmp/tmp.0vt0zLPiwq/openresty-1.25.3.2/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.0vt0zLPiwq/openresty-1.25.3.2/../lua-resty-events-0.2.0 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --with-http_v3_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --without-pcre2 --with-http_ssl_module

- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
{
  "id": "97f4cdd9-d46e-46a1-b926-47aa77cbb960",
  "version": "3.11.0",
  "etcd_version": "3.5.0",
  "hostname": "de10960c9a98",
  "boot_time": 1743428860
}

- APISIX Dashboard version, if relevant:
 
- Plugin runner version, for issues related to plugin runners:
version 0.2

- LuaRocks version, for installation issues (run `luarocks --version`):
