### ISSUE TITLE
help request: use splunk-hec-logging plugin

### ISSUE THREAD

**Issue by haddasbronfman** [apache/apisix#12117]
### Description

Hi, I'm trying to use `splunk-hec-logging` plugin, but with no luck.
This is my `values.yaml` file:

```
apisix:
  service:
    enable_debug: true
    type: NodePort

  apisix:
    plugins:
      - splunk-hec-logging

    plugin_attr:
      splunk-hec-logging:
        endpoint: 
          uri: "https://<my ip>.splunkcloud.com:8088/services/collector"
          token: "my token"
          timeout: 60

  dashboard:
    enabled: true

```

After I deploy my APISIX (locally) I send a curl request to my APISIX and I expect to see a log in Splunk, but I can't find it. 
I don't know if the configuration here is correct or not.
I saw several options about the uri (with /event or /raw at the end) and also several options for the token (with 'Splunk' before the token or without it) and I'm not sure what's the correct option... 

I do manage to send a curl or a postmen to my Splunk and see the logs.
I send the curl like this: 

```
curl -k "https://<my ip>.splunkcloud.com:8088/services/collector/raw" \                                                         6 ↵     -H "Authorization: Splunk <my token>" \
     -H "Content-Type: application/json" \
     -d '{"event": "Hello Splunk!", "sourcetype": "_json", "index": "apisixlogs"}'
```

In the curl option there is also the index (apisixlogs) but in the splunk-hec-logging plugin there is no place to write it... is that ok? 

Any idea why this is not working for my? 
thanks 

### Environment

- APISIX version:  2.10.0
- Operating system: Darwin HADDASB-M-99XX 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:24 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6030 arm64
