### ISSUE TITLE
feat: support mcp server base on apisix ,provide some current api as mcp tools

### ISSUE THREAD

**Issue by darkSheep404** [apache/apisix#12140]
### Description

I read that apisix currently supports sse
Is it possible to implement the mcp server based on sse protocol on apisix and take the traditional route as the service provided by mcp
The implementation of the tool that wraps the current interface of the system into MCP tools does not implant the original business system

**Comment by jujiale** [comment]
I also look forward to see this feature.

**Comment by helloworld1612** [comment]
I also look forward to see this feature.

**Comment by darkSheep404** [comment]
hi all, seems apisix team rollout a new features which provide stdio services as sse services
https://apisix.apache.org/blog/2025/04/21/host-mcp-server-with-api-gateway/
you gays can have a try 
but i think we still need the feature which take some current http route as the service/tools provided by mcp server
and i belive this will benifit more apisix user

**Comment by darkSheep404** [comment]
@moonming 
we would be very grateful if you could consider this idea

**Comment by moonming** [comment]
> [@moonming](https://github.com/moonming) we would be very grateful if you could consider this idea

> but i think we still need the feature which take some current http route as the service/tools provided by mcp server

Of course, contributions are welcome. Can you give an example? Ensure that our understanding is the same

**Comment by darkSheep404** [comment]
> > [@moonming](https://github.com/moonming) we would be very grateful if you could consider this idea
> 
> > but i think we still need the feature which take some current http route as the service/tools provided by mcp server
> 
> Of course, contributions are welcome. Can you give an example? Ensure that our understanding is the same

In my initial idea
`Option One` , config in routes which want to expose like mcp tools
```yml
routes:
  - uri: /user/userinfo
    plugins:
      ai-mcp-wrapper:
        name: "getUserInfo"
        description: "Get user information by username"
        parameters:
          properties:
            username:
              type: "string"
          required: ["username"]
```
`Option two`, use as gobal plugins to expose all the url want to expose as mcp tools

```yml
plugins:
  - name: ai-mcp-tools
    enable: true
    tools:
      - name: "getUserInfo"
        description: "Get user information by username"
        target_uri: "/user/userinfo"
        parameters:
          properties:
            username:
              type: "string"
              description: "The username to query"
          required: ["username"]
      - name: "createOrder"
        description: "Create a new order"
        target_uri: "/product/query"
        parameters:
          properties:
              productId:
                  type: "string"
               productName:
                    type: "string"
```
