### ISSUE TITLE
help request:

### ISSUE THREAD

**Issue by NandanSatheeshJupiter** [apache/apisix#12150]
### Description

I have created a custom docker image with the plugin created - 

Let's keep this a simple plugin for example - 
```
local core = require("apisix.core")

local plugin_name = "log"

local _M = {
    version = 0.1,
    priority = 0,
    name = plugin_name,
}

_M.schema = {
    type = "object",
    properties = {},
}

function _M.access(conf, ctx)
    core.log.info("log plugin triggered!")
end

return _M
```
Dockerfile - 
```
FROM apache/apisix:3.12.0-debian

USER root

RUN apt-get update && apt-get install -y vim

USER apisix

COPY ./jwt-auth-headers.lua /usr/local/apisix/apisix/plugins/jwt-auth-headers.lua
COPY ./log.lua /usr/local/apisix/apisix/plugins/log.lua
```
k8s YML 
```
apiVersion: v1
kind: Namespace
metadata:
  name: apisix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: apisix
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_admin_cors: true
      admin_key:
        - name: "admin"
          key: edd1c9f034335f136f87ad84b625c8f1
          role: admin
    deployment:
      role: data_plane
      role_data_plane:
        config_provider: yaml
    logger:
      level: "info"  
    
    plugins:
      - log
      - jwt-auth-headers
      - serverless-pre-function
      - grpc-transcode
      - limit-req
      - limit-count
      - proxy-rewrite
      - ip-restriction
      - response-rewrite
    
    plugin_attr:
      - log
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-routes
  namespace: apisix
data:
  apisix.yaml: |
    routes:
      - id: 100
        uri: /health
        plugins:
          log:
          serverless-pre-function:
            phase: access
            functions:
              - |
                return function(conf, ctx)
                  ngx.say('APISIX is healthy')
                  ngx.exit(200)
                end
      - id: 1
        uri: /hello
        upstream:
          type: roundrobin
          nodes:
            "127.0.0.1:8080": 1
        plugins:
          response-rewrite:
            headers:
              set:
                X-Config-Version: "v1"
            body: "Hello from APISIX v1\n"
    #END
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: apisix
  annotations:
    reloader.stakater.com/auto: "true"
    configmap.reloader.stakater.com/reload: "apisix-config,apisix-routes"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apisix
        image: custom-apisix:1.0.6
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        - containerPort: 9180
          name: admin
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /usr/local/apisix/conf/config.yaml
          subPath: config.yaml
        - name: routes
          mountPath: /usr/local/apisix/conf/apisix.yaml
          subPath: apisix.yaml
      volumes:
      - name: config
        configMap:
          name: apisix-config
      - name: routes
        configMap:
          name: apisix-routes
---
apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: apisix
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9080
    name: http
  - port: 9180
    targetPort: 9180
    name: admin
  selector:
    app: apisix
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: apisix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apisix
  maxReplicas: 10
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120  
      policies:
      - type: Pods
        value: 1 
        periodSeconds: 30
---
```

The issue is that the plugin is not getting loaded. Is there anything which is missed currently in the config? Help awaited. Thanks in advance. 

### Environment

- APISIX version (run `apisix version`): 3.12.0
- Operating system (run `uname -a`): 
```
Linux apisix-5df8c7454c-2mf4f 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 GNU/Linux
```
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
```
nginx version: openresty/1.27.1.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
built with OpenSSL 3.2.0 23 Nov 2023
TLS SNI support enabled
```
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): N/A
- APISIX Dashboard version, if relevant: N/A
- Plugin runner version, for issues related to plugin runners: N/A
- LuaRocks version, for installation issues (run `luarocks --version`): N/A

**Comment by mikyll** [comment]
With the configuration you provided, you're not mounting the custom plugin in APISIX container.

You have to:

1. Create a ConfigMap containing the plugin code:

    ```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: apisix-custom-plugin-log
      namespace: apisix
    data:
      log.lua: |
        local core = require("apisix.core")
        
        local plugin_name = "log"
        
        local _M = {
            version = 0.1,
            priority = 0,
            name = plugin_name,
        }
        
        _M.schema = {
            type = "object",
            properties = {},
        }
        
        function _M.access(conf, ctx)
            core.log.info("log plugin triggered!")
        end
        
        return _M
    ```
    
    (You can create this by running `kubectl create configmap apisix-custom-plugin-log --from-file=./log.lua -n apisix --dry-run=client -o yaml`)

2. Mount the ConfigMap to the container. In your apisix Deployment, add the following volume and volumeMount:

    ```yaml
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: apisix
      namespace: apisix
    # [...]
    spec:
      template:
        spec:
          containers:
          - name: apisix
            # [...]
            volumeMounts:
            - name: custom-plugin-log
              mountPath: /usr/local/apisix/apisix/plugins/log.lua
              subPath: log.lua
          volumes:
          - name: custom-plugin-log
            configMap:
              name: apisix-custom-plugin-log
    ```

This should load your plugin correctly 🙂 

For further information, you can have a look at the official documentation: [APISIX Docs | Using custom Plugins in APISIX Ingress](https://apisix.apache.org/docs/ingress-controller/tutorials/using-custom-plugins/)

**Comment by NandanSatheeshJupiter** [comment]
Thanks for the reply @mikyll 

I tried the above steps. Adding the YML - Not seeing any log printed. 

```
apiVersion: v1
kind: Namespace
metadata:
  name: apisix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: apisix
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_admin_cors: true
      admin_key:
        - name: "admin"
          key: edd1c9f034335f136f87ad84b625c8f1
          role: admin
    deployment:
      role: data_plane
      role_data_plane:
        config_provider: yaml
    logger:
      level: "info"  
    
    plugins:
      - log
      - jwt-auth-headers
      - serverless-pre-function
      - grpc-transcode
      - limit-req
      - limit-count
      - proxy-rewrite
      - ip-restriction
      - response-rewrite
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-routes
  namespace: apisix
data:
  apisix.yaml: |
    routes:
      - id: 100
        uri: /health
        plugins:
          log:
          serverless-pre-function:
            phase: access
            functions:
              - |
                return function(conf, ctx)
                  ngx.say('APISIX is healthy')
                  ngx.exit(200)
                end
      - id: 1
        uri: /hello
        upstream:
          type: roundrobin
          nodes:
            "127.0.0.1:8080": 1
        plugins:
          jwt-auth-headers:
            header: Authorization
            query: token
            cookie: jwt 
            hide_credentials: true
            clock_skew: 60
            claims_to_headers:
              key: X-User-Id
              username: X-User-Role
              iss: X-User-Email
          response-rewrite:
            headers:
              set:
                X-Config-Version: "v1"
            body: "Hello from APISIX v1\n"
    #END
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: apisix
  annotations:
    reloader.stakater.com/auto: "true"
    configmap.reloader.stakater.com/reload: "apisix-config,apisix-routes"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apisix
        image: apache/apisix:3.12.0-debian
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        - containerPort: 9180
          name: admin
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /usr/local/apisix/conf/config.yaml
          subPath: config.yaml
        - name: routes
          mountPath: /usr/local/apisix/conf/apisix.yaml
          subPath: apisix.yaml
        - name: custom-plugin-log
          mountPath: /usr/local/apisix/apisix/plugins/log.lua
          subPath: log.lua
      volumes:
      - name: config
        configMap:
          name: apisix-config
      - name: routes
        configMap:
          name: apisix-routes
      - name: custom-plugin-log
        configMap:
          name: apisix-custom-plugin-log
---
apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: apisix
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9080
    name: http
  - port: 9180
    targetPort: 9180
    name: admin
  selector:
    app: apisix
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: apisix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apisix
  maxReplicas: 10
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120  
      policies:
      - type: Pods
        value: 1 
        periodSeconds: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-custom-plugin-log
  namespace: apisix
data:
  log.lua: |
    local core = require("apisix.core")
    
    local plugin_name = "log"
    
    local _M = {
        version = 0.1,
        priority = 0,
        name = plugin_name,
    }
    
    _M.schema = {
        type = "object",
        properties = {},
    }
    
    function _M.access(conf, ctx)
        core.log.info("log plugin triggered!")
    end
    
    return _M
---
```
Only once this is successful, I can try another custom plugin jwt-auth-headers. 

Logs from APISIX - 
```
127.0.0.1 - - [17/Apr/2025:07:05:58 +0000] localhost:49203 "GET /health HTTP/1.1" 200 29 0.000 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" - - - "http://localhost:49203"
```

TIA.

**Comment by mikyll** [comment]
Hi @NandanSatheeshJupiter 

I tested this on minikube and the "log" plugin is loaded correctly, in fact, APISIX only logs the following error:

```lang-none
2025/04/17 08:19:59 [error] 73#73: *27 [lua] plugin.lua:144: load_plugin(): failed to load plugin [jwt-auth-headers] err: module 'apisix.plugins.jwt-auth-headers' not found:
	no field package.preload['apisix.plugins.jwt-auth-headers']
	no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/apisix/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/apisix/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/jwt-auth-headers.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/jwt-auth-headers/init.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/jwt-auth-headers.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/jwt-auth-headers/init.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/jwt-auth-headers/init.lua'
	no file './apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/apisix/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/apisix/deps/share/lua/5.1/apisix/plugins/jwt-auth-headers/init.lua'
	no file './apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/jwt-auth-headers.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/jwt-auth-headers/init.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/jwt-auth-headers.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/jwt-auth-headers/init.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/jwt-auth-headers/init.lua'
	no file './apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/jwt-auth-headers.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/jwt-auth-headers/init.lua'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix/plugins/jwt-auth-headers.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/apisix/plugins/jwt-auth-headers.so'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/jwt-auth-headers.so'
	no file '/usr/local/openresty/lualib/apisix/plugins/jwt-auth-headers.so'
	no file './apisix/plugins/jwt-auth-headers.so'
	no file '/usr/local/lib/lua/5.1/apisix/plugins/jwt-auth-headers.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/jwt-auth-headers.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './apisix/plugins/jwt-auth-headers.so'
	no file '/usr/local/lib/lua/5.1/apisix/plugins/jwt-auth-headers.so'
	no f
```

This is expected, since you haven't defined "jwt-auth-headers" yet 🙂

However, the reason why you're not seeing the log is caused by the following:

1. Incorrect APISIX log level in `config.yaml`;
2. "log" plugin priority.

## Issues

### 1. APISIX Log Level

In your `config.yaml`, you have:

```yaml
logger:
  level: "info"
```

Which doesn't actually change APISIX log level. To change the log level you should use the following:

```yaml
nginx_config:
  error_log_level: info
```

However, since at "info" level, APISIX logs are _a lot_, if you only want to test that the plugin is working, I suggest you to change the plugin level to "warn" instead:

```lua
core.log.warn("log plugin triggered!")
```

You can have a look at [config.yaml.example](https://github.com/apache/apisix/blob/master/conf/config.yaml.example) for a more comprehensive example.

### 2. Plugin Priority

Since your "log" plugin has priority `0`, when you enable it on route `/health`, it will **never** execute, because "serverless-pre-function" has higher priority (10000) and it truncates the request processing, by returning `200`.

You could change that by:

1. increasing the priority in "log" plugin:

    ```lua
    local _M = {
        version = 0.1,
        priority = 20000, -- Or any number > 10000
        name = plugin_name,
    }
    ```

2. increasing the priority in "log" instance, using plugin metadata:

    ```yaml
    routes:
      - id: 100
        uri: /health
        plugins:
          log:
            _meta:
              priority: 20000 # Or any number > 10000
          serverless-pre-function:
            phase: access
            functions:
              - |
                return function(conf, ctx)
                  ngx.say('APISIX is healthy')
                  ngx.exit(200)
                end
    ```

## Full Example

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: apisix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: apisix
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_admin_cors: true
      admin_key:
        - name: "admin"
          key: edd1c9f034335f136f87ad84b625c8f1
          role: admin
    deployment:
      role: data_plane
      role_data_plane:
        config_provider: yaml
    plugins:
      - log
      - jwt-auth-headers
      - serverless-pre-function
      - grpc-transcode
      - limit-req
      - limit-count
      - proxy-rewrite
      - ip-restriction
      - response-rewrite
    # nginx_config:
    #   error_log_level: info
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-routes
  namespace: apisix
data:
  apisix.yaml: |
    routes:
      - id: 100
        uri: /health
        plugins:
          log:
          serverless-pre-function:
            phase: access
            functions:
              - |
                return function(conf, ctx)
                  ngx.say('APISIX is healthy')
                  ngx.exit(200)
                end
      - id: 1
        uri: /hello
        upstream:
          type: roundrobin
          nodes:
            "127.0.0.1:8080": 1
        plugins:
          jwt-auth-headers:
            header: Authorization
            query: token
            cookie: jwt 
            hide_credentials: true
            clock_skew: 60
            claims_to_headers:
              key: X-User-Id
              username: X-User-Role
              iss: X-User-Email
          response-rewrite:
            headers:
              set:
                X-Config-Version: "v1"
            body: "Hello from APISIX v1\n"
      # Testing route
      - id: test_log
        uri: /test_log
        plugins:
          log:
            _meta:
              priority: 30000
    #END
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: apisix
  annotations:
    reloader.stakater.com/auto: "true"
    configmap.reloader.stakater.com/reload: "apisix-config,apisix-routes,apisix-custom-plugin-log"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apisix
        image: apache/apisix:3.12.0-debian
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        - containerPort: 9180
          name: admin
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /usr/local/apisix/conf/config.yaml
          subPath: config.yaml
        - name: routes
          mountPath: /usr/local/apisix/conf/apisix.yaml
          subPath: apisix.yaml
        - name: custom-plugin-log
          mountPath: /usr/local/apisix/apisix/plugins/log.lua
          subPath: log.lua
      volumes:
      - name: config
        configMap:
          name: apisix-config
      - name: routes
        configMap:
          name: apisix-routes
      - name: custom-plugin-log
        configMap:
          name: apisix-custom-plugin-log
---
apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: apisix
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9080
    name: http
  - port: 9180
    targetPort: 9180
    name: admin
  selector:
    app: apisix
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: apisix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apisix
  maxReplicas: 10
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120  
      policies:
      - type: Pods
        value: 1 
        periodSeconds: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-custom-plugin-log
  namespace: apisix
data:
  log.lua: |
    local core = require("apisix.core")
    
    local plugin_name = "log"
    
    local _M = {
        version = 0.1,
        priority = 0,
        name = plugin_name,
    }
    
    _M.schema = {
        type = "object",
        properties = {},
    }
    
    function _M.access(conf, ctx)
        core.log.warn("log plugin triggered!")
    end
    
    return _M
---
```

Hope that helped 🙂 let me know if you still encounter issues or unexpected behaviour
