### ISSUE TITLE
bug: Apisix should reject configurations with missing plugin references

### ISSUE THREAD

**Issue by cruftex** [apache/apisix#12189]
### Current Behavior

If a plugin is missing, the section simply is ignored.

### Expected Behavior

Apisix should refuse operation for that specific route, since the configuration is not intact

This is a possible security pitfall. In the example below, Apisix simply passed through traffic without user authentication.

### Steps to Reproduce

apisix docker image version 3.12.0-debian standalone mode (configuration via yaml file)

route like:

````
routes:
  - id: 1
    hosts:
      - my.domain.net
    uri: /*
    plugins:
      openid-connect:
        client_id: ...
        client_secret: ....
        discovery: ....
        scope: openid email
        bearer_only: false
        realm: ....
    upstream:
      type: roundrobin
      nodes:
        "httpbin.org": 1
````

### Environment

- APISIX version (run `apisix version`): 3.12.0-debian
