### ISSUE TITLE
help request: Unable to get custom plugin to work

### ISSUE THREAD

**Issue by dihmeetree** [apache/apisix#12190]
### Description

Hi guys I'm trying to get a custom plugin to work. 

Here is my very basic plugin code:
```lua
local core = require("apisix.core")

-- Declare the plugin's name
local plugin_name = "hello"

-- Define the plugin schema
local plugin_schema = {
    type = "object",
    properties = {},
    required = {},
}

-- Define the plugin with its version, priority, name, and schema
local _M = {
    version = 0.1,
    priority = 2000,
    name = plugin_name,
    schema = plugin_schema
}

-- Function to check if the plugin configuration is correct
function _M.check_schema(conf)
    return core.schema.check(plugin_schema, conf)
end

-- Function to be called during the access phase
function _M.access(conf, ctx)
    return 200, { message = "hit hello plugin" }
end

-- Return the plugin so it can be used by APISIX
return _M
```

I've added the neccesary Lua load option in my APISIX Control Plane config file like so:
```yaml
apisix:
  # ...
  # Path where plugins are located
  extra_lua_path: "/opt/?.lua"
```

And my APISIX Control Plane service in Docker compose is like so:
```yaml
apisix-control-plane:
    container_name: apisix-control-plane
    image: apache/apisix:3.12.0-debian
    restart: always
    volumes:
      - ./apisix/control_plane/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/plugins:/opt/apisix/plugins:ro # Notice i'm loading the plugins here
    depends_on:
      - apisix-etcd
    ports:
      - '9092:9092/tcp'
      - '9180:9180/tcp'
    networks:
      apisix:
```

Then I added a route like so to test the plugin
```
curl "http://127.0.0.1:9180/apisix/admin/routes/hello" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
   "name": "hello-route",
   "methods": [
      "GET"
   ],
   "uri": "/hello",
   "upstream_id":"1",
   "plugins": {
      "hello": {}
   }
}'
```

Doing this curl for the plugins list does return the hello plugin
```
curl http://localhost:9180/apisix/admin/plugins/list -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1
```
which returns
```
["hello","limit-count","prometheus","log-rotate"]
```

I should be able to go to the `/hello` route and see the custom message from the plugin no? However I do not, I just see the stuff from my upstream app instead.

Any idea's what i'm doing wrong?

### Environment

- APISIX version (run `apisix version`): Running in docker so it's: apache/apisix:3.12.0-debian
- Operating system (run `uname -a`): linux (Docker)
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): Whatever is in the apache/apisix:3.12.0-debian image
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): bitnami/etcd:3.5.21 Docker image
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
