### ISSUE TITLE
help request: unable to sync apisix upstream and route crd using name same as kubernetes service

### ISSUE THREAD

**Issue by rizalalfarizi123** [apache/apisix#12191]
### Description

So i have apisix deployment in same cluster but different namespace with the service. apisix in `platform` namespace and service is in `application` namespace, we use argoCD as gitops tools. currently we use external domain to solve this issue, something like this:
```
-- this is working
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: service-a-upstream
spec:
  retries: 3
  externalNodes:
  - type: Domain
    name: service-a.application.svc.cluster.local
```

and i want to use it as the documentation, so apisix will map the kube service it self, like this
```
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: service-a
spec:
  retries: 3
```
i have referenced the upstream in route, but i got error when syncing the CRD
in ApisixRoute
```
ApisixIngress synced failed, with error: 1 error occurred: * unexpected status code 400; error message: {"error_msg":"failed to fetch upstream info by upstream id [507eaa0], response code: 404"} 
```
in ApisixUpstream
```
ApisixIngress synced failed, with error: upstream doesn't exist. It will be created after ApisixRoute is created referencing it. in ApisixUpstream 
```

### Environment

- APISIX version (run `apisix version`): `docker.io/bitnami/apisix:3.11.0-debian-12-r0`
- APISIX Ingress controller version: `docker.io/bitnami/apisix-ingress-controller:1.8.3-debian-12-r0`
- Operating system (run `uname -a`): `Linux cs-685233466911-default 6.6.72+ #1 SMP PREEMPT_DYNAMIC Sat Apr 19 09:07:01 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
