### ISSUE TITLE
request help: How does a human add http3 headers

### ISSUE THREAD

**Issue by githubcdr** [apache/apisix#12195]
### Current Behavior

Hi,

I find it extremely frustrating to add a Alt-Svc header for http3, the colon seems to be the issue.

I can not add a simple header containing

"Alt-Svc: h3=":443";ma=400"

Via ingress controller this does not work as expected, the dashboard complains about a string (even exscaped)

```
k8s.apisix.apache.org/enable-response-rewrite: "true"
k8s.apisix.apache.org/response-rewrite-add-header: "Alt-Svc: h3=\\\":443\\\";ma=400"

NOR does

k8s.apisix.apache.org/response-rewrite-add-header: |
      Alt-Svc: h3=":443";ma=400
```

As a normal user that does not want to devote a life to yaml, how do I get this working?

Thanks

ps
http3 is working via curl tests

### Expected Behavior

Make it human friendly to enable http3

### Error Logs

NA

### Steps to Reproduce

1. enable http3 in helm values and enable UDP port
2. Sacrifice too many hours getting a header in the response to promote http3

### Environment

- APISIX version 3.12
- Operating system Kubernetes 1.33
- default install

**Comment by Baoyuantop** [comment]
I used the admin api for configuration:

```
{
  "uri": "/*",
  "methods": [
    "GET"
  ],
  "upstream": {
    "nodes": {
      "httpbin.org:80": 1
    }
  },
  "plugins": {
    "response-rewrite": {
      "headers": {
        "set": {
          "Alt-Svc": "h2=\"example.com:443\"; ma=86400"
        }
      }
    }
  }
}
```

```
curl -i 127.0.0.1:9080/get
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 303
Connection: keep-alive
Date: Wed, 07 May 2025 07:57:27 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Server: APISIX/3.12.0
Alt-Svc: h2="example.com:443"; ma=86400

{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Host": "127.0.0.1", 
    "User-Agent": "curl/8.7.1", 
    "X-Amzn-Trace-Id": "Root=1-681b1266-1fc2c422049856b51be1d1ed", 
    "X-Forwarded-Host": "127.0.0.1"
  }, 
  "url": "http://127.0.0.1/get"
}
```

**Comment by githubcdr** [comment]
Thanks for the reply, after spending some more time I also came to this solution. 

Next challenge is to make this work with ingress controller annotations;

So far none of these options provide a working solution, I think the ":" makes apisix confused..

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  namespace: podinfo
  annotations:
    k8s.apisix.apache.org/enable-response-rewrite: "true"
    k8s.apisix.apache.org/response-rewrite-set-header: "alt-svc: h3=:443;"
# or
    k8s.apisix.apache.org/response-rewrite-set-header: 'alt-svc: h3=":443"; ma=6789'
# OR
     k8s.apisix.apache.org/response-rewrite-set-header: "alt-svc: h3=\:443;"
```

It adds the header but with value "h3=\

Could be a bug?

**Comment by Baoyuantop** [comment]
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
  - name: rule1
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    backends:
       - serviceName: httpbin
         servicePort: 80
    plugins:
      - name: response-rewrite
        enable: true
        config:
          headers:
            set:
              Alt-Svc: 'h2="example.com:443"; ma=86400'
```

```
curl -i 127.0.0.1:9080/get -H 'Host: local.httpbin.org'

HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 239
Connection: keep-alive
Date: Thu, 08 May 2025 09:14:09 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Server: APISIX/3.11.0
Alt-Svc: h2="example.com:443"; ma=86400

{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Host": "local.httpbin.org", 
    "User-Agent": "curl/8.7.1", 
    "X-Forwarded-Host": "local.httpbin.org"
  }, 
  "origin": "127.0.0.1", 
  "url": "http://local.httpbin.org/get"
}
```
