### ISSUE TITLE
bug: I can't configure (or extend) the connection timeout at the route or NGINX level

### ISSUE THREAD

**Issue by embesozzi** [apache/apisix#12268]
### Current Behavior

The default timeout is set to 1 minute, and I would like to override it. I’ve tried several ways, but it’s not working

1) At route level is not working:

```
- uri: "/api"
    upstream:
      nodes:
        "host.docker.internal:xxxxx": 1
      timeout:
        connect: 300000
        read: 300000
        send: 300000
```

2) At proxy configuration level is not working

```
nginx_config: 
    http_configuration_snippet: |
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
   
```

There is a setting in nginx.conf that I can't override — or perhaps I just don't know how to.

```
http {
 
    keepalive_timeout 60s;
    client_header_timeout 60s;
    client_body_timeout 60s;
}
```

I tried this configuration but it's not working:

```
nginx_config: 
    http_configuration_snippet: |
        client_body_timeout: 300s;
        client_header_timeout: 300s;
        keepalive_timeout: 300s;
```

Is there a way to extend the 60-second timeout or override that setting?

### Expected Behavior

I want to avoid getting a 504 Gateway Timeout after 1 minute.

### Error Logs

At the browser level, the timeout occurs at 1 minute.

![Image](https://github.com/user-attachments/assets/06356571-ed39-41a6-902d-6e21c2964c1f)

### Steps to Reproduce

See section Current Behavior

### Environment

`
image: apache/apisix:3.12.0-debian
`

**Comment by embesozzi** [comment]
Thanks for the quick response. I changed it to:

```
  - uri: "/api"
    upstream:
      nodes:
        "host.docker.internal:xxxxx": 1
    timeout:
      connect: 600
      read: 600
      send: 600
```

But it's still not working - after one minute, I get the same 504 Gateway Timeout error.

**Comment by mikyll** [comment]
I tried with this minimal example, and it works fine...

File `config.yaml`:

```yaml
deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
```

File `apisix.yaml`:

```yaml
routes:
  - uri: "/anything"
    upstream:
      nodes:
        "httpbin.org": 1
  - uri: "/api"
    upstream:
      nodes:
        "httpbin.org": 1
    # 1 second timeout (overrides default 60s)
    timeout:
      connect: 1
      send: 1
      read: 1
    plugins:
      proxy-rewrite:
        uri: /delay/5
#END
```

Run with:

```bash
docker run --rm -it \
  -v ./conf/config.yaml:/usr/local/apisix/conf/config.yaml \
  -v ./conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml \
  -p 9080:9080 \
  apisix:latest
```

Test routes:

- Route with default timeout (60s) `/anything`:

    ```bash
    $ curl localhost:9080/anything
    {
      "args": {}, 
      "data": "", 
      "files": {}, 
      "form": {}, 
      "headers": {
        "Accept": "*/*", 
        "Host": "localhost", 
        "User-Agent": "curl/8.5.0", 
        "X-Amzn-Trace-Id": "Root=1-6838691d-7b3c765478707abb4d986629", 
        "X-Forwarded-Host": "localhost"
      }, 
      "json": null, 
      "method": "GET", 
      "origin": "10.0.2.100, X.X.X.X", 
      "url": "http://localhost/anything"
    }
    ```

- Route with timeout (1 second) `/api`:

    ```bash
    $ curl localhost:9080/api
    <html>
    <head><title>504 Gateway Time-out</title></head>
    <body>
    <center><h1>504 Gateway Time-out</h1></center>
    <hr><center>openresty</center>
    <p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p></body>
    </html>
    ```

---

Could you provide more configuration details?
