### ISSUE TITLE
help request: After upgrading from version 3.2 to 3.12, calling the admin API returns a 403 error

### ISSUE THREAD

**Issue by lxz999** [apache/apisix#12279]
### Description

After upgrading from version 3.2 to 3.12, calling the admin API returns a 403 error

### Environment

- APISIX version (run `apisix version`): 3.12
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by moonming** [comment]
@lxz999 Please provide a reproducible example

**Comment by lxz999** [comment]
> [@lxz999](https://github.com/lxz999) Please provide a reproducible example

In my configuration, I'm using config.yaml.example and modified the admin-key to 123455678. Then I executed this call:
curl --location 'http://127.0.0.1:9180/apisix/admin/upstreams/1' \
--header 'x-api-key: 123455678'
The backend logs show a 403 error.

**Comment by moonming** [comment]
@lxz999 did you restart apisix after modifying the admin-key? 403 is a client error, not the server side.

**Comment by lxz999** [comment]
> [@lxz999](https://github.com/lxz999) did you restart apisix after modifying the admin-key? 403 is a client error, not the server side.

After restarting, changing the admin-key still doesn't work. It was fine before the upgrade, but after upgrading to 3.12 it keeps returning 403 errors.

**Comment by mikyll** [comment]
@moonming @lxz999

Not sure if that's related, but I've noticed something curious: when setting the API key explicitly as a **string**, it works fine. But if the API-key is a **number**, setting it without quoting, makes calls to Admin API return 401.

Appearently not the same issue, since it's 401, not 403, but maybe gives an insight.

Maybe this can be tracked in a different issue, if that's unexpected behaviour 🙂 

## Minimal Reproducible Example

File `compose.yaml`:

```yaml
services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
    ports:
      - "2379:2379"
    healthcheck:
      test: "etcdctl endpoint health"
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      apisix:

  apisix:
    image: apache/apisix:latest
    depends_on:
      etcd:
        condition: service_healthy
    volumes:
      - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
      - "9180:9180/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
```

File `conf/config.yaml`:

```yaml
 
deployment:
  admin:
    admin_key_required: true
    admin_key:
      - name: admin
        key: 123455678
        role: admin

    allow_admin:
      - 127.0.0.0/24
      - 0.0.0.0/0

    admin_listen:
      ip: 0.0.0.0
      port: 9180

  etcd:
    host:
      - http://etcd:2379
    prefix: "/apisix"
    timeout: 30

#END
```

Run with:

```bash
docker compose up
```

### API Key Number

Using the following API key:

```yaml
deployment:
  admin:
    admin_key_required: true
    admin_key:
      - name: admin
        key: 123455678
        role: admin
```

Test the request:

```bash
curl -i -H "x-api-key: 123455678" "localhost:9180/apisix/admin/upstreams"
```

Result:

```lang-none
HTTP/1.1 401 Unauthorized
...
Server: APISIX/3.12.0

{"error_msg":"failed to check token","description":"wrong apikey"}
```

> [!WARNING]
> Is this expected?

Logs:

```lang-none:
[warn] 224#224: *24432 [lua] init.lua:120: set_ctx_and_check_token(): failed to check token: wrong apikey, client: 10.89.1.3, server: , request: "GET /apisix/admin/upstreams HTTP/1.1", host: "localhost:9180"
```

### API Key String

Using the following API key:

```yaml
deployment:
  admin:
    admin_key_required: true
    admin_key:
      - name: admin
        key: "123455678"
        role: admin
```

Test the request:

```bash
curl -i -H "x-api-key: 123455678" "localhost:9180/apisix/admin/upstreams"
```

Result:

```lang-none
HTTP/1.1 200 OK
...
Server: APISIX/3.12.0

{"total":0,"list":[]}
```
