### ISSUE TITLE
help request: How to configure a uri to ignore case

### ISSUE THREAD

**Issue by 1450793561** [apache/apisix#12303]
### Description

In apisix 3.9 version ，How to configure a uri to ignore case

There is an interface /upload. How to configure the route? Can both request /Upload and /upload be used

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mikyll** [comment]
Currently there's not way to set ignore case in route API URI (see [APISIX Docs | Admin API](https://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters)).

However, you could achieve something similar by using:

- multiple URIs, with `uris` parameter:

    ```yaml
    - id: test
      uris:
        - /Update
        - /update
      upstream:
        nodes:
          "httpbin.org": 1
      plugins:
        proxy-rewrite:
          uri: /get
    ```

- generic URI and `filter_func`:

    ```yaml
    - id: filter_func
      uri: /*
      filter_func: |
        function(vars)
          return string.lower(vars.request_uri) == "/update"
        end
      upstream:
        nodes:
          "httpbin.org": 1
      plugins:
        proxy-rewrite:
          uri: /get
    ```

**Comment by 1450793561** [comment]
> Currently there's not way to set ignore case in route API URI (see [APISIX Docs | Admin API](https://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters)).
> 
> However, you could achieve something similar by using:
> 
> * multiple URIs, with `uris` parameter:
>   - id: multiple_uris
>     uris:
>       - /Update
>       - /update
>     upstream:
>       nodes:
>         "httpbin.org": 1
> * generic URI and `filter_func`:
>   - id: filter_func
>     uri: /*
>     filter_func: |
>       function(vars)
>         return string.lower(vars.request_uri) == "/update"
>       end
>     upstream:
>       nodes:
>         "httpbin.org": 1

How to write the above using JSON format?

**Comment by Baoyuantop** [comment]
Please check https://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters

**Comment by 1450793561** [comment]
```
{
  "uri": "/*",
  "name": "test-test",
  "host": "abc.12123.com",
  "plugins": {
    "proxy-rewrite": {
      "headers": {
        "add": {
          "X-Request-ID": "112233"
        },
        "remove": [
          "X-test"
        ],
        "set": {
          "X-Api-Engine": "apisix",
          "X-Api-Version": "v1",
          "X-Api-useless": ""
        }
      }
    }
  },
"filter_func": " function(vars) return string.lower(vars.request_uri) == \"/upload" end",
  "upstream": {
    "nodes": [
      {
        "host": "10.2.139.37",
        "port": 8088,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```

**Comment by mikyll** [comment]
Example with Admin API (I added proxy-rewrite plugin to send a proper request to httpbin):
 
- multiple URIs, with `uris` parameter:

    ```yaml
    curl -X PUT -H "X-API-KEY: ${ADMIN_APIKEY}" "localhost:9180/apisix/admin/routes/test" -d '
    {
      "uris": [
        "/Update",
        "/update"
      ],
      "upstream": {
        "nodes": {
          "httpbin.org": 1
        }
      },
      "plugins": {
        "proxy-rewrite": {
          "uri": "/get"
        }
      }
    }'
    ```

- generic URI and `filter_func`:

    ```yaml
    curl -X PUT -H "X-API-KEY: ${ADMIN_APIKEY}" "localhost:9180/apisix/admin/routes/test" -d '
    {
      "uri": "/*",
      "filter_func": "function(vars); return string.lower(vars.request_uri) == \"/update\"; end",
      "upstream": {
        "nodes": {
          "httpbin.org": 1
        }
      },
      "plugins": {
        "proxy-rewrite": {
          "uri": "/get"
        }
      }
    }'
    ```

> [!NOTE]
>  You can write `filter_func` in a single line, by using `;` to separate instructions. To write strings you can use escaped double quotes `\" ... \"`, or multiline strings `[[ ... ]]`.
