### ISSUE TITLE
help request: Configuring timeout in apisix upstream created using ApisixRoute CRD

### ISSUE THREAD

**Issue by mehulcommtel** [apache/apisix#12313]
### Description

I am running APISIX as gateway in my k3s environment, and using APISIX routes to create routes and upstreams 
This is my ApisixRoute config file 
This creates a route and upstream but when i check using apisix dashboard the timeout configuration has not taken effect on upstream

what am i missing ?

```
apiVersion: apisix.apache.org/v2

kind: ApisixRoute

metadata:

  name: test

  namespace: backend

spec:

  http:

  - name: test

    match:

      hosts:

      - test.test.com

      paths:

      - /api/*

      - /object/download/*

    backends:

       - serviceName: test-service

         servicePort: 5000

         resolveGranularity: service

    timeout:

        connect: 5s

        read: 360s

        send: 360s

    plugins: 

      - name: proxy-rewrite

        enable: true

        config:

          regex_uri: 

          - "^/api/(.*)"        # Match and capture parts of the URI

          - "/$1"              # Rewrite to the second capture group

          headers:

            set:

              Host: $http_host

              X-Real-IP: $remote_addr

              X-Forwarded-For: $proxy_add_x_forwarded_for

              X-Forwarded-Proto: $scheme

              Upgrade: $http_upgrade

              Connection: "Upgrade" 
```

### Environment

- APISIX version (run `apisix version`): 3.11.0
- Operating system (run `uname -a`): ubuntu 22.04.1 (running apisix on k3s)
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
