### ISSUE TITLE
bug: openid-connect plugin does not load ENV vars

### ISSUE THREAD

**Issue by luarx** [apache/apisix#12342]
### Current Behavior

When referencing an ENV var from openid-connect plugin ("$env://GOOGLE_OPENID_CLIENT_SECRET") it is not loaded

This env var is present in apisix-control-plane and apisix-data-plane pods.

### Expected Behavior

I want to load secret values using Kubernetes secrets to not put them clear in ApisixRoute manifests.

### Steps to Reproduce

Create a route with this plugin configuration:

```
       plugins:
        - name: openid-connect
          enable: true
          config:
            bearer_only: false
            client_id: "XXX"
            client_secret: "$env://GOOGLE_OPENID_CLIENT_SECRET"
            discovery: "https://accounts.google.com/.well-known/openid-configuration"
            scope: openid profile
            redirect_uri: "https://example.com/callback"
```

### Environment

- APISIX version (run `apisix version`): v3.12
