### ISSUE TITLE
bug: openid connect error when 2tabs are open

### ISSUE THREAD

**Issue by emil191995** [apache/apisix#12360]
### Current Behavior

When I have 2 tabs of my app that redirected to login page and I login in first app second automaticaly redirects to redirect uri and returns 500 error for that page

### Expected Behavior

the second need to redirect my app page without 500 error

I debuged and found the issue.
in library openidc when first tab logs in it ends the session and when second comes to redirect_uri page it can not find the session state with the args in request uri cos it is already expired. so the way I solwed in my side is this
`
        if err then
            if session then
                session:close()
            end
            if err == "unauthorized request" then
                if conf.unauth_action == "pass" then
                    return nil
                end
                return 401
            end
            if err == "state from argument does not match state restored from session" then
                ngx.redirect(url)
                return nil
            end
            core.log.error("OIDC authentication failed: ", err)
            return 500
        end`

### Steps to Reproduce

run apisix via docker image
create route with plugin openid connect (I use keycloak as identity server)
open 2 tabs of your app 
login in first
second redirects to redirect_uri

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Baoyuantop** [comment]
Hi @emil191995, can you provide your error logs?

> open 2 tabs of your app
login in first
second redirects to redirect_uri

Can you describe this process in more detail?

**Comment by Baoyuantop** [comment]
I follow this guide and see a 500 error after login, error log:

```
2025/06/23 07:45:41 [error] 119#119: *14160 [lua] openidc.lua:1484: authenticate(): request to the redirect_uri path but there's no session state found, client: 192.168.97.1, server: _, request: "GET /anything/callback?state=3d30e8a771ad687b64aef36000b6b092&session_state=3260ed80-99d7-4d70-ad7c-a9c5edd64e7a&code=d3585cc3-7bb9-4ff6-b17e-0f2a8978f600.3260ed80-99d7-4d70-ad7c-a9c5edd64e7a.93c5f12d-e980-44ba-9d22-dbaa2dcc6042 HTTP/1.1", host: "localhost:9080"
2025/06/23 07:45:41 [error] 119#119: *14160 [lua] openid-connect.lua:680: phase_func(): OIDC authentication failed: request to the redirect_uri path but there's no session state found, client: 192.168.97.1, server: _, request: "GET /anything/callback?state=3d30e8a771ad687b64aef36000b6b092&session_state=3260ed80-99d7-4d70-ad7c-a9c5edd64e7a&code=d3585cc3-7bb9-4ff6-b17e-0f2a8978f600.3260ed80-99d7-4d70-ad7c-a9c5edd64e7a.93c5f12d-e980-44ba-9d22-dbaa2dcc6042 HTTP/1.1", host: "localhost:9080"
```

**Comment by AndreaVida** [comment]
Hi, I got the same issue as well, which I think is due to `lua-resty-openidc` library being unable to handle the state of 2 or more concurrent login sessions from different tabs of the same browser (see [lua-resty-openidc/issues/482](https://github.com/zmartzone/lua-resty-openidc/issues/482)).

When this happens apisix logs show those errors:
```
2025/06/23 15:04:32 [error] 51#51: *125572 [lua] openidc.lua:1106: authenticate(): state from argument: 0719c5fc06a12354487e0a531b31689c does not match state restored from session: 065c3b3ba7625fafe9e670355571841a, client: 10.42.0.3, server: _, request: "GET /callback?state=0719c5fc06a12354487e0a531b31689c&session_state=b0648d29-742a-4c7b-b0d6-6bb07dd0988f&iss=https%3A%2F%2Fportal.10.60.66.58.nip.io%3A31390%2Fauth%2Frealms%2Fmaster&code=1a4bc137-6c1c-4b2c-b92e-da93568e4a72.b0648d29-742a-4c7b-b0d6-6bb07dd0988f.3001bb42-4e21-4549-9201-b285c591db20 HTTP/1.1", host: "portal.10.60.66.58.nip.io:31390"
2025/06/23 15:04:32 [error] 51#51: *125572 [lua] openid-connect.lua:588: phase_func(): OIDC authentication failed: state from argument does not match state restored from session, client: 10.42.0.3, server: _, request: "GET /callback?state=0719c5fc06a12354487e0a531b31689c&session_state=b0648d29-742a-4c7b-b0d6-6bb07dd0988f&iss=https%3A%2F%2Fportal.10.60.66.58.nip.io%3A31390%2Fauth%2Frealms%2Fmaster&code=1a4bc137-6c1c-4b2c-b92e-da93568e4a72.b0648d29-742a-4c7b-b0d6-6bb07dd0988f.3001bb42-4e21-4549-9201-b285c591db20 HTTP/1.1", host: "portal.10.60.66.58.nip.io:31390"
2025/06/23 15:04:32 [warn] 51#51: *125572 [lua] plugin.lua:1174: run_plugin(): openid-connect exits with http status code 500, client: 10.42.0.3, server: _, request: "GET /callback?state=0719c5fc06a12354487e0a531b31689c&session_state=b0648d29-742a-4c7b-b0d6-6bb07dd0988f&iss=https%3A%2F%2Fportal.10.60.66.58.nip.io%3A31390%2Fauth%2Frealms%2Fmaster&code=1a4bc137-6c1c-4b2c-b92e-da93568e4a72.b0648d29-742a-4c7b-b0d6-6bb07dd0988f.3001bb42-4e21-4549-9201-b285c591db20 HTTP/1.1", host: "portal.10.60.66.58.nip.io:31390"
```

The page shows a 500 error returned from /callback endpoint call, however, the user is actually already logged in despite the error so redirecting the browser to a valid page is enough to bypass it.

IMHO what apisix `openid-plugin` can do in this case is to catch the error coming from the library and redirect the browser to the originally requested redirect_uri; I believe in most of the cases this will work fine and transparently.

**Comment by Baoyuantop** [comment]
Hi @AndreaVida, can you provide a detailed reproduction process?

**Comment by AndreaVida** [comment]
@Baoyuantop my setup is quite complex but I think it can be reproduced with simpler setups as well. Try with:

**Setup**
- Apisix 3.11 as gateway (in my case deployed on K8s trough https://github.com/apache/apisix-helm-chart)
- Keycloak 24.0.5 as IdP (deployed on K8s trough https://github.com/bitnami/charts/tree/main/bitnami/keycloak)
- Ingress for apisix svc, routes for keycloak and a test backend svc

apisix openid plugin config (enabled on test app only):
```yaml
"openid-connect": {
      "access_token_in_authorization_header": true,
      "bearer_only": false,
      "client_id": "apisix",
      "client_secret": "XXXXXXX",
      "discovery": "http://keycloak.default.svc/auth/realms/master/.well-known/openid-configuration",
      "introspection_endpoint": "http://keycloak.default.svc/auth/realms/master/protocol/openid-connect/token/introspect",
      "logout_path": "/logout",
      "post_logout_redirect_uri": "/",
      "realm": "master",
      "redirect_uri": "/callback",
      "scope": "openid",
      "session": {
        "secret": "XXXXXXX"
      },
      "session_contents": {
        "access_token": true,
        "id_token": false,
        "enc_id_token": false,
        "user": false
      },
      "set_access_token_header": true,
      "set_id_token_header": false,
      "set_userinfo_header": false,
      "ssl_verify": false,
      "use_jwks": true
    }
```

keycloak svc route (/auth/ is configured as httpRelativePath on Keycloak server for backward compatibility with older versions but can be also removed with rewrite plugin):
```json
{
  "uri": "/auth/*",
  "upstream": {
    "scheme": "http",
    "nodes": {
      "keycloak.default.svc:80": 1
    }
  }
}
```

**Steps**
1. Set master realm session idle timeout to a low limit to make testing easier
2. Connect to test app from main Ingress URL and complete login
3. Open 2 or more tabs on the same test app
4. Let the user session expire
5. Verify pages are still open and cookie is still present
6. Refresh all tabs and get redirected to Keycloak login page on all
7. Observe URL parameters like state and code are different for each tab
8. Try to complete login on one tab and face 500 error
