### ISSUE TITLE
request help: HTTP 431 Error during Keycloak Authentication

### ISSUE THREAD

**Issue by m4dm4rtig4n** [apache/apisix#12372]
### Issue description

When attempting to authenticate via Keycloak (OIDC), the system returns a **431 - Request Header Fields Too Large** error, blocking access to the backend service.

---

## Symptoms

* Users are redirected to Keycloak for login
* After successful login, redirect back to the service fails with:

  ```
  HTTP/1.1 431 Request Header Fields Too Large
  ```
* The protected service remains inaccessible

---

## Suspected Causes

* Header size exceeds buffer limits in APISIX/NGINX
* Possible contributing factors:

  * Too many cookies from Keycloak
  * Oversized `id_token` or `access_token`
  * Repeated redirections increasing header size

---

## Workaround Identified (but not clean)

* Tried removing cookies via `proxy-rewrite` plugin:

  ```yaml
  - name: proxy-rewrite
    config:
      headers:
        remove:
          - Cookie
  ```

  > This workaround reduces header size, but feels like a hack and may introduce side effects. It does not seem like a clean or long-term solution.

🛠️ To support this workaround more cleanly, a GitHub issue has been opened to allow cookie removal directly in the Ingress spec without using a plugin:
👉 https://github.com/apache/apisix-ingress-controller/issues/2414

---

## Actions Taken

* Increased buffer settings in APISIX:

  ```yaml
  client_header_buffer_size: 16k
  large_client_header_buffers:
    - 4
    - 64k
  ```

  > No noticeable improvement

### Environment

* **Reverse proxy:** APISIX
* **Authentication provider:** Keycloak v24.0.4
* **Deployment:** Kubernetes + Helm
* **Ingress:** APISIX Ingress Controller with `openid-connect` plugin
