### ISSUE TITLE
bug: yaml file array format problem

### ISSUE THREAD

**Issue by rhubard** [apache/apisix#1382]
### Issue description
```yaml
routes:
  - uri: "/*"
    vars:
      - 
        - "scheme"
        - "=="
        - "http"
```

this configure can work normally, but yaml will give an error if you write like this

```yaml
routes:
  - uri: "/*"
    vars:
      - - "scheme"
        - "=="
        - "http"
```

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

![image](https://user-images.githubusercontent.com/26682689/78108232-8d389c00-7429-11ea-882d-2d7c904b1029.png)

### What's the expected result?
As long as the yaml array is legal, it should be supported
