### ISSUE TITLE
request help:  in standalone mode, how to define the route rule to match the host

### ISSUE THREAD

**Issue by wangyjx** [apache/apisix#1535]
### Issue description
I am trying to start apisix in standalone mode, but unfortunately I dont know how to make the route to match the host.  

My route configuration is like 

```
routes:
  -
    uri: /hello
    upstream:
        nodes:
            "127.0.0.1:1980": 1
        type: roundrobin

  -
    uri: /serviceStatus
    host: test.xxx.com
    upstream:
        nodes:
            "somehost:32407": 1
        type: roundrobin

#END
```

when I try to visit http://test.xxx.com/serviceStatus, it always return 

"error_msg": "failed to match any routes". 

Can help me to figure this out?

### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS: Centos 7.6, docker

**Comment by moonming** [comment]
@membphis please take a look

**Comment by wangyjx** [comment]
any update on this?

**Comment by membphis** [comment]
sorry for my late reply, here is an example, you can make a try with it:

```
routes:
  -
    uri: /hello
    hosts: 
        - *.foo.com
        - bar.com
    upstream:
        nodes:
            "127.0.0.1:1980": 1
        type: roundrobin

  -
    uri: /serviceStatus
    host: test.xxx.com
    upstream:
        nodes:
            "somehost:32407": 1
        type: roundrobin

#END
```

**Comment by wangyjx** [comment]
@membphis  Thanks for your update.  Unfortunately, I use your example to my conf file as below

routes:
  -
    uri: /hello
    upstream:
        nodes:
            "127.0.0.1:1980": 1
        type: roundrobin
  -
    uri: /status
    hosts:
       - test.xxx.com
    upstream:
        nodes:
            "somehost:32407": 1
        type: roundrobin

#END

visit http://test.xxx.com/status still shows the error message ""error_msg": "failed to match any routes".    
visit http://test.xxx.com/hello return the correct response

**Comment by membphis** [comment]
I think you should check your ENV again. I confirm it can work fine.

Here is my fully yaml:

```
routes:
  -
    uri: /hello
    upstream:
        nodes:
            "127.0.0.1:1980": 1
        type: roundrobin
  -
    uri: /hello2
    hosts:
        - test.com
        - *.foo.com
    upstream:
        nodes:
            "127.0.0.1:1980": 1
        type: roundrobin
#END
```

![image](https://user-images.githubusercontent.com/6814606/81951577-ea825880-9637-11ea-8f72-f6054817ea07.png)
