### ISSUE TITLE
feature: Divide config.yaml into two files config-custom.yaml & config-default.yaml

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#1923]
### Issue description
1. When I deploy APISIX, only a small amount of configuration needs to be modified in conf.yaml.
2. When the APISIX version is upgraded, some configuration items may be added, and these configuration items may be ignored by the user and cause errors.

proposal
1.Divide config.yaml into two files config-custom.yaml & config-default.yaml.
2.`config-default.yaml` is the most complete configuration.
3.`config-custom.yaml` define the user customized configuration.
4. merge the two config file, get final config.

demo
config-custom.yaml
```YAML
apisix:
  node_listen: 80 
  allow_admin:
    - 10.0.0.0/24 
  admin_key:
    -name: "admin"
      key: asdfji213k335f136f87ad84b625c8df
etcd:
  host:
    - "http://10.10.10.2:2379"
    - "http://10.10.10.3:2379"
    - "http://10.10.12.3:2379"
```
config-default.yaml keep the same with APISIX version

generate the final configuration using `config-custom.yaml` to cover `config-default.yaml`.

### Environment

* apisix version 1.4
* OS:
