### ISSUE TITLE
request help: benchmark with Envoy and other gateways

### ISSUE THREAD

**Issue by moonming** [apache/apisix#1942]
### Issue description
Many users want to know the performance comparison between Apache APISIX and envoy, but a correct performance test is very difficult.
Maybe we need to maintain a benchmark with Envoy and other gateways? Of course, all of this is open source.

**Comment by membphis** [comment]
## system info:

```
rain@benchmark:~$ cat /proc/cpuinfo | grep name | cut -f2 -d: |uniq -c
      8  Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz

rain@benchmark:~$ cat /proc/meminfo | grep MemTotal
MemTotal:       57584840 kB

rain@benchmark:~$ cat /proc/version
Linux version 5.3.0-1034-azure (buildd@lcy01-amd64-020) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #35~18.04.1-Ubuntu SMP Mon Jul 13 12:54:45 UTC 2020
```

## 1 worker + 1 route, with no plugin

### envoy

```yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: "0.0.0.0", port_value: 10000 }

    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/hello" }
                route: { cluster: service_baidu }
          http_filters:
          - name: envoy.router

  clusters:
  - name: service_baidu
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: "127.0.0.1", port_value: 1980 }}]
```

```shell
sudo docker run --name=envoy --net=host --rm -d \
  -v $(pwd)/config.yaml:/etc/envoy.yaml \
  envoyproxy/envoy:v1.14-latest -c /etc/envoy.yaml --concurrency 1

rain@benchmark:~$ wrk http://127.0.0.1:10000/hello
Running 10s test @ http://127.0.0.1:10000/hello
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.91ms  206.63us  10.65ms   93.28%
    Req/Sec     5.48k   288.01     5.91k    69.50%
  109109 requests in 10.00s, 434.01MB read
Requests/sec:  10907.31
Transfer/sec:     43.39MB
rain@benchmark:~$ wrk http://127.0.0.1:10000/hello
Running 10s test @ http://127.0.0.1:10000/hello
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.90ms  194.32us  10.60ms   90.33%
    Req/Sec     5.52k   423.13     9.84k    84.58%
  110432 requests in 10.10s, 439.27MB read
Requests/sec:  10934.23
Transfer/sec:     43.49MB
```

### APISIX

```shell
$ curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uris":["/hello"],
    "upstream":{
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}'

rain@benchmark:~$ wrk http://127.0.0.1:9080/hello
Running 10s test @ http://127.0.0.1:9080/hello
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   795.08us  182.98us   7.46ms   89.19%
    Req/Sec     6.29k   483.09    11.41k    88.56%
  125675 requests in 10.10s, 501.94MB read
Requests/sec:  12443.07
Transfer/sec:     49.70MB
rain@benchmark:~$ wrk http://127.0.0.1:9080/hello
Running 10s test @ http://127.0.0.1:9080/hello
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   812.90us  217.38us  12.43ms   94.10%
    Req/Sec     6.14k   313.22     6.77k    74.00%
  122168 requests in 10.00s, 487.93MB read
Requests/sec:  12216.09
Transfer/sec:     48.79MB
```
