### ISSUE TITLE
feat: support `json` encoding escape for access logs

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2266]
For some users, they need to output the access log as a JSON encoding format.

Here is a related article:
https://stackoverflow.com/questions/25049667/how-to-generate-a-json-log-from-nginx

```yaml
nginx_config:
  ... ...
  http:
    access_log: "logs/access.log"
    access_log_format: '{"time_local":"$time_local","remote_addr":"$remote_addr","remote_user":"$remote_user","request":"$request","status": "$status","body_bytes_sent":"$body_bytes_sent","request_time":"$request_time","http_referrer":"$http_referer","http_user_agent":"$http_user_agent"}'
    access_log_format_escape: json       # allows setting json or default characters escaping in variables
```
