### ISSUE TITLE
Proposal: sync plugin/plugin attr to node

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#2381]
Targets:
1. make plugins hot load work on node
2. allow user to configure plugin attributes from admin
3. allow adding intercepts like IP-restriction to plugins' route

Steps:
1. change plugin syntax in config*.yml to:
```yaml
-
  name: pluginA
  attrs:
     a: b
-
  name: pluginB
...
```

2. sync `plugin` to node, and enable hot reload
3. sync `plugin attr` to node
4. add IP-restriction as a common intercept to plugins' route
