### ISSUE TITLE
request help: Stand-alone mode config file guide needed.

### ISSUE THREAD

**Issue by DirtyIndustry** [apache/apisix#2602]
### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: CentOS 8

The target url is [(http://dirtyindustry.cn:8080/api/basmatstrips](http://dirtyindustry.cn:8080/api/basmatstrips), and I wish access it from [http://dirtyindustry.cn:9080/hello/basmatstrips](http://dirtyindustry.cn:9080/hello/basmatstrips).

version 1 apisix.yaml:
```
routes:
    -
        uri: /hello*
        upstream:
            nodes:
                "127.0.0.1:8080": 1
            type: roundrobin
#END
```
 route worked but can't get any data.

version 2 apisix.yaml:
```
routes:
    -
        uri: /hello/${everything}
        upstream:
            nodes:
                "127.0.0.1:8080": 1
            type: roundrobin
        plugins:
            -
                redirect:
                    uri: "/api/${everything}"
#END
```
route don't work, return {"error_msg":"404 Route Not Found"}

version 3 apisix.yaml:
```
routes:
    -
        uri: /hello*
        upstream:
            nodes:
                "127.0.0.1:8080": 1
            type: roundrobin
        plugins:
            -
                redirect:
                    uri: "/api*"
#END
```
route don't work, return {"error_msg":"404 Route Not Found"}
