### ISSUE TITLE
request help: how to enable ssl for https in stand-alone mode?

### ISSUE THREAD

**Issue by isNextJuly** [apache/apisix#2616]
### Issue description
no doc to follow

### Environment
apisix 2.0
* apisix version (cmd: `apisix version`):
* OS:centos 7

**Comment by membphis** [comment]
Here is a simple example:

```yaml
ssl:
  -
    cert: "...",
    key: "...",
    sni: "yourdomain.com"
#END
```

welcome to add this to doc: https://github.com/apache/apisix/blob/master/doc/stand-alone.md
