### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by wenbinye** [apache/apisix#2758]
### Issue description

Cannot add stream_proxy config

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: CentOS 8

### Minimal test code / Steps to reproduce the issue
1. add in conf/config.yaml
```yaml
apisix:
  stream_proxy:
    tcp: [ 6370 ]
```
2. run `apisix init`，errors displayed：
```
lua: ./bin/apisix:613: attempt to index a nil value (local 'base')
stack traceback:
        ./bin/apisix:613: in upvalue 'merge_conf'
        ./bin/apisix:615: in upvalue 'merge_conf'
        ./bin/apisix:615: in upvalue 'merge_conf'
        ./bin/apisix:659: in upvalue 'read_yaml_conf'
        ./bin/apisix:825: in field '?'
        ./bin/apisix:1165: in main chunk
        [C]: in ?
```

### What's the actual result? (including assertion message & call stack if applicable)

nginx.conf was not generate.
if change conf/config-default.yaml add same config, `apisix init` will run successfully：
```yaml
apisix:
  stream_proxy:
    tcp: [ 6370 ]
```
