### ISSUE TITLE
request help: question about time zone

### ISSUE THREAD

**Issue by ziyou434** [apache/apisix#3039]
### Issue description
I find there are some code about time zone，but I don't know what they can do or where they can be use.
```
containers:
        - env:
            - name: TZ
              value: "Asia/Shanghai"

...

hostPath:
            path: /etc/localtime
            type: File
          name: localtime
```
My company is sensitive to time zone，I want to insure these configs  have no effect .

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: linux

**Comment by spacewander** [comment]
```
hostPath:
            path: /etc/localtime
            type: File
          name: localtime
```

This part of code mounts the host's /etc/localtime to the pod. Quoted from the doc:
> If the TZ environment variable does not have a value, the operation chooses a time zone by default. In the GNU C Library, the default time zone is like the specification ‘TZ=:/etc/localtime’ (or ‘TZ=:/usr/local/etc/localtime’, depending on how the GNU C Library was configured; see Installation). Other C libraries use their own rule for choosing the default time zone, so there is little we can say about them.

https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html

```
containers:
        - env:
            - name: TZ
              value: "Asia/Shanghai"
```
I think we should remove this, since it is bad idea to hard code timezone. 
@membphis @gxthrj What about your guys' opinion?
