### ISSUE TITLE
request help: Convert HTTPS to HTTP in apisix

### ISSUE THREAD

**Issue by kuberxy** [apache/apisix#3111]
like this nginx conf:
```nginx
# Force HTTPS
server {
  listen 80;
  server_name yourdomain.com;
  rewrite ^ https://$server_name$request_uri? permanent;
}

# SSL termination
server {
  listen 443 ssl;
  server_name yourdomain.com;

  access_log /var/log/nginx/access.log main;
  error_log /var/log/nginx/error.log error;

  ssl_certificate /etc/ssl/nginx/yourdomain.com.crt;
  ssl_certificate_key /etc/ssl/nginx/yourdomain.com.key;

  location / {
    proxy_set_header Host $host;
    proxy_pass http://localhost:8800;
  }
}

# Clear HTTP
server {
  listen 8800;
  server_name yourdomain.com;

  root /var/www;

  location /index.html {
    if_modified_since off;
    etag off;
    expires -1;
  }

  location / {
    try_files $uri/ $uri /index.html;
  }
}

**Comment by spacewander** [comment]
You can create a SSL object: https://github.com/apache/apisix/blob/master/doc/admin-api.md#ssl,
and then create a route object to match the host: https://github.com/apache/apisix/blob/master/doc/admin-api.md#route

**Comment by kuberxy** [comment]
> You can create a SSL object: https://github.com/apache/apisix/blob/master/doc/admin-api.md#ssl,
> and then create a route object to match the host: https://github.com/apache/apisix/blob/master/doc/admin-api.md#route

but how to implement proxy_pass in apisix?

**Comment by kuberxy** [comment]
Is there a good way?

config.yaml:
```yaml
apisix:
  config_center: yaml
  enable_admin: false
  enable_server_tokens: false
  node_listen: 8800

nginx_config:  
  error_log_level: "error" 
  http_configuration_snippet: |
    server {
        listen      80;
        server_name yourdomain.com;
        rewrite ^ https://$server_name$request_uri? permanent;
    }

    server {
        listen 443 ssl; 
        server_name yourdomain.com;

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log error;

        ssl_certificate /etc/ssl/nginx/yourdomain.com.crt;
        ssl_certificate_key /etc/ssl/nginx/yourdomain.com.key;

        location / {
            proxy_set_header Host $http_host;
            proxy_pass http://localhost:8800;
        }
    }
```

apisix.yaml:
```yaml
upstreams:
    -
        id: 1
        name: "tomcat"
        nodes:
            "192.168.1.1:8090": 1
            "192.168.1.2:8090": 1
            "192.168.1.3:8090": 1
        type: roundrobin

routes:
    -
        uri: /*
        upstream_id: 1
#END
```
