### ISSUE TITLE
request help: 如何覆盖掉全局的限速设置

### ISSUE THREAD

**Issue by kuberxy** [apache/apisix#3114]
我想对来自于公网的所有请求进行限速，但来自内网的请求不限速，该如何配置？
我尝试的配置如下：
apisix.yaml:
```yaml
plugins:
  - name: limit-req

global_rules:
    -
        id: 1
        plugins:
            limit-req:
                rate: 10
                burst: 0
                rejected_code: 503
                key: "remote_addr"

upstreams:
    -
        id: 1
        name: "nginx"
        nodes:
            "192.168.3.146:8080": 1
        type: roundrobin
        checks:
            active:
                http_path: "/"
                healthy:
                    interval: 2
                    successes: 1

routes:
    -
        uri: /*
        upstream_id: 1
    -
        remote_addr: "192.168.3.26"
        uri: /*
        plugins: 
            limit-req:
                rate: 1000
                burst: 0
                rejected_code: 429
                key: "remote_addr"
        priority: 10
#END

```
