### ISSUE TITLE
allow user to configure a fallback SSL cert

### ISSUE THREAD

**Issue by highkay** [apache/apisix#3147]
### Issue description

I have successfully setting sni for some domain, it worked. But right now I need setting sni for ip, I have generated some self signed certs with ip, but get error `failed to find any SSL certificate by SNI: xx.xx.xx.xx, context: ssl_certificate_by_lua*, client: 10.14.0.218, server: 0.0.0.0:9443` . Well I dig the issues and found someone said the sni doesnot support ip. So how can I force to use a self signed cert for ip in apisix just like native nginx.

### Environment

* apisix version 2.1
* OS: apache/apisix:2.1-alpine
* OpenResty / Nginx version: 

### Minimal test code / Steps to reproduce the issue
1. generate a self signed cert for ip
2. upload it to apisix via dashboard
3. create a route with an ip for `Domain name`
4. test the route and got error 

### What's the actual result? (including assertion message & call stack if applicable)

`failed to find any SSL certificate by SNI: xx.xx.xx.xx, context: ssl_certificate_by_lua*, client: 10.14.0.218, server: 0.0.0.0:9443` in error.log

### What's the expected result?

could work like domain route

**Comment by tokers** [comment]
@highkay What's your configuration about the SSL in APISIX?

**Comment by spacewander** [comment]
> Well I dig the issues and found someone said the sni doesnot support ip

The RFC 6066 says "Literal IPv4 and IPv6 addresses are not permitted" in the SNI: https://tools.ietf.org/html/rfc6066
Even we don't follow the RFC, the client may follow it and do not send SNI when the target is an IP. So support IP at our side doesn't always work.

> use a self signed cert for ip in apisix

What about using a virtual domain like k8s's svc.cluster.local?

**Comment by highkay** [comment]
> > Well I dig the issues and found someone said the sni doesnot support ip
> 
> The RFC 6066 says "Literal IPv4 and IPv6 addresses are not permitted" in the SNI: https://tools.ietf.org/html/rfc6066
> Even we don't follow the RFC, the client may follow it and do not send SNI when the target is an IP. So support IP at our side doesn't always work.
> 
> > use a self signed cert for ip in apisix
> 
> What about using a virtual domain like k8s's svc.cluster.local?

I delievered the app in an enviroment in intranet without virtual domain. I just wonder apisix could work like nginx or traefic, setting a default self signed cert for "*".

**Comment by highkay** [comment]
> @highkay What's your configuration about the SSL in APISIX?

```yaml
  ssl:
    enable: true
    enable_http2: true
    listen_port: 9443
    # ssl_trusted_certificate: /usr/local/apisix/conf/cert # Specifies a file path with trusted CA certificates in the PEM format
    #                                             # used to verify the certificate when APISIX needs to do SSL/TLS handshaking
    #                                             # with external services (e.g. etcd)
    ssl_cert: /usr/local/apisix/conf/cert/root.crt
    ssl_cert_key: /usr/local/apisix/conf/cert/root.key
```

the root key is a self signed cert with `mkcert` within a lot private ip.
