### ISSUE TITLE
request help: Can network use service name instead IP?

### ISSUE THREAD

**Issue by leenux** [apache/apisix#3235]
### Issue description
I found network use subnet 172.18.*.*
Can network use service name instead IP?
For example
```
networks:
  apisix-network:
    name: apisix-network
    driver: bridge
```
### Environment

* apisix version (cmd: `apisix version`):2.1
* OS: (cmd: `uname -a`):docker
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`):docker
