### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by cgc1983** [apache/apisix#3762]
### Issue description

apisix version:2.1
OS：Linux 2d6df599090f 4.4.0-198-generic #230-Ubuntu SMP Sat Nov 28 01:30:29 UTC 2020 x86_64 Linux
Nginx Version:openresty/1.19.3.1

```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/hello",
    "plugins": {
        "cors": {}
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:8080": 1
        }
    }
}'
```
{"error_msg":"unknown plugin [cors]"}
```
bash-5.0# cat config.yaml
apisix:
  admin_key:
  - key: edd1c9f034335f136f87ad84b625c8f1
    name: admin
    role: admin
  allow_admin:
  - 0.0.0.0/0
  enable_ipv6: false
  node_listen: 9080
plugin_attr:
  skywalking:
    endpoint_addr: http://172.17.16.68:12800
    service_instance_name: APISIX Instance Name
    service_name: APISIX
plugins:
- skywalking
```
### Environment

why the curl request return error message?

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
