### ISSUE TITLE
 9180 port 403 Forbidden

### ISSUE THREAD

**Issue by phperEric** [apache/apisix#3890]
config.yaml
```
apisix:
  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 192.168.0.0/24            # If we don't set any IP list, then any IP access is allowed by default.
  #   - "::/64"
  port_admin: 9180
  admin_key:
    - name: "admin"
      # yamllint disable rule:comments-indentation
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      # yamllint enable rule:comments-indentation
      role: admin
```

```
curl -i http://127.0.0.1:9180/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uris":[ "/*" ],
    "name":"apisix_proxy_dashboard",
    "upstream":{
        "nodes":[
            {
                "host":"127.0.0.1",
                "port":9000,
                "weight":1
            }
        ],
        "type":"roundrobin"
    }
}'
```

HTTP/1.1 403 Forbidden
Server: openresty
Date: Tue, 23 Mar 2021 06:59:35 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 150
Connection: keep-alive

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>

**Comment by Firstsawyou** [comment]
In `allow_admin` you need to configure the IP list that allows you to access the admin api. 
Example:

```yaml
apisix:
  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 192.168.0.0/24            # If we don't set any IP list, then any IP access is allowed by default.
    - 0.0.0.0/0
  #   - "::/64"
```
