### ISSUE TITLE
request help: nginx: [emerg] invalid port in "table:" of the "listen" directive in ...

### ISSUE THREAD

**Issue by zyue27** [apache/apisix#3920]
### Issue description

I add `node_listen` to the `config.yaml ` 
```
  node_listen:
      - port: 9080
        enable_http2: false
      - port: 9081
        enable_http2: true
```
wnen I restart apisix ,it goes wrong with:
`nginx: [emerg] invalid port in "table:" of the "listen" directive in /usr/local/apisix/conf/nginx.conf:163`

![Snipaste_2021-03-28_11-24-35](https://user-images.githubusercontent.com/42901890/112741410-32903c80-8fb8-11eb-8e60-ad1235f55fe6.png)

### Environment

* apisix version (cmd: `apisix version`):2.3
* OS (cmd: `uname -a`):Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.3.1
