### ISSUE TITLE
[discuss]: how to make the annotations in the config-default.yaml file clearer

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#3962]
# Description:

Currently, the annotations style in the config-default.yaml file is very misleading, for example:

```yaml
router:
  http: 'radixtree_uri'         # radixtree_uri: match route by uri(base on radixtree)
                                  # radixtree_host_uri: match route by host + uri(base on radixtree)
                                  # radixtree_uri_with_parameter: like radixtree_uri but match uri with parameters,
                                  #   see https://github.com/api7/lua-resty-radixtree/#parameters-in-path for
                                  #   more details.
  ssl: 'radixtree_sni'          # radixtree_sni: match route by SNI(base on radixtree)
# stream_proxy:                 # TCP/UDP proxy
#   tcp:             
```
This annotations style is easy to understand that `stream_proxy` is at the same level as `ssl`, but `stream_proxy` is at the same level as `router`.
I think we need a better way of annotation to make it easier for users to understand the hierarchical relationship before them.
what do you think?
