### ISSUE TITLE
discuss: Suggest to add a downgrade strategy to the chash load balancing strategy

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#4276]
### Issue description

Now when upstream chooses chash load balancing, and specify the key, such as

```yaml
  loadbalancer:
    type: chash
    hashOn: cookie
    key: "X-Foo"
```

If the request does not contain any cookies, all traffic will visit a single node and will not be sent to other nodes.

In such a scenario, downgrading the load balancing strategy to polling seems to be a more reasonable solution.

What do you think?
