### ISSUE TITLE
bug: In the docker startup environment, promethues is configured, and there is a problem with the ip detection logic. If the ip is not in the container, an error will be reported.

### ISSUE THREAD

**Issue by liwenzheng** [apache/apisix#4530]
### Issue description
``` 
docker启动环境下，配置promethues，ip检测逻辑有问题，如非容器内ip则会报错。
```
### conf/config.yalm
```
plugin_attr:
  prometheus:
    export_uri: /apisix/prometheus/metrics
    export_addr:
      ip:  172.20.225.102
      port: 9092
```
### docker-compose.yml
```
    networks:
      apisix:
```
### error
```
nginx: [emerg] bind() to 172.20.225.102:9092 failed (99: Address not available)
```
