### ISSUE TITLE
question: How to fix the log with HTTP status code 499 was found in `error.log`

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#4715]
Nginx defines 499 HTTP status codes that means client closes the connection without waiting for a response, controlled by the [`proxy_ignore_client_abort`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ignore_client_abort) command.

In APISIX, you can turn on `proxy_ignore_client_abort` via [customize Nginx configuration](./customize-nginx-configuration.md), which means that APISIX ignores client abort exceptions, does not break the connection to the upstream earlier, and always waits for the upstream response.

for example:

```yaml
nginx_config:
  http_server_configuration_snippet: |
    proxy_ignore_client_abort on;
```
