### ISSUE TITLE
bug: apisix does not take effect on VirtualService policy in istio environment

### ISSUE THREAD

**Issue by dufeixiang** [apache/apisix#4729]
### environment：
- apisix: 2.5
- istio: 1.8.6
### isito config：
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: official-website-web
spec:
  hosts:
    - official-website-web
  http:
    - route:
        - destination:
            host: official-website-web
            subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: official-website-web
spec:
  host: official-website-web
  subsets:
    - labels:
        app: official-website-web
        version: v1
      name: v1
    - labels:
        app: official-website-web
        version: v2
      name: v2
```

#### In istio environment, apisix does not take effect after apisix proxy backend svc and VirtualService specify the policy. When accessing the corresponding service through apisix external network address, the default polling policy is still implemented, and v1 and v2 will be accessed, but in apisix pod VirtualService can take effect when you use curl to access the corresponding service, then only the v1 version will be accessed
