### ISSUE TITLE
ip-restriction无法在 APISIX 中获取真实的客户端 IP

### ISSUE THREAD

**Issue by wjmmjr** [apache/apisix#4767]
环境：k8s helm安装的apisix
问题：使用ip-restriction插件，客户端访问路由发现apisix服务获取的是集群节点的ip,而不是客户端的ip。
曾在configmap中添加如下配置并重启了服务，仍不起作用，获取的还是集群节点的ip
```
nginx_config:
  http:
     real_ip_header: "X-Forwarded-For"
     real_ip_from:
          - 10.3.0.0/32  #集群所在子网地址
          - 127.0.0.1
          - 'unix:'
```
怎么解决？
