### ISSUE TITLE
request help: Whether the active health check is not perfect？

### ISSUE THREAD

**Issue by kuberxy** [apache/apisix#4796]
## Issue description
When the upstream network is unavailable or the upstream is unhealthy, apisix will still forward the request to the problem node
I did a test in two scenarios, as follows

#### nginx1(One of the upstream)
```
# config
mkdir /tmp/upstream
cd /tmp/upstream
mkdir logs/ conf/

tee conf/openresty.conf <<EOF
worker_processes  1;
error_log logs/error.log;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8090;
        location / {
            default_type text/html;
            content_by_lua_block {
                ngx.say("<p>hello, world</p>")
            }
        }
    }
}
EOF

# start
sudo openresty -p `pwd`/ -c conf/openresty.conf

# drop package 
sudo iptables -A OUTPUT -p tcp --sport 8090 ! --dport 8090 -j DROP 
```

#### nginx2 and nginx3 (Other upstream)
```
# config
mkdir /tmp/upstream
cd /tmp/upstream
mkdir logs/ conf/

tee conf/openresty.conf <<EOF
worker_processes  1;
error_log logs/error.log;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8090;
        location / {
            default_type text/html;
            content_by_lua_block {
                ngx.say("<p>hello, world</p>")
            }
        }
    }
}
EOF

# start
sudo openresty -p `pwd`/ -c conf/openresty.conf
```

#### use apisix as proxy
config.yaml:
```
apisix:
  config_center: yaml
  enable_admin: false
  enable_server_tokens: false
  enable_control: false
  node_listen: 80

nginx_config:  
  error_log_level: "error" 
  http: 
    access_log_format: '{"@timestamp":"$time_iso8601","client_ip":"$clientRealIp","accessip_list":"$proxy_add_x_forwarded_for","http_host":"$host","url":"$request_uri","http_referer":"$http_referer","user_agent":"$http_user_agent","method":"$request_method","status_code":"$status","total_bytes_sent":"$bytes_sent","body_bytes_sent":"$body_bytes_sent","request_time":"$request_time","upstream_response_time":"$upstream_time" }'
    access_log_format_escape: json
  http_configuration_snippet: |
    # lua timer limitations
    lua_max_pending_timers 40960;
    lua_max_running_timers 256;
    
    # access log vriable
    map $http_x_forwarded_for $clientRealIp {
        "" $remote_addr;
        ~^(?P<firstAddr>[0-9\.]+),?.*$ $firstAddr;
    }

    map $upstream_response_time $upstream_time {
        default 0;
        ~^(?P<time>[0-9]+\.[0-9]+)$ $time;
    }

    # other conf
    http2_max_header_size 4000k;
    http2_max_field_size 4000k;

    proxy_read_timeout 240s;

    client_header_buffer_size 512k;
    large_client_header_buffers 4 512k;
```

apisix.yaml:
```
upstreams:
    -
        id: 1
        name: "nginx"
        nodes:
            "nginx1:8090": 1
            "nginx2:8090": 1
            "nginx3:8090": 1
        type: roundrobin
        checks:
            active:
                timeout: 5
                http_path: "/active"
                healthy:
                    http_statuses:
                    - 200
                    - 301
                    - 302
                    - 304
                    successes: 1
                    interval: 2
                unhealthy:
                    http_statuses:
                    - 500
                    - 502
                    - 503
                    - 504
                    http_failures: 2
                    interval: 1
            passive:
                healthy:
                    http_statuses:
                    - 200
                    - 206
                    - 301
                    - 302
                    - 304
                    successes: 3
                unhealthy:
                    http_statuses:
                    - 499
                    - 500
                    - 503
                    - 502
                    - 504
                    tcp_failures: 3
                    http_failures: 3

routes:
    -
        uri: /*
        upstream_id: 1

#END
```
The request was still forwarded to nginx1 and was retried after 60 seconds
```
$ time for i in $(seq 15); do curl 192.168.2.11;done
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>

real	1m0.276s
user	0m0.130s
sys	0m0.085s
```
#### use openresty as proxy
```
# config
mkdir /tmp/proxy
cd /tmp/proxy
mkdir logs/ conf/

tee conf/openresty.conf <<\EOF
#user  nobody;
#worker_processes  1;

error_log  logs/error.log;

pid        logs/nginx.pid;

events {
    worker_connections  1024;
}


http {
    default_type  application/octet-stream;

    # access log vriable
    map $http_x_forwarded_for $clientRealIp {
        "" $remote_addr;
        ~^(?P<firstAddr>[0-9\.]+),?.*$ $firstAddr;
    }

    map $upstream_response_time $upstream_time {
        default 0;
        ~^(?P<time>[0-9]+\.[0-9]+)$ $time;
    }

    log_format json '{'
        '"@timestamp":"$time_iso8601",'
        '"client_ip":"$clientRealIp",'
        '"accessip_list":"$proxy_add_x_forwarded_for",'
        '"http_host":"$host",'
        '"url":"$request_uri",'
        '"http_referer":"$http_referer",'
        '"user_agent":"$http_user_agent",'
        '"method":"$request_method",'
        '"status_code":"$status",'
        '"total_bytes_sent":"$bytes_sent",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"request_time":"$request_time",'
        '"upstream_response_time":"$upstream_time"'
    '}';

    access_log  logs/access.log  json;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;
    
    # cy app conf
    http2_max_header_size 4000k;
    http2_max_field_size 4000k;

    proxy_read_timeout 240s;

    client_header_buffer_size 512k;
    large_client_header_buffers 4 512k;
    
upstream nginx {
    server nginx1:8090 weight=1 max_conns=0 max_fails=1 fail_timeout=10;
    server nginx2:8090 weight=1 max_conns=0 max_fails=1 fail_timeout=10;
    server nginx3:8090 weight=1 max_conns=0 max_fails=1 fail_timeout=10;

}

lua_shared_dict healthcheck 1m;

lua_socket_log_errors off;

init_worker_by_lua_block {
    local hc = require "resty.upstream.healthcheck"

    local ok, err = hc.spawn_checker{
        shm = "healthcheck",
        upstream = "nginx",
        type = "http",

        http_req = "GET /active HTTP/1.1\r\nHost: nginx\r\n\r\n",

        interval = 2000,
        timeout = 5000,
        fall = 3,
        rise = 2,
        valid_statuses = {200, 302},
        concurrency = 10,
    }

    if not ok then
        ngx.log(ngx.ERR, "failed to spawn health checker: ", err)
        return
    end
}

server {
    server_name 0.0.0.0;
    listen 12354;

    location = /status {
        access_log off;
        allow 127.0.0.1;
        deny all;

        default_type text/plain;
        content_by_lua_block {
            local hc = require "resty.upstream.healthcheck"
            ngx.print(hc.status_page())
        }
    }
}

server {
    server_name 0.0.0.0;
    listen      80;

    location / {
        proxy_pass http://nginx;
        proxy_set_header Host $http_host;
    }
    
}

}

EOF

# start
sudo openresty -p `pwd`/ -c conf/openresty.conf
```
The request is not forwarded to the upstream of the lost packet
```
$ time for i in $(seq 15); do curl 192.168.2.11;done
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>

real    0m0.201s
user    0m0.136s
sys 0m0.056s
```

#### nginx1(One of the upstream)
```
# config
mkdir /tmp/upstream
cd /tmp/upstream
mkdir logs/ conf/

tee conf/openresty.conf <<EOF
worker_processes  1;
error_log logs/error.log;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8090;

        location /active {
            default_type text/html;
            content_by_lua_block {
                ngx.exit(500)
            }
        }	

        location / {
            default_type text/html;
            content_by_lua_block {
                ngx.say("<p>healthy 500</p>")
            }
        }
    }
}
EOF

# start
sudo openresty -p `pwd`/ -c conf/openresty.conf

```

#### nginx2 and nginx3 (Other upstream)
Same configuration as above

#### use apisix as proxy
Same configuration as above

The request was still forwarded to nginx1
```
$ for i in $(seq 15); do curl 192.168.2.11;done
<p>healthy 500</p>
<p>healthy 500</p>
<p>hello, world</p>
<p>healthy 500</p>
<p>hello, world</p>
<p>hello, world</p>
<p>healthy 500</p>
<p>hello, world</p>
<p>hello, world</p>
<p>healthy 500</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>healthy 500</p>
<p>hello, world</p>
```
#### use openresty as proxy
Same configuration as above

The request is not forwarded to unhealthy upstream
```
$ for i in $(seq 15); do curl 192.168.2.11;done
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
```

## Environment
* apisix version (cmd: `apisix version`): 2.3
* OS (cmd: `uname -a`): 4.15.0-111-generic Ubuntu 18.04
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.15.8.3
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): Stand-Alone
* apisix-dashboard version, if have: not have
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): 2.4.2

**Comment by spacewander** [comment]
I tried to reproduce it but failed.

Here is my upstream:
```
worker_processes 1;
daemon off;
error_log stderr warn;
events {
    worker_connections 65535;
}
http {
    access_log off;
    resolver 114.114.114.114;
    server {
        listen 1980;
        location /active {
            default_type text/html;
            content_by_lua_block {
                ngx.exit(500)
            }
        }

        location / {
            default_type text/html;
            content_by_lua_block {
                ngx.say("<p>healthy 500</p>")
            }
        }
    }
    server {
        listen 8090;
        location / {
            default_type text/html;
            content_by_lua_block {
                ngx.say("<p>hello, world</p>")
            }
        }
    }
}
```

My conf:
```
apisix:
  config_center: yaml
  enable_admin: false
  enable_server_tokens: false
  enable_control: false

nginx_config:
  error_log_level: "warn"
  http:
    access_log_format: '{"@timestamp":"$time_iso8601","client_ip":"$clientRealIp","accessip_list":"$proxy_add_x_forwarded_for","http_host":"$host","url":"$request_uri","http_referer":"$http_referer","user_agent":"$http_user_agent","method":"$request_method","status_code":"$status","total_bytes_sent":"$bytes_sent","body_bytes_sent":"$body_bytes_sent","request_time":"$request_time","upstream_response_time":"$upstream_time" }'
    access_log_format_escape: json
  http_configuration_snippet: |
    # lua timer limitations
    lua_max_pending_timers 40960;
    lua_max_running_timers 256;

    # access log vriable
    map $http_x_forwarded_for $clientRealIp {
        "" $remote_addr;
        ~^(?P<firstAddr>[0-9\.]+),?.*$ $firstAddr;
    }

    map $upstream_response_time $upstream_time {
        default 0;
        ~^(?P<time>[0-9]+\.[0-9]+)$ $time;
    }

    # other conf
    http2_max_header_size 4000k;
    http2_max_field_size 4000k;

    proxy_read_timeout 240s;

    client_header_buffer_size 512k;
    large_client_header_buffers 4 512k;
```

```
upstreams:
    -
        id: 1
        name: "nginx"
        nodes:
            "127.0.0.1:1980": 1
            "127.0.0.1:8090": 1
            "127.0.0.2:8090": 1
        type: roundrobin
        checks:
            active:
                timeout: 5
                http_path: "/active"
                healthy:
                    http_statuses:
                    - 200
                    - 301
                    - 302
                    - 304
                    successes: 1
                    interval: 2
                unhealthy:
                    http_statuses:
                    - 500
                    - 502
                    - 503
                    - 504
                    http_failures: 2
                    interval: 1
            passive:
                healthy:
                    http_statuses:
                    - 200
                    - 206
                    - 301
                    - 302
                    - 304
                    successes: 3
                unhealthy:
                    http_statuses:
                    - 499
                    - 500
                    - 503
                    - 502
                    - 504
                    tcp_failures: 3
                    http_failures: 3

routes:
    -
        uri: /*
        upstream_id: 1

#END
```

I start to try it once I see this log:
```
2021/08/11 12:05:19 [warn] 10803#10803: *1438 [lua] healthcheck.lua:1107: log(): [healthcheck] (upstream#/upstreams/1) unhealthy HTTP increment (2/2) for '(127.0.0.1:1980)', context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9080
```

And the result...
```
 ￥ time for i in $(seq 15); do curl 127.0.0.1:9080;done
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
 ￥ time for i in $(seq 15); do curl 127.0.0.1:9080;sleep 1;done
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
<p>hello, world</p>
```
