### ISSUE TITLE
Integration of eureka as discovery registry fail

### ISSUE THREAD

**Issue by 123fuxiaohui** [apache/apisix#4904]
### Issue description

apisix配置如下:

**conf/config.yaml**

```
apisix:
  discovery: eureka
  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin



eureka:
  host: 'http://127.0.0.1:8761'
  prefix: "/eureka/"
  fetch_interval: 30 # 从 eureka 中拉取数据的时间间隔，默认30秒
  weight: 100 # default weight for node
  timeout:
    connect: 2000 # 连接 eureka 的超时时间，默认2000ms
    send: 2000 # 向 eureka 发送数据的超时时间，默认2000ms
    read: 5000 # 从 eureka 读数据的超时时间，默认5000ms
```

**upstream 配置如下**

```
 {
                "modifiedIndex": 293,
                "value": {
                    "id": "369827360922403711",
                    "type": "roundrobin",
                    "create_time": 1629963884,
                    "update_time": 1629963884,
                    "service_name": "BJHL-CONSUMER-DEMO",
                    "name": "apisix-demo",
                    "discovery_type": "eureka"
                },
                "key": "/apisix/upstreams/369827360922403711",
                "createdIndex": 293
            }
```

route 配置如下
```
 {
                "modifiedIndex": 293,
                "value": {
                    "id": "369827360922403711",
                    "type": "roundrobin",
                    "create_time": 1629963884,
                    "update_time": 1629963884,
                    "service_name": "BJHL-CONSUMER-DEMO",
                    "name": "apisix-demo",
                    "discovery_type": "eureka"
                },
                "key": "/apisix/upstreams/369827360922403711",
                "createdIndex": 293
            }
```

访问的时候报错:

2021/08/26 16:02:49 [error] 10324#6650627: *1336 [lua] init.lua:485: http_access_phase(): failed to set upstream: _**discovery eureka is uninitialized**_, client: ::1, server: _, request: "GET /fxh-test/hello HTTP/1.1", host: "localhost:9080"

1,如果想集成eureka注册中心需要怎么配置呢
2,apisix-dashboard 配置upstream的类型为service_name的话，只能通过数据视图吗

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):
