### ISSUE TITLE
admin api request unauthorized(4107) 

### ISSUE THREAD

**Issue by ztgoto** [apache/apisix#5005]
### Issue description

```
#curl -XPUT -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' 'http://127.0.0.1:8999/apisix/admin/routes/1' -d '{
    "uri": "/baseauth/*",
    "upstream": {
        "service_name": "baseauth",
        "type": "roundrobin",
        "discovery_type": "nacos",
        "discovery_args": {
          "namespace_id": "3072804a-e201-4867-a10a-a5fbf2eba3c7",
          "group_name": "DEFAULT"
        }
    }
}'
{"code":4107,"message":"request unauthorized","data":null,"request_id":""}
```

config.yaml
```
apisix:
  allow_admin:
    - 0.0.0.0/0
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  
      role: admin
```

### Environment

- apisix version (cmd: `apisix version`):  2.8
- OS (cmd: `uname -a`):  `Linux 119 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): `nginx version: openresty/1.19.3.2`
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):
