### ISSUE TITLE
apisix etcd tls ca error

### ISSUE THREAD

**Issue by eno16777736** [apache/apisix#5448]
### Issue description

 使用自建etcd集群并开启auth认证和TLS之后，对接apisix时产生如下报错：
1.当我设置：
```
 tls:
    # To enable etcd client certificate you need to build APISIX-Openresty, see
    # http://apisix.apache.org/docs/apisix/how-to-build#6-build-openresty-for-apisix
    cert: /****/server.pem          # path of certificate used by the etcd client
    key: /****/server-key.pem           # path of key used by the etcd client
    verify: false  
```
apisix server端会产生大量报错：
```
2021/11/08 11:30:41 [error] 52#52: *86882 [lua] config_etcd.lua:563: no healthy etcd endpoint available, next retry after 32s, context: ngx.timer
2021/11/08 11:30:41 [error] 43#43: *86886 [lua] config_etcd.lua:563: no healthy etcd endpoint available, next retry after 32s, context: ngx.timer
```
2. 当我设置：verify: true时：apisix server启动失败，报错信息：certificate verify failed!
### Environment

- apisix version (cmd: `apisix version`): 2.10.0
- OS (cmd: `uname -a`): 
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):
