### ISSUE TITLE
request help: etcd tls connect handshake failed

### ISSUE THREAD

**Issue by deepzz0** [apache/apisix#5650]
### Issue description

```
2021/11/30 10:19:20 [warn] 45#45: *75201 [lua] v3.lua:631: request_chunk(): https://172.19.125.95:2379: handshake failed. Retrying, context: ngx.timer
2021/11/30 10:19:20 [error] 48#48: *75191 SSL_do_handshake() failed (SSL: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:SSL alert number 42), context: ngx.timer
```

```
etcd:
  host:                                 # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "https://172.19.65.126:2379"             # multiple etcd address
    - "https://172.19.178.136:2379"             # multiple etcd address
    - "https://172.19.125.105:2379"             # multiple etcd address
  prefix: "/apisix"     # apisix configurations prefix
  timeout: 30   # 30 seconds
  tls:
    cert: "/etcd-ssl/tls.crt"
    key: "/etcd-ssl/tls.key"
    verify: true
```

![image](https://user-images.githubusercontent.com/10971608/144029909-4b6de3cc-6a35-4ce0-8faf-5fdf5259a334.png)

Above is my configuration, I can confirm that the certificate is ok. I saw the previous issue said openResty does not support mTLS?

### Environment

- apisix version (cmd: `apisix version`): 2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by deepzz0** [comment]
Upgrading to Apisix version 2.11.0 has been resolved, but but a new error appeared:
```
11/30 11:16:28 [warn] 49#49: *22332 [lua] v3.lua:151: _request_uri(): https://172.19.65.156:2379: certificate host mismatch. Retrying, context: ngx.timer
2021/11/30 11:16:28 [warn] 49#49: *22332 [lua] v3.lua:151: _request_uri(): https://172.19.65.156:2379: certificate host mismatch. Retrying, context: ngx.timer
2021/11/30 11:16:28 [warn] 49#49: *22332 [lua] health_check.lua:90: report_failure(): update endpoint: https://172.19.65.156:2379 to unhealthy, context: ngx.timer
```

My config:
```
etcd:
  host:                                 # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "https://172.19.65.156:2379"             # multiple etcd address
    - "https://172.19.178.146:2379"             # multiple etcd address
    - "https://172.19.125.95:2379"             # multiple etcd address
  prefix: "/apisix"     # apisix configurations prefix
  timeout: 30   # 30 seconds
  tls:
    cert: "/etcd-ssl/tls.crt"
    key: "/etcd-ssl/tls.key"
    verify: true
```

my etcd cert:
```
09v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                94:03:8D:57:B1:80:16:B1:24:F1:FB:54:84:48:D9:85:3D:50:A5:1A
            X509v3 Authority Key Identifier: 
                keyid:D8:91:86:C9:95:9D:40:22:31:17:18:30:8C:0E:90:2A:AD:07:84:31

            X509v3 Subject Alternative Name: 
                IP Address:172.19.65.156, IP Address:172.19.125.95, IP Address:172.19.178.146, IP Address:127.0.0.1
```

what's wrong?
