### ISSUE TITLE
bug: java plugin error permission denied

### ISSUE THREAD

**Issue by sunyu-2020** [apache/apisix#5814]
### Issue description

Use java to develop extension plug-ins,se docker as a container,when the network is abnormal or the container restarts,the sock file in the container reports an error:permission denied

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

Use java to develop extension plug-ins,se docker as a container,when the network is abnormal or the container restarts,the sock file in the container reports an error:permission denied

### Actual result

The container restarts or the network is abnormal and no longer reports an error permission problem

### Error log

2021/12/13 09:21:40 [error] 49#49: *1748952 [lua] init.lua:689: phase_func(): failed to connect to the unix socket unix:/usr/local/apisix/conf/apisix-46.sock: permission denied,

**Comment by dyrnq** [comment]
open  user  configuration, such as `root` or other user with permission

```yaml
apisix:
  nginx_config:                   # config for render the template to generate nginx.conf
    user: root                    # specifies the execution user of the worker process.
                                  # the "user" directive makes sense only if the master process runs with super-user privileges.
                                  # if you're not root user,the default is current user.
```
