### ISSUE TITLE
bug: problems caused by stream_proxy (tcp proxy)

### ISSUE THREAD

**Issue by IT-coach-666** [apache/apisix#6034]
I use apisix to encapsulate the openstack’s API to achieve high availability and rate limiting.

# Problem description
My apisix configuration file (``config.yaml``) shows below (only shows the problem related part):
![0-apisix_config](https://user-images.githubusercontent.com/19731222/148711666-68f74f3b-86e6-40a8-9f9c-7f0b0a63478f.jpg)

I use the ``stream_proxy`` (tcp proxy) to listen ``vip`` (provided by ``keepalived``) and 11211, 3306 ports (related to ``memcached`` and ``mysql`` services), and then I will create ``upstream`` and ``route`` related to memcached and mysql services to achive High Availability (shown below).

Notice: I observed that, for ``msyql`` and ``memcache`` services, ``stream_proxy`` (``tcp proxy``) must be used, otherwise (if still use the ``http proxy``), ``mysql`` and ``memcache`` services wouldn’t work out (commands below couldn’t connect correctly).  
`telnet  <vip>  11211`
`mysql -ukeystone -pKeyStone_pwd -h<vip>`

For simplicity, related ``upstreams`` has only one node:
Mysql’s ``upstream`` shows blow:
![1-mysql-upstream](https://user-images.githubusercontent.com/19731222/148712010-81172869-35dc-46f8-8406-63487c74b541.jpg)

Memcached’s ``upstream`` shows below:
![2-memcache-upstream](https://user-images.githubusercontent.com/19731222/148712025-b70d1e2c-17c0-41dd-8f27-5e6ce7b066f0.jpg)

Mysql’s ``stream_route`` (experiment shows that it’s also valid for ordinary route, but will have the same problem) shows below (matched by 3306 port and forward the service to specific node):
![3-mysql-stream-route](https://user-images.githubusercontent.com/19731222/148712038-b9dfea6b-18d2-4012-8954-b140e1f83a99.jpg)

Memcache’s ``stream_route`` :
![4-memcached-stream-route](https://user-images.githubusercontent.com/19731222/148712051-7daf8441-a77b-483a-9b5d-03430277088e.jpg)

Then we test the ``mysql`` and ``memcache`` services, execute the command below (it shows correctly):
`telnet  <vip>  11211`
`mysql -ukeystone -pKeyStone_pwd -h<vip>`
![5-telnet-11211](https://user-images.githubusercontent.com/19731222/148712073-3c0b89ea-e4c4-4061-bcfc-eb7a0cd0e7e8.jpg)
![6-mysql-login](https://user-images.githubusercontent.com/19731222/148712078-508f834d-0509-4062-9842-19fed3c6df03.jpg)

### 1) Problems caused by ``nova-api`` (``memcached`` related)
Configuration related to ``memcached`` in ``nova.conf`` (if use the ``vip``, there are some problems in ``nova-api.log``,  if use specific ip, no ERROR will occur):
![7-nova-api-config](https://user-images.githubusercontent.com/19731222/148712098-1c58cfbb-0053-420d-906d-0d4baafbf2b8.jpg)
![8-nova-api-log-1](https://user-images.githubusercontent.com/19731222/148712105-ebee2b4b-be93-492a-b511-7e48062734a0.png)
![9-nova-api-log-2](https://user-images.githubusercontent.com/19731222/148712106-5f11e2f4-6490-4c92-aad7-f5ae92b40520.png)

### 2) Problems caused by ``masakari`` (``mysql`` related)
I alse use the ``vip`` to connect mysql in masakari configuration file (if use real ip, no ERROR will occur):
![10-mysql-error-1](https://user-images.githubusercontent.com/19731222/148712116-cf2935f0-a23d-43b0-9488-1b7163fdad65.png)
![11-mysql-error-2](https://user-images.githubusercontent.com/19731222/148712119-752aebb4-5d85-4c63-b729-f02c50efa94b.png)

### Summary
Because I only set one node in upstream, and evidence shows that apisix is functioning correctly, but it still cause some minor problem, which seems related to stream_proxy (tcp proxy), and belows are my question about the apisix’s stream_proxy:

1. Does the ``stream_proxy`` (tcp proxy) is a short connection? And if so, it will interrupt in the client side, which will cause the server’s side to trigger some error log (refer to: https://www.jb51.net/article/57602.htm).

2. Is there any alternative solution to connect ``mysql`` and ``memcached`` with apisix?

If I use the haproxy to achieve High Availability, problems above will not occur (but haproxy doesn’t have rate limiting functionality).

**Comment by JiaYueHuang** [comment]
I use apisix to encapsulate the openstack’s API to achieve high availability and rate limiting.

1.Problem description
My apisix configuration file (config.yaml) shows below (only shows the problem related part):
![apisix_config](https://user-images.githubusercontent.com/19731222/148710546-d957badd-f561-4b6a-8179-4c78df4dcd6e.png)
I use the stream_proxy (tcp proxy) to listen ``vip`` (provided by keepalived) and 11211, 3306 ports (related to memcached and mysql services), and then I will create ``upstream`` and ``route`` related to memcached and mysql services to achive High Availability (shown below).

Notice: I observed that, for msyql and memcache services, stream_proxy (tcp proxy) must be used, otherwise (if still use the http proxy), mysql and memcache services wouldn’t work out (commands below couldn’t connect correctly).  
`telnet  <vip>  11211`
`mysql -ukeystone -pKeyStone_pwd -h<vip>`

**Comment by tzssangglass** [comment]
> 1. Does the `stream_proxy` (tcp proxy) is a short connection?

AFAIK, not short connection by default. pls show the stream proxy configuration in `nginx.conf`.

This error, from your description, APISIX disconnected connection? cc @spacewander the stream proxy has timeout configuration in the upstream, I think it has something to do with the timeout?

**Comment by spacewander** [comment]
Look like you have set the upstream's timeout to 30s, which is relatively short for TCP connection. Does it cause the problem?

**Comment by JiaYueHuang** [comment]
> > 1. Does the `stream_proxy` (tcp proxy) is a short connection?
> 
> AFAIK, not short connection by default. pls show the stream proxy configuration in `nginx.conf`.
> 
> This error, from your description, APISIX disconnected connection? cc @spacewander the stream proxy has timeout configuration in the upstream, I think it has something to do with the timeout?

configuration sample:
```
apisix:
  node_listen:

    - ip: 176.76.8.246
      port: 9080
    
    - ip: 176.76.8.246
      port: 35357
    - ip: 176.76.8.246
      port: 5000
    - ip: 176.76.8.246
      port: 9292
    - ip: 176.76.8.246
      port: 9191
    - ip: 176.76.8.246
      port: 8776
    - ip: 176.76.8.246
      port: 8774
    - ip: 176.76.8.246
      port: 9696
    - ip: 176.76.8.246
      port: 8786
    - ip: 176.76.8.246
      port: 8778
    - ip: 176.76.8.246
      port: 8777
    - ip: 176.76.8.246
      port: 6666
    - ip: 176.76.8.246
      port: 8780
    - ip: 176.76.8.246
      port: 8779
    
  enable_tcp_pp: true
  enable_tcp_pp_to_upstream: true

  stream_proxy:
    only: false
    tcp:
      - "176.76.8.246:3306"
      - "176.76.8.246:11211"

  allow_admin:
    #- 127.0.0.0/24
    #- 0.0.0.0/24
    - 0.0.0.0/0
    


  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  
      role: admin

  router:
    http: radixtree_uri_with_parameter

etcd:
  host:
    - "http://176.76.8.165:2379"
    - "http://176.76.8.181:2379"
```
