### ISSUE TITLE
bug: plugin kafka-logger configuration error

### ISSUE THREAD

**Issue by devops-utils-tools** [apache/apisix#6283]
### Issue description

2022-02-10T15:14:39+08:00	error	apisix/route.go:161	failed to create route: unexpected status code 400; error message: {"error_msg":"failed to check the configuration of plugin kafka-logger err: property \"broker_list\" validation failed: wrong type: expected object, got string"}

2022-02-10T15:14:39+08:00	warn	ingress/apisix_route.go:292	sync ApisixRoute failed, will retry	{"object": {"Type":1,"Object":{"Key":"default/method-route","OldObject":null,"GroupVersion":"apisix.apache.org/v2beta1"},"Tombstone":null}, "error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"failed to check the configuration of plugin kafka-logger err: property \\\"broker_list\\\" validation failed: wrong type: expected object, got string\"}\n\n\n"}
W0210 15:14:39.263811       1 warnings.go:70] apisix.apache.org/v2beta1 ApisixRoute is deprecated; use apisix.apache.org/v2beta2 ApisixRoute

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce
```
source yaml


apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: method-route
spec:
  http:
  - name: method
    backends:
    - serviceName: kubernetes
      servicePort: 443
    match:
      methods:
      - GET
      paths:
      - /111
    plugins:
      - name: request-id
        enable: true
        config:
          include_in_response: true
          header_name: "X-Request-Id"

      # - name: skywalking-logger
      #   enable: true
      #   config:
      #     sample_ratio: 1
      #     service_name: "skywalking-apisix-method"
      #     service_instance_name: "skywalking-apisix-method"
      #     endpoint_addr: "http://127.0.0.1:12800"
      #     report_interval: 30
      #     timeout: 15
      #     batch_max_size: 3000
      #     name: skywalking-logger-method

      - name: cors
        enable: true

      - name: proxy-rewrite
        enable: true
        config:
          regex_uri:
          - ^/case/(.*)
          - /newcase/

      - name: kafka-logger
        enable: true
        config:
          broker_list: "{192.168.25.111:9092}"

         #  broker_list:
         #  -  192.168.25.111:9092

          kafka_topic: apisix_method
          name: kafka-logger-method
          key: kafka-logger-method
          producer_type: async
          batch_max_size: 3000
          inactive_timeout: 30
          buffer_duration: 300
          retry_delay: 5
```

### Actual result
```
{"object": {"Type":1,"Object":{"Key":"default/method-route","OldObject":null,"GroupVersion":"apisix.apache.org/v2beta1"},"Tombstone":null}, "error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"failed to check the configuration of plugin kafka-logger err: property \\\"broker_list\\\" validation failed: wrong type: expected object, got string\"}\n\n\n"}
```
### Error log
```
2022-02-10T15:16:05+08:00	warn	ingress/apisix_route.go:292	sync ApisixRoute failed, will retry	{"object": {"Type":1,"Object":{"Key":"default/method-route","OldObject":null,"GroupVersion":"apisix.apache.org/v2beta1"},"Tombstone":null}, "error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"failed to check the configuration of plugin kafka-logger err: property \\\"broker_list\\\" validation failed: wrong type: expected object, got string\"}\n\n\n"}
W0210 15:16:05.277090       1 warnings.go:70] apisix.apache.org/v2beta1 ApisixRoute is deprecated; use apisix.apache.org/v2beta2 ApisixRoute
[GIN] 2022/02/10 - 15:16:07 | 200 |      56.022µs |   192.168.25.63 | GET      "/healthz"
[GIN] 2022/02/10 - 15:16:08 | 200 |      78.626µs |   192.168.25.63 | GET      "/healthz"
2022-02-10T15:16:08+08:00	error	apisix/route.go:161	failed to create route: unexpected status code 400; error message: {"error_msg":"failed to check the configuration of plugin kafka-logger err: property \"broker_list\" validation failed: wrong type: expected object, got string"}

2022-02-10T15:16:08+08:00	warn	ingress/apisix_route.go:292	sync ApisixRoute failed, will retry	{"object": {"Type":1,"Object":{"Key":"default/method-route","OldObject":null,"GroupVersion":"apisix.apache.org/v2beta1"},"Tombstone":null}, "error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"failed to check the configuration of plugin kafka-logger err: property \\\"broker_list\\\" validation failed: wrong type: expected object, got string\"}\n\n\n"}
W0210 15:16:08.822787       1 warnings.go:70] apisix.apache.org/v2beta1 ApisixRoute is deprecated; use apisix.apache.org/v2beta2 ApisixRoute
[GIN] 2022/02/10 - 15:16:17 | 200 |     133.224µs |   192.168.25.63 | GET      "/healthz"
[GIN] 2022/02/10 - 15:16:18 | 200 |      66.645µs |   192.168.25.63 | GET      "/healthz"
[GIN] 2022/02/10 - 15:16:27 | 200 |       60.59µs |   192.168.25.63 | GET      "/healthz"
[GIN] 2022/02/10 - 15:16:28 | 200 |      57.763µs |   192.168.25.63 | GET      "/healthz"
```

**Comment by devops-utils-tools** [comment]
`

apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: method-route
spec:
  http:
  - name: method
    backends:
    - serviceName: kubernetes
      servicePort: 443
    match:
      methods:
      - GET
      paths:
      - /111
    plugins:
      - name: request-id
        enable: true
        config:
          include_in_response: true
          header_name: "X-Request-Id"

      # - name: skywalking-logger
      #   enable: true
      #   config:
      #     sample_ratio: 1
      #     service_name: "skywalking-apisix-method"
      #     service_instance_name: "skywalking-apisix-method"
      #     endpoint_addr: "http://127.0.0.1:12800"
      #     report_interval: 30
      #     timeout: 15
      #     batch_max_size: 3000
      #     name: skywalking-logger-method

      - name: cors
        enable: true

      - name: proxy-rewrite
        enable: true
        config:
          regex_uri:
          - ^/case/(.*)
          - /newcase/$1

      - name: kafka-logger
        enable: true
        config:
          broker_list: "{192.168.25.111:9092}"
          
          # broker_list: 
          # - 192.168.25.111:9092

          kafka_topic: apisix_method
          name: kafka-logger-method
          key: kafka-logger-method
          producer_type: async
          batch_max_size: 3000
          inactive_timeout: 30
          buffer_duration: 300
          retry_delay: 5
          max_retry_count: 3



`

**Comment by devops-utils-tools** [comment]
`
apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: method-route
spec:
  http:
  - name: method
    backends:
    - serviceName: kubernetes
      servicePort: 443
    match:
      methods:
      - GET
      paths:
      - /111
    plugins:
      - name: request-id
        enable: true
        config:
          include_in_response: true
          header_name: "X-Request-Id"

      # - name: skywalking-logger
      #   enable: true
      #   config:
      #     sample_ratio: 1
      #     service_name: "skywalking-apisix-method"
      #     service_instance_name: "skywalking-apisix-method"
      #     endpoint_addr: "http://127.0.0.1:12800"
      #     report_interval: 30
      #     timeout: 15
      #     batch_max_size: 3000
      #     name: skywalking-logger-method

      - name: cors
        enable: true

      - name: proxy-rewrite
        enable: true
        config:
          regex_uri:
          - ^/case/(.*)
          - /newcase/$1

      - name: kafka-logger
        enable: true
        config:
          broker_list: "{192.168.25.111:9092}"
          
          # broker_list: 
          # - 192.168.25.111:9092

          kafka_topic: apisix_method
          name: kafka-logger-method
          key: kafka-logger-method
          producer_type: async
          batch_max_size: 3000
          inactive_timeout: 30
          buffer_duration: 300
          retry_delay: 5
          max_retry_count: 3

`

**Comment by devops-utils-tools** [comment]
```

apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: method-route
spec:
  http:
  - name: method
    backends:
    - serviceName: kubernetes
      servicePort: 443
    match:
      methods:
      - GET
      paths:
      - /111
    plugins:
      - name: request-id
        enable: true
        config:
          include_in_response: true
          header_name: "X-Request-Id"

      # - name: skywalking-logger
      #   enable: true
      #   config:
      #     sample_ratio: 1
      #     service_name: "skywalking-apisix-method"
      #     service_instance_name: "skywalking-apisix-method"
      #     endpoint_addr: "http://127.0.0.1:12800"
      #     report_interval: 30
      #     timeout: 15
      #     batch_max_size: 3000
      #     name: skywalking-logger-method

      - name: cors
        enable: true

      - name: proxy-rewrite
        enable: true
        config:
          regex_uri:
          - ^/case/(.*)
          - /newcase/$1

      - name: kafka-logger
        enable: true
        config:
          broker_list: "{192.168.25.111:9092}"
          
          # broker_list: 
          # - 192.168.25.111:9092

          kafka_topic: apisix_method
          name: kafka-logger-method
          key: kafka-logger-method
          producer_type: async
          batch_max_size: 3000
          inactive_timeout: 30
          buffer_duration: 300
          retry_delay: 5
          max_retry_count: 3


```
