### ISSUE TITLE
request help: errors on load_plugin 

### ISSUE THREAD

**Issue by WeiWANG0118** [apache/apisix#6516]
### Issue description

Hello team, I have a problem with **load_plugin**.  It will crash the service and give me a cross-origin problem. PS: I already enable cors plugin. So I’m guessing there is a problem. And here is the error.logs. 

```
no field package.preload['apisix.plugins.public-api']
        no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/public-api.lua'
        no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/public-api/init.lua'
        no file '/usr/local/apisix/apisix/plugins/public-api.lua'
        no file '/usr/local/apisix/apisix/plugins/public-api/init.lua'
        no file '/usr/local/openresty/site/lualib/apisix/plugins/public-api.ljbc'
        no file '/usr/local/openresty/site/lualib/apisix/plugins/public-api/init.ljbc'
        no file '/usr/local/openresty/lualib/apisix/plugins/public-api.ljbc'
        no file '/usr/local/openresty/lualib/apisix/plugins/public-api/init.ljbc'
        no file '/usr/local/openresty/site/lualib/apisix/plugins/public-api.lua'
        no file '/usr/local/openresty/site/lualib/apisix/plugins/public-api/init.lua'
        no file '/usr/local/openresty/lualib/apisix/plugins/public-api.lua'
        no file '/usr/local/openresty/lualib/apisix/plugins/public-api/init.lua'
        no file './apisix/plugins/public-api.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/public-api.lua'
        no file '/usr/local/share/lua/5.1/apisix/plugins/public-api.lua'
        no file '/usr/local/share/lua/5.1/apisix/plugins/public-api/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/public-api.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/public-api/init.lua'
        no file './apisix/plugins/public-api.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/public-api.lua'
        no file '/usr/local/share/lua/5.1/apisix/plugins/public-api.lua'
        no file '/usr/local/share/lua/5.1/apisix/plugins/public-api/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/public-api.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/public-api/init.lua'
        no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix/plugins/public-api.so'
        no file '/usr/local/apisix//deps/lib/lua/5.1/apisix/plugins/public-api.so'
        no file '/usr/local/openresty/site/lualib/apisix/plugins/public-api.so'
        no file '/usr/local/openresty/lualib/apisix/plugins/public-api.so'
        no file './apisix/plugins/public-api.so'
        no file '/usr/local/lib/lua/5.1/apisix/plugins/public-api.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/public-api.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './apisix/plugins/public-api.so'
        no file '/usr/local/lib/lua/5.1/apisix/plugins/public-api.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/public-api.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix.so'
        no file '/usr/local/apisix//deps/lib/lua/5.1/apisix.so'
        no file '/usr/local/openresty/site/lualib/apisix.so'
        no file '/usr/local/openresty/lualib/apisix.so'
        no file './apisix.so'
        no file '/usr/local/lib/lua/5.1/apisix.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './apisix.so'
        no file '/usr/local/lib/lua/5.1/apisix.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
        no file '/usr/local/lib/lua/5.1/loadall.so', context: init_worker_by_lua*
```

config.yaml - apisix
```
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  allow_admin:
    - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

# TODO: have to change this
  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin                 # admin: manage all configuration data
                                  # viewer: only can view configuration data
    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a2
      role: viewer

  
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://ip-adresse:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
```

### Environment

- apisix version (cmd: `apisix version`): 2.12.1
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.415
- apisix-dashboard version, if have:2.10.1
