### ISSUE TITLE
bug: The function of ip-restriction is contrary 

### ISSUE THREAD

**Issue by kingmouse-yx** [apache/apisix#6537]
### Issue description

when I test the white list, the routing configuration information is as follows 
```json
{
  "uri": "/mock/521171/aa",
  "name": "API-test",
  "methods": [
    "POST"
  ],
  "plugins": {
    "ip-restriction": {
      "disable": false,
      "whitelist": [
        "127.0.0.1"
      ]
    }
  },
  "upstream_id": "396931816625275591",
  "labels": {
    "demo": "demo1"
  },
  "status": 1
}
```
At this point, I hope 127.0.0.1 can pass. But the actual return result is as follows.
```json
{"message":"Your IP address is not allowed"}
```
when I test the black list, the routing configuration information is as follows 
```json
{
  "uri": "/mock/521171/aa",
  "name": "API-test",
  "methods": [
    "POST"
  ],
  "plugins": {
    "ip-restriction": {
      "blacklist": [
        "127.0.0.1"
      ],
      "disable": false
    }
  },
  "upstream_id": "396931816625275591",
  "labels": {
    "demo": "demo1"
  },
  "status": 1
}
```
At this point, I don't want 127.0.0.1 to pass. But the actual return result is as follows.
```json
{
    "tag": {
        "certStatus": "1",
        "certTp": "01"
    },
    "data": {
        "a_name": "xxx",
        "a_age": "29"
    },
    "certId": "341126197709218366",
    "userid": "xxxxxxxxxxxx01",
    "realname": "test",
    "caseId": "11111111999999990000009909"
}
```
This is completely contrary to my expectation

### Environment

- apisix version (cmd: `apisix version`): 2.12.1
- OS (cmd: `uname -a`): Linux node-15 3.10.0-862.51.1.el7.x86_64 #1 SMP Sun Sep 27 11:41:03 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
- apisix-dashboard version, if have: 2.10.1
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1.add upstream
2.add route, setting ip-restriction with whitelist or blacklist
3.access with apisix
4.Or use following cmd and access the service

### Actual result

1. The whitelist cannot be passed
2. The blacklist can be passed

### Error log

2022/03/08 02:10:02 [warn] 43#43: *160645 [lua] plugin.lua:658: run_plugin(): ip-restriction exits with http status code 403, client: 172.18.0.1, server: _, request: "POST /mock/521171/aa HTTP/1.1", host: "127.0.0.1:9080"

### Expected result

1. The blacklist cannot be passed
2. The whitelist can be passed

**Comment by liangliang4ward** [comment]
Do you access Apisix directly, or do you add a layer of proxies, such as Nginx or SLB

ref: https://github.com/apache/apisix/issues/4712

**Comment by kingmouse-yx** [comment]
> 是直接访问Apisix，还是加一层代理，比如Nginx或者SLB
> 
> 参考：#4712

**Comment by kingmouse-yx** [comment]
> 是直接访问Apisix，还是加一层代理，比如Nginx或者SLB
> 
> 参考：#4712

I access Apisix directly.

**Comment by liangliang4ward** [comment]
> > 是直接访问Apisix，还是加一层代理，比如Nginx或者SLB
> > 参考：#4712
> 
> I access Apisix directly.

How did you verify that? curl?

**Comment by kingmouse-yx** [comment]
> 
yes

**Comment by kingmouse-yx** [comment]
> > > 是直接访问Apisix，还是加代理，比如Nginx或者SLB
> > > 参考：#4712
> > 
> > 
> > 我直接访问 APIsix。
> 
> 你是如何验证的？卷曲？

yes

**Comment by liangliang4ward** [comment]
> > > > 是直接访问Apisix，还是加代理，比如Nginx或者SLB
> > > > 参考：#4712
> > > 
> > > 
> > > 我直接访问 APIsix。
> > 
> > 
> > 你是如何验证的？卷曲？
> 
> yes

pls show you cmd

**Comment by kingmouse-yx** [comment]
> > > > 是直接访问Apisix，还是加代理，比如Nginx或者SLB
> > > > 参考：#4712
> > > 
> > > 
> > > 我直接访问 API6。
> > 
> > 
> > 你是如何验证的？卷曲？
> 
> 是的

curl --location --request POST '127.0.0.1:9080/mock/521171/aa' --data-raw ''

**Comment by kingmouse-yx** [comment]
> > > > > Do you access Apisix directly, or do you add a layer of proxies, such as Nginx or SLB
> > > > > ref：#4712
> > > > 
> > > > 
> > > > I access Apisix directly.
> > > 
> > > 
> > > How did you verify that? curl?
> > 
> > 
> > yes
> 
> pls show you cmd

curl --location --request POST '127.0.0.1:9080/mock/521171/aa' --data-raw ''

**Comment by liangliang4ward** [comment]
> > > > > > Do you access Apisix directly, or do you add a layer of proxies, such as Nginx or SLB
> > > > > > ref：#4712
> > > > > 
> > > > > 
> > > > > I access Apisix directly.
> > > > 
> > > > 
> > > > How did you verify that? curl?
> > > 
> > > 
> > > yes
> > 
> > 
> > pls show you cmd
> 
> curl --location --request POST '127.0.0.1:9080/mock/521171/aa' --data-raw ''

```yaml
{
  "uri": "/mock/521171/aa",
  "name": "test1111",
  "methods": [
    "POST"
  ],
  "plugins": {
    "ip-restriction": {
      "blacklist": [
        "127.0.0.1"
      ],
      "disable": false
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "127.0.0.1",
        "port": 80,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```

```shell
 curl --location --request POST '127.0.0.1:9080/mock/521171/aa' --data ''
```
```result
{"message":"Your IP address is not allowed"}
```
