### ISSUE TITLE
help request: Is it possible to add another listen port without breaking the existing  long-running connections？

### ISSUE THREAD

**Issue by liuning89757** [apache/apisix#6704]
### Description

I would like to use Apisix as a loadbalancer, but find out Admin API not provide a function to add a listen port dynamic, so i have to modify Apisix config file like: 
```
apisix:
  stream_proxy: # TCP/UDP proxy
    tcp: # add another TCP proxy address list
      - 9100
```
It works out but after execute  `apisix reload`, the long-runing connection will be killed because `worker_shutdown_timeout 240s;` is set in nginx.conf. So  i suppose to know is there another approach to dynamic add listening port without effect already existing connections？Or is  it technical possible to dynamic add port just like add a route using Admin API？

### Environment

- APISIX version (run `apisix version`): 2.12.1
- Operating system (run `uname -a`): centos 7.6
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.9.1
