### ISSUE TITLE
bug: cannot use file-logger to log to stdout

### ISSUE THREAD

**Issue by Alasiac** [apache/apisix#6797]
### Current Behavior

When using the file-logger plugin, it is possible to send the logging to stdout by defining /dev/stdout. This in order to use the docker output and relais this in kubernetes to a ELK stack. Though an error is thrown indicating a permission denied for the current user.

### Expected Behavior

Be able to use /dev/stdout as a destination with the file-logger plugin.

### Error Logs

failed to open file: /dev/stdout, error info: /dev/stdout: Permission denied while logging request

### Steps to Reproduce

Run apisix docker with apisix.yaml:
```
routes:
  - uri: /*
    upstream_id: 1
    plugins:
      file-logger:
        path: /dev/stdout

upstreams:
  - id: 1
    nodes:
      "host.docker.internal:3000": 1
    type: roundrobin

plugins:
  - name: file-logger
#END
```

### Environment

- APISIX Docker version: apache/apisix:2.13.0-alpine
- Host system: Macbook Pro Intel with docker desktop for mac
