### ISSUE TITLE
Etcd CPU linear rise with an empty three node apisix cluster.

### ISSUE THREAD

**Issue by ltt1987** [apache/apisix#6798]
### Current Behavior

I created an empty three node apisix cluster, there is no anything routers. The three apisix node connected one new etcd node.

And I already **disabled** `server-info` plugin. Other plugins are configured by default.

After about 2 weeks of idle running, I got the following  problem : Etcd server CPU linear rise .

<img width="1112" alt="WX20220406-134622@2x" src="https://user-images.githubusercontent.com/8955240/162104924-c67f9a38-3586-4529-b4dc-0d083e951ddc.png">

Until I stop the apisix service manually, etcd CPU is back to normal immediately.

### Steps to Reproduce

RUN with docker swarm.

etcd-compose.yaml
```
version: "3.8"

services:
  etcd:
    image: bitnami/etcd:3.5.2
    networks:
      - test_network
    volumes:
      - /etc/localtime:/etc/localtime
      - "etcd:/bitnami/etcd"
    environment:
      ETCD_ROOT_PASSWORD: xxxxxx
      ETCD_NAME: etcd
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==test-etcd-01"


volumes:
  etcd:

networks:
  test_network:
    external: true

```

apisix-compose.yaml
```
version: "3.8"

services:
  apisix:
    image: apache/apisix:2.12.1-alpine
    volumes:
      - /etc/localtime:/etc/localtime
      - /app/apisix/apisix_log:/usr/local/apisix/logs
      - /app/apisix/apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
    networks:
      - test_network
    environment:
      HOSTNAME: ${HOSTNAME}_apisix
    ports:
      - "9080:9080"
      - "9091:9091"
      - "9043:9443"
      - "9092:9092"
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

networks:
  test_network:
    external: true
```

### Environment

- APISIX version: 2.12.1
- Operating system: Linux test-apisix-001 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.2
