### ISSUE TITLE
request help: why the location in response header that returned by APISIX has the 9443 port?

### ISSUE THREAD

**Issue by shuoshadow** [apache/apisix#6954]
### Issue description
apisix前使用slb 443端口转发到apisix的9443端口
apisix 代理https请求后 携带了9443端口导致无法重定向
![image](https://user-images.githubusercontent.com/10016360/120430719-01fac380-c3aa-11eb-98a6-66440e9f51b7.png)

是因为header的原因吗？我配置了apisixroute的proxy-rewrite插件也不行
```yaml
    - name: proxy-rewrite
      enable: true
      config:
        headers:
          "Host": $host
```
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
