### ISSUE TITLE
bug: openid-connect plugin access_token_in_authorization_header does not work when combined with token attributes

### ISSUE THREAD

**Issue by amrellafy** [apache/apisix#7110]
### Current Behavior

Settings access_token_in_authorization_header will not work if other header token attributes is explicitly set to false.

```yaml
  openid-connect:
        access_token_in_authorization_header: true
        set_id_token_header: false
        set_userinfo_header: false
        set_access_token_header: false
```

The following yaml configuration will not add access token to the Authorization header as intended. 

### Expected Behavior

access_token_in_authorization_header should append the authorization header even if other other set_* attributes is explicitly set to false. 

### Steps to Reproduce

1. run apisix 2.14 on docker image in standalone mode. 
2. create  route with openid-connect and use the snippet mentioned.

### Environment

- APISIX version: 2.14
- Operating system: docker, centos image
