### ISSUE TITLE
bug: nginx.stream.access_log_format can not work.

### ISSUE THREAD

**Issue by imiskolee** [apache/apisix#7124]
### Current Behavior

current config.yaml

```yaml
apisix:
  admin_key:
    - name: admin
      key: ***********
      role: admin
  allow_admin:
    - 0.0.0.0/0
  router:
    http: "radixtree_uri_with_parameter"
  ssl:
    fallback_sni: "*******"
etcd:
  host:
    - "http://************:2379"
nginx_config:
  stream:
    enable_access_log: true
    access_log: /dev/stdout
    access_log_format: "{\"remote_addr\":\"$remote_addr\",\"time\":\"$time_local\",\"request_time\":\"$request_time\",\"host\": \"$host\",\"request\":\"$request\",\"status\":\"$status\",\"content_length\":\"$content_length\",\"body_bytes_sent\":\"$body_bytes_sent\",\"http_referer\":\"$http_referer\",\"http_user_agent\":\"$http_user_agent\",\"upstream_addr\":\"$upstream_addr\",\"response_time\":\"$upstream_response_time\",\"upstream_scheme\":\"$upstream_host$upstream_uri\",\"service_name\":\"$service_name\",\"router_name\":\"$route_name\",\"request_body\":\"$request_body\"}"
```
but the access log on /dev/stdout still :

```
100.125.67.146 - - [25/May/2022:03:45:50 +0000] ********* "GET /version HTTP/2.0" 200 101 0.004 "-" "curl/7.79.1" 10.247.178.85:80 200 0.001 "http://***********"
```

### Expected Behavior

i think the output format need to follow the config.yaml as a JSON 

### Steps to Reproduce

see Current Behavior

### Environment

docker image: 2.13.1-alpine
