### ISSUE TITLE
docs: add `API Gateway` keywords in English and Chinese docs

### ISSUE THREAD

**Issue by moonming** [apache/apisix#7218]
### Current State

only Apache APISIX, no API Gateway keyword.

### Desired State

see https://github.com/apache/apisix/pull/7217

**Comment by moonming** [comment]
@navendu-pottekkat what do you think? Is this good for SEO?

**Comment by navendu-pottekkat** [comment]
@moonming It might be a good idea. I have been adding keywords on the pages I have been re-writing. Currently, I follow this structure (for Plugins):

```yaml
---
title: plugin name
keywords:
  - APISIX
  - Plugin
  - Actual Plugin Name (Node status)
  - apisix-plugin-name
description: This document contains information about the Apache APISIX plugin-name Plugin.
---
```

Adding this front matter should give better SEO than what we have before. We did not have any metadata of the pages before—no description or keywords.

In SEO terms I'm not sure if adding a general keyword like "API Gateway" will help us or hinder us. Maybe @juzhiyuan has a better idea because he has been exploring SEO recently. If we decide to add this keyword, we can add a "good first label to this issue."

Our current status is shown below:

![Screenshot 2022-06-09 at 9 32 31 AM](https://user-images.githubusercontent.com/49474499/172761829-209401c9-59c4-496f-9cfa-8767c1921fb0.png)

As you can see, we are in a sweet spot.
