### ISSUE TITLE
help request: etcd "client-cert-auth" cannot be used with gRPC-gateway

### ISSUE THREAD

**Issue by ffch** [apache/apisix#7280]
### Description

I have a problem with starting apisix：

the conf.yaml:
```
etcd:
  host:
    - https://xxxx:4001
  prefix: /apisix
  tls:
    verify: true
    cert: conf/cert/etcd_client.pem
    key: conf/cert/etcd_client_key.pem
apisix:
  enable_control: true
  ssl:
    ssl_trusted_certificate: conf/cert/etcd_ca.pem
```
then use docker to start, error is :
```
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
etcd "client-cert-auth" cannot be used with gRPC-gateway, please configure the etcd username and password in configuration file
```

**the same configuration is ok on dashboard and apisix-seed。**

help me, thanks!

_the etcd is 3.4, use password and username is ok, but I need the way to use the certificate_

### Environment

FROM apache/apisix:latest

WORKDIR /usr/local/apisix
COPY apisix .
COPY conf .
COPY conf/config.yaml /usr/local/apisix/conf/config.yaml
COPY conf/cert/etcd_ca.pem /usr/local/apisix/conf/cert/etcd_ca.pem
COPY conf/cert/etcd_client.pem /usr/local/apisix/conf/cert/etcd_client.pem
COPY conf/cert/etcd_client_key.pem /usr/local/apisix/conf/cert/etcd_client_key.pem
