### ISSUE TITLE
help request: need a way to support multiple lua_ssl_trusted_certificate configuration

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#7424]
### Description

```
apisix:
    ssl:
          ssl_trusted_certificate: t/certs/apisix.crt
deployment:
    role: data_plane
    role_data_plane:
        config_provider: control_plane
        control_plane:
            host:
            - "https://admin.apisix.dev:22379"
            prefix: "/apisix"
            timeout: 30
            tls:
                verify: false
    certs:
        cert: t/certs/mtls_client.crt
        cert_key: t/certs/mtls_client.key
        trusted_ca_cert: t/certs/mtls_ca.crt
```
The configuration above will raise an error as we currently only support one `lua_ssl_trusted_certificate`. Need to find a way to solve this.

### Environment

- APISIX version (run `apisix version`): master
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
