### ISSUE TITLE
help request: Can't enable plugin authz-casdoor

### ISSUE THREAD

**Issue by airclear** [apache/apisix#7460]
### Description

Install with Helm , Chart version: 0.10.0

Helm values:

```yaml
gateway:
  type: NodePort
  tls:
    enabled: true

etcd:
  # install etcd(v3) by default, set false if do not want to install etcd(v3) together
  enabled: false
  host:
    - http://etcd.ingress-apisix.svc.cluster.local:2379  

ingress-controller:
  enabled: true
  config.apisix.serviceNamespace: ingress-apisix

plugins:
  - api-breaker
  - authz-keycloak
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  - echo
  - fault-injection
  - grpc-transcode
  - hmac-auth
  - http-logger
  - ip-restriction
  - ua-restriction
  - jwt-auth
  - kafka-logger
  - key-auth
  - limit-conn
  - limit-count
  - limit-req
  - node-status
  - openid-connect
  - authz-casbin
  - authz-casdoor
  - prometheus
  - proxy-cache
  - proxy-mirror
  - proxy-rewrite
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - serverless-post-function
  - serverless-pre-function
  - sls-logger
  - syslog
  - tcp-logger
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - traffic-split
  - gzip
  - real-ip
  - ext-plugin-pre-req
  - ext-plugin-post-req
stream_plugins:
  - mqtt-proxy
  - ip-restriction
  - limit-conn


```

Config the Route by curl:

```
curl "http://apisix.xxx.com:32380/apisix/admin/routes/3a8b12cf"  -H 'Authorization:-3Dkvk' -X PUT -d '
{
  "uri": "/anything/*",
  "name": "casdoor-httpbin",
  "methods": ["GET"],
  "host": "httpbin.xxx.com",
  "plugins": {
    "authz-casdoor": {
        "endpoint_addr":"http://10.200.180.82:7001",
        "callback_url":"http://apisix.xxxx.com:32380/anything/callback",
        "client_id":"xx",
        "client_secret":"xx"
    }
  },
  "upstream_id": "5ce57b8e",
  "status": 1
}'

```

response :

```
{"code":10000,"message":"schema validate failed: schema not found, path: plugins.authz-casdoor","data":null,"request_id":"48b8e334-f12a-4a41-98f9-e4275825aa92"}

```

### Environment

- APISIX version (run `apisix version`): apache/apisix:2.14.1-alpine
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:  apache/apisix-dashboard:2.13-alpine  (no used)
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
