### ISSUE TITLE
bug: use kubernetes dicovery start failed

### ISSUE THREAD

**Issue by myoss** [apache/apisix#7473]
### Current Behavior

apisix use kubernetes dicovery start failed

### Error Logs

 kubectl -n ingress-apisix logs -f apisix-bd9687cc7-68vvr

```
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
2022/07/15 17:25:24 [warn] 1#1: low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:287
nginx: [warn] low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:287
nginx: [error] init_by_lua error: /usr/local/openresty/lualib/ngx/process.lua:5: unsupported subsystem: stream
stack traceback:
        [C]: in function 'error'
        /usr/local/openresty/lualib/resty/core/base.lua:223: in function 'allows_subsystem'
        /usr/local/openresty/lualib/ngx/process.lua:5: in main chunk
        [C]: in function 'require'
        /usr/local/apisix/apisix/discovery/kubernetes/init.lua:27: in main chunk
        [C]: in function 'require'
        /usr/local/apisix/apisix/discovery/init.lua:28: in main chunk
        [C]: in function 'require'
        /usr/local/apisix/apisix/upstream.lua:19: in main chunk
        [C]: in function 'require'
        /usr/local/apisix/apisix/http/service.lua:18: in main chunk
        [C]: in function 'require'
        /usr/local/apisix/apisix/init.lua:34: in main chunk
        [C]: in function 'require'
        init_by_lua:3: in main chunk
```

### Steps to Reproduce

vi charts/apisix/values.yaml

```
discovery:
  enabled: true
  registry:
    kubernetes:
      service:
        # apiserver schema, options [http, https]
        schema: https #default https

        # apiserver host, options [ipv4, ipv6, domain, environment variable]
        host: ${KUBERNETES_SERVICE_HOST} #default ${KUBERNETES_SERVICE_HOST}

        # apiserver port, options [port number, environment variable]
        port: ${KUBERNETES_SERVICE_PORT}  #default ${KUBERNETES_SERVICE_PORT}

      client:
        # serviceaccount token or token_file
        token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      namespace_selector:
        # only save endpoints with namespace equal default
        equal: app
```

helm upgrade apisix charts/apisix  --namespace ingress-apisix

 kubectl -n ingress-apisix logs -f apisix-bd9687cc7-68vvr

### Environment

- APISIX version (run `apisix version`): use latest code [https://github.com/apache/apisix/commit/a04964e2a3ad1430152818ed3dbb8130438de877](https://github.com/apache/apisix/commit/a04964e2a3ad1430152818ed3dbb8130438de877), build docker images
- Operating system (run `uname -a`): `Linux iZbp18of4fhb66ti309tdmZ 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
