### ISSUE TITLE
help request: how to define public-api in ApisixRoute CRD

### ISSUE THREAD

**Issue by akalittle** [apache/apisix#7605]
### Description

Here below is my yaml file of  CRD `ApisixRoute`
I want to implement keyAuth
but some path will should be excluded to the keyAuth

But the config below didn't work.

```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: status-tracker
  namespace: launcher
spec:
  http:
    - name: status-tracker-rule
      match:
        hosts:
          - api.devus.dregon.cc
        paths:
          - /status-tracker*
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - ^/status-tracker/(.*)
              - /$1
        - name: public-api
          enable: true
          config:
            uri: /metrics
      backends:
        - serviceName: status-tracker
          servicePort: 8000
      authentication:
        enable: true
        type: keyAuth
        keyAuth:
          header: Authentication
```

### Environment

apache/apisix:2.15.0-alpine
apache/apisix-ingress-controller:1.4.1
docker.io/bitnami/etcd:3.5.4-debian-11-r14

Kubernetes cluster version:
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.21.12-gke.2200
