### ISSUE TITLE
bug: Restrictions for users(consumers) who are defined in namespaces that include hyphen(-) in their name do not work 

### ISSUE THREAD

**Issue by hesamhamdarsi** [apache/apisix#7738]
### Current Behavior

let's say we define the "consumer1" in namespace "aaa" . the restriction rules (method, apikey) in apisixRoute CRD  like the following works as expected:
```yml
- name: consumer-restriction
      enable: true
      config:
        allowed_by_methods:
        - user: "aaa_consumer1"
          methods:
          - "GET"

 ```
user is able to send the GET request, but not other methods (as expected)
```sh
GET:
curl https://httpbin.apisix.<DOMAIN>/anything -H 'apikey: <consumer1_key>' -i
HTTP/2 200
Post:
curl https://httpbin.apisix.<DOMAIN>/anything -H 'apikey: <consumer1_key>' -d ' ' -i
HTTP/2 403
```
but as soon as we define the consumer in a namespace like "aaa-bbb" that includes hyphen symbol in it's name, the rule doesn't work as we expect:
```yml
- name: consumer-restriction
      enable: true
      config:
        allowed_by_methods:
        - user: "aaa-bbb_consumer1"
          methods:
          - "GET"

 ```
user has full access on any method:
```sh
GET:
curl https://httpbin.apisix.<DOMAIN>/anything -H 'apikey: <consumer1_key>' -i
HTTP/2 200
Post:
curl https://httpbin.apisix.<DOMAIN>/anything -H 'apikey: <consumer1_key>' -d ' ' -i
HTTP/2 200
```

### Steps to Reproduce

1. Run apisix-ingress-controller using helm chart (chart version: 0.9.3, appVersion: 1.4.1) --> latest version on helm repo
2. create the same consumer once in <aaa> and once in <aaa-bbb> namespaces
3. create a route to httpbin service and enable <consumer-restriction> plugin
4. add restriction rules like allowed_by_methods, whitelist and blacklist for the specific user
5. check the behaviour of consumer in namespace with hyphen include with the other one 

### Environment

- APISIX version : 2.14.1 , Image: 2.15.0-alpine
- Operating system : Linux
- OpenResty / Nginx version : openresty/1.19.9.1
