### ISSUE TITLE
help request: How to support multiple ports for the ApisixUpstream 

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix#7774]
### Description

I want to  define  multiple ports for the ApisixUpstream ,
I refer to the documentation
https://apisix.apache.org/zh/docs/ingress-controller/1.4.0/concepts/apisix_upstream/

when I create  my ApisixUpstream use  kubectl apply -f  test-up.yaml,
it make a err like this: 
apisixupstream.apisix.apache.org/xsgrpc-service unchanged
error: error validating "test-up.yaml": error validating data: ValidationError(Service.spec): unknown field "portLevelSettings" in io.k8s.api.core.v1.ServiceSpec; if you choose to ignore these errors, turn validation off with --validate=false

this is my  test-up.yaml  file:  
```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixUpstream
metadata:
  name: xsgrpc-service
  namespace: test-arch
spec:
  portLevelSettings:
  - port: 50051
    scheme: grpc
  - port: 80
    scheme: http
  timeout:
    connect: 1s
    read: 3s
    send: 3s

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xsgrpc
  name: xsgrpc-service
spec:
  portLevelSettings:
  - name: http
    port: 80
    targetPort: 30080
  - name: grpc
    port: 50051
    targetPort: 30051
  selector:
    app: xsgrpc
```

my apisix ingress controller version is : 1.4

### Environment

- APISIX version (run `apisix version`):2.13.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
