### ISSUE TITLE
bug: install latest apisix via helm install error

### ISSUE THREAD

**Issue by ArenaSu** [apache/apisix#7991]
### Current Behavior

failed to install apisix via helm tool

### Expected Behavior

install apisix via helm tool success

### Error Logs

# kubectl logs -f apisix-etcd-0 -n apisix
etcd 07:55:43.78
etcd 07:55:43.78 Welcome to the Bitnami etcd container
etcd 07:55:43.79 Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 07:55:43.79 Submit issues and feature requests at https://github.com/bitnami/containers/issues
etcd 07:55:43.79
etcd 07:55:43.79 INFO  ==> ** Starting etcd setup **
etcd 07:55:43.81 INFO  ==> Validating settings in ETCD_* env vars..
etcd 07:55:43.82 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 07:55:43.82 INFO  ==> Initializing etcd
etcd 07:55:43.83 INFO  ==> Generating etcd config file using env variables
etcd 07:55:43.85 INFO  ==> There is no data from previous deployments
etcd 07:55:43.85 INFO  ==> Bootstrapping a new cluster
etcd 07:56:43.93 ERROR ==> Headless service domain does not have an IP per initial member in the cluster

### Steps to Reproduce

1. create three local type pv
2. helm repo add apisix https://charts.apiseven.com
3. helm repo update
4. helm install apisix apisix/apisix --create-namespace  --namespace apisix

initial service info below:
```
# kubectl get svc -n apisix -o wide
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE   SELECTOR
apisix-admin           ClusterIP   12.239.47.15     <none>        9180/TCP            91s   app.kubernetes.io/instance=apisix,app.kubernetes.io/name=apisix
apisix-etcd            ClusterIP   12.239.36.181    <none>        2379/TCP,2380/TCP   91s   app.kubernetes.io/instance=apisix,app.kubernetes.io/name=etcd
apisix-etcd-headless   ClusterIP   None             <none>        2379/TCP,2380/TCP   91s   app.kubernetes.io/instance=apisix,app.kubernetes.io/name=etcd
apisix-gateway         NodePort    12.239.120.215   <none>        80:30822/TCP        91s   app.kubernetes.io/instance=apisix,app.kubernetes.io/name=apisix
```

pod info below:
```
# kubectl get pod -n apisix -o wide
NAME                      READY   STATUS     RESTARTS        AGE   IP               NODE    NOMINATED NODE   READINESS GATES
apisix-6bb8f77b8d-4x4nx   0/1     Init:0/1   0               70m   12.240.176.184   node2   <none>           <none>
apisix-etcd-0             0/1     Running    7 (7m15s ago)   18m   12.240.176.191   node2   <none>           <none>
apisix-etcd-1             0/1     Running    7 (7m20s ago)   18m   12.240.176.192   node2   <none>           <none>
apisix-etcd-2             0/1     Running    7 (7m15s ago)   18m   12.240.176.193   node2   <none>           <none>
```

pv info below:
```
# kubectl get pv -n apisix
NAME    CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                       STORAGECLASS   REASON   AGE
vol-1   8Gi        RWO            Retain           Bound    apisix/data-apisix-etcd-2                           107m
vol-2   8Gi        RWO            Retain           Bound    apisix/data-apisix-etcd-0                           107m
vol-3   8Gi        RWO            Retain           Bound    apisix/data-apisix-etcd-1                           107m
```

pvc info below:
```
# kubectl get pvc -n apisix
NAME                 STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-apisix-etcd-0   Bound    vol-2    8Gi        RWO                           124m
data-apisix-etcd-1   Bound    vol-3    8Gi        RWO                           124m
data-apisix-etcd-2   Bound    vol-1    8Gi        RWO                           124m
```

pv yaml below:
```
# cat pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-1
  namespace: apisix
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-2
  namespace: apisix
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-3
  namespace: apisix
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol3"
```

### Environment

- APISIX version (run `apisix version`):2.15.0
- Operating system (run `uname -a`): Centos 7.9 

```Linux node1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 8.3.4 (https://charts.bitnami.com/bitnami)
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
