### ISSUE TITLE
bug: plugin(openid-connect): when set `use_jwks: true`, userinfo is not set

### ISSUE THREAD

**Issue by lovepocky** [apache/apisix#8133]
### Current Behavior

When set `use_jwks: true`, the plugin not set userinfo into headers

https://github.com/apache/apisix/blob/23356d6c4a58379f5cf33be92e0d88cc6399a853/apisix/plugins/openid-connect.lua#L228-L240

maybe line 240 should be `return res, err, token, res` ?

### Expected Behavior

userinfo set into headers as x-userinfo

### Steps to Reproduce

configs:
```yaml
routes:
  - uri: 
    plugins:
      openid-connect:
        # https://github.com/apache/apisix/issues/5425
        client_id: xxx
        client_secret: xxx
        discovery: some_host/oidc/.well-known/openid-configuration
        use_jwks: true
        bearer_only: true
        access_token_in_authorization_header: true
        set_userinfo_header: true
```

### Environment

- APISIX version (docker: 2.15.0-alpine):
