### ISSUE TITLE
help request: what extra_labels of prometheus plugin i can use?

### ISSUE THREAD

**Issue by xinxinh2020** [apache/apisix#8146]
### Description

Hi, i want to add some labels to metrics, and some labels are literals instead of vars. I find it will be an empty string when i use literals.  
Besides, i cannot find how to define vars like $upstream_addr. 
```yaml
plugin_attr:
  prometheus:
    metrics:
        http_status:
            extra_labels:
                - upstream_addr: $upstream_addr
                - upstream_status: $upstream_status

```
Any reply would be greatly appreciated :)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
