### ISSUE TITLE
docs: What does it mean If the kubernetes service discovery runs inside a pod? 

### ISSUE THREAD

**Issue by sheng-jie** [apache/apisix#8220]
### Current State

In this article：[Discovery-Kubernetes](https://apisix.apache.org/docs/apisix/2.15/discovery/kubernetes/)

The description in italics below is a bit confusing. What does it mean If the kubernetes service discovery runs inside/outside a pod? 

_If the kubernetes service discovery runs inside a pod_, you can use minimal configuration:

```
discovery:
  kubernetes: { }
```
_If the kubernetes service discovery runs outside a pod_, you need to create or select a specified [ServiceAccount](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/), then get its token value, and use following configuration:

```
discovery:
  kubernetes:
    service:
      schema: https
      host: # enter apiserver host value here
      port: # enter apiserver port value here
    client:
      token: # enter serviceaccount token value here
      #token_file: # enter file path here
```

### Desired State

Need to clarify.
