### ISSUE TITLE
help request: How to configure apisix to allow route by role ?

### ISSUE THREAD

**Issue by wavemoroc001** [apache/apisix#8296]
### Description

I integrated keycloak with `authz-keycloak` plugins and i want to allow each route by role. 

This is my config
```json 
{
  "bearer_only": true,
  "client_id": "myclient",
  "disable": false,
  "discovery": "https://gateway-classroom.wavemoroc.app:8443/auth/realms/Apisix/.well-known/uma2-configuration",
  "permissions": [
    "student-scope"
  ]
}

``` 

and throw this error

```
Accessing discovery URL (https://gateway-classroom.wavemoroc.app:8443/auth/realms/Apisix/.well-known/uma2-configuration) failed: 20: unable to get local issuer certificate
```

Cloud you advice me some solution to archive my goal ? 

### Environment

- APISIX version (run `apisix version`): 3.0.0
- Operating system (run `uname -a`): 3.0.0-debian (Docker)
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.15
- Plugin runner version, for issues related to plugin runners:  `authz-keycloak`

**Comment by Hazel6869** [comment]
@wavemoroc001 Hi, you can see https://apisix.apache.org/zh/docs/apisix/FAQ/#%E6%88%91%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3-unable-to-get-local-issuer-certificate-%E8%BF%99%E4%B8%AA%E9%94%99%E8%AF%AF

**Comment by wavemoroc001** [comment]
@Hazel6869 It still show that error, Is it related to my certificate ? I use [Cloudflare Origin Certificate](https://developers.cloudflare.com/ssl//origin-configuration/)

**Comment by Hazel6869** [comment]
> @Hazel6869 It still show that error, Is it related to my certificate ? I use [Cloudflare Origin Certificate](https://developers.cloudflare.com/ssl//origin-configuration/)

I don‘t know 🤔,  did you follow the documentation?

**Comment by wavemoroc001** [comment]
@Hazel6869  I did follow document this is` my config.yaml`

```yaml
apisix:
  ssl:
    ssl_trusted_certificate: "/usr/local/apisix/cert/classroom_cert.crt"
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl_protocols: TLSv1.2 TLSv1.3
    # ssl_cert: /usr/local/apisix/conf/cert/classroom_cert.crt
    # ssl_cert_key: /usr/local/apisix/conf/cert/classroom_key.key
    enable: true
    listen:                       # APISIX listening port in https.
      - port: 9443
        enable_http2: true

  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    allow_admin:               # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30                     # 30 seconds

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
```

I look in error.log. It say that

```log
2022/11/10 08:10:53 [error] 46#46: *5016 [lua] radixtree_sni.lua:146: match_and_set(): failed to find any SSL certificate by SNI: gateway-classroom.wavemoroc.app, context: ssl_certificate_by_lua*, client: 172.68.234.221, server: 0.0.0.0:9443

```
<img width="1444" alt="Screen Shot 2565-11-10 at 15 11 32" src="https://user-images.githubusercontent.com/56395197/201036445-2fa978fd-5d85-4166-8954-df15436b6afe.png">
