### ISSUE TITLE
help request: proxy-write and grpc-web not work together

### ISSUE THREAD

**Issue by wyudong** [apache/apisix#8303]
### Description

I'm trying to make two routes and two upstream grpc service work like this:

``` 
route    upstream uri   upstream name
/ac/*    /*             service-ac
/po/*    /*             service-po
```

Since I saw this [issue](https://github.com/apache/apisix/issues/4290) said the route path should be consistent with the uri provided by the backend service, I added the proxy-rewrite plugin to my routes conf. But the web client got empty response from the server and `grpc-message: unknown service ac/ac.foo` appearred in the response header.

The upstream service is configured correctly because if I remove the proxy-rewrite plugin and use `/*` as one of the route path, e.g. `/* -> /* (service-ac)`, the client communicates with service-ac correctly. But setting `/*` to service-po again does not work. I guess the routes have conflict when both setting to `/*`.

Am I doing anything wrong when dealing with the proxy-rewrite and grpc-web? And what's the best practice to proxy the grpc service which is hosted at the root domain?

```
{
  "uri": "/ac/*",
  "name": "Ac",
  "methods": [
    "POST",
    "OPTIONS"
  ],
  "plugins": {
    "grpc-web": {
      "disable": false
    },
    "proxy-rewrite": {
      "regex_uri": [
        "^/ac/(.*)",
        "/$1"
      ]
    }
  },
  "upstream_id": "433572647238894232",
  "labels": {
    "API_VERSION": "v1"
  },
  "status": 1
}
{
  "uri": "/po/*",
  "name": "Po",
  "methods": [
    "POST",
    "OPTIONS"
  ],
  "plugins": {
    "grpc-web": {
      "disable": false
    },
    "proxy-rewrite": {
      "regex_uri": [
        "^/po/(.*)",
        "/$1"
      ]
    }
  },
  "upstream_id": "433579894627107480",
  "labels": {
    "API_VERSION": "v1"
  },
  "status": 1
}
```

### Environment

I installed apisix and apisix-dashboard using helm.

```
helm install apisix apisix/apisix -n apisix --set gateway.type=NodePort 
helm install apisix-dashboard apisix/apisix-dashboard -n apisix
```

The apisix ingress conf:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: X-User-Agent,Content-Type,X-GRPC-WEB
    nginx.ingress.kubernetes.io/cors-allow-methods: OPTIONS,GET,POST,PUT,DELETE
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: example
  namespace: apisix
spec:
  rules:
  - host: api6.example.com
    http:
      paths:
      - backend:
          service:
            name: apisix-gateway
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - api6.example.com
    secretName: apisix-tls
status:
  loadBalancer:
    ingress:
    - ip: 192.168.66.77
```
