### ISSUE TITLE
request help: APISIX retuen error 3 name error with multi Consul DNS

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#8345]
### Discussed in https://github.com/apache/apisix/discussions/8338

<div type='discussions-op-text'>

<sup>Originally posted by **Fabriceli** November 16, 2022</sup>
Version info:
- APISIX 3.0.0
- Consul 1.9.5
- Linux arch x86_64

ERROR:
```sh
[error] 43382#43382: *1626 [lua] init.lua:428: handle_upstream(): failed to set upstream: no valid upstream node: failed to query the DNS server: dns server error: 3 name error, client: a.a.a.a, server: _, request: "GET /api/v0/test/ HTTP/1.1", host: "b.b.b.b"
```

with `/usr/local/apisix/conf/config.yaml`:
```yaml
discovery:
  dns:
    servers:
      - "x.x.x.x:8600" 
      - "y.y.y.y:8600"
```
service A is **only** valid in Consul y.y.y.y:8600. APISIX is not support multi Consul DNS? </div>
