### ISSUE TITLE
help request: openid-connect  with proxy-rewrite => preferred_username 

### ISSUE THREAD

**Issue by dgradecak** [apache/apisix#8353]
### Description

I would like to set a downstream header that the value is based on the OIDC user attributes. I am mostly interested in using preffered_username but sure, this can apply to any claims

### Environment

- APISIX version (run `apisix version`): 3.0.0
- Operating system (run `uname -a`): "official" docker image

**Comment by dgradecak** [comment]
sample config:

```
routes:
   -
    uri: /*
    plugins:       
        openid-connect:
            client_id: "apisix"
            client_secret: "..."
            discovery: "..."
            scope: "openid profile"
            bearer_only: false
            realm: "master"
            redirect_uri: ".../.apisix/callback"
            set_id_token_header: false
            set_userinfo_header: true
            set_access_token_header: false
            session:
              secret: "testtesttesttesttest"        
        proxy-rewrite: 
            headers: 
                X-Alfresco-Remote-User: "!!!HERE_GOES_THE_CLAIM!!!"

    upstream_id: 1
```

**Comment by tzssangglass** [comment]
> proxy-rewrite: 
>             headers: 
>                 X-Remote-User: "!!!HERE_GOES_THE_CLAIM!!!"

we can use 

```
> proxy-rewrite: 
>             headers: 
>                 X-Remote-User: $consumer_name
```

about `$consumer_name`: https://github.com/apache/apisix/blob/master/docs/en/latest/apisix-variable.md#list-of-variables

Note that the `consumer_name` here comes from the `name` when you added the consumer. ref: https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#consumer

**Comment by dgradecak** [comment]
consumers are really not clear to me, even if I read and re-re-read the docs.

Are you sure it is meant that the plugin openid-connect would set a claim in the $consumer_name variable?

**Comment by dgradecak** [comment]
I made it work for me but, I have a big doubt it is the right way. I created a new plugin that is executed after oidc and it extracts the userinfo header and uses the preffered_name claim

```
plugins:
     openid-connect:
         ...
     rewrite-openid-connect-userinfo:
            remote_user_header: "X-My-Remote-User"
```

```
local core    = require("apisix.core")
local ngx     = ngx

local plugin_name = "rewrite-openid-connect-userinfo"

local schema = {
    type = "object",
    properties = {        
        remote_user_header = {
            description = "external auth header",
            type = "string",
            default = "X-Remote-User",
        },
		oidc_userinfo_header = {
            description = "external auth header",
            type = "string",
            default = "X-Userinfo",
        },
		userinfo_claim = {
            description = "oidc username to be mapped to remote_user_header",
            type = "string",
            default = "preferred_username",
        }
    }
}

local _M = {
    version = 0.1,
    priority = 1000,
    name = plugin_name,
    schema = schema,
}

function _M.check_schema(conf)    

    local ok, err = core.schema.check(schema, conf)
    if not ok then
        return false, err
    end

    return true
end

function _M.rewrite(plugin_conf, ctx)
    local conf = core.table.clone(plugin_conf)
	local user = core.json.decode(ngx.decode_base64(core.request.header(ctx, conf.oidc_userinfo_header)))[conf.userinfo_claim]
	core.request.set_header(ctx, conf.remote_user_header, user)	 
end

return _M
```
