### ISSUE TITLE
help request: traffic-split blue-green not take effect

### ISSUE THREAD

**Issue by marksugar** [apache/apisix#8372]
### Description

Server: APISIX/2.15.0

two sets of Pods in k8s called nginxa and nginxb, which is okay when I use backends for weighting
```
      backends:
      - serviceName: nginxb
        servicePort: 80
        weight: 40
      - serviceName: nginxa
        servicePort: 80
        weight: 60
```
When I tried to use the plugins' traffic-split, it didn't work.

yaml is as follows
```
      plugins:
      - name: traffic-split
        enable: true
        config:
          rules:
          - match:
            vars: ["http_release","==","new_release123"]
            weighted_upstreams:
            - name: nginxa
              weight: 100
      backends:
      - serviceName: nginxb
        servicePort: 80
```
In the routing of the dashboard, the data editor is represented as follows
```
{
  "uris": [
    "/*"
  ],
  "name": "default_nginx_root",
  "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
  "hosts": [
    "nginx.test.com"
  ],
  "plugins": {
    "traffic-split": {
      "rules": [
        {
          "vars": [
            "http_release",
            "==",
            "new_release123"
          ],
          "weighted_upstreams": [
            {
              "name": "default_nginxb_80",
              "nodes": [
                "192.120.1.216"
              ],
              "weight": 90
            }
          ]
        }
      ]
    }
  },
  "upstream_id": "1b1fd9dd",
  "labels": {
    "managed-by": "apisix-ingress-controller"
  },
  "status": 1
}
```
Although this configuration does not throw an error, it does not do anything.

When I change the configuration as follows, the data in the data editor in the dashboard route does not change in any way
```
      plugins:
      - name: traffic-split
        enable: true
        config:
          rules:
            match:
            - vars: ["http_release","==","new_release123"]
            weighted_upstreams:
            - upstream:
              - name: nginxa
              - type: roundrobin
              - weight: 100
      backends:
      - serviceName: nginxb
        servicePort: 80
```
so, What is the correct configuration to use YAML in K8S?

Thank you so much

### Environment

helm install apisix 

version default

Server: APISIX/2.15.0
