### ISSUE TITLE
help request: how to configure file-log plugin

### ISSUE THREAD

**Issue by ederparaiso** [apache/apisix#8387]
### Description

Hi, as posted on slack forum, I'm trying to configure file-log plugin in apisix (version 3.0.0)
It doesn't show any erros but  no file.log file was created in /usr/local/apisix/logs. Is this the root directory when I specify a relative path in file-log configuration path? What I'm still doing wrong? 

Also, I just want to understand why, by default, (in my tests at least) /usr/local/apisix/logs is created with root permissions even if I don't map it to a external volume. Should this directory have write persmissions to apisix user by default?

Thanks in advance!

compose file
```yaml
version: '3.7'

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.13-alpine
    container_name: apisix-dashboard
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      - apisix_network

  apisix:
    image: apache/apisix:3.0.0-debian
    container_name: apisix
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      - apisix_network

  etcd:
    image: bitnami/etcd:3.4.15
    container_name: etcd
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379/"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379/"
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix_network

networks:
  apisix_network:
    driver: bridge
    external: true

volumes:
  etcd_data:
    driver: local
 ```

route/plugin configs
```json
{
  "uri": "/v3/bc8fdfcd-0392-49fa-8520-c8644d1688c8",
  "name": "test",
  "plugins": {
    "file-logger": {
      "path": "logs/file.log"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "run.mocky.io",
        "port": 443,
        "weight": 1
      }
    ],
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "https",
    "pass_host": "pass"
  },
  "status": 1
}
```

example
```sh
curl -i http://127.0.0.1:9080/v3/bc8fdfcd-0392-49fa-8520-c8644d1688c8 -H "Host: http://run.mocky.io/"
```

### Environment

- APISIX version 3.0.0-debian (run via docker image)

**Comment by tzssangglass** [comment]
try with

```json
  "file-logger": {
      "path": "file.log"
  }
```

**Comment by mscb402** [comment]
I was trying your config at my local docker. Everything is OK! The file can create success in `/usr/local/apisix/logs`.
<img width="874" alt="image" src="https://user-images.githubusercontent.com/11229089/203686406-41df8db3-7167-49c1-960d-3ef7509ccecb.png">

**Comment by mscb402** [comment]
I just copy and paste the route config you provided. And nothing was wrong.

This is my docker-compose config
```
version: "3"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.13-alpine
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      apisix:

  apisix:
    image: apache/apisix:latest
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

  web1:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  web2:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      apisix:

  grafana:
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_conf/provisioning:/etc/grafana/provisioning"
      - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
      - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
```

**Comment by mscb402** [comment]
There is no problem with your configuration, so according to my inference, maybe there is a problem with your usage like you have not accessed this route correctly. So I re-read your description and you are using

`curl -i http://127.0.0.1:9080/v3/bc8fdfcd-0392-49fa-8520-c8644d1688c8 -H "Host: http://run.mocky.io/"`

this command to access this route, which is wrong. Because you didn't configure `HOST` in your route. So you should access route like this

`curl -i http://127.0.0.1:9080/v3/bc8fdfcd-0392-49fa-8520-c8644d1688c8 `

**Comment by mscb402** [comment]
So maybe you should try this route config
```
{
  "uri": "/v3/bc8fdfcd-0392-49fa-8520-c8644d1688c8",
  "name": "test",
  "host": "run.mocky.io",
  "plugins": {
    "file-logger": {
      "path": "logs/file.log"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "run.mocky.io",
        "port": 443,
        "weight": 1
      }
    ],
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "https",
    "pass_host": "pass"
  },
  "status": 1
}
```

keep mind `host` is add to config.

and then access this route from curl

```
curl -i http://127.0.0.1:9080/v3/bc8fdfcd-0392-49fa-8520-c8644d1688c8 -H "Host: run.mocky.io" 
```

there is what you will get

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 16
Connection: keep-alive
Date: Thu, 24 Nov 2022 03:37:50 GMT
Sozu-Id: 01GJKVD31W1TN8WFR0NW0NPFJQ
Server: APISIX/3.0.0

{"result": "ok"}
```

And the file log will append:
```
## tail -n1 file.log

{"response":{"status":200,"size":222,"headers":{"sozu-id":"01GJKVD31W1TN8WFR0NW0NPFJQ","content-length":"16","server":"APISIX\/3.0.0","connection":"close","date":"Thu, 24 Nov 2022 03:37:50 GMT","content-type":"application\/json; charset=UTF-8"}},"apisix_latency":0,"route_id":"00000000000000000032","server":{"hostname":"bd257b6c70bc","version":"3.0.0"},"client_ip":"172.20.0.1","request":{"uri":"\/v3\/bc8fdfcd-0392-49fa-8520-c8644d1688c8","size":115,"querystring":{},"method":"GET","url":"http:\/\/run.mocky.io:9080\/v3\/bc8fdfcd-0392-49fa-8520-c8644d1688c8","headers":{"accept":"*\/*","host":"run.mocky.io","user-agent":"curl\/7.84.0"}},"start_time":1669261068867,"upstream_latency":1702,"latency":1701.9999027252,"service_id":"","upstream":"46.252.181.103:443"}
```

**Comment by ederparaiso** [comment]
Hi @mscb402 , thanks for your attention! I noted that you are using the latest version of apisix image.
```yaml
image: apache/apisix:latest
```

I'm using 
```yaml
image: apache/apisix:3.0.0-debian
```

Maybe its a problem with this version... Also, in this version, if a make curl request without host header I receive a 404 error. I agree with you but what is happening is the opposite (with my original config)

**Comment by ederparaiso** [comment]
Also I noted that I'm using only apisix, etc and dashboard instances. I don't think so but it worth to ask: It prometheus is necessary to file-log works?

**Comment by mscb402** [comment]
> Also I noted that I'm using only apisix, etc and dashboard instances. I don't think so but it worth to ask: Is prometheus necessary to file-log works?

prometheus is not necessary for file-log.

**Comment by mscb402** [comment]
I try using `apache/apisix:3.0.0-debian` image, still, work for me.

docker compose config
```yaml
version: "3"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.13-alpine
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      apisix:

  apisix:
    image: apache/apisix:3.0.0-debian
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
```

post route config (your version)
```shell
curl -i -X POST \
   -H "X-API-KEY:edd1c9f034335f136f87ad84b625c8f1" \
   -H "Content-Type:application/json" \
   -d \
'{
  "uri": "/v3/bc8fdfcd-0392-49fa-8520-c8644d1688c8",
  "name": "test",
  "plugins": {
    "file-logger": {
      "path": "logs/file.log"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "run.mocky.io",
        "port": 443,
        "weight": 1
      }
    ],
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "https",
    "pass_host": "pass"
  },
  "status": 1
}' \
 'http://127.0.0.1:9180/apisix/admin/routes'
```

try access this route using curl

```
curl -i http://127.0.0.1:9080/v3/bc8fdfcd-0392-49fa-8520-c8644d1688c8
```

and look at file log

```json
➜  tail -n1 file.log                                                    
{"service_id":"","apisix_latency":1290.9998645782,"request":{"url":"http:\/\/127.0.0.1:9080\/v3\/bc8fdfcd-0392-49fa-8520-c8644d1688c8","querystring":{},"method":"GET","uri":"\/v3\/bc8fdfcd-0392-49fa-8520-c8644d1688c8","size":117,"headers":{"user-agent":"curl\/7.84.0","host":"127.0.0.1:9080","accept":"*\/*"}},"response":{"size":1629,"status":404,"headers":{"content-type":"text\/html; charset=utf-8","x-clevercloudupgrade":"true","cache-control":"no-cache","server":"APISIX\/3.0.0","transfer-encoding":"chunked","connection":"close"}},"upstream_latency":1326,"route_id":"00000000000000000015","latency":2616.9998645782,"start_time":1669339166647,"upstream":"185.42.117.109:443","server":{"hostname":"4797f0986fd0","version":"3.0.0"},"client_ip":"172.20.0.1"}
```
