### ISSUE TITLE
help request: Declarative deployed routes are not added anymore (0.11.3 helm)

### ISSUE THREAD

**Issue by wofr** [apache/apisix#8465]
### Description

The following routes works fine when I use apisix 0.11.0 (helm deplyoment).  I do the deplyoment of the route in a declarative way.  When I switch to use apisxi 0.11.3 the deplyoment does not work anymore.  The only adaption I did on the route was use (apiVersion: apisix.apache.org/v2 instead of v2beta3)

I do not really know what causes the problem the routes are simply not added to the gateway.  

 ```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixTls
metadata:
  name: {{ .Values.apisixTLSRoute }}
#  namespace: apisix
spec:
  hosts:
  - {{ .Values.hostName }}
  secret:
    name: {{ .Values.ingressSecret }}
    namespace: apisix
---
# Define the route to access the backend
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .Values.apisixRoute }}
#  namespace: apisix
spec:
  http:
  - name: {{ .Values.hostName }}
    match:
      paths:
      - /*
      - /graphql
      hosts:
      - {{ .Values.hostName }}
    backends:
    - serviceName: {{ .Values.service }}
      servicePort: {{ .Values.appPort }}
    websocket: true
    
    plugins:
     - name: cors
       enable: true
     - name: redirect
       enable: true
       config:
         http_to_https: true       
     - name: openid-connect
       enable: true
       config:
         access_token_in_authorization_header: true
         bearer_only: false
         # When set to true, verifies the identity provider's SSL certificates. 
         ssl_verify: false
         client_id: "apisix"
         # Encrypt secret
         # Secret need to correspond with the secret defined in keycloak
         client_secret: "XXXXXXXXXXXXXXXX"
         disable: false
         discovery: "https://XXXXXXXXXXXXXXXXXXXXXXXXXX"
         realm: "XXXXXXXXXXX_staging"
         redirect_uri: "/callback"
         session:
           secret: {{ .Values.secretTokenKey }}
```

### Environment

- APISIX version (run `apisix version`): /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua version 2.15.1
- Operating system (run `uname -a`): Linux apisix-staging-8589bc6d9-w26wt 5.10.133+ #1 SMP Sat Sep 10 14:54:12 UTC 2022 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 0.6.1
