### ISSUE TITLE
bug: discovery/dns cause panic

### ISSUE THREAD

**Issue by caibirdme** [apache/apisix#8554]
### Current Behavior

1. config dns dicovery in config.yaml:
```yaml
discovery:
  dns:
    servers:
      - 9.166.239.254:53  # k8s coredns svc
```
2. config tcp proxy:
```yaml
    stream_routes:
      - server_port: 10000
        upstream:
          service_name: app-service.namespace:8081
          scheme: tcp
          discovery_type: dns
          type: roundrobin
```
3. send request to xxx:10000
4. apisix aborted with log:
```
2022-12-22T15:07:02.512209987Z 2022/12/22 23:07:02 [error] 56#56: *91098 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/discovery/dns/init.lua:32: attempt to index upvalue 'dns_client' (a nil value)
2022-12-22T15:07:02.512250920Z stack traceback:
2022-12-22T15:07:02.512256678Z coroutine 0:
2022-12-22T15:07:02.512259872Z 	/usr/local/apisix/apisix/discovery/dns/init.lua: in function 'nodes'
2022-12-22T15:07:02.512263539Z 	/usr/local/apisix/apisix/upstream.lua:259: in function 'set_upstream'
2022-12-22T15:07:02.512266986Z 	/usr/local/apisix/apisix/init.lua:959: in function 'stream_preread_phase'
2022-12-22T15:07:02.512270259Z 	preread_by_lua(nginx.conf:90):2: in main chunk while prereading client data, client: 9.166.233.109, server: 0.0.0.0:10000
```

### Expected Behavior

proxy request to desired k8s service

### Error Logs

2022-12-22T15:07:02.512209987Z 2022/12/22 23:07:02 [error] 56#56: *91098 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/discovery/dns/init.lua:32: attempt to index upvalue 'dns_client' (a nil value)
2022-12-22T15:07:02.512250920Z stack traceback:
2022-12-22T15:07:02.512256678Z coroutine 0:
2022-12-22T15:07:02.512259872Z 	/usr/local/apisix/apisix/discovery/dns/init.lua: in function 'nodes'
2022-12-22T15:07:02.512263539Z 	/usr/local/apisix/apisix/upstream.lua:259: in function 'set_upstream'
2022-12-22T15:07:02.512266986Z 	/usr/local/apisix/apisix/init.lua:959: in function 'stream_preread_phase'
2022-12-22T15:07:02.512270259Z 	preread_by_lua(nginx.conf:90):2: in main chunk while prereading client data, client: 9.166.233.109, server: 0.0.0.0:10000

### Steps to Reproduce

as current behavior described

### Environment

- APISIX version (run `apisix version`): 2.15.1 (using helm chart v0.11.4)
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): no etcd, yaml
- APISIX Dashboard version, if relevant: no
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by caibirdme** [comment]
When I use nodes directly rather than dns service_name, it works as expected. So I think this might be a bug of discovery/dns
```yaml
    stream_routes:
      - server_port: 10000
        upstream:
          nodes:
            "1.2.3.4:8081": 1
          type: roundrobin
```

And the dns server is healthy, I can use nslookup to check:
```
nslookup qwe-trpc.test 9.166.239.254:53

Server:         9.166.239.254
Address:        9.166.239.254#53

Name:   qwe-trpc.test.svc.cluster.local
Address: 9.166.239.70
```
