### ISSUE TITLE
bug: plugin ext-plugin-post-resp not invoked

### ISSUE THREAD

**Issue by sashokbg** [apache/apisix#8637]
### Current Behavior

When a route has the **ext-plugin-post-resp** plugin configured, then the plugin is not called

### Expected Behavior

The **ext-plugin-post-resp** should be called on my route

### Error Logs

apache-apisix                     | 2023/01/09 11:53:52 [warn] 943#943: *182326 [lua] plugin.lua:202: load(): new plugins: {"consumer-restriction":true,"gzip":true,"limit-count":true,"redirect":true,"traffic-split":true,"ext-plugin-post-resp":true,"echo":true,"ip-restriction":true,"referer-restriction":true,"request-id":true,"http-logger":true,"grpc-web":true,"ext-plugin-pre-req":true,"azure-functions":true,"skywalking-logger":true,"kafka-proxy":true,"udp-logger":true,"key-auth":true,"inspect":true,"forward-auth":true,"proxy-mirror":true,"prometheus":true,"basic-auth":true,"wolf-rbac":true,"kafka-logger":true,"openfunction":true,"request-validation":true,"authz-casbin":true,"real-ip":true,"server-info":true,"zipkin":true,"ua-restriction":true,"loggly":true,"serverless-pre-function":true,"aws-lambda":true,"hmac-auth":true,"ext-plugin-post-req":true,"opa":true,"file-logger":true,"serverless-post-function":true,"proxy-control":true,"syslog":true,"openwhisk":true,"limit-req":true,"response-rewrite":true,"splunk-hec-logging":true,"tencent-cloud-cls":true,"clickhouse-logger":true,"fault-injection":true,"proxy-cache":true,"authz-casdoor":true,"datadog":true,"cors":true,"sls-logger":true,"cas-auth":true,"csrf":true,"jwt-auth":true,"api-breaker":true,"elasticsearch-logger":true,"public-api":true,"workflow":true,"proxy-rewrite":true,"limit-conn":true,"ldap-auth":true,"openid-connect":true,"grpc-transcode":true,"rocketmq-logger":true,"client-control":true,"authz-keycloak":true,"example-plugin":true,"uri-blocker":true,"google-cloud-logging":true,"ai":true,"tcp-logger":true,"mocking":true}, context: init_worker_by_lua*

### Steps to Reproduce

Using the following config:

```
upstreams:
  -
    id: 1
    nodes:
      "127.0.0.1:8080": 1
    type: roundrobin

routes:
  -
    uri: /configuration/message-types
    upstream_id: 1
    plugins:
      ext-plugin-post-resp:
        conf:
          - name: "ProxymFilter"
            value: "{\"enable\":\"feature\"}"}
```

When testing with curl
Then my plugin is not invoked.

Replacing  **ext-plugin-post-resp** with **ext-plugin-pre-req** and everytihing works fine.

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): Linux alexander-p14s 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64 GNU/Linux
- Plugin runner version, for issues related to plugin runners:
			<groupId>org.apache.apisix</groupId>
			<artifactId>apisix-runner-starter</artifactId>
			<version>0.4.0</version>
