### ISSUE TITLE
help request: 3.1.0 report error cannot open logs/error: Permission denied

### ISSUE THREAD

**Issue by yunduansing** [apache/apisix#8646]
### Description

[alert] could not open error log file: open() "/usr/local/apisix/logs/error.log" failed (13: Permission denied)

are u closed the cmd 'chmod' in the official docker image ?

### Environment

- APISIX version (run `apisix version`):3.1.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
In the Docker image `error.log` is linked to stderr. This may be different from a regular file. 
Beyond that `Permission denied` will exists when you use the file-logger plugin to write the log to the local file. If you face this problem, you should create this file and run the `chmod`  manual.

**Comment by tokers** [comment]
If you just want to see the error.log, try to use `docker logs`.

**Comment by Fabriceli** [comment]
Current user has no permission, maybe this [config](https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L135) can help you

**Comment by pixeldin** [comment]
## Some reason
Hi，community! This problem also occurs in my environment(ubuntu 22.04), after struggling for long time trying to figure out what is the problem, most of the solution I found pointed to mutual access permission issues between docker containers and your OS mounted filesystems. 

## Solution refer to safe policy
- @mscb402 If your machine supports SELinux command, such as (CentOS), maybe you can try update the access policy by `setenforce 0` temporarily. 
- In my environment，since the ubuntu system adopts the `AppArmor` to management file security access mode, some way for reference only is replace policy manager way with SELinux and I think that is a little complicated.
https://www.linode.com/docs/guides/how-to-install-selinux-on-ubuntu-22-04/

## Perhaps a less elegant way
Finally, it somehow works in my env, my solution steps are：
- First I change the docker-compose.yml configuration like this:
  ```
  apisix:
    image: apache/apisix:latest
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/nginx.conf:/usr/local/apisix/conf/nginx.conf
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_client_body_temp:/usr/local/apisix/client_body_temp
      - ./apisix_proxy_temp:/usr/local/apisix/proxy_temp
  ```
  **I found the file volumes list above will be initialized by apisix startup in the docker's running log.**

- And then pre-create them into your file location(like `apisix-docker/example/`) before the container starts.

Maybe this is not a best solution, if anyone have a better idea, I hope to get your advice.

**Comment by ZUOXIANGE** [comment]
I change the `docker-compose.yml` like this,then fix it
``` yaml
 apisix:
    image: apache/apisix:latest
    user: root
```
