### ISSUE TITLE
bug: Unable to use memory proxy cache

### ISSUE THREAD

**Issue by kamsz** [apache/apisix#8719]
### Current Behavior

Memory proxy cache is failing

### Expected Behavior

Memory proxy cache is working

### Error Logs
```
2023/01/23 00:11:43 [error] 50#50: *521530 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/proxy-cache/memory.lua:47: attempt to index field 'dict' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/apisix/apisix/plugins/proxy-cache/memory.lua: in function 'get'
        ...cal/apisix/apisix/plugins/proxy-cache/memory_handler.lua:204: in function 'phase_func'
        /usr/local/apisix/apisix/plugin.lua:1094: in function 'run_plugin'
        /usr/local/apisix/apisix/init.lua:615: in function 'http_access_phase'
```
### Steps to Reproduce

        - name: proxy-cache
          enable: true
          config:
            cache_ttl: 60
            cache_strategy: memory
            cache_zone: memory_cache
            cache_bypass:
              - '$http_authorization'

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): Debian GNU/Linux 10 (buster)
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@kamsz The memory zone should be defined in APISIX config.yaml? Did you define this?

**Comment by monkeyDluffy6017** [comment]
Hi @kamsz, where do you define these configurations? It doesn't look like the format is right
<img width="314" alt="image" src="https://user-images.githubusercontent.com/9354193/215382616-9e26790b-26a4-4a58-9fbc-2594c7b690d8.png">

**Comment by monkeyDluffy6017** [comment]
Could you follow the steps in https://github.com/apache/apisix/blob/master/t/plugin/proxy-cache/memory.t?
1. define a memory zone 
`lua_shared_dict memory_cache 50m;`
2. config the route with the `proxy cache` plugin 
```
('/apisix/admin/routes/1',
                    ngx.HTTP_PUT,
                    [[{
                        "plugins": {
                            "proxy-cache": {
                               "cache_strategy": "memory",
                               "cache_key":["$host","$uri"],
                               "cache_zone": "memory_cache",
                               "cache_bypass": ["$arg_bypass"],
                               "cache_method": ["GET"],
                               "hide_cache_headers": false,
                               "cache_ttl": 300,
                               "cache_http_status": [200],
                               "no_cache": ["$arg_no_cache"]
                            }
                        },
                        "upstream": {
                            "nodes": {
                                "127.0.0.1:1986": 1
                            },
                            "type": "roundrobin"
                        },
                        "uri": "/hello*"
                   }]]
                   )
```
```

**Comment by jensg-st** [comment]
Hi,

I'd like to resurrect this issue. I'm experiencing the same with a standard installation with the ingress controller with the following configuration:

```yaml
name: proxy-cache
enabled: true
config:
  cache_bypass:
  - "$arg_bypass"
  cache_control: false
  cache_strategy: memory
  cache_ttl: 600
  hide_cache_headers: false
```
 
If I switch to `disk` it works. I'm happy to follow your suggestions to debug that issue.

**Comment by monkeyDluffy6017** [comment]
Hi @jensg-st @kamsz I think it's an apisix ingress conntroller problem, Could you ask in [apisix ingress controller](https://github.com/apache/apisix-ingress-controller/issues)

**Comment by monkeyDluffy6017** [comment]
@jensg-st yes, this zone should be added yourself

**Comment by jensg-st** [comment]
Like this?

```yaml
        zones:                             # The parameters of a cache                                                                 
        - name: memory_cache                                                                                                           
          memory_size: 100m                                                                                                       
                                                                                                                         
        - name: disk_cache_one             # The name of the cache, administrator can be specify                         
                                           # which cache to use by name in the admin api                                 
          memory_size: 50m                 # The size of shared memory, it's used to store the cache index           
          disk_size: 1G                    # The size of disk, it's used to store the cache data                     
          disk_path: "/tmp/disk_cache_one" # The path to store the cache data                                        
          cache_levels: "1:2"              # The hierarchy levels of a cache                                         
      #  - name: disk_cache_two                                                
```

**Comment by realreachard** [comment]
> Like this?
> 
> ```yaml
>         zones:                             # The parameters of a cache                                                                 
>         - name: memory_cache                                                                                                           
>           memory_size: 100m                                                                                                       
>                                                                                                                          
>         - name: disk_cache_one             # The name of the cache, administrator can be specify                         
>                                            # which cache to use by name in the admin api                                 
>           memory_size: 50m                 # The size of shared memory, it's used to store the cache index           
>           disk_size: 1G                    # The size of disk, it's used to store the cache data                     
>           disk_path: "/tmp/disk_cache_one" # The path to store the cache data                                        
>           cache_levels: "1:2"              # The hierarchy levels of a cache                                         
>       #  - name: disk_cache_two                                                
> ```

same problem , but got Response code 500. 
how to config memory proxy cache  in /apisix_conf/config.yaml  ?

**Comment by jensg-st** [comment]
Any advice how to configure it to make it work?

**Comment by monkeyDluffy6017** [comment]
Hi, @jensg-st, Do you set this in plugin config
![image](https://user-images.githubusercontent.com/9354193/229192669-99b5c17a-9e4b-4d3d-8321-db0890aa3a73.png)

**Comment by jensg-st** [comment]
I have started from scratch and added this to the configmap:

```yaml
zones:                             # The parameters of a cache
         - name: memory-cache
           memory_size: 100m
```

And in the route:

```yaml
plugins:
    - config:
        cache_strategy: memory
        cache_zone: memory-cache
      enable: true
      name: proxy-cache
```

It seems to work now and I can not reproduce the issue anymore. Seems to be ok.
