### ISSUE TITLE
docs(plugin-develop): wrong indent in encrypted-storage-fields

### ISSUE THREAD

**Issue by ronething** [apache/apisix#8796]
### Current State

- https://apisix.apache.org/docs/apisix/plugin-develop/#encrypted-storage-fields

```yaml
apisix:
    data_encryption:
    enable: true
    keyring:
        - edd1c9f0985e76a2
        - qeddd145sfvddff4
```

### Desired State

maybe something like below.

```
apisix:
  data_encryption:
    enable: true
    keyring:
      - edd1c9f0985e76a2
      - qeddd145sfvddff4
```
