### ISSUE TITLE
help request: etcd->http://etcd:2379: failed to parse domain

### ISSUE THREAD

**Issue by syl000** [apache/apisix#8800]
### Description

my error log have a warn,I don't know why ,does anyone know it ？

./apisix_log/error.log:

`2023/02/07 02:22:25 [warn] 52#52: *12717338 [lua] v3.lua:829: request_chunk(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer`

`[error] 76#76: *12281706 [lua] config_etcd.lua:631: no healthy etcd endpoint available, next retry after 2s, context: ngx.timer`

`[warn] 109#109: *10905451 [lua] v3.lua:245: _request_uri(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, client: 172.19.0.7, server: , request: "GET /apisix/prometheus/metrics HTTP/1.1", host: "apisix:9091"`

docker-compose.yml
```
etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - /data/etcd:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:
```

### Environment

- APISIX version (run `apisix version`):3.1.0
- Operating system (run `uname -a`):Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.15
