### ISSUE TITLE
feat: As a user, I would like a strip-path annotation feature like kong has

### ISSUE THREAD

**Issue by ecoupal-believe** [apache/apisix#8854]
### Description

I have an ingress that look like that:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    k8s.apisix.apache.org/strip-path: "true"
spec:
  ingressClassName: apisix
  rules:
    - host: api.mycorp
      http:
        paths:
          - path: /api1
            pathType: Prefix
            backend:
              service:
                name: api1
                port:
                  number: 80
          - path: /api2
            pathType: Prefix
            backend:
              service:
                name: api2
                port:
                  number: 80
          - path: /api3
            pathType: Prefix
            backend:
              service:
                name: api3
                port:
                  number: 80
```

I want the upstream path to look like `/test-action?apikey=1234` when I access the following url url: `https://api.mycorp/api2/test-action?apikey=1234`

I already tried with `k8s.apisix.apache.org/rewrite-target-regex` and `k8s.apisix.apache.org/rewrite-target-regex-template` without any success.
