### ISSUE TITLE
bug: enable https Redirect error port

### ISSUE THREAD

**Issue by overstarry** [apache/apisix#8929]
### Current Behavior

 enable https Redirect error port

### Error Logs

curl:
![image](https://user-images.githubusercontent.com/23260162/221073973-e256f5ac-09e0-49fb-9fc5-5554522237e0.png)

The correct one is https://xxx.com

### Steps to Reproduce

docker-compose:
```
version: "3"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.0-alpine
    restart: always
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "19000:9000"
    networks:
      - apisix

  apisix:
    image: apache/apisix:3.1.0-centos
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "80:9080/tcp"
      - "443:9443/tcp"
      - "9280:9180/tcp"
    networks:
      apisix:


  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - ./etcd_data:/bitnami/etcd
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:


networks:
  apisix:
    name: "apisix-net"
    driver: bridge

volumes:
  etcd_data:
    driver: local

```
route:
```
{
  "uri": "/*",
  "name": "xxx",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "www.xxx.com",
  "plugins": {
    "redirect": {
      "http_to_https": true
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "xxx-xxx",
        "port": 3000,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by overstarry** [comment]
apisix config:
```
apisix:
  node_listen: 9080 # APISIX listening port
  enable_ipv6: false

deployment:
  admin:
    allow_admin: # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0 # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.
    admin_listen:
      port: 9180
    admin_key:
      - name: "xxxx"
        key: xx
        role: admin
  ssl:
    listen:
      - port: 9443

  etcd:
    host: # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379" # multiple etcd address
    prefix: "/apisix" # apisix configurations prefix
    timeout: 30
      # 30 seconds

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
  log-rotate:
    interval: 604800 # rotate interval (unit: second)
    max_kept: 365 # max number of log files will be kept
    enable_compression: false # enable log file compression(gzip) or not, default false

```
