### ISSUE TITLE
bug: call download file route got error [upstream sent invalid header: "\x20..."]

### ISSUE THREAD

**Issue by Fabriceli** [apache/apisix#8934]
### Current Behavior

1. create a route via apisix-dashboard
2. call this route to download doc file, got error:
```sh
[error] 139#139: *1067452 upstream sent invalid header: "\x20..." while reading response header from upstream, client: 10.86.111.222, server: _, request: "POST /abc HTTP/1.1", upstream: "http://10.18.93.225:8080/abc", host: "a.b.sit"
```

if create ingress(kind: ingress; ingressClassName: Apisix), this route can work fine

### Expected Behavior

download file success

### Error Logs

```sh
[error] 139#139: *1067452 upstream sent invalid header: "\x20..." while reading response header from upstream, client: 10.86.111.222, server: _, request: "POST /abc HTTP/1.1", upstream: "http://10.18.93.225:8080/abc", host: "a.b.sit"
```

### Steps to Reproduce

1. Run Apisix via k8s with helm charts install
2. Create a route to download doc file via apisix-dashboard
3. Call the route got error via curl
```sh
 [error] 139#139: *1067452 upstream sent invalid header: "\x20..." while reading response header from upstream, client: 10.86.111.222, server: _, request: "POST /abc HTTP/1.1", upstream: "http://10.18.93.225:8080/abc", host: "a.b.sit"
```

### Environment

- APISIX version (run `apisix version`):
3.1.0
- Operating system (run `uname -a`):
```sh
Linux metal-master1-sit 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
3.5.6
- APISIX Dashboard version, if relevant:
3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> Create a route to download doc file via apisix-dashboard

Could you please share your route configuration?

**Comment by Fabriceli** [comment]
> > Create a route to download doc file via apisix-dashboard
> 
> Could you please share your route configuration?

```yaml
{
  "uri": "/abc/*",
  "name": "report",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "a.b.c",
  "upstream": {
    "nodes": [
      {
        "host": "10.18.93.225",
        "port": 8080,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```

**Comment by Fabriceli** [comment]
> > Create a route to download doc file via apisix-dashboard
> 
> Could you please share your route configuration?

```yaml
{
  "uri": "/abc/*",
  "name": "report",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "a.b.c",
  "upstream": {
    "nodes": [
      {
        "host": "10.18.93.225",
        "port": 8080,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```
