### ISSUE TITLE
docs: missing how to register protos in standalone mode

### ISSUE THREAD

**Issue by pottekkat** [apache/apisix#8986]
### Current State

The current [standalone mode documentation](https://apisix.apache.org/docs/apisix/next/deployment-modes/#standalone) does not explain how to register protos with APISIX in the yaml file.

### Desired State

This additional section should be added to the documentation.

**Comment by navendu-pottekkat** [comment]
@nfrankel Could you comment the example you used here?

**Comment by nfrankel** [comment]
I ended up not using YAML 😅

The idea is to translate something like [this](https://github.com/ajavageek/grpc-apisix/blob/master/model/src/main/proto/model.proto).

You can get your hands on the project and change the [API call](https://github.com/ajavageek/grpc-apisix/blob/master/commands/1.add-proto.sh) to YAML.

If you don't have time, I can do it.

**Comment by Neilblaze** [comment]
@nfrankel @navendu-pottekkat If there's any written doc or guide for the aforementioned I'd love to work on this. 😄

**Comment by Ajay-singh1** [comment]
I would love to work for this.

**Comment by navendu-pottekkat** [comment]
@Neilblaze You can use the proto shared above and translate it to standalone. You might have to do some testing to see if it works. You can also use the protos used in the gRPC examples used in the docs.

**Comment by Neilblaze** [comment]
will it be something like this? 😄 

```yaml
apisix:
    node_listen: "127.0.0.1:9080"
    http_admin:
        listen: "127.0.01:9180"
    ssl:
        enable: false

    proto:
        grpc:
            - name: model
            paths:
                - "/path/to/model.proto"
```

and for [this](https://github.com/ajavageek/grpc-apisix/blob/master/model/src/main/proto/model.proto) (in standalone) the proto would look like:

```proto
syntax = "proto3";

message HelloRequest {
    string name = 1;
}

message HelloResponse {
    string message = 1;
}
```



cc: @nfrankel, @navendu-pottekkat
