### ISSUE TITLE
help request: Readiness probe failed: dial tcp xxxx:80: i/o timeout

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix#9143]
### Description

I found that after running for a while there is an unhealthy situation, tcp socket response time exceeds 1s, Readiness probe failed: dial tcp xxxx:80: i/o timeout, I have enabled the global prometheus plugin, could it be related to this.And there is also an io timeout for the service request gateway response during this time.
readinessProbe is the default configuration
```yaml
        readinessProbe:
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
```
Looking at the events of other apisix pods, the problem has been experienced at various times.
### Environment

- APISIX version (run `apisix version`):2.13.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
