### ISSUE TITLE
request help: We may need to add support for specifies a non-default path of conf/apisix.yaml file at startup when using standalone mode in k8s

### ISSUE THREAD

**Issue by totemofwolf** [apache/apisix#919]
### Issue description

Does apisix support specifies a non-default path of conf/apisix.yaml file at startup?
I see that Stand-alone mode is for k8s (https://github.com/apache/incubator-apisix/blob/master/doc/stand-alone-cn.md), but k8s pods's configuration file will not change since you `modify its content ngx-gw-x.nsa.work.conf.yaml and do kubectl apply ngx-gw-x.nsa.work.conf.yaml` when using `configmap with subpath mount option` like this:
```
  volumeMounts:
    - mountPath: /etc/nginx/conf.d/x.nsa.work.conf
      name: exp-configmap
      subPath: x.nsa.work.conf

volumes:
- configMap:
    name: ngx-gw-x.nsa.work.conf
  name: exp-configmap
```
What is even more incredible in k8s is that if you do not `mount configmap with subpath option`, the dest directory `conf/` in pod will be cleared except for the apisix.yaml file only.
