### ISSUE TITLE
forward-auth support setting custom response status_code

### ISSUE THREAD

**Issue by caibirdme** [apache/apisix#9257]
### Description

forward-auth plugin checks the status_code responded from external service, if it's not 2xx, it aborts the request and return the body and the status_code to the client. But there're two cases that cannot be 
 well handled by forward-auth:
1. the external auth service returns **200** + `{"status": -1001, "msg":"invalid token"}`
2. the external auth service returns **4xx** + `{"status": -1001, "msg":"invalid token"}`, but the api calling convention between client and service requires that the api will always return **200** + json

To fully solve this problems, we need support custom judgement logic, something like:
```yaml
only_2xx: true  # only 2xx status code can be considered as true
check_json_body: "$.foo.bar.status != -1001" 
success_status_code: 200 # no matter what apisix receives from auth service, return 200 to client if passed the checking
fail_status_code: 200 # ... 
```

Supporting check_json_body expression is a little bit complicated, especially for deeply nested json and multiple conditions such as `a and (b or c) and d`.
Maybe support only_2xx + success_status_code + fail_status_code is more feasible.
