### ISSUE TITLE
failed SSL handshake 

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9262]
### Description

When I enabled https for health check, I configured the ssl_trusted_certificate configuration, but it did not work。

the apisix config is :
![图片](https://user-images.githubusercontent.com/62246176/230587709-6cc9b35f-9f56-40d3-9110-bf661010d67a.png)
the error log is:
![图片](https://user-images.githubusercontent.com/62246176/230587781-c52b3735-ce75-408e-b40f-1e0db5d41d1d.png)

**Comment by kingluo** [comment]
Do you happen to use TLSv1.3 only on the upstream server?

By default, cosocket does not use TLSv1.3, you need to configure it explicitly:

`config.yaml`

```yaml
nginx_config:
  http_configuration_snippet: |
    lua_ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
```
