### ISSUE TITLE
interval between health checks is incorrect

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#9327]
### Description

Below is the configuration I set up for the health check：
![image](https://user-images.githubusercontent.com/131146587/232730900-7cfe3296-7bff-4fc5-853d-867a11bb2412.png)

My interface returns code is 200, normally. First, it should access the interface five times, at intervals of 10 seconds, and then start accessing an unhealthy configuration once, at intervals of 15 seconds. However, my log prints are obviously inconsistent. What's wrong with that
![image](https://user-images.githubusercontent.com/131146587/232731607-36557e79-4fbb-400f-9d1d-a5c8fd6090cf.png)

### Environment

- APISIX version (run `apisix :2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by bin-53** [comment]
![image](https://user-images.githubusercontent.com/131146587/232732226-e2eba5b1-4973-4438-bb57-0c89ce37a471.png)

**Comment by tao12345666333** [comment]
@monkeyDluffy6017 PTAL, thanks

**Comment by tao12345666333** [comment]
Does your application interface contain other logic?

**Comment by bin-53** [comment]
> 

![image](https://user-images.githubusercontent.com/131146587/232947713-7e89f4ca-408b-4ad2-89e6-bb3368d3e9b7.png)
No, the interface is pretty simple

**Comment by kingluo** [comment]
How many nodes are in the upstream?

**Comment by bin-53** [comment]
> How many nodes are in the upstream?
two
![image](https://user-images.githubusercontent.com/131146587/232952737-8f3ef360-cad2-4c64-984d-731ee3005a2d.png)

**Comment by kingluo** [comment]
Are all nodes healthy actually? And how about the CPU load of APISIX?

Note that, the health check upon the nodes is executed serially:

https://github.com/api7/lua-resty-healthcheck/blob/0aa2cbdfae47c750552909762bf20d999e536e41/lib/resty/healthcheck.lua#L952-L961

**Comment by bin-53** [comment]
> 
all nodes healthy ，apisix is new and working well，wait,"the health check upon the nodes is executed serially" refers to the interval for all nodes,not just one node? For example, if I configure three upstream nodes, The interval of active health check is 10 seconds, which means that the request is sent to detect a node every 10 seconds, right? It does not detect every node every 10 seconds, right?

**Comment by bin-53** [comment]
> Are all nodes healthy actually? And how about the CPU load of APISIX?
> 
> Note that, the health check upon the nodes is executed serially:
> 
> https://github.com/api7/lua-resty-healthcheck/blob/0aa2cbdfae47c750552909762bf20d999e536e41/lib/resty/healthcheck.lua#L952-L961

The strangest thing is that The Times and intervals are so different from the configuration
![image](https://user-images.githubusercontent.com/131146587/232974753-796de83e-fc53-42fa-b5cc-4884005e9139.png)
![image](https://user-images.githubusercontent.com/131146587/232974784-42b41d40-aaaa-4db4-8d96-cbd92a8d506f.png)

![image](https://user-images.githubusercontent.com/131146587/232974581-116266f1-6635-4bb6-964b-40c2c40a4958.png)

**Comment by kingluo** [comment]
> > 
> 
> all nodes healthy ，apisix is new and working well，wait,"the health check upon the nodes is executed serially" refers to the interval for all nodes,not just one node? For example, if I configure three upstream nodes, The interval of active health check is 10 seconds, which means that the request is sent to detect a node every 10 seconds, right? It does not detect every node every 10 seconds, right?

If you set 10 secs, then the flow is like:

sleep 10 secs --> check node1 --> check node2 --> check node3 --> sleep 10 secs --> ...

**Comment by kingluo** [comment]
However, unhealthy and healthy checkers are running in parallel.

**Comment by kingluo** [comment]
> The strangest thing is that The Times and intervals are so different from the configuration

Yes, it's strange. Maybe I will try to reproduce it later.

**Comment by bin-53** [comment]
> reprod

OKey，Wait for your reply,tks

**Comment by bin-53** [comment]
> > The strangest thing is that The Times and intervals are so different from the configuration
> 
> Yes, it's strange. Maybe I will try to reproduce it later.

hello，Is there any progress？

**Comment by kingluo** [comment]
@Sn0rt Please take this issue.

**Comment by Sn0rt** [comment]
@bin-53 can you attache the error.log ?

which file can found from apisix logs directory.

**Comment by Sn0rt** [comment]
> > @bin-53 can you attache the error.log ?
> > which file can found from apisix logs directory.
> > The more certain thing is that this implementation does have the [problem](https://github.com/Kong/lua-resty-healthcheck/pull/57/files) of inaccurate interval.
> 
> Thank your reply~ There is no error log output in this health interval check, and neither is my access log. Excuse me, which configuration do I need to modify? I can output a detailed error log or access log during the health check,thanks

can you try this config ?

```diff
diff --git a/conf/config-default.yaml b/conf/config-default.yaml
index 4f97adc4..f2796416 100755
--- a/conf/config-default.yaml
+++ b/conf/config-default.yaml
@@ -136,7 +136,7 @@ nginx_config:                     # config for render the template to generate n
                                   # the "user" directive makes sense only if the master process runs with super-user privileges.
                                   # if you're not root user,the default is current user.
   error_log: logs/error.log
-  error_log_level:  warn          # warn,error
+  error_log_level:  info          # warn,error
   worker_processes: auto          # if you want use multiple cores in container, you can inject the number of cpu as environment variable "APISIX_WORKER_PROCESSES"
   enable_cpu_affinity: false      # disable CPU affinity by default, if APISIX is deployed on a physical machine, it can be enabled and work well.
   worker_rlimit_nofile: 20480     # the number of files a worker process can open, should be larger than worker_connections
diff --git a/conf/debug.yaml b/conf/debug.yaml
index 23c8d51a..268d744c 100644
--- a/conf/debug.yaml
+++ b/conf/debug.yaml
@@ -15,7 +15,7 @@
 # limitations under the License.
 #
 basic:
-  enable: false
+  enable: true
 http_filter:
   enable: false         # enable or disable this feature
   enable_header_name: X-APISIX-Dynamic-Debug # the header name of dynamic enable
```

**Comment by bin-53** [comment]
> 

Ok, I'll try it right away

**Comment by bin-53** [comment]
> > > @bin-53 can you attache the error.log ?
> > > which file can found from apisix logs directory.
> > > The more certain thing is that this implementation does have the [problem](https://github.com/Kong/lua-resty-healthcheck/pull/57/files) of inaccurate interval.
> > 
> > 
> > Thank your reply~ There is no error log output in this health interval check, and neither is my access log. Excuse me, which configuration do I need to modify? I can output a detailed error log or access log during the health check,thanks
> 
> can you try this config ?
> 
> ```diff
> diff --git a/conf/config-default.yaml b/conf/config-default.yaml
> index 4f97adc4..f2796416 100755
> --- a/conf/config-default.yaml
> +++ b/conf/config-default.yaml
> @@ -136,7 +136,7 @@ nginx_config:                     # config for render the template to generate n
>                                    # the "user" directive makes sense only if the master process runs with super-user privileges.
>                                    # if you're not root user,the default is current user.
>    error_log: logs/error.log
> -  error_log_level:  warn          # warn,error
> +  error_log_level:  info          # warn,error
>    worker_processes: auto          # if you want use multiple cores in container, you can inject the number of cpu as environment variable "APISIX_WORKER_PROCESSES"
>    enable_cpu_affinity: false      # disable CPU affinity by default, if APISIX is deployed on a physical machine, it can be enabled and work well.
>    worker_rlimit_nofile: 20480     # the number of files a worker process can open, should be larger than worker_connections
> diff --git a/conf/debug.yaml b/conf/debug.yaml
> index 23c8d51a..268d744c 100644
> --- a/conf/debug.yaml
> +++ b/conf/debug.yaml
> @@ -15,7 +15,7 @@
>  # limitations under the License.
>  #
>  basic:
> -  enable: false
> +  enable: true
>  http_filter:
>    enable: false         # enable or disable this feature
>    enable_header_name: X-APISIX-Dynamic-Debug # the header name of dynamic enable
> ```
> 
> and to reproduce this issues .
Hello, I have modified the configuration file, but there is no log output available during the health check
![image](https://user-images.githubusercontent.com/131146587/233526977-4b9c5416-bd69-4325-8cda-7b534bc43f1d.png)
![image](https://user-images.githubusercontent.com/131146587/233526997-c27a8695-a180-48c1-a905-e2f275b90877.png)
```
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false
  ssl:
    enable: true
    enable_http2: true
    ssl_trusted_certificate: /usr/local/apisix/conf/cert/apisix.ca-bundle

  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin                 # admin: manage all configuration data
                                  # viewer: only can view configuration data
    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a2
      role: viewer
  
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://etcd:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds

      
nginx_config:                     # config for render the template to generate nginx.conf
  error_log: logs/error.log
  error_log_level:  info   
  worker_processes: 1          # if you want use multiple cores in container, you can inject the number of cpu as environment variable "APISIX_WORKER_PROCESSES"
  stream:
    lua_shared_dict:
      internal-status: 10m
      plugin-limit-req: 10m
      plugin-limit-count: 10m
      prometheus-metrics: 10m
      plugin-limit-conn: 10m
      upstream-healthcheck: 10m
      worker-events: 10m
      lrucache-lock: 100m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      plugin-limit-count-redis-cluster-slot-lock: 100m
      tracing_buffer: 10m
      plugin-api-breaker: 10m
      etcd-cluster-health-check: 10m
      discovery: 1m
      jwks: 1m
      introspection: 10m
      access-tokens: 1m
      ext-plugin: 1m
      tars: 1m
      cas-auth: 10m
#  http:
#    enable_access_log: true         # enable access log or not, default true
#    access_log: logs/access.log
#    access_log_format:     '$remote_addr - [$remote_addr] - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time  $upstream_addr $upstream_response_length $upstream_response_time $upstream_status  $host [$http_client_v] [$http_device_id] [$http_utm_source] [$http_platform_brand] [$scheme] '
    
plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

```
