### ISSUE TITLE
QPS too low!!!

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#9343]
### Description

I used wrk2 for performance tests, but the results were confusing,Is there any problem with the configuration?（centos7 4c32g）
I'll test directly upstream ,the result is :
![image](https://user-images.githubusercontent.com/39228009/233247515-d6691634-f852-45ce-946f-6e1b593a2148.png)

use apisix proxy ,the result is ：
![image](https://user-images.githubusercontent.com/39228009/233247687-c5ae5d7a-81f4-443c-8374-1ad09f178ba9.png)

this my config.yaml:
![image](https://user-images.githubusercontent.com/39228009/233247757-cede92a7-e4ef-4691-bfca-d1b3107b7a49.png)

this is my route config:
```
{
    "uri": "/ces/*",
    "name": "ces11",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS",
        "CONNECT",
        "TRACE"
    ],
    "upstream": {
        "nodes": [
            {
                "host": "10.4.16.12",
                "port": 8180,
                "weight": 1
            }
        ],
        "retries": 4,
        "timeout": {
            "connect": 10,
            "send": 10,
            "read": 10
        },
        "type": "roundrobin",
        "scheme": "http",
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        },
        "retry_timeout": 4
    },
    "status": 1
}
```

### Environment

- APISIX version (run `apisix 2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hansedong** [comment]
I think you can provide more information, such as what your Nginx configuration is?

**Comment by githubxubin** [comment]
> 
Here is my apisix_conf configuration. I didn't add anything else. Am I missing something
----
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false
  ssl:
    enable: true
    enable_http2: true
    listen_port: 9443
    ssl_trusted_certificate: /usr/local/apisix/conf/cert/apisix.ca-bundle


  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin                 # admin: manage all configuration data
                                  # viewer: only can view configuration data
    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a2
      role: viewer
  
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://etcd:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds

      
nginx_config:                     # config for render the template to generate nginx.conf
  error_log: logs/error.log
  error_log_level:  warn   
  worker_processes: auto          # if you want use multiple cores in container, you can inject the number of cpu as environment variable "APISIX_WORKER_PROCESSES".
  http:
    lua_shared_dict:
      internal-status: 10m
      plugin-limit-req: 10m
      plugin-limit-count: 10m
      prometheus-metrics: 10m
      plugin-limit-conn: 10m
      upstream-healthcheck: 10m
      worker-events: 10m
      lrucache-lock: 100m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      plugin-limit-count-redis-cluster-slot-lock: 100m
      tracing_buffer: 10m
      plugin-api-breaker: 10m
      etcd-cluster-health-check: 10m
      discovery: 1m
      jwks: 1m
      introspection: 10m
      access-tokens: 1m
      ext-plugin: 1m
      tars: 1m
      cas-auth: 10m
  http_configuration_snippet: |
    lua_ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;


plugins:
    # the plugins you enabled
    - log-rotate
    - jwt-auth
    - ip-restriction
    - jwt-auth
    - kafka-logger
    - key-auth
    - limit-conn
    - public-api
    - limit-count
    - limit-req
    - basic-auth
    - cors
    - proxy-cache
    - proxy-mirror
    - proxy-rewrite
    - redirect
    - referer-restriction
    - request-id
    - request-validation
    - response-rewrite   

plugin_attr:
    log-rotate:
        interval: 360000   # rotate interval (unit: second)
        max_kept: 168     # max number of log files will be kept
        enable_compression: true    # enable log file compression(gzip) or not, default false

**Comment by githubxubin** [comment]
> I think you can provide more information, such as what your Nginx configuration is?

Here is my apisix_conf configuration. I didn't add anything else. Am I missing something
```
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false
  ssl:
    enable: true
    enable_http2: true
    listen_port: 9443
    ssl_trusted_certificate: /usr/local/apisix/conf/cert/apisix.ca-bundle


  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin                 # admin: manage all configuration data
                                  # viewer: only can view configuration data
    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a2
      role: viewer
  
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://etcd:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds

      
nginx_config:                     # config for render the template to generate nginx.conf
  error_log: logs/error.log
  error_log_level:  warn   
  worker_processes: auto          # if you want use multiple cores in container, you can inject the number of cpu as environment variable "APISIX_WORKER_PROCESSES".
  http:
    lua_shared_dict:
      internal-status: 10m
      plugin-limit-req: 10m
      plugin-limit-count: 10m
      prometheus-metrics: 10m
      plugin-limit-conn: 10m
      upstream-healthcheck: 10m
      worker-events: 10m
      lrucache-lock: 100m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      plugin-limit-count-redis-cluster-slot-lock: 100m
      tracing_buffer: 10m
      plugin-api-breaker: 10m
      etcd-cluster-health-check: 10m
      discovery: 1m
      jwks: 1m
      introspection: 10m
      access-tokens: 1m
      ext-plugin: 1m
      tars: 1m
      cas-auth: 10m
  http_configuration_snippet: |
    lua_ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;


plugins:
    # the plugins you enabled
    - log-rotate
    - jwt-auth
    - ip-restriction
    - jwt-auth
    - kafka-logger
    - key-auth
    - limit-conn
    - public-api
    - limit-count
    - limit-req
    - basic-auth
    - cors
    - proxy-cache
    - proxy-mirror
    - proxy-rewrite
    - redirect
    - referer-restriction
    - request-id
    - request-validation
    - response-rewrite   

plugin_attr:
    log-rotate:
        interval: 360000   # rotate interval (unit: second)
        max_kept: 168     # max number of log files will be kept
        enable_compression: true    # enable log file compression(gzip) or not, default false
```
