### ISSUE TITLE
help request: apisix.yaml can not save

### ISSUE THREAD

**Issue by addhww** [apache/apisix#9368]
### Description

I run apisix with below command,
`docker run -d --name apache-apisix -p 9080:9080 -p 9180:9180 -e APISIX_STAND_ALONE=true apache/apisix:3.2.0-centos`
edit the /usr/local/apisix/conf/apisix.yaml file
```
routes:
  -
    id: httpbin
    uri: /*
    upstream:
      nodes:
        "httpbin.org": 1
      type: roundrobin
    plugin_config_id: 1

plugin_configs:
  -
    id: 1
    plugins:
      response-rewrite:
        body: "Hello APISIX\n"
    desc: "response-rewrite"
#END
```
I send request to http://127.0.0.1:9080/ and the response is right.
But after I restart the container with below command
`docker restart apache-apisix`
the request http://127.0.0.1:9080/ get "404 Route Not Found", and the apisix.yaml has no routes

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
