### ISSUE TITLE
Development environment for mac

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9408]
### Description

I set up the apisix development environment locally to develop the plug-in, but I failed to mount the directory. The following error message is displayed：
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/usr/local/NetAuth_APIG/dashboard_conf/conf.yaml" to rootfs at "/usr/local/apisix-dashboard/conf/conf.yaml": mount /usr/local/NetAuth_APIG/dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml (via /proc/self/fd/9), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
I have all the correct paths, I have all worked properly under centos7,

But right now my system is macos
![image](https://user-images.githubusercontent.com/62246176/236371636-75f8310f-89dd-40ed-8123-748572567959.png)

Also, I use a personal user on the mac, because root can't use brew to install docker

### Environment

- APISIX version (run `apisix version`):2.15-alpine
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by thor533** [comment]
This is the mount

```
services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.13-alpine
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      apisix:
```
