### ISSUE TITLE
help request: discovery nacos support https?

### ISSUE THREAD

**Issue by laizuan** [apache/apisix#9439]
### Description

```txt
2023/05/09 03:52:22 [error] 49#49: *10 [lua] init.lua:269: get_token_param error:20: unable to get local issuer certificate, context: ngx.timer
2023/05/09 03:52:51 [error] 49#49: *2042 [lua] init.lua:124: get_token_param(): nacos login fail:dev password desc:20: unable to get local issuer certificate, context: ngx.timer
```

the above error occurs when using it

```yaml
discovery:
  nacos:
    host:
      - "https://dev:password@xxx.xxxxx.com"
    prefix: "/nacos/v1/"
    fetch_interval: 30    # default 30 sec
    weight: 100           # default 100
    timeout:
      connect: 2000       # default 2000 ms
      send: 2000          # default 2000 ms
      read: 3000          # default 5000 ms
```
this configuration works correctly

```yaml
discovery:
  nacos:
    host:
      - "http://dev:password@xxx.xxxxx.com:8848"
    prefix: "/nacos/v1/"
    fetch_interval: 30    # default 30 sec
    weight: 100           # default 100
    timeout:
      connect: 2000       # default 2000 ms
      send: 2000          # default 2000 ms
      read: 3000          # default 5000 ms
```

### Environment

- APISIX version (run `apisix version`):
3.2.0-debian
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by laizuan** [comment]
https://apisix.apache.org/zh/docs/apisix/FAQ/#%E6%88%91%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3-unable-to-get-local-issuer-certificate-%E8%BF%99%E4%B8%AA%E9%94%99%E8%AF%AF

I think this will help me

**Comment by karl-chanel** [comment]
你好问下你的nacos的https是自签证书还是用的lets encrypt?

**Comment by laizuan** [comment]
@karl-chanel hi，非自签，腾讯云里面的免费证书

**Comment by karl-chanel** [comment]
那你的问题解决了吗？你是把ca证书通过上面的方式设置进去了吗？

**Comment by laizuan** [comment]
@karl-chanel 抱歉，我只是看了文档但我没有尝试。现在使用的是http协议，因为现在还在开发阶段

**Comment by karl-chanel** [comment]
好的，再问一下，在浏览器里通过https访问你的nacos时，浏览器会报证书不安全的提示吗

**Comment by karl-chanel** [comment]
就是说腾讯云提供的免费证书是不是也像lets encrypt一样是被系统信任的

**Comment by laizuan** [comment]
不会一切正常，也是通过apisix代理转发。只不过我通过控制台上传证书无效。我最后使用配置nginx来实现

```yml
apisix:
  node_listen: 
    - 1443
  ssl:
    enable: false
    listen:
      - port: 443
  enable_ipv6: false
  enable_server_tokens: false
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092
nginx_config:
    http_server_configuration_snippet: |
            listen 443 ssl;
            ssl_certificate /usr/local/apisix/static/ssl.crt;
            ssl_certificate_key  /usr/local/apisix/static/ssl.key;
            ssl_session_timeout 5m;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
            ssl_prefer_server_ciphers on;
```


这个问题我提了issues #9397
