### ISSUE TITLE
help request: Error: "failed to find any SSL certificate by SNI" when in dashboard SNI exists

### ISSUE THREAD

**Issue by MirtoBusico** [apache/apisix#9518]
### Description

I have a route, upstream and SNI for the host "www.h.net"
But when I try to access the URL I receive an error and looking at the logs the last lines are:
```
127.0.0.6 - - [20/May/2023:15:57:56 +0000] apisix-admin.apisix.svc.cluster.local:9180 "GET /apisix/admin/upstreams/6d394703 HTTP/1.1" 404 39 0.002 "-" "Go-http-client/1.1" - - - "http://apisix-admin.apisix.svc.cluster.local:9180"
127.0.0.6 - - [20/May/2023:15:57:56 +0000] apisix-admin.apisix.svc.cluster.local:9180 "GET /apisix/admin/upstreams/93400b20 HTTP/1.1" 404 39 0.002 "-" "Go-http-client/1.1" - - - "http://apisix-admin.apisix.svc.cluster.local:9180"
127.0.0.6 - - [20/May/2023:15:57:56 +0000] apisix-admin.apisix.svc.cluster.local:9180 "GET /apisix/admin/upstreams/3b59d238 HTTP/1.1" 404 39 0.001 "-" "Go-http-client/1.1" - - - "http://apisix-admin.apisix.svc.cluster.local:9180"
127.0.0.6 - - [20/May/2023:16:17:53 +0000] 192.168.151.10 "GET / HTTP/1.1" 404 47 0.000 "-" "curl/7.88.1" - - - "http://192.168.151.10"
2023/05/20 16:28:28 [error] 50#50: *325034 [lua] radixtree_sni.lua:176: match_and_set(): failed to find any SSL certificate by SNI: www.h.net, context: ssl_certificate_by_lua*, client: 127.0.0.6, server: 0.0.0.0:9443
2023/05/20 16:28:28 [error] 53#53: *325036 [lua] radixtree_sni.lua:176: match_and_set(): failed to find any SSL certificate by SNI: www.h.net, context: ssl_certificate_by_lua*, client: 127.0.0.6, server: 0.0.0.0:9443
``` 

What I'm doing wrong?

The route definition is:
```
{
  "uri": "/*",
  "name": "www",
  "desc": "www.h.net primary route",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "www.h.net",
  "plugins": {
    "redirect": {
      "http_to_https": true
    }
  },
  "upstream_id": "461493987803398719",
  "status": 1
}
```

The upstream definition is:
```
{
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "scheme": "http",
  "discovery_type": "dns",
  "pass_host": "pass",
  "name": "productpage",
  "service_name": "productpage.bookinfo.svc.cluster.local:9080",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}
```

The SNI (copied from the Apisix-dashboard) is:
```
SNI                                             Expiration Time         Update Time             Operation
www www.h.net www.ext.h.net www.int.h.net       2032-11-23 13:08:26     2023-05-20 19:25:44
```

Apisix was installed with chart:

```
sysop@hdev:~/H/software/apisisx$ helm show chart apisix/apisix
annotations:
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 3.3.0
dependencies:
- condition: etcd.enabled
  name: etcd
  repository: https://charts.bitnami.com/bitnami
  version: 8.7.7
- alias: dashboard
  condition: dashboard.enabled
  name: apisix-dashboard
  repository: https://charts.apiseven.com
  version: 0.8.0
- alias: ingress-controller
  condition: ingress-controller.enabled
  name: apisix-ingress-controller
  repository: https://charts.apiseven.com
  version: 0.11.4
description: A Helm chart for Apache APISIX v3
icon: https://apache.org/logos/res/apisix/apisix.png
maintainers:
- name: tao12345666333
name: apisix
sources:
- https://github.com/apache/apisix-helm-chart
type: application
version: 1.4.0
```
Dashboard version is 3.0.0

BTW in the previous installation (the one reported in this [blog post](https://apisix.apache.org/blog/2023/01/02/accessing_apisix-dashboard_from_everywhere_with_keycloak_authentication/)) it worked 

Then the apisix chart was
```
sysop@hdev:~/H/software/apisisx$ helm show chart apisix/apisix
annotations:
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 2.15.1
dependencies:
- condition: etcd.enabled
  name: etcd
  repository: https://charts.bitnami.com/bitnami
  version: 8.3.4
- alias: dashboard
  condition: dashboard.enabled
  name: apisix-dashboard
  repository: https://charts.apiseven.com
  version: 0.6.1
- alias: ingress-controller
  condition: ingress-controller.enabled
  name: apisix-ingress-controller
  repository: https://charts.apiseven.com
  version: 0.10.1
description: A Helm chart for Apache APISIX
icon: https://apache.org/logos/res/apisix/apisix.png
maintainers:
- name: tao12345666333
name: apisix
sources:
- https://github.com/apache/apisix-helm-chart
type: application
version: 0.11.3
``` 
Dashboard version was 2.13.0

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`):  `Linux apisix-694d5589cc-l2948 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux`
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
