### ISSUE TITLE
feat: Support consul acl access control when discovering with consul or consul_kv

### ISSUE THREAD

**Issue by hulining** [apache/apisix#9532]
### Description

When using consul and consul_kv as service discovery, it is hoped to support the incoming token to enable consul acl.

An example configuration file is as follows:

```yaml
# for consul
discovery:
  consul:
    servers:
      - "http://127.0.0.1:8500"
      - "http://127.0.0.1:8600"
    token: "consul-access-token"  # add consul acl token config
    skip_services:
      - "service_a"
#...
```

```yaml
# for consul_kv
discovery:
  consul_kv:
    servers:
      - "http://127.0.0.1:8500"
      - "http://127.0.0.1:8600"
    token: "consul-access-token"  # add consul acl token config
    prefix: "upstreams"
    skip_keys:
      - "upstreams/unused_api/"
#...
```

There is a discussion about consul acl in a similar issue #6692.

Official document of consul [acl](https://www.consul.io/docs/security/acl). And [lua-resty-consul](https://github.com/hamishforbes/lua-resty-consul) supports consul acl access control.

If the evaluation is feasible, please help to support it, thanks a lot~~
