### ISSUE TITLE
bug: "File-Logger and Log-Rotate Integration: Logging Issue with Renamed Files"

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix#9536]
I used the file-logger plugin to output logs to the local file `logs/access.log`. Additionally, I utilized the log-rotate plugin to rotate the file when it exceeded 1MB in size. However, I encountered an issue where after log-rotate renamed `access.log` to `2023-05-25_17-49-08__access.log`, the file-logger plugin continued appending new logs to `2023-05-25_17-49-08__access.log` instead of writing them to the `access.log` file.

**Comment by shreemaan-abhishek** [comment]
@jinjianming please share your configurations.

**Comment by shreemaan-abhishek** [comment]
I tried to replicate this bug, but unlike the OP said, once the log has been rotated the new logs get appended correctly into access.log.

**Comment by moonming** [comment]
@lingsamuel is this a bug?
@jinjianming Can you provide reproduction steps?

**Comment by jinjianming** [comment]
@lingsamuel @moonming  @shreemaan-abhishek Sorry for the issue with my initial description, it can be reproduce through this configuration;
`image is：apache/apisix:3.2.0-debian`
```
pluginAttrs:
    log-rotate:
        interval: 30    # rotate interval (unit: second)
        max_kept: 2     # max number of log files will be kept
        max_size: -1      # max size of log files will be kept
        enable_compression: false    # enable log file compression(gzip) or not, default false
```

Both log files will have new logs flowing in without generating a new access.log
![image](https://github.com/apache/apisix/assets/57084209/5ead12a8-4402-4b7e-8ee1-adf7dad6de1a)

Is it related to the container outputting logs to the terminal/dev/sdout ？

**Comment by jinjianming** [comment]
```yaml# access log and error log configuration
logs:
  # -- Enable access log or not, default true
  enableAccessLog: false
  # -- Access log path
  accessLog: "/dev/stdout"
  # -- Access log format
  accessLogFormat: '$remote_addr - $remote_user [$time_local] $http_host \"$request\" $status $body_bytes_sent $request_time \"$http_referer\" \"$http_user_agent\" $upstream_addr $upstream_status $upstream_response_time \"$
upstream_scheme://$upstream_host$upstream_uri\"'
  # -- Allows setting json or default characters escaping in variables
  accessLogFormatEscape: default
  # -- Error log path
  errorLog: "/dev/stderr"
  # -- Error log level
  errorLogLevel: "warn"
```
