### ISSUE TITLE
request help: etcd tls connect handshake failed #5650

### ISSUE THREAD

**Issue by kamly** [apache/apisix#9557]
## 日志

```
2023/05/26 23:58:41 [error] 140#140: *857 [lua] config_etcd.lua:628: no healthy etcd endpoint available, next retry after 16s, context: ngx.timer
2023/05/26 23:58:41 [error] 76#76: *455 [lua] config_etcd.lua:628: no healthy etcd endpoint available, next retry after 16s, context: ngx.timer
```

## 配置

```
 apisix:
      ssl:
        enable: true
        listen:
          - port: 9443
            enable_http2: true
        ssl_protocols: "TLSv1.2 TLSv1.3"
        ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA"
        ssl_trusted_certificate: "/usr/local/apisix/conf/ssl/ssl-cacert"

        etcd:
          host:                          # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
            - "https://9.100.99.130:2379"             # multiple etcd address
          prefix: "/wj-gateway-canary"    # configuration prefix in etcd
          timeout: 30    # 30 seconds
          tls:
            cert: "/etcd-ssl/etcd-cert"
            key: "/etcd-ssl/etcd-key"
            verify: true
            sni: "9.100.99.130"
```

查了 etcd 的证书，没有找到 sni 相关配置，所以 sni 写了 IP

请问我应该怎样处理？

## 类似问题

https://github.com/apache/apisix/issues/5650
https://github.com/apache/apisix/issues/5155

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`): Linux gateway 5.4.119-1-tlinux4-0008 #1 SMP Fri Nov 26 11:17:45 CST 2021 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
built with OpenSSL 1.1.1s  1 Nov 2022
TLS SNI support enabled
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"etcd_version":"unknown","version":"3.2.0","hostname":"gateway","id":"14df74a4-9777-4814-8cd0-a255c9df1f06","boot_time":1685145505}
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
