### ISSUE TITLE
help request: How to configure https for external domain upstream 

### ISSUE THREAD

**Issue by anilaws** [apache/apisix#9564]
### Description

I am trying to configure https scheme for external domain upstream following the doc https://apisix.apache.org/docs/ingress-controller/tutorials/external-service/ but the doc doesn't have an example for configuring https scheme

Below is the yaml file used 

```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
  - name: rule1
    match:
      paths:
      - /test*
    upstreams:
    - name: test-upstream          
---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: test-upstream
spec:
  externalNodes:
  - type: Domain
    name: test.domain.com
    port: 443
    scheme : https
```

getting error 
error validating data: ValidationError(ApisixUpstream.spec.externalNodes[0]): unknown field "scheme" in org.apache.apisix.v2.ApisixUpstream.spec.externalNodes; if you choose to ignore these errors, turn validation off with --validate=false

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): Linux apisix-67b9ff86c7-fnpsd 5.15.93-55.139.amzn2.x86_64 https://github.com/apache/apisix/pull/1 SMP Tue Feb 14 21:47:11 UTC 2023 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): "3.5.0
- APISIX Dashboard version, if relevant: 3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
