### ISSUE TITLE
bug: OpenTelemetry plug-in must be used with Collector?

### ISSUE THREAD

**Issue by Jamel-jun** [apache/apisix#9593]
### Current Behavior

Failed to integrate Aliyun sls trace.

### Expected Behavior

Correctly export trace to sls trace

### Steps to Reproduce

apisix_conf.yaml
```yaml
plugin_attr:
  opentelemetry:
    resource:
      service.name: APISIX
    collector:
      address: https://demo-project.log.aliyuncs.com/opentelemetry/v1/traces
      request_headers:
        x-sls-otel-project: demo-project
        x-sls-otel-instance-id: demo-sls
        x-sls-otel-ak-id: xxxx
        x-sls-otel-ak-secret: xxxx
plugins:
  - opentelemetry
```

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`): 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
