### ISSUE TITLE
enabled etcd https ， apisix 503 error

### ISSUE THREAD

**Issue by Michael754267513** [apache/apisix#9644]
### Current Behavior

config etcd http tls enabled。 
```
etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "https://10.11.44.129:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
      - "https://10.11.46.7:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
      - "https://10.11.44.3:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
                                    # e.g. https://127.0.0.1:2379.
    prefix: /apisix                 # configuration prefix in etcd
    use_grpc: false                # enable the experimental configuration sync via gRPC
    timeout: 7200                     # 30 seconds. Use a much higher timeout (like an hour) if the  is true.
    #resync_delay: 5                # when sync failed and a rest is needed, resync after the configured seconds plus 50% random jitter
    #health_check_timeout: 10       # etcd retry the unhealthy nodes after the configured seconds
    startup_retry: 1                # the number of retry to etcd during the startup, default to 2
    #user: root                     # root username for etcd
    #password: 5tHkHhYkjr6cQY       # root password for etcd
    tls:
      # To enable etcd client certificate you need to build APISIX-Base, see
      # https://apisix.apache.org/docs/apisix/FAQ#how-do-i-build-the-apisix-base-environment
      cert: /opt/apisix/ssl/etcd.pem          # path of certificate used by the etcd client
      key: /opt/apisix/ssl/etcd-key.pem            # path of key used by the etcd client
      verify: true                 # whether to verify the etcd endpoint certificate when setup a TLS connection to etcd,
                                    # the default value is true, e.g. the certificate will be verified strictly.
      #sni:                         # the SNI for etcd TLS requests. If missed, the host part of the URL will be used.```

```

```
[root@abc1 conf]# curl http://127.0.0.1:9180/apisix/admin/routes?api_key= 123456789 -i
HTTP/1.1 503 Service Temporarily Unavailable
Date: Mon, 12 Jun 2023 10:55:01 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/3.3.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600
X-API-VERSION: v3

{"error_msg":"invalid response code: 503"}
```

### Expected Behavior

```
curl http://127.0.0.1:9180/apisix/admin/routes?api_key=123456789 -i
```

### Error Logs

```
2023/06/12 18:56:25 [error] 9178#9178: *99612 [lua] conf_server.lua:99: access(): failure in conf server: failed to find valid upstream server: all upstream servers tried, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/06/12 18:56:25 [warn] 9178#9178: *99631 [lua] conf_server.lua:219: pick_node(): endpoint 1.1.1.1:2379 is unhealthy, skipped, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/06/12 18:56:25 [warn] 9178#9178: *99631 [lua] conf_server.lua:219: pick_node(): endpoint 1.1.1.2:2379 is unhealthy, skipped, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/06/12 18:56:25 [warn] 9178#9178: *99631 [lua] conf_server.lua:219: pick_node(): endpoint 1.1.1.3:2379 is unhealthy, skipped, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/06/12 18:56:25 [error] 9178#9178: *99631 [lua] conf_server.lua:99: access(): failure in conf server: failed to find valid upstream server: all upstream servers tried, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
```

### Steps to Reproduce

1. create etcd cluster with three node, enable tls
2. yum install apisix 
3. change apisix etcd config with tls
4. start apisix

### Environment

- APISIX version (run `apisix version`):  3.3.0
- Operating system (run `uname -a`):  5.4.153-1.el7.elrepo.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"etcd_version":"unknown","hostname":"abc1","id":"1970f9a5-cd5b-4a51-b739-e075a7b23a7f","version":"3.3.0","boot_time":1686567207}
- APISIX Dashboard version, if relevant: 3.0.0 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Please format your issue description using "```" (three tildes). And also add an issue title.

<img width="929" alt="image" src="https://github.com/apache/apisix/assets/61597896/f62047b2-dcf9-4b9e-9426-3a6fdbed5309">

<img width="647" alt="image" src="https://github.com/apache/apisix/assets/61597896/9f627d31-777a-4a8f-beb1-cba5ff8c36f2">

**Comment by Sn0rt** [comment]
@shreemaan-abhishek have your tried reproduced this issues ?

**Comment by shreemaan-abhishek** [comment]
@Sn0rt, no not yet. I didn't know when the user updated the issue description.

@Michael754267513, looks like the upstreams are not reachable did you make sure they are available? Also please share your route and other relevant configurations.

**Comment by shreemaan-abhishek** [comment]
@Michael754267513, @mosaicwang it worked for me:

setup etcd cluster with tls like so:

```yaml
version: "3.7"

services:
  etcd0:
    image: "gcr.io/etcd-development/etcd:v3.4.15"
    container_name: etcd0
    ports:
      - "23800:2380"
      - "23790:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd0
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:23790
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ENABLE_GRPC_GATEWAY=${ETCD_ENABLE_GRPC_GATEWAY:-true}
      - ETCD_CERT_FILE=/certs/etcd.pem
      - ETCD_KEY_FILE=/certs/etcd.key
    volumes:
      - ./t/certs:/certs

  etcd1:
    image: "gcr.io/etcd-development/etcd:v3.4.15"
    container_name: etcd1
    ports:
      - "23801:2380"
      - "23791:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:23791
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ENABLE_GRPC_GATEWAY=${ETCD_ENABLE_GRPC_GATEWAY:-true}
      - ETCD_CERT_FILE=/certs/etcd.pem
      - ETCD_KEY_FILE=/certs/etcd.key
    volumes:
      - ./t/certs:/certs

  etcd2:
    image: "gcr.io/etcd-development/etcd:v3.4.15"
    container_name: etcd2
    ports:
      - "23802:2380"
      - "23792:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:23792
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ENABLE_GRPC_GATEWAY=${ETCD_ENABLE_GRPC_GATEWAY:-true}
      - ETCD_CERT_FILE=/certs/etcd.pem
      - ETCD_KEY_FILE=/certs/etcd.key
    volumes:
      - ./t/certs:/certs
```

And I used the same config for Apisix just as you provided. Are you using decoupled mode?
