### ISSUE TITLE
help request: public-api can't be opened

### ISSUE THREAD

**Issue by GloryAndDream** [apache/apisix#9666]
### Description

HI, I tried to open plugin "public-api", and tried to run below yaml file in k8s:
```

apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: jwt-sign-api
  namespace: ingress-apisix
spec:
  http:
  - name: public-api
    match:
      hosts:
      - api.laiguaba.com
      paths:
      - /apisix/plugin/jwt/sign
    backends:
    - serviceName: apisix-admin
      servicePort: 9180
    plugins:
    - name: public-api
      enable: true

```

and got error:

```
2023-06-15T13:59:55+08:00	apisix/route.go:163	failed to create route: unexpected status code 400; error message: {"error_msg":"unknown plugin [public-api]"}

2023-06-15T13:59:55+08:00	apisix/apisix_route.go:513	sync ApisixRoute failed, will retry	{"object": {"Type":1,"Object":{"Key":"ingress-apisix/jwt-sign-api","OldObject":null,"GroupVersion":"apisix.apache.org/v2"},"OldObject":null,"Tombstone":null}, "error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"unknown plugin [public-api]\"}\n\n\n"}

```
it is very strange becasue I can see this plugin  in dashboard page, anyone knows how to resolve this？

![image](https://github.com/apache/apisix/assets/18462722/accb2d7b-1601-471f-bd94-57249df64170)

### Environment

- APISIX version (run `apisix version`): 3.1.1
-  APISIX Ingress version : 1.6.0
- Operating system (run `uname -a`): Alibaba cloud linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
