### ISSUE TITLE
bug: Empty spec object after applying ApisixUpstream with external service

### ISSUE THREAD

**Issue by monlor** [apache/apisix#9791]
### Current Behavior

I followed the steps outlined in the document [https://apisix.apache.org/en/docs/ingress-controller/tutorials/external-service/] to apply an ApisixUpstream containing an external service to my cluster. However, after applying it to the cluster, I noticed that the spec object is empty.

### Steps to Reproduce

```
k apply -f - <<-EOF
# httpbin-upstream.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: httpbin-upstream
spec:
  externalNodes:
  - type: Domain
    name: httpbin.org
EOF
```

### Environment

Deployment via apisix helm chart v2.0.0
- APISIX version: v3.3.0
- Operating system: docker v3.3.0-debain
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
