### ISSUE TITLE
help request: I use enable_compression in log-rotate plugin, but apisix did not delete the original access log 

### ISSUE THREAD

**Issue by iamacnhero** [apache/apisix#9819]
### Description

I configged in config.yml like this:

```
plugin_attr:
  log-rotate:
      interval: 86400             # rotate interval (unit: second)
      max_kept: 30                # max number of log files will be kept
      max_size: -1                # max size of log files will be kept
      enable_compression: true    # enable log file compression(gzip) or not, default false
```

but the original log does not deleted:

<img width="707" alt="image" src="https://github.com/apache/apisix/assets/775369/ca7a9beb-7408-4ddd-88c3-a42d6cf9d2cb">

why? how should I fix this ?

### Environment

- APISIX version: 3.0.0
- Operating system: Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 GNU/Linux
- OpenResty / Nginx version: openresty/1.21.4.1
- etcd version: 3.5.9
- Plugin runner version, for issues related to plugin runners: log-rotate
