### ISSUE TITLE
jwt-auth： 404 not found in Stand-alone mode

### ISSUE THREAD

**Issue by WwwJy** [apache/apisix#9821]
### Description

Hi Community

My Apisix service is started in Stand-alone mode
When I requested the  **/apisix/plugin/jwt/sign** interface to prepare to obtain a token, I received a result of 404 not found

I configured the content of auth and public-api on apisix.yaml according to the documents, but still obtained the same results

The guidance we are following include:
https://apisix.apache.org/docs/apisix/2.15/stand-alone/
https://apisix.apache.org/docs/apisix/2.15/plugins/public-api/
https://apisix.apache.org/zh/docs/apisix/2.15/plugins/jwt-auth/

Please refer to our operation step as Appendix.

The configuration of **apisix.yaml** is as follows
```
consumers:
- plugins:
    jwt-auth:
      key: user-key
      secret: my-secret-key
    public-api: {}
  uri: /apisix/plugin/jwt/sign
  username: jack
```

I noticed that there is very little description of apisix.yaml and there is no configuration template to refer to, which makes it difficult for me to determine if my configuration items are truly correct

Your feedback is really appreciated so much.

### Environment

- APISIX version (2.15.3):
- Operating system (Linux):
- OpenResty / Nginx version (openresty/1.21.4.1):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by WwwJy** [comment]
There was an error in my configuration. The plugin-api should be configured on the **route.** After I updated it, it should be like this
```
consumers:
- plugins:
    jwt-auth:
      key: user-key
      secret: my-secret-key
  username: jack
routes:
  plugins:
    public-api: {}
  uri: /apisix/plugin/jwt/sign
```
Now I have a new error
```log
[error]: failed to set upstream: missing upstream configuration in Route or Service
````

I don't understand why we need to configure upstream？
