### ISSUE TITLE
feat: As a user, I want to implement current limiting based on a specific key value in the request header. The source of the key value can be URL parameters, HTTP request headers

### ISSUE THREAD

**Issue by huangyutongs** [apache/apisix#9830]
### Description

The current current limit can only be based on the source ip, and there are few coverage scenarios.
If current limiting can be implemented based on specific key values, it will have more scalability.
such as Alibaba Cloud's higress
https://higress.io/zh-cn/docs/plugins/key-rate-limit

**Comment by Revolyssup** [comment]
@huangyutongs You can use limit-req plugin for rate limiting requests and use the variable field to specify the key. You can add a header as a key using a variable like `$http_name_of_the_header`

**Comment by huangyutongs** [comment]
> @huangyutongs You can use limit-req plugin for rate limiting requests and use the variable field to specify the key. You can add a header as a key using a variable like `$http_name_of_the_header` https://apisix.apache.org/docs/apisix/plugins/limit-req/#description

I want to do limit-req for the request header x-userid: test, how to do it,

**Comment by qwzhou89** [comment]
> I want to do limit-req for the request header `x-userid: test`, how to do it,

I think you can reference it with $http_x_userid

**Comment by huangyutongs** [comment]
> > I want to do limit-req for the request header `x-userid: test`, how to do it,
> 
> I think you can reference it with $http_x_userid

It seems that the content of the request header cannot be obtained
Here is my configuration
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: apisix-dashbord-route
spec:
  http:
  - backends:
    - serviceName: apisix-dashboard
      servicePort: 80
    match:
      hosts:
      - apisixui.baidu.cn
      paths:
      - /*
    name: apisix-dashbord-route
    plugins:
    - config:
        burst: 0
        key: $http_x_userid
        key_type: var_combination
        rate: 1
        rejected_code: 500
        rejected_msg: Requests are too frequent, please try again later.
      enable: true
      name: limit-req
```
Quickly make two requests
```
curl -I 192.168.110.186 -H "host: apisixui.baidu.cn"
HTTP/1.1 500 Internal Server Error
```
There is no x-userid: test in my request header, but it is limited
