### ISSUE TITLE
feat: Changing the apisix.yaml configuration for Standalone mode

### ISSUE THREAD

**Issue by dreek1337** [apache/apisix#9839]
### Description

When creating the apisix.yaml configuration in standalone mode, for upstreams I need to specify the host and port in node as a key, but yaml cannot pull env for keys, so I want to suggest that it would be better to specify host and port separately for node.

How it was.:
```
upstreams:
  - id: 1
    type: roundrobin
    nodes:
      ${{APISIX_USERS_MS_HOST}}:${{APISIX_USERS_MS_PORT}}: 1    <- This does not work
    retries: 2
```
How it will be:
```
upstreams:
  - id: 1
    type: roundrobin
    nodes:
      1:
        host: ${{APISIX_USERS_MS_HOST}}
        port: ${{APISIX_USERS_MS_PORT}}
    retries: 2
```
