### ISSUE TITLE
help request: After restarting, the Apisix routing configuration does not take effect

### ISSUE THREAD

**Issue by ShuLian1984** [apache/apisix#9847]
After restarting, the routing rules do not take effect on a properly running apixis container, and the routing configuration information is not lost. It can be obtained through the admin API and no error messages were found in the logs.

I Need to resubmit for each route rule to take effect

- APISIX version (run `apisix version`):  
```
apache/apisix:3.3.0
```

- Operating system (run `uname -a`): 
```
[dev@bigdata-304 bootlog]# printf "`uname -rs`\n`cat /etc/redhat-release`\n`cat /etc/os-release`\n"
Linux 3.10.0-1062.18.1.el7.x86_64
CentOS Linux release 7.7.1908 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
```
nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
built with OpenSSL 1.1.1s  1 Nov 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.8 -DNGX_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../apisix-nginx-module-1.12.0 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/stream --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/meta --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../wasm-nginx-module-0.6.4 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.kOo9UFlgbS/openresty-1.21.4.1/../grpc-client-nginx-module-v0.4.2 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
```
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
```
bitnami/etcd:3.5.9-2
```

- APISIX Dashboard version, if relevant:
```
apache/apisix-dashboard:3.0.1
```

**Comment by ShuLian1984** [comment]
docker-compose.yml
```
version: '2.4'
services:
  etcd:
    container_name: etcd
    image: bitnami/etcd:3.5.9-2
    restart: always
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    volumes:
      - "./data:/bitnami/etcd/data"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:
        ipv4_address: 172.64.0.2

  apisix:
    container_name: apisix
    image: apache/apisix:3.3.0
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix:/usr/local/apisix/apisix
      - ./logs:/usr/local/apisix/logs:rw
    ports:
      - "19180:9180/tcp" # admin api port
      - "19080:9080/tcp" # http port
      - "19091:9091/tcp" # Prometheus port
      - "19443:9443/tcp" # https port
      - "19092:9092/tcp" # control port
      - "19100-19120:9100-9120/tcp" # tcp port
    depends_on:
      - etcd
    networks:
      apisix:
        ipv4_address: 172.64.0.3

  apisix-dashboard:
    container_name: apisix-dashboard
    image: apache/apisix-dashboard:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/dashboard.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
      - ./config/schema.json:/usr/local/apisix-dashboard/conf/schema.json:ro
      - ./logs:/usr/local/apisix-dashboard/logs:rw
    ports:
      - "19000:9000/tcp" # Dashboard port
    depends_on:
      - etcd
      - apisix
    networks:
      apisix:
        ipv4_address: 172.64.0.4

# docker network create apisix_net --subnet 172.64.0.0/16 --gateway 172.64.0.1
networks:
  apisix:
    external:
      name: apisix_net
```
---
my config.yaml
```
apisix:
  node_listen: 9080
  enable_ipv6: false
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092
  stream_proxy:
    only: false
    tcp:
      - 9100
      - 9101
      - 9102
      - 9103
      - 9104
      - 9105
      - 9106
      - 9107
      - 9108
      - 9109
      - 9110
      - 9111
      - 9112
      - 9113
      - 9114
      - 9115
      - 9116
      - 9117
      - 9118
      - 9119
      - 9120
  # extra_lua_path: "/usr/local/apisix/apisix/ext_plugins/?.lua" 

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

    enable_admin_cors: true
    admin_listen:
      ip: 0.0.0.0
      port: 9180

  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

plugins:
- server-info
- skywalking
- skywalking-logger

plugin_attr:

  prometheus:
    export_uri: /apisix/metrics
    export_addr:
      ip: "0.0.0.0"
      port: 9091
  skywalking:
    service_name: dev::APISIX
    service_instance_name: 10.10.85.14
    endpoint_addr: http://10.10.85.14:12800

discovery:
  nacos:
    host:
      - "http://nacos:nacos@10.10.85.14:8848"
    prefix: "/nacos/v1/"
    fetch_interval: 30
    weight: 100
    timeout:
      connect: 2000
      send: 2000
      read: 5000
```
---
Route information obtained from the admin API

```
{
    "total": 5,
    "list": [
        {
            "createdIndex": 3,
            "modifiedIndex": 1973,
            "key": "/apisix/routes/"
        },
        {
            "createdIndex": 1470,
            "value": {
                "id": "468393803724620526",
                "uri": "/device-transport/mqtt/*",
                "upstream": {
                    "pass_host": "pass",
                    "scheme": "http",
                    "nodes": [
                        {
                            "host": "10.10.19.179",
                            "port": 9988,
                            "weight": 1
                        }
                    ],
                    "timeout": {
                        "send": 6,
                        "read": 6,
                        "connect": 6
                    },
                    "type": "roundrobin",
                    "keepalive_pool": {
                        "requests": 1000,
                        "size": 320,
                        "idle_timeout": 60
                    }
                },
                "name": "device-transport",
                "status": 1,
                "create_time": 1688714062,
                "plugins": {
                    "ucsp-auth": {
                        "secret": "7b5cde0a41bf4588983e7e1685492b29",
                        "key": "1234567890abcdef",
                        "secret_map": {
                            "100080012": "56e608c295d4415b88938e290c507953",
                            "970010016": "7b5cde0a41bf4588983e7e1685492b29"
                        },
                        "redis": {
                            "idle_time": 20000,
                            "redis_host": "10.10.85.14",
                            "redis_password": "ubt83474428",
                            "redis_port": "19100",
                            "pool_size": 20,
                            "redis_ssl": "",
                            "redis_ssl_verify": "",
                            "redis_timeout": 1000,
                            "redis_database": "0"
                        },
                        "_meta": {
                            "disable": false
                        },
                        "iv": "1234567890123456"
                    }
                },
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "DELETE",
                    "PATCH",
                    "HEAD",
                    "OPTIONS",
                    "CONNECT",
                    "TRACE",
                    "PURGE"
                ],
                "update_time": 1689325213
            },
            "key": "/apisix/routes/468393803724620526",
            "modifiedIndex": 1918
        },
        {
            "createdIndex": 1659,
            "value": {
                "update_time": 1689304188,
                "id": "468965470297391854",
                "status": 0,
                "upstream": {
                    "pass_host": "pass",
                    "scheme": "http",
                    "nodes": [
                        {
                            "host": "10.10.85.14",
                            "port": 8848,
                            "weight": 1
                        }
                    ],
                    "timeout": {
                        "send": 6,
                        "read": 6,
                        "connect": 6
                    },
                    "type": "roundrobin",
                    "keepalive_pool": {
                        "requests": 1000,
                        "size": 320,
                        "idle_timeout": 60
                    }
                },
                "create_time": 1689054802,
                "uri": "/nacos/*",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "DELETE",
                    "PATCH",
                    "HEAD",
                    "OPTIONS",
                    "CONNECT",
                    "TRACE",
                    "PURGE"
                ],
                "name": "nacos"
            },
            "key": "/apisix/routes/468965470297391854",
            "modifiedIndex": 1810
        },
        {
            "createdIndex": 1751,
            "value": {
                "id": "469259980801835758",
                "uri": "/usercenter/*",
                "name": "usercenter-local",
                "upstream_id": "469259855744467694",
                "status": 1,
                "host": "ucsp-dev.ubtrobot.com",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "DELETE",
                    "PATCH",
                    "HEAD",
                    "OPTIONS",
                    "CONNECT",
                    "TRACE",
                    "PURGE"
                ],
                "create_time": 1689230344,
                "update_time": 1689325903
            },
            "key": "/apisix/routes/469259980801835758",
            "modifiedIndex": 1933
        },
        {
            "createdIndex": 1752,
            "value": {
                "update_time": 1689325908,
                "id": "469260008534573806",
                "status": 1,
                "uri": "/usercenter/*",
                "create_time": 1689230361,
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "DELETE",
                    "PATCH",
                    "HEAD",
                    "OPTIONS",
                    "CONNECT",
                    "TRACE",
                    "PURGE"
                ],
                "upstream_id": "469259940989502190",
                "name": "usercenter"
            },
            "key": "/apisix/routes/469260008534573806",
            "modifiedIndex": 1934
        }
    ]
}
```
---
Access Results
```
[dev@bigdata-304 apisix]$ curl http://10.10.85.14:19080/device-transport/mqtt/v1/test/gateway
{"error_msg":"404 Route Not Found"}
```
---
apisix access.log
```
10.10.85.14 - - [17/Jul/2023:11:06:35 +0800] 10.10.85.14:19080 "GET /device-transport/mqtt/v1/test/gateway HTTP/1.1" 404 47 0.000 "-" "curl/7.29.0" - - - "http://10.10.85.14:19080"
```
the error.log no records for this request.
