### ISSUE TITLE
help request:  docker pull huge image failed

### ISSUE THREAD

**Issue by hellojukay** [apache/apisix#9857]
### Description

When use apisix as gateway , when network slow (5M/s)  and docker pull huge image ( image size more than 1GB) always failed， **When the network speed is good, it can always pull success**
```
$ docker  pull docker.xyz.com/jadt/iii:v3
v3: Pulling from jadt/iii
fb668870d8a7: Pull complete
4542784317be: Pull complete
e0bec5df5af5: Pull complete
4053f75740ab: Pull complete
57e09105cdfd: Pull complete
606761d225e5: Pull complete
69473a703fb4: Pull complete
a08ab4e0594b: Pull complete
4cd507bccac2: Pull complete
fa92f16621a4: Downloading [==================================================>]  1.412GB/1.412GB
6dc2b05bd224: Download complete
bdd5f6455bdd: Downloading [==================================================>]  1.146GB/1.146GB
48d915a4e6f6: Download complete
2a70c506252e: Downloading [==================================================>]  3.088GB/3.088GB
4f4fb700ef54: Download complete
bfe9228f18ac: Download complete
515667f151fa: Download complete
faa704319aa2: Downloading [==================================================>]   2.13GB/2.13GB
unexpected EOF
```
But when then gateway switch to  nginx ingress , docker pull success （Also in case of slow network）

# Nginx ingress config
```
$ kubectl describe ingress docker-platform-artifactory-ha -n jfrog
Name:             docker-platform-artifactory-ha
Labels:           app=artifactory-ha
                  app.kubernetes.io/managed-by=Helm
                  chart=artifactory-ha-107.24.3
                  heritage=Helm
                  release=jfrog-platform
Namespace:        jfrog
Address:          10.100.0.5
Ingress Class:    <none>
Default backend:  10.100.25.63:8082,10.100.25.72:8082
TLS:
  xyz.com terminates
Rules:
  Host                Path  Backends
  ----                ----  --------
  docker.xyz.com
                      /   jfrog-platform-1-artifactory-ha:8082 (10.100.25.63:8082,10.100.25.72:8082)
Annotations:          field.cattle.io/publicEndpoints:
                        [{"addresses":["10.100.0.5"],"port":80,"protocol":"HTTP","serviceName":"jfrog:jfrog-platform-1-artifactory-ha","ingressName":"jfrog:docker...
                      kubernetes.io/ingress.class: devops-gateway
                      meta.helm.sh/release-name: jfrog-platform
                      meta.helm.sh/release-namespace: jfrog
                      nginx.ingress.kubernetes.io/configuration-snippet:
                        rewrite ^/v2/docker-local/(.*) /artifactory/api/docker/docker-local/v2/$1 break;
                        rewrite ^/(v2)/(.*) /artifactory/api/docker/docker/$1/$2;
                      nginx.ingress.kubernetes.io/proxy-body-size: 20480m
                      nginx.ingress.kubernetes.io/proxy-connect-timeout: 60
                      nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 0
                      nginx.ingress.kubernetes.io/proxy-read-timeout: 300
                      nginx.ingress.kubernetes.io/proxy-send-timeout: 300
Events:               <none>
``` 

# APISIX router
```
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: jfrog-platform-1-artifactory-ha-docker-v2
  namespace: jfrog
spec:
  http:
    - name: docker
      timeout:
        send: 3600s
        read: 3600s
        connect: 360s
      match:
        hosts:
          - docker.xyz.com
        paths:
          - /v2/*
      backends:
        - serviceName: jfrog-platform-1-artifactory-ha
          servicePort: 8082
      websocket: true
      plugins:
      - config:
          http_to_https: true
        enable: false
        name: redirect
      - name: client-control
        enable: true
        config:
          max_body_size: 171798691840
      - name: proxy-control
        enable: true
        config:
          request_buffering: false
      - config:
          regex_uri:
          - ^/v2/(.*)
          - /artifactory/api/docker/docker/v2/$1
        enable: true
        name: proxy-rewrite
    - name: all
      timeout:
        send: 3600s
        read: 3600s
        connect: 360s
      match:
        hosts:
          - docker.xyz.com
        paths:
          - /*
      backends:
        - serviceName: jfrog-platform-1-artifactory-ha
          servicePort: 8082
      websocket: true
      plugins:
      - config:
          http_to_https: true
        enable: false
        name: redirect
      - name: client-control
        enable: true
        config:
          max_body_size: 171798691840
      - name: proxy-control
        enable: true
        config:
          request_buffering: false
      - config:
          regex_uri:
          - ^/v2/docker-local/(.*)
          - /artifactory/api/docker/docker-local/v2/$1
        enable: true
        name: proxy-rewrite

```
### Environment

- APISIX version (run `apisix version`):
```
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua version
2.15.0
```
- Operating system (run `uname -a`):
```
Linux apisix-5d6c8565cd-dnlll 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 Linux
```
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
```
bash-5.1# openresty -V
nginx version: openresty/1.21.4.1
built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424)
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.1 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.M4fAebVwPS/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.M4fAebVwPS/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.M4fAebVwPS/openresty-1.21.4.1/../apisix-nginx-module-1.9.0 --add-module=/tmp/tmp.M4fAebVwPS/openresty-1.21.4.1/../apisix-nginx-module-1.9.0/src/stream --add-module=/tmp/tmp.M4fAebVwPS/openresty-1.21.4.1/../apisix-nginx-module-1.9.0/src/meta --add-module=/tmp/tmp.M4fAebVwPS/openresty-1.21.4.1/../wasm-nginx-module-0.6.2 --add-module=/tmp/tmp.M4fAebVwPS/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
```
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
```
bash-5.1# luarocks --version
/usr/local/bin/luarocks 3.8.0
LuaRocks main command-line interface
```
