### ISSUE TITLE
help request: sync_debug_hooks(): failed to load module

### ISSUE THREAD

**Issue by darkSheep404** [apache/apisix#9869]
### Description

I added a custom plugin and it works for router i  appointed
`COPY ./plugins /usr/local/apisix/apisix/plugins`
but I get  errors when I try to configure it in debug.yml like 
```
local plugin_name = "custom-openid-connect"

local _M = {
    version = 0.1,
    priority = 2601,
    name = plugin_name,
    schema = schema,
}
```

```
hook_conf:
  enable: true # Enables/disables hook debug trace
  name: custom-openid-hook # Module list name of the hook that enabled the debug trace
  log_level: warn #
  is_print_input_args: true # When set to `true` enables printing input arguments
  is_print_return_value: true # When set to `true` enables printing returned values

openid-hook: # Module function list, Name: hook_phase
  resty.openidc: # Referenced module name
    - authenticate
    - introspect
custom-openid-hook:
  custom-openid-connect:
    - rewrite
#END
```
it leads to error
```
2023/07/20 05:38:09 [error] 63#63: *18 [lua] debug.lua:187: sync_debug_hooks(): failed to load module [custom-openid-connect]: module 'custom-openid-connect' not found:
	no field package.preload['custom-openid-connect']
	no file '/usr/local/apisix//deps/share/lua/5.1/custom-openid-connect.lua'
	no file '/usr/local/apisix//deps/share/lua/5.1/custom-openid-connect/init.lua'
	no file '/usr/local/apisix/custom-openid-connect.lua'
	no file '/usr/local/apisix/custom-openid-connect/init.lua'
	no file '/usr/local/openresty/site/lualib/custom-openid-connect.ljbc'
	no file '/usr/local/openresty/site/lualib/custom-openid-connect/init.ljbc'
	no file '/usr/local/openresty/lualib/custom-openid-connect.ljbc'
	no file '/usr/local/openresty/lualib/custom-openid-connect/init.ljbc'
	no file '/usr/local/openresty/site/lualib/custom-openid-connect.lua'
	no file '/usr/local/openresty/site/lualib/custom-openid-connect/init.lua'
	no file '/usr/local/openresty/lualib/custom-openid-connect.lua'
	no file '/usr/local/openresty/lualib/custom-openid-connect/init.lua'
	no file './custom-openid-connect.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/custom-openid-connect.lua'
	no file '/usr/local/share/lua/5.1/custom-openid-connect.lua'
	no file '/usr/local/share/lua/5.1/custom-openid-connect/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/custom-openid-connect.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/custom-openid-connect/init.lua'
	no file './custom-openid-connect.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/custom-openid-connect.lua'
	no file '/usr/local/share/lua/5.1/custom-openid-connect.lua'
	no file '/usr/local/share/lua/5.1/custom-openid-connect/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/custom-openid-connect.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/custom-openid-connect/init.lua'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/custom-openid-connect.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/custom-openid-connect.so'
	no file '/usr/local/openresty/site/lualib/custom-openid-connect.so'
	no file '/usr/local/openresty/lualib/custom-openid-connect.so'
	no file './custom-openid-connect.so'
	no file '/usr/local/lib/lua/5.1/custom-openid-connect.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/custom-openid-connect.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './custom-openid-connect.so'
	no file '/usr/local/lib/lua/5.1/custom-openid-connect.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/custom-openid-connect.so'
```
i found it doesn't scan plugins folder so i modify config file and found changes in nginx.conf
```
apisix:
  ...
  extra_lua_path: "/usr/local/apisix/apisix/plugins/?.lua;"
```
```
    lua_package_path:  "/usr/local/apisix/apisix/plugins/?.lua;$prefix/deps/share/lua/5.1/?.lua;$prefix/deps/share/lua/5.1/?/init.lua;/usr/local/apisix/?.lua;/usr/local/apisix/?/init.lua;;./?.lua;/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/openresty/luajit/share/lua/5.1/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?/init.lua;";
  
```
but leads to new error

```
2023/07/20 05:33:50 [error] 66#66: init_worker_by_lua error: /usr/local/apisix/apisix/plugins/prometheus.lua:40: attempt to index local 'exporter' (a number value)
stack traceback:
	/usr/local/apisix/apisix/plugins/prometheus.lua:40: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/apisix/plugins/prometheus/exporter.lua:17: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/apisix/plugin.lua:551: in function 'init_worker'
	/usr/local/apisix/apisix/init.lua:119: in function 'http_init_worker'
	init_worker_by_lua:2: in main chunk
2023/07/20 05:33:50 [error] 58#58: init_worker_by_lua error: /usr/local/apisix/apisix/plugins/prometheus.lua:40: attempt to index local 'exporter' (a number value)
stack traceback:
	/usr/local/apisix/apisix/plugins/prometheus.lua:40: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/apisix/plugins/prometheus/exporter.lua:17: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/apisix/plugin.lua:551: in function 'init_worker'
	/usr/local/apisix/apisix/init.lua:119: in function 'http_init_worker'
	init_worker_by_lua:2: in main chunk
```

```log
2023/07/20 05:27:18 [error] 62#62: *45254 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/init.lua:362: attempt to index upvalue 'local_conf' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/apisix/apisix/init.lua: in function 'http_access_phase'
	access_by_lua(nginx.conf:265):2: in main chunk, client: 172.20.0.1, server: _, request: "GET /api/admin/keycloak/sso/token?login_hint=fengbr@test.com HTTP/1.1", host: "localhost:9080", referrer: "http://localhost:9527/"
2023/07/20 05:27:18 [error] 52#52: *45253 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/init.lua:362: attempt to index upvalue 'local_conf' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/apisix/apisix/init.lua: in function 'http_access_phase'
	access_by_lua(nginx.conf:265):2: in main chunk, client: 172.20.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "localhost:9080", referrer: 
```
pls kindly help to check it! many thanks!

### Environment

- APISIX version :
```'
FROM apache/apisix:2.12.1-alpine

COPY ./plugins /usr/local/apisix/apisix/plugins
```
-enviorment:  docker desktop for windows

**Comment by Sn0rt** [comment]
takealook

**Comment by Revolyssup** [comment]
Change your hook config to 
``` yaml
hook_conf:
  enable: true # Enables/disables hook debug trace
  name: custom-openid-hook # Module list name of the hook that enabled the debug trace
  log_level: warn #
  is_print_input_args: true # When set to `true` enables printing input arguments
  is_print_return_value: true # When set to `true` enables printing returned values

openid-hook: # Module function list, Name: hook_phase
  apisix.plugins.resty.openidc: # Referenced module name
    - authenticate
    - introspect
custom-openid-hook:
  apisix.plugins.custom-openid-connect:
    - rewrite
#END
```
