### ISSUE TITLE
help request: Dynamic routing based on HTTP_STATUS from first API

### ISSUE THREAD

**Issue by chilcano** [apache/apisix#9928]
### Description

Hi All,
I would like to route the request to 3rd API based on the 1st API HTTP_STATUS response.
I mean:

1. Call `http://apisix/api1`
2. Get `api1` response / `http_status`
3. If `http_status = 200`, then call to `http://apisix/api2`
4. If `http_status = 400`, then call to `http://apisix/api3`

Please, could anyone share an APISIX route snippet to do that?.
Any idea is welcome.
Regards.
 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by qwzhou89** [comment]
This can be achieved by combining several plugins, such as the following:
```yaml
uri: /internal-check
plugins:
  response-rewrite:
    headers:
      X-Api1-Status: '$status'
    status_code: 200
  proxy-rewrite: 
    uri: "/api1",
upstream:
  nodes:
    - host: apisix
      port: 80
      weight: 1
  type: roundrobin
status: 1
---
uri: /testTrafficSplit
host: apisix
plugins:
  forward-auth:
    upstream_headers:
      - X-Api1-Status
    uri: http://127.0.0.1/internal-check
  serverless-pre-function:
    functions:
      - |
        local core = require('apisix.core');
        return function(conf, ctx)
          if ctx.var.http_x_api1_status == '200' then
            ctx.var.upstream_uri = '/api2'
          elseif ctx.var.http_x_api1_status == '400' then
            ctx.var.upstream_uri = '/api3'
          end
        end
    phase: before_proxy
upstream:
  nodes:
    - host: apisix
      port: 80
      weight: 1
  type: roundrobin
status: 1
```
